### ISSUE TITLE
Switch from private Unicode ranges to proper SVG images

### ISSUE THREAD

**Issue by linkmauve** [conversejs/converse.js#1004]
Using a font with images in some private Unicode range is a hack, which degrades very poorly for users who don’t use @font-face for any reason.

They should be replaced with proper images.

**Comment by jcbrand** [comment]
Currently in the master branch the fonts are included in the CSS so users won't load the CSS without the fonts. The fonts are also named in a way to avoid collisions.

Using fonts works well and lots of projects do it. If it were to eventually become a problem we could change to images, but I don't see a need to do so now and there's many more important things to spend time on. To prevent clutter I'm closing this ticket.

**Comment by linkmauve** [comment]
It actually already is a problem, not all CSS parsers support @font-face, it also is an accessibility feature to disable it since many websites become unreadable with them.

See also https://github.com/blog/2112-delivering-octicons-with-svg for a more technical reasoning.

**Comment by jcbrand** [comment]
OK,I'll reopen, but is not something I'm personally motivated to work on. There's IMO many other higher priority things to do.

**Comment by jcbrand** [comment]
This looks like helpful information: 

https://fontawesome.com/how-to-use/on-the-web/advanced/svg-sprites
