### ISSUE TITLE
Minified builds do not work in some circumstances

### ISSUE THREAD

**Issue by richard-fairthorne** [conversejs/converse.js#1017]
Minified builds found on CDN's do not work. They produce errors related to emojione.

## example

```
<html>
<head>
  <link rel="stylesheet" type="text/css" media="screen" href="https://cdn.conversejs.org/3.3.2/css/converse.min.css">
  <script src="https://cdn.conversejs.org/3.3.2/dist/converse.min.js"></script>
</head>
<body>
  <script>
      converse.initialize({
          bosh_service_url: 'https://conversejs.org/http-bind/', // Please use this connection manager only for testing purposes
          show_controlbox_by_default: true
      });
  </script>
</body>
</html>
```

## result in chrome

```
converse.min.js:sourcemap:293 Uncaught SyntaxError: Invalid regular expression: /<object[^>]*>.*?</object>|<span[^>]*>.*?</span>|<(?:object|embed|svg|img|div|span|p|a)[^>]*>|(?:ðŸ³)ï¸?â€?(?:ðŸŒˆ)|(?:ðŸ‘)ï¸?â€?(?:ðŸ—¨)ï¸?|[#-9]ï¸?âƒ£|(?:(?:ðŸ´)(?:ï¿½[ï¿½-ï¿½]){1,6})|(?:ï¿½[ï¿½-ï¿½]){2}|(?:(?:ï¿½[ï¿½ï¿½]))ï¸?(?:ï¿½[ï¿½-ï¿½])?â€?(?:[âš•âš–âœˆ]|ï¿½[ï¿½-ï¿½]|ï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½])|(?:ï¿½[ï¿½ï¿½]|ï¿½[ï¿½-ï¿½])(?:ï¿½[ï¿½-ï¿½])?â€?[â™€â™‚âš•âš–âœˆ]?ï¸?|(?:(?:â¤|ï¿½[ï¿½-ï¿½ï¿½])[â€ï¸]{0,2}){1,3}(?:â¤|ï¿½[ï¿½-ï¿½ï¿½])|(?:(?:â¤|ï¿½[ï¿½-ï¿½ï¿½])ï¸?){2,4}|(?:ï¿½[ï¿½ï¿½ï¿½ï¿½-ï¿½ï¿½ï¿½-ï¿½]|ï¿½[ï¿½ï¿½]|ï¿½[ï¿½-ï¿½]|ï¿½[ï¿½-ï¿½]|ï¿½[ï¿½-ï¿½]|â›¹|ðŸ‘¯)ï¸?(?:ï¿½[ï¿½-ï¿½])?â€?[â™€â™‚]?ï¸?|(?:[â˜â›¹âœŠ-âœ]|ï¿½[ï¿½-ï¿½]|ï¿½[ï¿½-ï¿½ï¿½-ï¿½ï¿½-ï¿½ï¿½-ï¿½]|ï¿½[ï¿½-ï¿½])ï¸?(?:ï¿½[ï¿½-ï¿½])|(?:[â†”-â†™â†©-â†ª]ï¸?|[#*]|[ã€°ã€½]ï¸?|(?:ï¿½[ï¿½-ï¿½]|ðŸ†Ž|ï¿½[ï¿½-ï¿½])ï¸?|â“‚ï¸?|[ãŠ—ãŠ™]ï¸?|(?:ï¿½[ï¿½-ï¿½]|ðŸˆš|ðŸˆ¯|ï¿½[ï¿½-ï¿½]|ï¿½[ï¿½-ï¿½])ï¸?|[â€¼â‰]ï¸?|[â–ª-â–«â–¶â—€â—»-â—¾]ï¸?|[Â©Â®]ï¸?|[â„¢â„¹]ï¸?|ðŸ€„ï¸?|[â¬…-â¬‡â¬›-â¬œâ­â­•]ï¸?|[âŒš-âŒ›âŒ¨ââ©-â³â¸-âº]ï¸?|ðŸƒ|[â¤´â¤µ]ï¸?)|[âœ€-âž¿]ï¸?|[ï¿½-ï¿½][ï¿½-ï¿½]ï¸?|[â˜€-â›¿]ï¸?|[0-9]ï¸/: Range out of order in character class
    at new RegExp (<anonymous>)
    at emojione (converse.min.js:sourcemap:293)
    at converse.min.js:sourcemap:293
    at converse.min.js:sourcemap:266
    at converse.min.js:sourcemap:266
emojione @ converse.min.js:sourcemap:293
(anonymous) @ converse.min.js:sourcemap:293
(anonymous) @ converse.min.js:sourcemap:266
(anonymous) @ converse.min.js:sourcemap:266
```

## workaround

Do not use minified builds

## suggested temporary fixes

- stop building broken minified builds for the CDN
- stop using broken minified builds in the documentation, specifically where it is likely to confuse newbies like me: https://conversejs.org/docs/html/quickstart.html#getting-a-demo-up-and-running

## ideal fix

- report upstream to the minify vendor.

Hope that's enough data. I nearly gave up adopting this 2 hours after finding it, because it was hard for me to debug given lack of familiarity with the project.

**Comment by jcbrand** [comment]
The specific build you link to in your example, https://cdn.conversejs.org/3.3.2/dist/converse.min.js, works fine for me. In fact, it can be tested live here: https://conversejs.org/3.3.2/

So I'm a bit confused. Is that the actual build that's giving you problems, or are you using another build?

**Comment by richard-fairthorne** [comment]
Thanks for the quick response. The example is the actual file that fails. Removing ".min" from the filenames fixes the issues. So, the problem appears to be the browser?

I'll check a various clients and report back. This error is from this client:

```
Google Chrome	63.0.3239.132 (Official Build) (64-bit)
Revision	2e6edcfee630baa3775f37cb11796b1603a64360-refs/branch-heads/3239@{#709}
OS	Mac OS X
JavaScript	V8 6.3.292.49
Flash	28.0.0.161 /Users/admin/Library/Application Support/Google/Chrome/PepperFlash/28.0.0.161/PepperFlashPlayer.plugin
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
Command Line	/Applications/Google Chrome.app/Contents/MacOS/Google Chrome --flag-switches-begin --flag-switches-end
Executable Path	/Applications/Google Chrome.app/Contents/MacOS/Google Chrome
Profile Path	/Users/admin/Library/Application Support/Google/Chrome/Profile 1
Variations	c134752e-b8b72c88
4c328cc8-3f4a17df
3095aa95-3f4a17df
47e5d3db-3d47f4f4
1210a805-ecd831c
b1edbc38-cf4f6ead
ba3f87da-45bda656
776de70c-eadfd437
79616653-3f4a17df
9e201a2b-6e3ce1c
68812885-4d2fac87
f347910c-3d47f4f4
4b61504a-d25ea691
9773d3bd-f23d1dea
8e3b2dc5-93702590
f79cb77b-3d47f4f4
4ea303a6-ecbb250e
3d7e3f6a-2eb01455
d92562a9-ca7d8d80
90bcbadc-3f4a17df
25fc488a-4d2fac87
1c2f7bbf-3f4a17df
58a025e3-c2b41702
1bced4a3-90fa85cd
b2f0086-93053e47
ef25c1eb-3f4a17df
494d8760-6843eff2
f47ae82a-86f22ee5
3ac60855-486e2a9c
f296190c-92bb99a9
4442aae2-6e597ede
ed1d377-e1cc0f14
75f0f0a0-e1cc0f14
e2b18481-6e597ede
e7e71889-4ad60575
94e68624-803f8fc4
f141d4bc-28ad44a
e9ce63c1-36ab09a2
da4aaa01-4d2fac87
```

**Comment by richard-fairthorne** [comment]
Same issue in safari. Regex error in the js.map -- I'm scratching my head. I am inclined to think it's something situational on my end, but I haven't got a clue.

I'm serving the html file from a server on my local host. I'll deploy it into the wild and see what happens.

**Comment by richard-fairthorne** [comment]
In Safari, the browser window shows this information:

![screen shot 2018-02-13 at 10 02 12 pm](https://user-images.githubusercontent.com/1225460/36185901-b0a41262-1109-11e8-8ac5-7e726129ff17.png)

**Comment by jcbrand** [comment]
I tested your example code as-is yesterday before I replied and it worked for me.

Try to do a hard refresh of all CDN assets through the browser. Perhaps something is cached.

The bourbon error is something else, that's CSS. To fix that, remove `./css/converse.min.css` and generate it again with `make css/converse.min.css`.

**Comment by richard-fairthorne** [comment]
I have never used firefox before. Just installed it. It exhibits the same issue.

**Comment by jcbrand** [comment]
@richard-fairthorne any update on this?

**Comment by Zash** [comment]
The error looks like something feed UTF-8 data into a parser expecting Latin1. There doesn't seem to be any encoding specified on the HTML data from those pages on `hashbang.info`, nor from the CDN. Possible cause? See if adding `<meta charset=utf-8>` appears to fix it.

**Comment by badfiles** [comment]
I confirm this issue. `<meta charset=utf-8>` fixes running the minified version for me. I use another charset, and the minified version is somehow incompatible with mine.

**Comment by richard-fairthorne** [comment]
I confirm the workaround that Zash and badfiles are using.

https://hashbang.info/index_converse_min_utf-8.html

It seems as though, for a wide variety of browsers on mac, it only works after setting the character set to UTF-8. Is this something that a BOM could solve? I had to find a temporary solution, but I'd love to switch back.

I'll see if I can find a fix that doesn't require possibly breaking changes to websites.

**Comment by richard-fairthorne** [comment]
Easy peazy!

If the documentation were updated to include the following tag, or similar, the problem would be resolved:

```
<script charset='utf-8' src="https://cdn.conversejs.org/3.3.2/dist/converse.min.js">
```

This solution is based on Zash/badfiles, requires no code changes, and fixes the problem across all of my browsers.

https://hashbang.info/index_converse_min_utf-8_script.html

Thanks for your help everyone.
