### ISSUE TITLE
Typing in MUC shows "Typing from another device"

### ISSUE THREAD

**Issue by ge0rg** [conversejs/converse.js#1026]
When I'm in a MUC with full-screen converse (3.3.3), and I start typing, I see "Typing from another device" displayed, despite not being active in any other client at the same time. Is it possible that this was introduced with #802, and that the internal logic sees the MUC reflection as "I'm typing" without checking whether this was initially sent by converse?

Maybe this asks for a complete block of self-typing in MUCs, or at least tracking of our own CSN message IDs so we can ignore them?

**Comment by jcbrand** [comment]
What server are you using? Is there a MUC where I can test this? I haven't seen this myself yet. 

The code naively assumes any incoming CSN messages are from other devices.

**Comment by ge0rg** [comment]
I've tested it with a self-hosted 3.3.3 on the prosody MUC (prosody@conference.prosody.im) and on another MUC running on chat.yax.im.

**Comment by jcbrand** [comment]
I just tested with the Prosody MUC and can confirm that I received `<composing>` and `<paused>` CSN messages (by looking in the dev console), but I did NOT get any "Typing from another device" notifications, I didn't get any CSN notifications at all.

I remember there already being a check for message IDs to filter out dupes, so this makes sense to me.

Are you able to replicate reliably?

**Comment by Zash** [comment]
I too see this, using [mod_conversejs](https://modules.prosody.im/mod_conversejs.html) on my development Prosody.

**Comment by guusdk** [comment]
I'm seeing the same thing in an Openfire-based MUC.

**Comment by jcbrand** [comment]
I've disabled the `typing from another device` CSN messages. To keep this feature we would need to keep track of the ids of these notifications which seems like unnecessary complexity and given the negligible value of this feature.

**Comment by jcbrand** [comment]
Reopening since I realised we can check whether the incoming CSN is a carbon copy and show the notification based on that.

**Comment by ge0rg** [comment]
You won't get Carbons for 'groupchat' messages, only for MUC-PMs.
