### ISSUE TITLE
Roster nicknames not shown or JID is shown instead

### ISSUE THREAD

**Issue by badfiles** [conversejs/converse.js#1031]
Something strange happened to roster names.
If I connect over websocket, I see no nicknames at all.
If I connect over bosh, I see nicknames, but first click on a user leaves jid instead of a nickname.

**Comment by jcbrand** [comment]
Can you provide some debug info? There's not enough info in your report for me to be able to help.

**Comment by badfiles** [comment]
I tried to collect debug info, but it is pretty hard to accomplish. While I can see bosh packets, WebSocket packets are encrypted. 
Which debug info would you like to see?

**Comment by jcbrand** [comment]
Set `debug` to `true` when calling `converse.initialize` and check if any errors or warnings are logged in the browser console.

**Comment by badfiles** [comment]
The minified build does not work on my test browser, the discussion is somewhere in issues, same regex problem.
I saw no errors when debug was on. If I looked at raw traffic with Wireshark, I saw the names in packets from the server. 
As I have mentioned earlier, I cannot determine what exactly causes the bug. I even saw the names once when the connection was via WebSocket. One thing is 100% reproducible -- if the names appeared, they are replaced with jid after clicking on them.

**Comment by badfiles** [comment]
Here's what happens after loading the roster,
the bosh connection leaves people 'unclicked'.
the WebSocket connection somehow 'clicks' every item, it happens pretty fast, hard to notice.
Anyway, after mysterious 'autoclick' or manual clicking an item, a name becomes a jid.
![screenshot from 2018-03-07 10-28-55](https://user-images.githubusercontent.com/1597304/37079651-5c877f24-21f4-11e8-84f7-fd4aa9c574cd.png)
![screenshot from 2018-03-07 10-29-03](https://user-images.githubusercontent.com/1597304/37079652-5ca61678-21f4-11e8-9776-7ee6d1066c63.png)

**Comment by jcbrand** [comment]
Where are you getting your builds from? You are using an old version of converse.js

**Comment by jcbrand** [comment]
Ok, so initially you have nicknames, and then somehow they turn into JIDs. I guess what's happening is that nicknames are gotten from the roster, and then vcards are fetched and then nicknames are overwritten with JIDs because there isn't a fullname in the vcard.

**Comment by badfiles** [comment]
building w/o `"converse-vcard",       // XEP-0054 VCard-temp`
and/or setting `use_vcards: false,` did not help.

**Comment by jcbrand** [comment]
Hmm, then I have no idea what's going on.

**Comment by jcbrand** [comment]
Refs #690

**Comment by Echolon** [comment]
@badfiles do you still expierence this issue?

**Comment by Echolon** [comment]
ref. https://github.com/conversejs/converse.js/issues/1130

**Comment by jcbrand** [comment]
Closing due to no response and AFAICT it's fixed.
