### ISSUE TITLE
Error: converse-core missing es6-promise

### ISSUE THREAD

**Issue by mamdouh87** [conversejs/converse.js#1035]
I tried to use converse in angular 4 application but during initialization, it throws error Error: converse-core missing es6-promise, I tried to install all known es-promise lib and make the target of my project es6 but it throws the same error, below is the code I tried to use 

 converse.initialize({
      bosh_service_url: 'http://localhost:7070/http-bind/', // Please use this connection manager only for testing purposes
      show_controlbox_by_default: true
    });
  }

**Comment by jcbrand** [comment]
You're not loading the dependencies. What are you using to load dependencies, webpack?

**Comment by vikramHM** [comment]
What is the solution for this?
1. In angular cli converse.js file is added in script section
2. importing in componet like this import '../assest/js/converse.js';
i am facing above error
