### ISSUE TITLE
XEPs support page with version

### ISSUE THREAD

**Issue by Neustradamus** [conversejs/converse.js#1037]
It is possible to have a XEPs support page with version?
https://conversejs.org/#features

Examples:
- https://metronome.im/supported-xeps-list
- https://dev.gajim.org/gajim/gajim/wikis/help/GajimXEPSupport
- https://github.com/jappix/jappix/blob/master/PROTOCOL.md

**Comment by jcbrand** [comment]
You're invited to create it for us ;)

**Comment by jcbrand** [comment]
I'm willing to consider pull requests, I'm however not doing this myself.

**Comment by Neustradamus** [comment]
I do not know the implemented versions.

**Comment by Neustradamus** [comment]
@jcbrand: Can you add VERSION?

Example: XEP-XXXX (v1.2)

**Comment by Neustradamus** [comment]
Dear @conversejs team, @jcbrand,

Can you add version of XEPs?

Example, what are the OMEMO XEP supported versions?
