### ISSUE TITLE
No "away" status notification message from Openfire server

### ISSUE THREAD

**Issue by drlight17** [conversejs/converse.js#1040]
Hello! Could anyone help me with the trouble. I have an Openfire 4.2.2 server and a web site with conversejs chat. Everyting works perfectly except for one thing: when anyone send a message to anyone with "away" status, this message correctly forwards by openfire plugin emailOnAway to the corresponding user's email address, but the notification message doesn't show up in conversejs. I have a test Pandion client and this notification message correctly shows up in it. Why doesn't it in conversejs? My config looks like this:

`converse.initialize({
		authentication: 'login',
		auto_away: 300,
			i18n: 'ru',
		locales_url: '/templates/it_blackwhite2/converse/locale/{{{locale}}}/LC_MESSAGES/converse.json',
		auto_reconnect: true,
        bosh_service_url: 'https://xxx.xxx.com:7443/http-bind/', // Please use this connection manager only for testing purposes
        show_controlbox_by_default: false,
		message_archiving: 'always',
		allow_muc: false,
		allow_muc_invitations: false,
		allow_registration: false,
		locked_domain: 'jabber',
		show_message_load_animation: true,
		show_send_button: true,
		use_vcards: false,
		play_sounds: true,
		time_format: 'HH:mm:ss',
		debug: true

    });`

**Comment by jcbrand** [comment]
What does the stanza with the notification message look like? Check your browser console for the logged stanza traffic.

**Comment by drlight17** [comment]
Thanks for the response! There are 3 packets generated when I send message from one to offline (away or dnd) user. Packets look like this in the order of appearance:
```
1) <message to="samoilovyo@jabber" id="1ahtF-592" type="chat">
  <thread>xEbejy</thread>
  <paused xmlns="http://jabber.org/protocol/chatstates"/>
</message>

2) <message to="samoilovyo@jabber" id="1ahtF-593" type="chat">
  <body>test</body>
  <thread>xEbejy</thread>
  <x xmlns="jabber:x:event">
    <offline/>
    <composing/>
  </x>
  <active xmlns="http://jabber.org/protocol/chatstates"/>
</message>

3) <message to="durovaov@jabber" from="samoilovyo@jabber">
  <subject>User is currently offline</subject>
  <body>User is currently offline.Your message was forwarded to the user's email (admin@mgre.ru).</body>
  <thread>8b249d0c-c79a-4bc1-91c3-cf0f89bc29fc</thread>
</message>

```
I used spark client debug mode to look through packets

**Comment by drlight17** [comment]
In chrome console i see the following:

```
 2018-03-19T10:53:06+03:00 DEBUG: <body xmlns="http://jabber.org/protocol/httpbind" ack="3716121090"><message xmlns="jabber:client" to="durovaov@jabber" from="samoilovyo@jabber"><subject>User is currently offline.Your message was forwarded to the user's email (admin@mgre.ru).</body></message></body>
10:53:06.592 converse.js:39341  2018-03-19T10:53:06+03:00 INFO: no requests during idle cycle, sending blank request 
10:53:06.593 converse.js:39339  2018-03-19T10:53:06+03:00 DEBUG: _throttledRequestHandler called with 1 requests 
10:53:06.593 converse.js:39339  2018-03-19T10:53:06+03:00 DEBUG: request id 29.0 posting 
10:53:06.594 converse.js:39339  2018-03-19T10:53:06+03:00 DEBUG: request id 29.0 state changed to 1 
10:53:06.594 converse.js:39339  2018-03-19T10:53:06+03:00 DEBUG: <body rid="3716121091" xmlns="http://jabber.org/protocol/httpbind" sid="7foupqypvm"/>
10:53:06.635 converse.js:39339  2018-03-19T10:53:06+03:00 DEBUG: request id 29.1 state changed to 2 
10:53:06.636 converse.js:39339  2018-03-19T10:53:06+03:00 DEBUG: request id 29.1 state changed to 3 
10:53:06.636 converse.js:39339  2018-03-19T10:53:06+03:00 DEBUG: request id 29.1 state changed to 4 
10:53:06.636 converse.js:39339  2018-03-19T10:53:06+03:00 DEBUG: removing request 
10:53:06.637 converse.js:39339  2018-03-19T10:53:06+03:00 DEBUG: _throttledRequestHandler called with 0 requests 
10:53:06.637 converse.js:39339  2018-03-19T10:53:06+03:00 DEBUG: request id 29 should now be removed 
10:53:06.637 converse.js:39339  2018-03-19T10:53:06+03:00 DEBUG: request id 29.1 got 200 
10:53:06.638 converse.js:39341  2018-03-19T10:53:06+03:00 INFO: _dataRecv called 
10:53:06.638 converse.js:39339  2018-03-19T10:53:06+03:00 DEBUG: <body xmlns="http://jabber.org/protocol/httpbind" ack="3716121090"><message xmlns="jabber:client" to="durovaov@jabber" type="chat" id="f75a3690-db17-48f5-8acd-383774481804" from="durovaov@jabber/converse.js-134941693"><forwarded xmlns="urn:xmpp:forward:0"><delay xmns="urn:xmpp:delay" stamp="2018-03-19T10:53:06+03:00"/><message xmlns="jabber:client" from="durovaov@jabber/converse.js-134941693" to="samoilovyo@jabber" type="chat" id="f75a3690-db17-48f5-8acd-383774481804"><body>test</body><active xmlns="http://jabber.org/protocol/chatstates"/></message></forwarded></message></body>
```

**Comment by jcbrand** [comment]
@drlight17 Converse 4 has been released in the meantime, could you please check whether you still have this problem?

**Comment by Echolon** [comment]
@drlight17 I will close this as there is release 8.x so far. Please comeback if it is still existent!
