### ISSUE TITLE
@ online @ roster group is not updated

### ISSUE THREAD

**Issue by francosansone** [conversejs/converse.js#1045]
Hello.

I'm using converse in a web app. I have a shared roster group in a ejabberd chat server  with @online@ users. I need to see the users online!

The problem is when I connect to the chat, it shows the users online, but if a user connects to a chat while I'm online, my contact list is not updated.

The problem is solved when I close the window. I guess the problem is due to sessionStorage. I tried to solve this for many days, but I can't.

```
  converse.initialize({
    whitelisted_plugins: ['converse-mam'],
    websocket_url: 'ws://<ip-server>:<port-server>/ws',
    auto_reconnect: true,
    cache_otr_key: true,
    message_archiving: 'onRoster',
    forward_messages: true,
    message_storage: "local",
    show_send_button: true,
    message_carbons: true,
    show_controlbox_by_default: true,
    auto_login: true,
    allow_logout: false,
    allow_muc: false,
    roster_group: true,
    jid: email,
    password: pass,
    ping_interval: 10
    debug: true
  });
```

**Comment by jcbrand** [comment]
What is `@online@`? Is that an ejabberd feature?

Also, what do you mean with `if a user connects to a chat`?

**Comment by francosansone** [comment]
A shared roster group of ejabberd with users: `@oline@` is a dynamic roster group with online users at this time.

Converse caches the members of a group of lists and does not update until you clean sessionStorage (closing the browser window). This is the problem. I need HELP to automate this process.

`If a user connects to a chat`that is to say if a user log in the chat.

**Comment by jcbrand** [comment]
Unless ejabberd pushes some kind of update to all connected users, there's nothing converse.js can do about it.

You can set debug to `true` and then open your browser's console and check all the stanza traffic. When a new user logs in, check if other users receive some kind of notification from Ejabberd about that via an XMPP stanza.

**Comment by francosansone** [comment]
I solved this (partially) by writing this plugin:

```
converse.plugins.add('updateContacts', {
    initialize: function () {
      var _converse = this._converse;
      _converse.api.listen.on('update', function () {
        _converse.roster.fetchFromServer()
          .then(() => {
            _converse.clearSession();
            console.log('update')
            _converse.emit('rosterContactsFetched');
            _converse.sendInitialPresence();
          }).catch((reason) => {
            _converse.log(reason, Strophe.LogLevel.ERROR);
            _converse.sendInitialPresence();
          });
        });
        setInterval(() => _converse.emit('update'), 10000)
      }
  })
```
In converse-core.js, the ignore_cache variable is set to false for default. Is there any way to set true?

https://github.com/conversejs/converse.js/blob/master/src/converse-core.js#L764

**Comment by jcbrand** [comment]
I would recommend that you don't implement a hack like this.

For one thing, calling `_converse.clearSession` clears more than just the roster and simply calling it within a session is not a good idea.

Instead, turn on debug mode and watch the stanza traffic between converse.js and ejabberd. When another user comes online, check if converse.js received a roster push stanza from ejabberd which informs it about the new online user.

If so, then the solution is clear and we can put it in the core code, no need to write your own plugin.

If not, then we can think again about what to do.

You can also save the browser console output (which contains the stanza traffic) and email it to me and I'll take a look.
