### ISSUE TITLE
Some troubles with csi_waiting_time

### ISSUE THREAD

**Issue by rheman** [conversejs/converse.js#1046]
Hi everyone.
I am using conversejs 3.2.1 with ejabberd 16.01.
I have enabled mod_client_state module  under ejabberd 16.01.
so in my conversejs I have put the following entry.

csi_waiting_time: 60

But after 1 hour of idle session (without the mouse moves) the chat state indication is still online .
I thing the chat state indication should be inactive.

I dont know what I did wrong 

Best regard

**Comment by jcbrand** [comment]
The `csi_waiting_time` is measured in seconds, not minutes.

https://conversejs.org/docs/html/configuration.html#csi-waiting-time

Set `debug` to `true` when calling `converse.initialize` and then check in your browser console whether an `inactive` CSI gets sent out after the timeout.

**Comment by rheman** [comment]
Thanks a lot
