### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by ghost** [conversejs/converse.js#1052]
In Firefox the chat date is shown with stranger characters.

     星期五 3月 30日 2018

I tried changing browser language but it doesn't work; However in chrome works well.

**Comment by jcbrand** [comment]
Which locale are you using?

**Comment by Zash** [comment]
I see this too.

- The system has `LANG=en_US.UTF-8`
- `navigator.language = "sv-SE"`

Anything else?

**Comment by jcbrand** [comment]
My suspicion is that if you're using a locale that moment.js doesn't support, that it "falls through" to the last locale, which is Chinese.

If so, it's a bug in `src/i18n.js`

**Comment by aitzol76** [comment]
You are right. Works changing web browser language from "eu"(basque) to "en-us"
