### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by aitzol76** [conversejs/converse.js#1055]
Hi! I 'm getting this error when try `make dist` in Ubuntu 16.04:

`
Error: Error: ENOENT: no such file or directory, open '/var/www/html/converse.js-master/builds/utils.js'
In module tree:
    converse
      converse-core

    at Object.fs.openSync (fs.js:652:18)

Makefile:198: recipe for target 'dist/converse.js' failed
make: *** [dist/converse.js] Error 1
`

**Comment by jcbrand** [comment]
Thanks, should be fixed now.
