### ISSUE TITLE
Unify vertical spacing between chats

### ISSUE THREAD

**Issue by Nyco** [conversejs/converse.js#1066]
Screenshot:

![capture d ecran 2018-03-29 a 21 46 54](https://user-images.githubusercontent.com/25348/38621649-92000c5c-3da1-11e8-8b66-cc6ec47fb357.png)

Problems:

- Spacings are inconsistent between groupchats and one-to-one chats

Proposed:

- Use the same spacing as one-to-one chats spacing for the groupchats
  - It is more relaxing
  - It is mobile/multitouch-compatible (smartphones and tablets, devices with fingers, no mouse or trackpad)
    - Lower spacings are difficult to tap/click on mobile on RocketChat

Examples:

![capture d ecran 2018-03-29 a 22 18 51](https://user-images.githubusercontent.com/25348/38621913-3f39eca8-3da2-11e8-8af1-1dde0ccbc81d.png)

![hipchat-overview-hero](https://user-images.githubusercontent.com/25348/38622031-8736b630-3da2-11e8-85ae-053b0d64e24f.png)

**Comment by Nyco** [comment]
Thinking out loud: globally, *maybe* every single item in this sidebar should have spacing with the above and below, whatever it is.

**Comment by jcbrand** [comment]
This is now done, let me know if you still see some inconsistencies.
