### ISSUE TITLE
Visually simplify buttons view

### ISSUE THREAD

**Issue by Nyco** [conversejs/converse.js#1068]
Screenshot:

![converse-4 0 0alpha-side_pane-buttons-overload](https://user-images.githubusercontent.com/25348/38637667-2033fa4a-3dcc-11e8-88a6-3952857d2f4e.png)

Problems:

- Too many **visible** buttons completely clutter the interface
- Much noise for a features that are rarely used, only once or twice
- That is a huge cognitive overhead

Proposed:

- Only display these buttons when hovered, make them invisible by default
- Add (a double of the) same buttons in the group/one-to-one conversation content (right pane), this time visible by default
  - As on mobile the users can’t hover

Examples:
![capture d ecran 2018-03-29 a 22 18 51](https://user-images.githubusercontent.com/25348/38637799-8338a94c-3dcc-11e8-9680-a5ac2cb83e01.png)
On Slack, when the one-to-one chat "David Lakomski" is hovered, it shows a "Remove from list" button (circled cross).

![capture d ecran 2018-03-29 a 22 19 34](https://user-images.githubusercontent.com/25348/38637818-9adf5bcc-3dcc-11e8-9c09-601eaaddb2ec.png)
On RockerChat, when the group "infos" is hovered, it shows a "Option" button (three vertical dots).

**Comment by jcbrand** [comment]
This has been done now.
