### ISSUE TITLE
Highlight selected and hovered conversations

### ISSUE THREAD

**Issue by Nyco** [conversejs/converse.js#1069]
Screenshot:

![capture d ecran 2018-03-29 a 22 23 43](https://user-images.githubusercontent.com/25348/38638311-2ce1b320-3dce-11e8-8a88-dad280f24902.png)

Problems:

In this screenshot:
- I can’t tell which conversation is selected (that’s commTeam)
- I have a hard time telling which one I hover (that’s scam, no poor pun, sorry ;-) )

Proposed:

- Maybe keep the font color change when hovered
- Add a background when hovered
- Add a background when selected
- Selected and hovered conversations must have a different background color
- These background colors should cover the whole width of this sidebar
- I can't think of other colors that lighter and darker greys (I haven't tried though, and I don't trust my taste)

Examples:
![capture d ecran 2018-03-29 a 22 18 51](https://user-images.githubusercontent.com/25348/38637799-8338a94c-3dcc-11e8-9680-a5ac2cb83e01.png)
On Slack, the group "Général" is selected, and the one-to-one chat "David Lakomski" is hovered.

![capture d ecran 2018-03-29 a 22 19 34](https://user-images.githubusercontent.com/25348/38637818-9adf5bcc-3dcc-11e8-9c09-601eaaddb2ec.png)
On RockerChat, the one-to-one chat "sylvain" is selected, and the group "infos" is hovered.

**Comment by Nyco** [comment]
OK, on both Slack and RocketChat:
- hovered: only the background changes to something darker than the default color
- selected: the background changes to something really different than the default color AND the font color goes white-ish (one of the themes of Slack is close to Converse and uses a blue background, could work for Converse as well)

**Comment by jcbrand** [comment]
Thanks @Nyco, I've updated the conversations to only show the buttons on hover and made the info button available on the conversation view (so that mobile users have access to it).

**Comment by jcbrand** [comment]
The currently open groupchat is now highlighted in the sidebar.

**Comment by jcbrand** [comment]
Open private chats are now also highlighted in the sidebar (all of this in `fullscreen` view_mode).

**Comment by jcbrand** [comment]
BTW @Nyco, thanks for the effort and the great recommendations. Looks much better now.
