### ISSUE TITLE
Fix the width of conversation list

### ISSUE THREAD

**Issue by Nyco** [conversejs/converse.js#1070]
Screenshots:

![capture d ecran 2018-03-29 a 22 28 24](https://user-images.githubusercontent.com/25348/38638924-0c79b59a-3dd0-11e8-9268-c43479a7f71b.png)
![capture d ecran 2018-03-29 a 22 28 13](https://user-images.githubusercontent.com/25348/38638925-0cad1598-3dd0-11e8-8a56-2d4b754a910d.png)

Problem:

- The amount of displayed info changes when I resize the app window
- Some items have a CR+LF, line is broken
- This makes me lose my habits of where to find my items, as the position and content changes

Proposed:

- Keep the width fixed
- Do not allow to break lines

Optionally: when the app windows width is below a certain threshold, do not display the conversation list (left pane, sidebar)

Examples:

On Slack:
![capture d ecran 2018-03-29 a 22 30 36](https://user-images.githubusercontent.com/25348/38638940-199b0800-3dd0-11e8-905c-292e6ee92886.png)
![capture d ecran 2018-03-29 a 22 30 28](https://user-images.githubusercontent.com/25348/38638943-19c5e660-3dd0-11e8-8af8-1c1e8abe366c.png)

On RocketChat:
![capture d ecran 2018-03-29 a 22 31 46](https://user-images.githubusercontent.com/25348/38639155-ad265570-3dd0-11e8-8cf4-504d848d0e9c.png)
![capture d ecran 2018-03-29 a 22 31 39](https://user-images.githubusercontent.com/25348/38639194-c4fc84a8-3dd0-11e8-82af-1c7f099b5dc1.png)
![capture d ecran 2018-03-29 a 22 31 55](https://user-images.githubusercontent.com/25348/38639202-cb2e2fe8-3dd0-11e8-881f-bb76761675e2.png)

**Comment by jcbrand** [comment]
I've made some changes so that the sidebar stays larger at certain viewports widths. Perhaps that solves the problem for you?

I'm not sure how to keep the sidebar at fixed width while having the chats responsive, not with the current CSS and bootstrap.

**Comment by Nyco** [comment]
Thinking again, maybe a fixed width is not the way to go.
The current implement looks fine to me.
