### ISSUE TITLE
Connection failure [after xmpp server restart]

### ISSUE THREAD

**Issue by gnidorah** [conversejs/converse.js#1075]
Hi.
I have converse.js configured following way
```js
authentication: 'login',
auto_reconnect: true,
auto_login: true,
jid: mylogin,
password: mypass
```
It works fine, even I have network issue converse.js reconnects when network is good again
BUT
If xmpp server was restarted, converse.js stucks with spinning logo and following error
```
Connection failure

Sorry, we could not connect to the XMPP host with domain: "myhost"
```
and it never connects, until I refresh page.
Is it expected behaviour?

**Comment by gnidorah** [comment]
Prosody 0.10Converse.js 3.3.2I don't reload the pageHere's the minimal test page ```<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><link rel="stylesheet" type="text/css" media="screen" href="https://cdn.conversejs.org/3.3.2/css/converse.min.css"><script src="https://cdn.conversejs.org/3.3.2/dist/converse.min.js"></script></head><body>text</body><script>    converse.initialize({        bosh_service_url: 'https://conversejs.org/http-bind/', // Please use this connection manager only for testing purposes        show_controlbox_by_default: true, auto_reconnect: true,auto_login: true,jid: "myjid",password: "mypass"    });</script></html>``` 14.04.2018, 10:21, "JC Brand" <notifications@github.com>:No, it should also reconnect after a server restart. What server are you using?However, with manual login, reconnection only works if you haven't reloaded the page since you logged in. If you reload the page, then your username and password (which were in memory) are no longer available and reconnection is not possible.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by gnidorah** [comment]
Prosody 0.10
Converse.js 3.3.2
I don't reload the page (but if I'll reload it will login, since jid and password are hardcoded in this test)
Here's the minimal test page

```html
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" type="text/css" media="screen" href="https://cdn.conversejs.org/3.3.2/css/converse.min.css">
<script src="https://cdn.conversejs.org/3.3.2/dist/converse.min.js"></script>
</head>
<body>
text
</body>
<script>
    converse.initialize({
        bosh_service_url: 'https://conversejs.org/http-bind/', // Please use this connection manager only for testing purposes
        show_controlbox_by_default: true,

auto_reconnect: true,
auto_login: true,
jid: "myjid",
password: "mypass"
    });
</script>
</html>
```

**Comment by jcbrand** [comment]
Haven't been able to reproduce. No news is good news I presume.

**Comment by FaizanZahid** [comment]
I am also having a similar issue, when my prosody xampp server restarts, the page where i m initliazing converses, refreshs and converse window is never loaded , it shows loading icon infinitely. 
i have to reload the page manually to let converse chat open again.

In JS console, i get web socket closed unexpectedly error.
