### ISSUE TITLE
history page - modify rosterContact list  , show only contacs with whom I spoke earlier

### ISSUE THREAD

**Issue by RafalxM** [conversejs/converse.js#1078]
I would like to run a separate chat history page, with contact roster filled only only those contacts with whom I spoke earlier - It's specific , but when I create new user account I adding him to group 'contacts' , so he can  chat with any other in this  group/roster.
I have chat visible at all pages of my web service - and there contact list contain all users.
Now,  only at history page I  would like to list contacts with conversation history only.

I know that rosterItem has attribute 'num_unread'  ,  I think that similar attribute, like 'num_archived' , would be very helpfull in this case - not direct what I need, but it would allow to show contacts I want to list.

Maybe some of you have an idea.
Thank you.

**Comment by jcbrand** [comment]
You could do a MAM query for each contact to see if there is an archive history and then keep track of this in an attribute like `num_archived`.
