### ISSUE TITLE
Add XEP-0359: Unique and Stable Stanza IDs function 

### ISSUE THREAD

**Issue by tursiops33** [conversejs/converse.js#1079]
Hi everyone,
I would like to propose adding the following feature to the chat client:

This XEP introduces unique and stable IDs for messages, which are beneficial in various ways. For example, they can be used together with Message Archive Management (XEP-0313) [1] to uniquely identify a message within an archive. They are also useful in the context of Multi-User Chat (XEP-0045) [2] conferences, as they allow to identify a message reflected by a MUC service back to the originating entity.

More details on the feature here https://xmpp.org/extensions/xep-0359.html

Thanks!

**Comment by jcbrand** [comment]
Done since at least 4.2.0.
