### ISSUE TITLE
Duplicate messages in the chat after logout/login

### ISSUE THREAD

**Issue by zlaxy** [conversejs/converse.js#1087]
After logout/login there is duplicates in the chat window:
![scrot](https://s7.postimg.cc/vgio2rinv/2018-04-26-124355_1280x800_scrot.png)

**Comment by cthu1hoo** [comment]
I'm getting this issue on 4.1.2 (and in fact any release newer than 4.0.6). Login/logout or simply reloading the page would cause all lines to duplicate.

 I'm using BOSH and loading Converse from CDN.

**Comment by jcbrand** [comment]
@cthu1hoo This appears to be fixed for me in 4.1.2. Clear your localStorage cache, that might be the cause.

**Comment by cthu1hoo** [comment]
@jcbrand I'm testing in incognito mode, so there's no shared cache. Still getting duplicates, every reload.

If that helps my Converse configuration is visible here (nothing unusual): https://xmpp.fakecake.org

**Comment by jcbrand** [comment]
You're still using version 4.0.5. Says so on the login form.

**Comment by cthu1hoo** [comment]
I have people using this server so obviously it's running version that works properly. The point was to share my local settings in case that would help diagnosing the problem, I didn't change anything when testing 4.1.2 (except for removing some CSS rules).

**Comment by cthu1hoo** [comment]
This also happens on https://conversejs.org/fullscreen.html

I can provide a test account on my server if that would help although it's basically just Prosody 0.11 from stretch backports.
