### ISSUE TITLE
Please add `Connected` filter by status option

### ISSUE THREAD

**Issue by zlaxy** [conversejs/converse.js#1089]
Please add `not offline` (or you can call it something else) filter by status option for showing all users with not offlise statuses (online, away, busy etc)

**Comment by zlaxy** [comment]
Done: https://github.com/conversejs/converse.js/pull/1090

**Comment by zlaxy** [comment]
Please, realise this feature before new release.

**Comment by t2d** [comment]
Would be great to have this. Atm, conversejs is quite hard to use if you have a big roster, especially with multiple groups. Online/Away contacts of later groups are then hidden under a long list of offline contacts of the first group.

**Comment by t2d** [comment]
awesome, thank you!
