### ISSUE TITLE
show members in members-only rooms

### ISSUE THREAD

**Issue by ChaosKid42** [conversejs/converse.js#1094]
converse.js shows only occupants in a muc room (i.e. only those users who are actually "online" in a muc). I feel this is completely OK for an open room. In case of a members-only room however it feels strange that the administrator/owner who adds members to his room has absolutely no feedback (i.e. there is no list of current members).

Therefore I suggest that converse.js shows also those members of a members-only room who are currently not visiting the room.

**Comment by jcbrand** [comment]
Agreed, suggestions for how the UI should look would be welcome :)

**Comment by ChaosKid42** [comment]
I would simply show those users without any status circle and using a color of lightgrey. See example for user ChaosKid42:

![screenshot-2018-5-5 converse js 1](https://user-images.githubusercontent.com/15179432/39667561-aefa349c-50b9-11e8-9c75-3606fe33be23.png)

**Comment by jcbrand** [comment]
Done. This is done for all rooms, not only members-only rooms (since any room can have a members list).

**Comment by ChaosKid42** [comment]
Thank you for imlementing this! It improves managing a members-only room very much.

However I have one suggestion: If you add a new member to a room using the command "/member <jid>" the occupants list is not updated. You have to leave and rejoin the room to see an updated list. Same happens, if you update the list of members using another client.

It would be very nice if these changes would automatically lead to an update of the occupants list.

**Comment by jcbrand** [comment]
Good point, should be better now :)

**Comment by ChaosKid42** [comment]
I'd like to test but currently I'm not able to run it:
```
FATAL: initialize@http://localhost:8000/dist/converse.js:54439:7
initializePlugin@http://localhost:8000/dist/converse.js:42796:21
loadPluginDependencies/<@http://localhost:8000/dist/converse.js:42739:21
arrayEach@http://localhost:8000/dist/converse.js:4442:11
forEach@http://localhost:8000/dist/converse.js:13264:14
loadPluginDependencies@http://localhost:8000/dist/converse.js:42732:13
initializePlugin@http://localhost:8000/dist/converse.js:42792:21
arrayEach@http://localhost:8000/dist/converse.js:4442:11
forEach@http://localhost:8000/dist/converse.js:13264:14
initializePlugins@http://localhost:8000/dist/converse.js:42829:13
_converse.initialize/this.initPlugins@http://localhost:8000/dist/converse.js:44516:7
finishInitialization@http://localhost:8000/dist/converse.js:44536:7
tryCatch@http://localhost:8000/dist/converse.js:3132:12
invokeCallback@http://localhost:8000/dist/converse.js:3147:13
publish@http://localhost:8000/dist/converse.js:3121:7
flush@http://localhost:8000/dist/converse.js:2851:5
```

**Comment by jcbrand** [comment]
Sorry, should be fixed now.

**Comment by ChaosKid42** [comment]
Works like a charm. Thank you!

**Comment by ChaosKid42** [comment]
I reopened the issue because I found another bug :-(

A member (no the user currently using converse.js) that is leaving a room is not changed from "online" to "offline" but removed from the list of occupants entirely. After the user of converse.js leaves and rejoins the room the list of occupants is updated and the member is correctly shown as offline member.

**Comment by jcbrand** [comment]
@ChaosKid42 That should now be fixed as well.

Ideally I would add tests to check that this is the case, but I currently don't have time for this.

**Comment by ChaosKid42** [comment]
Perfect. Thanks!

**Comment by jcbrand** [comment]
Super, I managed to add some tests today as well.
