### ISSUE TITLE
How to build on Windows?

### ISSUE THREAD

**Issue by ghostcode** [conversejs/converse.js#1097]
https://conversejs.org/docs/html/developer_guidelines.html#installing-the-development-and-front-end-dependencies

I follow this doc, and run npm install ,what's next or how to build ?

**Comment by jcbrand** [comment]
We're looking for someone who would be willing to support and document building on Windows!

Take a look at the last comment in ticket #641, that might help you.

Closing this ticket because it's a duplicate of #641

**Comment by ghostcode** [comment]
@jcbrand thanks
