### ISSUE TITLE
Bookmarks are not shown when using IE11

### ISSUE THREAD

**Issue by ChaosKid42** [conversejs/converse.js#1098]
MUC bookmarks are not shown, when you use IE11 on https://inverse.chat/ 

Works like a charm when using current versions of Firefox or Chrome.

**Comment by ChaosKid42** [comment]
The problem seems to exist also in https://conversejs.org/4.0.0-alpha/fullscreen.html.

Maybe the bookmark plugin is not loaded in IE11?

**Comment by jcbrand** [comment]
> Maybe the bookmark plugin is not loaded in IE11?

I doubt it, but perhaps there's some unsupported modern JavaScript in the plugin.

**Comment by ChaosKid42** [comment]
After an extensive session of trial and error I ended up with this patch which seems to solve my problem:
```patch
diff --git a/src/converse-bookmarks.js b/src/converse-bookmarks.js
index c381134c1..71991c84f 100644
--- a/src/converse-bookmarks.js
+++ b/src/converse-bookmarks.js
@@ -477,7 +477,7 @@
                 insertIntoControlBox () {
                     const controlboxview = _converse.chatboxviews.get('controlbox');
                     if (!_.isUndefined(controlboxview) &&
-                            !_converse.root.contains(this.el)) {
+                            !_converse.root.body.contains(this.el)) {
                         const container = controlboxview.el.querySelector('#chatrooms');
                         if (!_.isNull(container)) {
                             container.insertBefore(this.el, container.firstChild);
```

But honestly I don't know if this actually makes any sense :-)

**Comment by jcbrand** [comment]
@ChaosKid42 Should now be fixed, can you please double check?

**Comment by ChaosKid42** [comment]
Will have to backport your patch to v3.3.4 because HEAD doesn't seem to work at all in IE 11. I will be able to do that maybe tomorrow.

**Comment by ChaosKid42** [comment]
@jcbrand Backport done. Easier than expected. Seems to work. Closing the issue.
