### ISSUE TITLE
request failed with status 404 -> URL du lien source : converse-singleton.js.map;

### ISSUE THREAD

**Issue by nicolas-san** [conversejs/converse.js#1107]
Hello !
I just copy paste the code of the quickstart guide https://conversejs.org/docs/html/quickstart.html#getting-a-demo-up-and-running, and I have a 404 error on the translation file, 
converse try to load the translation file from the local files:

> https://mysite.localdev/fr_FR/admin/locale/fr/LC_MESSAGES/converse.json

I can see this in the profiler (it's a symfony based website)
> GET | locale/fr/LC_MESSAGES/converse.json | 5374ms

Have I done something wrong ?

Thanks a lot for your help !

**Comment by jcbrand** [comment]
If you want translations, then you're expected to host the `locale` directory as well. This information should be added to the quickstart guide.

**Comment by jcbrand** [comment]
> Converse.js is translated into multiple languages. The default build, converse.min.js, includes all
languages.

This is no longer true, translations are fetched via XHR on demand. I've updated the docs, but the update will only be visible with the next release.

**Comment by nicolas-san** [comment]
Sorry, I have missed your question, no nothing loads, I have this error only, no fallback

**Comment by jcbrand** [comment]
If you don't want to host the locale, try setting `i18n` to `'en'` when calling `converse.initialize`.

Let me know if that helps.

**Comment by nicolas-san** [comment]
I have done some tests, the fallback is working, I have something in my page that breaks converse, but the only visible error is the language warning.
I have tried in a blank page with the minimum markup, and it works, thanks for your help, I should have started by this basic test :)
