### ISSUE TITLE
Browser support and firefox legacy?

### ISSUE THREAD

**Issue by hir3npatel** [conversejs/converse.js#1108]
Hi, is there a list of supported browsers and versions as such?

Currently the latest release has some issues on Firefox Extended Support Release (ESR 52), which is legacy FF for legacy Add-Ons and Windows XP/Vista. Issue is that the user roster does not show. (It works fine on firefox 60)

Is firefox legacy meant to work and be supported by conversejs?

Thanks.

**Comment by jcbrand** [comment]
The general goal is to support the last 2 versions of all modern browsers, so that excludes FF legacy and also IE (although IE 11 still works currently and people sometimes commit fixes for it).

**Comment by jcbrand** [comment]
If a company needs support for an older browser due to in-house requirements, they can [contact me](http://opkode.com/contact.html) and we can discuss funding.

**Comment by mckaygerhard** [comment]
was its the lasted version that supports firefox correctly at least firefox 40 as minimum
