### ISSUE TITLE
No error displayed on room creation denied

### ISSUE THREAD

**Issue by Ppjet6** [conversejs/converse.js#1114]
Converse version: 7b1948327 (master)

## Steps to reproduce

- Conversejs configuration as below:
```
converse.initialize({
    authentication: 'anonymous',
    auto_login: true,
    auto_join_rooms: [
        'foobar@chat.foo.bar',
    ],
    bosh_service_url: '/bosh',
    jid: 'anon.foo.bar',
    debug: true,
    [..],
});
```
sasl anonymous probably doesn't have to do with the error not being displayed but I'm adding it for completeness. (It does have to do with not being able to create the room in this particular case, but that's not the point of the ticket)

## What happens

The chatroom loads indefinitely

In the console (among others):
```
<presence xmlns="jabber:client" type="error" to="uuid1@anon.foo.bar/uuid2" from="foobar@chat.foo.bar/foo">
  <error type="cancel">
    <not-allowed xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/>
      <text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">Room creation is restricted</text>
  </error>
</presence>
```

## What I expect

Having a visual clue (some sort of error displayed) would be helpful.

**Comment by jcbrand** [comment]
@Ppjet6 There's already [an automate test](https://github.com/conversejs/converse.js/blob/dffcc13dea632a298633d0dc2b0a9f5a6901ab6b/spec/chatroom.js#L3071) for exactly this. [See here](https://conversejs.org/tests/?spec=Chatrooms%20When%20attempting%20to%20enter%20a%20groupchat%20will%20show%20an%20error%20message%20if%20the%20user%20is%20not%20allowed%20to%20have%20created%20the%20groupchat)
