### ISSUE TITLE
Verify X.509 password less login

### ISSUE THREAD

**Issue by vavadiyahiren** [conversejs/converse.js#1116]
Hi Team,

Is there any way available to login without password with x.509 certificate verification.

I am using openfire server 4.2.0 and enabled certificate verification so now i am finding any web client which can help me to login with certificate verification.

Thanks,
Hiren vavadiya

**Comment by jcbrand** [comment]
Yes, it's explained in this (older) blog post: https://opkode.com/blog/strophe_converse_sasl_external/
