### ISSUE TITLE
Status Flapping (Away/Online jiters)

### ISSUE THREAD

**Issue by mcrosson** [conversejs/converse.js#1117]
When connected to an XMPP server from 2 different computers via converse.js current 'online' status can flap between 'online' and 'away' if one of the two computers has gone auto-away.

Version : https://conversejs.org/4.0.0-alpha/dist/converse.min.js (2018/06/20)

**Comment by jcbrand** [comment]
I've seen this before, but when I tried to reproduce it to find and fix the bug, I couldn't...

**Comment by mcrosson** [comment]
@jcbrand Understood. Feel free to close as you see fit.

**Comment by jcbrand** [comment]
I think the bug is still there, it's just not that easy to find/reproduce.
