### ISSUE TITLE
new option to pick muc nickname from vcard's nickname

### ISSUE THREAD

**Issue by tbeitter** [conversejs/converse.js#1127]
right now we have the option to "muc_nickname_from_jid" to pick the user identified of the jid as nickname for a muc.

As a user is able to set a nickname within it's profile (vcard) it would be great if ConverseJS could use that nickname (if set, otherwise fall back to the jid-method) as nickname for muc joining.

**Comment by jcbrand** [comment]
I have to double-check, but I think the latest code already does this.

**Comment by jcbrand** [comment]
In the current master branch code, the nickname from the user's VCard is used (if it's available).
