### ISSUE TITLE
roomconfig_presencebroadcast for participant/visitor disabled with every config save

### ISSUE THREAD

**Issue by tbeitter** [conversejs/converse.js#1128]
converse.js v3.3.4

The toggleboxes for presencebroadcast are set to
```
[x] Moderator
[ ] Participant
[ ] Visitor
```
everytime you open the room configuration in converse.js. No matter how they are set before the config tab was opened. If you then save the config you removed the broadcast for participants and visitors and the users wont see the room members. It seems the toggleboxes are set to some default and not grabbed from the actual room configuration.

**Comment by ChaosKid42** [comment]
This is a known bug. See https://github.com/conversejs/converse.js/issues/1039.
Already Fixed in the current development version by https://github.com/conversejs/converse.js/pull/1101 and https://github.com/conversejs/converse.js/pull/1102.
