### ISSUE TITLE
Remove Inverse’s Contacts tab when in anonymous mode

### ISSUE THREAD

**Issue by linkmauve** [conversejs/converse.js#1129]
When the user connected with ANONYMOUS SASL, contacts make little sense, so it would be better to disable them altogether.

The only action still useful in this tab is the status change, and it could be moved to the Rooms tab. Since there is only one tab left, the tab list should also be hidden.

**Comment by jcbrand** [comment]
Fixed. The newest version doesn't have tabs, so it's simply a matter of hiding the contacts' roster view from the left sidebar (i.e. controlbox).
