### ISSUE TITLE
Display the room’s vCard-temp avatar

### ISSUE THREAD

**Issue by linkmauve** [conversejs/converse.js#1130]
I already have a mockup patch available, which uses [Prosody](https://prosody.im/)’s [mod_http_avatar](https://modules.prosody.im/mod_http_avatar.html) to retrieve the image data, instead of fetching it from the vCard-temp itself: https://linkmauve.fr/files/0001-Display-the-room-s-avatar-if-it-has-a-vCard-temp.patch

Here is how it looks:
![wayland-screenshot-2018-07-14_18-22-16](https://user-images.githubusercontent.com/7755816/42726336-f9412078-8792-11e8-8bf7-07f3546ca830.png)

**Comment by jcbrand** [comment]
I like the idea, but I think your patch will show a broken image in some browsers (FF?) if no avatar is available. So the solution should probably only render an `img` tag is there really is an avatar.

**Comment by linkmauve** [comment]
Yes, and for that we need to query it from the vCard of the MUC, which is the main part of this issue.

**Comment by jcbrand** [comment]
This has been implemented recently
