### ISSUE TITLE
Converse does not work on xhtml pages

### ISSUE THREAD

**Issue by Lukc** [conversejs/converse.js#1131]
Steps to reproduce:
- take any converse.js example
- change its extension from .html to .xhtml
- enjoy XML parsing errors

**Comment by jcbrand** [comment]
Why should this project care about supporting xhtml?

**Comment by Lukc** [comment]
Well… I wanted to use converse.js and my website is xhtml. Having to switch to html for converse.js alone would be annoying.

**Comment by jcbrand** [comment]
If you're willing to make the necessary changes for xhtml support, and to make a pull request, I'll happily review and merge. Until then, I'll close this ticket, since this is not something that I'll work on.
