### ISSUE TITLE
Don’t print an error in the chat when it has been displayed to the user already

### ISSUE THREAD

**Issue by linkmauve** [conversejs/converse.js#1134]
When I joined a MUC, I got asked for my nick, and I picked a nick which was already present, which led to a proper error, but then once I selected a nick which wasn’t present already and successfully joined the MUC, this message was printed:
> Sorry, an error occurred: `<forbidden xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/>`

**Comment by Echolon** [comment]
@linkmauve does this still happen?
