### ISSUE TITLE
Open a new tab when someone sends you a private message

### ISSUE THREAD

**Issue by linkmauve** [conversejs/converse.js#1138]
In a room, private messages are currently displayed as a normal message coming from the room’s JID, see below the orange messages on the left part of this screenshot:
![](https://framapic.org/EgpZCFrfeGSV/ERYZCL9m9rV5.png)

A more user-friendly solution would be to open a new tab for each person who sends you a PM.

**Comment by jcbrand** [comment]
Yes, private MUC messages aren't yet properly supported.

**Comment by lovetox** [comment]
Right now its broken, it doesnt show the nick anymore

just

```
gajim@conference.gajim.org 11:13
Do you know how to change the font color?
```

**Comment by jcbrand** [comment]
Closing in favour of #698
