### ISSUE TITLE
Up arrow edits previous message, down arrow erases the currently writing message

### ISSUE THREAD

**Issue by Nyco** [conversejs/converse.js#1142]
This applies to computers with a keyboards, this does not apply mobile/tablets.

I have two bug scenarios. I believe they are related, I can still split this bug report.

1. Up and back down:
* I write a message in input field
* I hit the up arrow n times for whatever reason
* I hit the down arrow again, n times as well, my message I was writing is erased/blank

2. Down and back up:
* I write a message in input field
* I hit the down arrow for whatever reason
* I hit the up arrow again, my message I was writing is erased/blank

In both cases, I would expect that my temporary message should be "saved" for editing in the input field.

**Comment by jcbrand** [comment]
Fixed in 19f6bce2466a63432b541e254505594b59284f8c, but in a different way then suggested.

Here's the commit message:

Up and down arrows only serve as message correction shortcuts if the textarea is empty.
This means that: 
- Up arrow doesn't start correction of previous message if we're currently writing a message
- Down arrow doesn't erase currently written message

This is based on user-feedback and is also how Slack handles these shortcuts.

**Comment by Nyco** [comment]
Great, thanks a lot! :)

Unfortunately, it does not seem to work on my setup:
* macOS latest
* Firefox latest, Chrome latest, Opera latest
* Converse latest commit

Steps to reproduce:
GIVEN I have logged in successfully
AND I have sent a message (groupchat or one-to-one)
AND I have a new message typed in but not sent yet
AND I am navigating up/down arrow in my sent messages
WHEN I hit the bottom of the list (my currently typing message)
THEN it should be displayed in the input field textarea ready to edit again (and send later)
BUT  the input field textarea is fully blank, empty

**Comment by jcbrand** [comment]
Check again... you should not be able to edit older messages at all if you're currently drafting a new message.

**Comment by jcbrand** [comment]
@Nyco The up/down arrow now no longer works for editing messages if you have a message in the textarea. So based on your latest feedback, it sounds to me like you didn't actually have this fix applied when testing.

There is still the issue where a user clicks the pencil icon to edit a message and thereby overwrites the textarea. I think for this we can just add a confirmation dialog.

To save the previous textarea value and then revert back to it could be quite confusing to users and also complicates the code in a way that doesn't appear necessary.
