### ISSUE TITLE
Able to send a blank message

### ISSUE THREAD

**Issue by prajwalpoojari-TOPS** [conversejs/converse.js#1143]
@jcbrand 
![image](https://user-images.githubusercontent.com/41666915/43380198-db387d4e-93ed-11e8-86cb-7a4e450078ba.png)

**Comment by jcbrand** [comment]
What version are you using? How do you do this? Doesn't look to be possible in the master branch.

**Comment by prajwalpoojari-TOPS** [comment]
Version: 3.3.4

**Comment by prajwalpoojari-TOPS** [comment]
@jcbrand Thnx for your support.

As of now, we made a solution for this, We override the "onMessageSubmitted" method of "ChatRoomView" (as we are using conversejs muc embedded). Below is the code:
 
converse.plugins.add('myplugin', {
    initialize: function () {
        var _converse = this._converse;
    },
    overrides: {
        ChatRoomView: { //FOR MUC
            onMessageSubmitted : function(text){
                if (!text.replace(/\s/g, '').length) {
                    return false;
                }
                return this.__super__.onMessageSubmitted.apply(this, arguments);
            }
        }
    }
});

**Comment by jcbrand** [comment]
Thanks @prajwalpoojari-TOPS, it's fixed now in master.
