### ISSUE TITLE
With xhr_user_search, contact requests are not being sent out

### ISSUE THREAD

**Issue by michalrus** [conversejs/converse.js#1149]
Used version: 7fafc6758ec2ee5986c27b7efa081bdeefeb1a2e.

-------

My server returns the following search result:

```json
[{"fullname":"John","id":"john@mydomain"}]
```

… and this renders correctly in Converse UI.

But after clicking on “Add”, nothing happens — no new stanzas are being sent over the WebSocket, nothing in the network tab.

**Comment by jcbrand** [comment]
Much has changed since the last release, so it wouldn't be surprising if this feature broke, especially since there's no specific test for it.

I don't have an easy way to manually test this, so an automated test is really needed to expose any bugs and to avoid regressions in the future.
