### ISSUE TITLE
Make sure SVG avatars work on Firefox too

### ISSUE THREAD

**Issue by linkmauve** [conversejs/converse.js#1156]
When joining a MUC where my regular JID is present, I see most of the other people’s avatars except for mine, which is transparent rather than unset.

In Firefox’s dev console, tab Storage, I correctly see the complete base64’d SVG file in the `image` key, as well as the image/svg+xml in `image_type`.

![wayland-screenshot-2018-08-10_18-19-20](https://user-images.githubusercontent.com/7755816/43969429-67bcf06c-9cca-11e8-9850-7c5ac630cd2e.png)

**Comment by jcbrand** [comment]
Looks fixed to me...

![screen shot 2018-09-06 at 16 24 49](https://user-images.githubusercontent.com/683911/45164959-02170600-b1f4-11e8-8f9a-23871097921d.png)

**Comment by jcbrand** [comment]
Oh, I see it's a Firefox issue

**Comment by jcbrand** [comment]
@linkmauve Doesn't look to me to be a Converse issue. Have you seen this? https://stackoverflow.com/questions/23514921/problems-calling-drawimage-with-svg-on-a-canvas-context-object-in-firefox
