### ISSUE TITLE
Avatars should maintain ratio

### ISSUE THREAD

**Issue by guusdk** [conversejs/converse.js#1157]
My avatar is not square. However, when ConverseJS 4.0.0. alpha displays it in the top-left corner, it forces it to be square by skewing. That distorts the image quite a bit. It might be better to either crop, or to center a non-square image.

**Comment by jcbrand** [comment]
![screen shot 2018-09-06 at 14 18 47](https://user-images.githubusercontent.com/683911/45156929-d68a2080-b1df-11e8-9b77-84464778173d.png)

Looks fine to me, where are you seeing this and with what version?
