### ISSUE TITLE
Non-joined participants (members for instance) display an unwanted status message

### ISSUE THREAD

**Issue by linkmauve** [conversejs/converse.js#1169]
They print “ has joined the groupchat” in the MUC on our join.

**Comment by jcbrand** [comment]
Is there a MUC I can see this behaviour? I don't think I've seen it before.

**Comment by linkmauve** [comment]
You have to be owner (or at least allowed to query the member/admin/owner lists), and then join any MUC.  I reproduced at any MUC on chat.jabberfr.org, you can create any and you should automatically be the owner, there you can set some members.
