### ISSUE TITLE
XEP-0367: Message Attaching (URL previews)

### ISSUE THREAD

**Issue by rscmbbng** [conversejs/converse.js#1173]
Most web chat applications have a functionality that expands a url in a message into a small preview of the page it links to. Usually these are based on the page's open graph tags. This provides a much richer web chat experience, that is currently missing in converse.js 

See example below from 'whatsapp' web interface

![image](https://user-images.githubusercontent.com/5276865/44722388-2cb6df80-aacd-11e8-8e4c-3e1e5c653edf.png)

**Comment by jcbrand** [comment]
Yes, there is a XEP that can be used for this: https://xmpp.org/extensions/xep-0367.html

**Comment by jcbrand** [comment]
@mwild1 has already created a bot that supports it:  xmpp-sprint-playground@chat.jabberfr.org

**Comment by jcbrand** [comment]
This is supported in latest Converse via support for OGP data with XEP-0422 message fastening, as done by Prosody's mod_ogp.

https://modules.prosody.im/mod_ogp.html

**Comment by rscmbbng** [comment]
great!
