### ISSUE TITLE
XEP-0085 : unable to configure chat state notifications sendings

### ISSUE THREAD

**Issue by Aurelien6201** [conversejs/converse.js#1176]
Hello,

As mentioned in the XEP-0085 documentation (Chat State Notification), part 5.2 "Support Requirements" :
(https://xmpp.org/extensions/xep-0085.html)

_A client MUST allow users to configure whether they want to send chat state notifications._

I checked on the documentation but I was not able to find any way to customize these notification sendings (in my case I would like to disable them).
May we consider this as a Converse.js issue ?

**Comment by jcbrand** [comment]
Yep, thanks for reporting.
