### ISSUE TITLE
Bug at muc itself as a occupants?

### ISSUE THREAD

**Issue by genofire** [conversejs/converse.js#1183]
I got the error log:
```
 TypeError: e.getDisplayName(...) is undefined converse-core.js:283:12
```

Problems, seams do be here:
https://github.com/conversejs/converse.js/blob/8cc88d9b17c281e317cf7cbfcdb12df1692c1fe8/src/converse-muc.js#L314

**Comment by jcbrand** [comment]
This has been fixed in 2f2b2ceaf2d9d1968bffd9b5be25c702664f2a0c
