### ISSUE TITLE
UTF-8 characters have the wrong encoding when using OMEMO

### ISSUE THREAD

**Issue by allo-** [conversejs/converse.js#1187]
In converse.js I see UTF-8 characters (e.g. ``ü``) from apps like Conversations or gajim as two bytes like ``Ã¼`` and in Conversations I see ``�`` for such characters sent via Conversations.

The page includes:
```
<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
```

**Comment by allo-** [comment]
This happens only with OMEMO enabled.

**Comment by allo-** [comment]
I managed to fix it by modifying the arrayBuffer <-> string methods:
```
  u.arrayBufferToString2 = function (ab) { 
    return new TextDecoder("utf-8").decode(ab);
  };
  u.stringToArrayBuffer2 = function (string) {
    const bytes = new TextEncoder("utf-8").encode(string)
    return bytes.buffer;
  };
```

Now it seems to work for me. I guess you need to implement it with a API which is supported by more/older browsers as well.

**Comment by jcbrand** [comment]
Thanks, unfortunately TextDecoder/TextEncoder is not implemented in Edge.

https://caniuse.com/#search=textdecoder

**Comment by jcbrand** [comment]
This might be a solution: https://github.com/dcodeIO/bytebuffer.js

**Comment by jcbrand** [comment]
> Does the api even need conversion?

We don't just encrypt with libsignal, the browser's builtin crypto is used to encrypt the actual message and then they keys that were generated to do that are encrypted by libsignal.

**Comment by jcbrand** [comment]
Fixed in master, will be included in the next release.

**Comment by sleeksorrow** [comment]
With rev 45643d52bf1f189391b06df58d40516e52b8729f I am not able to write encrypted messages. Receiving client running "Conversations" just does not show any new message. Receiving Client running Pidgin with Lurch is showing: "There was an error decrypting an OMEMO message addressed to this device. See the debug log for details." Lurch debug log shows "failed to decrypt payload (-10020)"

Reverted to 4.0.0 to make basic sending work again

**Comment by jcbrand** [comment]
@sleeksorrow thanks for reporting, I'll look into it

**Comment by jcbrand** [comment]
I did a `git bisect` and found that the offending commit is this one: https://github.com/conversejs/converse.js/commit/e05b7e9de3083cf8c867548ee5bc51bf421f76f3
