### ISSUE TITLE
Video playback failure

### ISSUE THREAD

**Issue by contrapunctus-1** [conversejs/converse.js#1189]
I uploaded a video via HTTP Upload from Gajim. In Gajim, I clicked the link, which opened the video in Firefox. Firefox was able to play it.

When I try to view the same video inline from inverse.chat, I get the "No video with supported format and MIME type found." error where the video should be.

Firefox 62.0 (32-bit), Debian GNU/Linux 9.5 (stretch)

**Comment by jcbrand** [comment]
Can you give me the URL of the video so that I can test it myself?

**Comment by contrapunctus-1** [comment]
https://upload.jabberfr.org/GCeF7Nlmw65QDQet/no%20burn%20zing%20-%20Z89GV7mRN2AFy.mp4

**Comment by jcbrand** [comment]
@contrapunctus-1 I took a look... at first the video didn't play and then after playing around with markup it started playing. But here's the crazy part, now it also plays with the original markup.

Looks to me like a Firefox bug. In any case, it started playing once I removed the `<source>` element. So I updated the code to not have that.

Can you test again?

**Comment by contrapunctus-1** [comment]
(Again using inverse.chat) Sorry, no change. 🙁

**Comment by jcbrand** [comment]
inverse.chat hasn't been updated yet.

**Comment by contrapunctus-1** [comment]
Tried it by hosting it locally. It's working!

**Comment by jcbrand** [comment]
Super, thanks for checking.

**Comment by contrapunctus-1** [comment]
I'm still getting this on Firefox v77.0.1 (32-bit), Debian Testing, using inverse.chat.

Sent from jabber.fr -> conference.jabberfr.org. Both the sending account and another account on jabjab.de face this issue.
