### ISSUE TITLE
Inefficient completion

### ISSUE THREAD

**Issue by contrapunctus-1** [conversejs/converse.js#1194]
If a room has members foo, bar and baz, pressing "f <TAB>" or "fo <TAB>" should automatically complete to "foo" (it's the only one starting with "f"/"fo") - instead, it shows it to me as the only candidate in the completion list, you have to click on it. I just realized that pressing Tab again will select that completion, but it seems hard to discover as well as inefficient - if there's just one possible candidate, why not expand it on the first tab itself?

**Comment by jcbrand** [comment]
I'm not sure I prefer your proposal. You might be thinking that there's someone else's name that starts with "fo" and who is still in the chat.

By showing you only one result, you can see that the other person is no longer there.

Also, learning to type tab quickly twice is not hard.
