### ISSUE TITLE
@ highlights are not correctly converted to references

### ISSUE THREAD

**Issue by Ppjet6** [conversejs/converse.js#1198]
Version: 989ce0f54 (master)

Also mentioned in #1197.

## Steps to reproduce

In a chatroom with `userU` joined, or has an affiliation that is not none:
- Type `@userU` in the input, (you get the selection thingy)
- `userU` leaves the room, or affiliation gets revoked
- Send the message

## What happens

Message appears (and is sent) as `@userU`, and not `userU` (with the added reference in `<body/>`).

## What I expect

Not entirely sure to be honest..
Converse could keep some kind of cache for $duration, and send a reference to the last known nick with that value.

This is less of an issue when the target user doesn't appear in the list in the first place, (not joined or no affiliation).

**Comment by jcbrand** [comment]
Not worth the effort, I think it's OK the way it is now.
