### ISSUE TITLE
Link encoding issue

### ISSUE THREAD

**Issue by guusdk** [conversejs/converse.js#1204]
In 4.0.0, a message that contains this URL displays a link that, when clicked, returns to an incorrect page.

Link used: https://github.com/xsf/xeps/pulls?q=is%3Apr+is%3Aopen+label%3A%22Needs+Council%22
Page opened: https://github.com/xsf/xeps/pulls?q=is%253Apr+is%253Aopen+label%253A%22Needs+Council%22

Note that both link open a Github issue list, but one of them is empty (the filter used is different).

This problem reportedly does not occur in other client (Poezio) that receive the link. That makes it reasonable to assume that the problem lies within Converse's parsing/encoding routines.

**Comment by jcbrand** [comment]
Fixed, thanks.
