### ISSUE TITLE
Close button in edit popup doesn't work

### ISSUE THREAD

**Issue by poVoq** [conversejs/converse.js#1211]
At least in the anonymous chat demo the "close" button on the popup that shows the changes of edited messages doesn't work at all. Only by pressing the "ESC" button on my keyboard I can escape that popup.

**Comment by jcbrand** [comment]
I just tested in both Firefox and Chromium. Works fine for me.

**Comment by poVoq** [comment]
Firefox 62.02 on Linux.

**Comment by jcbrand** [comment]
Can you still reproduce with the latest code? Make sure to clear your cache.
