### ISSUE TITLE
On webview based mobile browsers the layout is a bit broken

### ISSUE THREAD

**Issue by poVoq** [conversejs/converse.js#1212]
On my Webview based Android app and also the default LinageOS browser that uses the internal webview the layout of the chat is a bit broken. It works fine on Firefox Mobile.

The setup is a link to a fullscreen chat, that works nicely on Desktop browsers. However when using it with a webview (chrome based) browser it seems to switch to some sort of mobile view fine, but part of the HTML background (that is normally not visible at all) is bleeding through that the top 20% of the screen or so.

Oh and is there a way to auto-hide the right hand participants side-bar mobile browsers?

**Comment by jcbrand** [comment]
Should be fixed now, can you please check again?

**Comment by poVoq** [comment]
Which branch? This was with a check out from the Master branch and 4.0.1 /dist binaries.

**Comment by jcbrand** [comment]
Should be fixed in this commit in master: https://github.com/conversejs/converse.js/commit/1dbaa37f98db2be77574de5b28ac42c63aeb2647
