### ISSUE TITLE
Switch roster filter input and icons

### ISSUE THREAD

**Issue by deleolajide** [conversejs/converse.js#1213]
It's not clear how to filter the contacts... maybe put 2 drop-down side by side? Its confusing having icons to the right that change something to their left...

**Comment by jcbrand** [comment]
> Its confusing having icons to the right that change something to their left...

What do you mean by this?

**Comment by deleolajide** [comment]
Sorry, I should have put a quote on this.  The [original issue](https://github.com/igniterealtime/Pade/issues/50#issuecomment-419736442) was from @IzzabelleM

I stood behind her watching her trying to use the contacts filter.  Maybe switching the icons to the left might be more intuitive as @IzzabelleM suggested.

**Comment by jcbrand** [comment]
Funnily enough, it used to be two dropdowns, but IIRC the bootstrap 4 design from Benoit Roy introduced the icons instead of a dropdown.
