### ISSUE TITLE
Setting allow_contact_requests: false has no effect

### ISSUE THREAD

**Issue by focus121** [conversejs/converse.js#1214]
#### Issue description

It doesn't have an effect when set the Configuration setting "allow_contact_requests" too "false". Still the **Add a contact** widget, **Contact Requests** and **Pending Contacts** roster sections appear.

#### Steps to reproduce the issue

1.  Configure in the *initialize* method the setting. 
`allow_contact_requests: false`

Guess its needed to regenerate the minified. I did.

#### What's the expected result?

-  **Add a contact** widget, **Contact Requests** and **Pending Contacts** roster sections not appear

#### What's the actual result?

-  **Add a contact** widget, **Contact Requests** and **Pending Contacts** roster sections appear

**Comment by poseroo** [comment]
I did that also, but it has no effect. Is it a bug? or did i also do something wrong?
