### ISSUE TITLE
Funny issue with the spinner revealing vertical scrollbar

### ISSUE THREAD

**Issue by luciash** [conversejs/converse.js#1216]
On the loading screen there is an animated spinner which reveals animated horizontal scrollbar on hover...
See the screencast recorded: https://youtu.be/iwFqMKx934Y

**Comment by luciash** [comment]
Chrome Canary 71.0.3575.0 on Win10. Happens only on loading as seen on the video when it is loading for longer time. Try Ctrl+F5 to reload the window and DevTools inspect?
On the "Sources" tab you can pause the script execution quickly after the reload to see that issue. Hmm, could it be only Padé related?

Anyway, this is the element causing it:
`<span class="spinner fa fa-spinner centered"></span>`

There is this in converse.css on line 9008:
```
#conversejs .spinner {
    -webkit-animation: spin 2s infinite, linear;
    -moz-animation: spin 2s infinite, linear;
    animation: spin 2s infinite, linear;
    display: block;
    text-align: center;
    margin: 2em;
    font-size: 24px;
}
```

I suggest to add e.g. max-width: 100px to the CSS rules for #conversejs .spinner or limit the parent element with overflow: hidden to prevent the accidental reveal of the scrollbar when the element is rotating.

**Comment by jcbrand** [comment]
Thanks for giving all the info. I did inspect it and specifically that element your mentioning, and for me it was not longer than the containing element, and wasn't causing a horizontal scrollbar.

It might be a Pade thing or a Windows thing (which I find unlikely).

**Comment by luciash** [comment]
Is the spinner spinning for you? Because it has display: block the element has full width of the parent and when it rotates it causes the issue as seen on the video. Maybe your parent element or window has limited width so it does not do it for you?

Can we forward this issue to https://github.com/igniterealtime/Pade somehow?

**Comment by deleolajide** [comment]
Pade always does auto-login and never shows the login prompt. I never seen it on my Windows desktop with Chrome stable and dev channel version. I will install Canary and try to re-produce.

**Comment by deleolajide** [comment]
I can't reproduce it with Chrome Version 72.0.3581.0 (Official Build) canary (64-bit). Here is my screencast captured with Pade :-)

https://wikisuite.net:7443/httpfileupload/5498493f-dc3b-41fa-8b3e-c50088f08313/screencast-6hkdxvqsv.webm

**Comment by luciash** [comment]
put breakpoint on line 52798 of converse.js
 
(right click the line number and choose "Add breakpoint")
 
it should pause after ctrl+F5 on the loading screen so you can see the issue with scrollbar on right edge of the window of the spinner
 
See https://developers.google.com/web/tools/chrome-devtools/javascript/breakpoints for more help

**Comment by luciash** [comment]
Thanks! I confirm the problem is gone in v4.0.5
