### ISSUE TITLE
disconnects when updating vcard

### ISSUE THREAD

**Issue by poseroo** [conversejs/converse.js#1219]
whenever i click on the profile, the vcard dialog box opens. II try to add more than one field in one go, the session disconnects and then after clearing the cache and re-logging in a good few times the whole thing works. is this a bug or just happenning in my case due to incorrect settings in my converse installation?

**Comment by jcbrand** [comment]
Set `debug` to `true` when calling `converse.initialize` and then try it again. Look for errors in the browser's developer console and if you find any, paste them here.

**Comment by poseroo** [comment]
![image](https://user-images.githubusercontent.com/22302517/46099481-81d93480-c1e4-11e8-84af-eb2ae2feb1e5.png)

**Comment by poseroo** [comment]
I sent u an email with credentials through the contact form.

**Comment by poseroo** [comment]
i changed the files back. yes there was other javascripts. i have just removed them so that u can test.

**Comment by poseroo** [comment]
https://sonkhya.com/newversion/ this is where the server is hosted

**Comment by poseroo** [comment]
i made these changes in the css: 
<style>
.brand-heading,.brand-subtitle,.switch-form{
display:none;
}
.icon-conversejs{
display:none; 
}
#converse-login-panel{
background-color: #ccc;
}
.chatbox-btn.add-contact{
display:none; 
}
.chatbox-btn.show-add-muc-modal{
display:none; 
}
</style>

**Comment by poseroo** [comment]
![image](https://user-images.githubusercontent.com/22302517/46102389-c6b49980-c1eb-11e8-8c81-baa1b4888216.png)
it keeps on giving unable to connect to strophe.js...

**Comment by jcbrand** [comment]
Thanks, I won't be able to do any testing today, and I'll first test with a vanilla Converse install on my own machine.

**Comment by poseroo** [comment]
If I write a plugin to hook the messages, then when i try to update vcard it crashes. I wrote a plugin to include mathjax, then i wrote another plugin to hook  into the messageSend method using mathquill. In both cases, on updateVcard converse crashes.

**Comment by jcbrand** [comment]
This issue tracker is only for issues with the standard (vanilla) Converse, not with customized versions.
If you can't reproduce the problem with vanilla Converse, then the problem most likely is in your own customizations and you'll have to look there for a fix.
