### ISSUE TITLE
IE11 regression

### ISSUE THREAD

**Issue by ao2** [conversejs/converse.js#1224]
Hi,

a contact of mine was not able to use the latest version of conversejs from work, where he's required to use IE11.

Version 3.3.4 works fine, but that does not have OMEMO, while newer versions didn't work, giving a blueish page with nothing else on the fullpage screen.

To recap, on Windows 7 with IE11:
- https://conversejs.org/3.3.4/ works fine
- https://conversejs.org/4.0.0/ and https://conversejs.org/ do not work
- https://conversejs.org/4.0.0/fullscreen.html and https://conversejs.org/fullscreen.html give a bluiesh page

I am not sure if there is any network filtering too in his case which can interfere with loading resources needed by conversejs.

Is anyone able to reproduce the problem?

Thanks,
   Antonio

**Comment by MotoGP-Fan** [comment]
Hi Antionio, have a look here to JC's answer:
https://github.com/conversejs/converse.js/issues/1220

**Comment by jcbrand** [comment]
Yes, unfortunately for your contact IE11 is no longer supported from version 4.

**Comment by ao2** [comment]
I see, thanks anyway.
