### ISSUE TITLE
when enabling xep 0360, one cannot click on the contacts anymore

### ISSUE THREAD

**Issue by poseroo** [conversejs/converse.js#1226]
Hi
I installed the latest version of converse. I also enabled xep 0360 in ejabberd. After that whenever i login, if I click on the contacts on the left window the chat window does not open.

please find console details:
![image](https://user-images.githubusercontent.com/22302517/46078712-8dac0300-c1b2-11e8-9b9d-48cf87d396a7.png)

**Comment by poseroo** [comment]
what am i doing wrong in provisioning converse? or are there any compatibality issues ejabberd xep0363?

**Comment by jcbrand** [comment]
> or are there any compatibality issues ejabberd xep0363?

Looks like there might be. Could you create a test account for me so that I can debug this?

If so, please send the credentials to me through my contact page: https://opkode.com/contact.html

**Comment by poseroo** [comment]
i sent u credentials
username sandratest@isientrance.com
password sent to u en email

**Comment by poseroo** [comment]
if i download and use vanilla converse this problem is not there. but if i make changes to the template and then make build and make dist and use the newly built conversejs this problem crops up.

**Comment by poseroo** [comment]
after removing browser history and cache it is working.. but it does not update contact list automatically one each login. is there a way to ensure converse does not store anything in history or cache.  I have also got the http file upload working with ejabberd. kindly let me know how to disable cache and browser history.

**Comment by jcbrand** [comment]
> kindly let me know how to disable cache and browser history.

You can try setting the [trusted](https://conversejs.org/docs/html/configuration.html#trusted) setting to `false`, so that contacts and messages aren't cached beyond the current session.

**Comment by jcbrand** [comment]
The problem here is the `invalid arguments` error, which prevents chats from being opened.

Looks like you're using a modified version of Converse here, is that true? If so, then I can't help you further, sorry.

If you can reproduce this problem with the latest version of Converse and without any modifications, then please reopen this bug report.
