### ISSUE TITLE
Login form does not work in Epiphany

### ISSUE THREAD

**Issue by Zash** [conversejs/converse.js#1227]
When clicking 'Log in' nothing appears to happen, save the following shows up in the console:

```
[Error] TypeError: form_data.get is not a function. (In 'form_data.get('trusted')', 'form_data.get' is undefined)
    authenticate (converse.js:62663)
    wrapper (converse.js:14184)
    (anonymous function) (converse.js:2131)
```

-   [Gnome Web aka Epiphany version 3.22.7 from Debian 9](https://packages.debian.org/stretch/epiphany-browser)
- Converse.js version 4.0.1
- mod_conversjs

**Comment by jcbrand** [comment]
I'm quite sure the problem here is that Epiphany doesn't support the [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData) API.

The next release of Converse will include a polyfill (because Edge also doesn't support it fully).

**Comment by jcbrand** [comment]
It should be fixed in this commit: https://github.com/conversejs/converse.js/commit/31080bf2f95735012323e4bdf1f7dccd05ea50e6
