### ISSUE TITLE
Can not setup development env? dev.html contains dist/converse.js, libsignal-protocol.js is missing ...

### ISSUE THREAD

**Issue by goors** [conversejs/converse.js#1239]
Hi,

```
1. clone repo
2. make dev
3. make serve
```

`http://127.0.0.1:8000/3rdparty/libsignal-protocol-javascript/dist/libsignal-protocol.js net::ERR_ABORTED 404 (Not Found)` is missing and `dev.html` contains `dist/converse.js`. When you try to change  `dev.html`  with `src/converse.js` or `src/converse-core.js `nothing is happening you still get can not get `Uncaught ReferenceError: converse is not defined.`

So can you help out or push some new files that are missing or that are modified?

**Comment by licaon-kter** [comment]
Did you put `libsignal-protocol-javascript` there? It's not included by default...

**Comment by goors** [comment]
Forget libsignal-protocol.js. What about dist/converse.js, i mean you said in your document:

> However, when developing or changing the theme, you’ll want to load all the unminified JS and CSS resources as separate files. To do this, open http://localhost:8000/dev.html instead.

What is loaded unminified?

**Comment by goors** [comment]
How do you edit template, refresh page and see new chnages? I dont see how you can do that if you load it via cdn?

I mean all of that stuff from src/ must be loaded separately if you eant to see changes.

You edit src/somehtmlfile and you see chnages when you recresh browser.

So it is more like how to start project in development with all that stuff from src?

**Comment by goors** [comment]
yes, @jcbrand thank you.

**Comment by goors** [comment]
@jcbrand maybe you can help me out with omemo, every time i try to send encrypted message i got error: `sorry, could not send the message due to an error. Identity key changed with omemo enabled.`

**Comment by jcbrand** [comment]
I haven't seen that one before. Are you testing between Converse and a different XMPP client?

**Comment by goors** [comment]
@jcbrand I am testing with two browsers and two users. Every time when trying to send message i got that: `sorry, could not send the message due to an error. Identity key changed with omemo enabled.`

**Comment by goors** [comment]
@jcbrand now when i add two new users no "lock" icon is present (libsignal is loaded of course). I can see both fingerprints of both users in their profile but when i click on profile of some user in contacts Omemo fingerprints is empty.
also when i add users to rooster I have to login/logout so that pending contacts disappear.

**Comment by goors** [comment]
@jcbrand i am also getting invalid date in messages and no messages are sent .... wired!

**Comment by jcbrand** [comment]
Ok, one thing at a time. Set `debug: true` when calling `converse.initialize` and then set logging to `verbose` in the browser console.

Then try to reproduce a particular problem (not all at once :)), look for errors or feedback in the browser's dev console.

Then create a new ticket in github where you paste the errors and describe the problem. Do this for each problem you have. Also, please don't use modified code, only vanilla Converse, otherwise I can't help.

Thanks.

**Comment by goors** [comment]
as far as i can see u can send one message and then key changes and you got this error `sorry, could not send the message due to an error. Identity key changed with omemo enabled.`
