### ISSUE TITLE
Can't switch presence to "Online"

### ISSUE THREAD

**Issue by ticpu** [conversejs/converse.js#1241]
I'm using ejabberd-18.04 as a server and ConverseJS 4.0.2 as a client connected via http-bind.

If I mark my first computer ConverseJS as Away, I can not set my second computer ConverseJS to Online and I can not remove the status message. Both of those reset to the state of the other browser upon selection.

In summary, the server echoes back the other client's status and the new client not only show the remote status but also applies it to the current resource.

**Comment by Echolon** [comment]
@ticpu does this still happen in the latest version?

**Comment by ticpu** [comment]
Sorry about that but we completely switched product to Mattermost in the end, I don't have anything set-up to try and replicate issue.
