### ISSUE TITLE
changing colour of text messages

### ISSUE THREAD

**Issue by poseroo** [conversejs/converse.js#1243]
Hi
I was thinking of doing this:

    converse.plugins.add('myplugin', {
     	overrides: {
         MessageView: {
             render: function () {
                     return this.__super__.render.apply(this);
             }
         }
     }

On doing this what I found that the colour of all chat messages change.
I want to change the colour of last chat message only.
Which function in which class should i override?

Also the jsfiddle in docs don't work.

**Comment by jcbrand** [comment]
> Which function in which class should i override?

There is no particular function that lets you know what message is the last. You'll probably have to write your own code that checks whether a message is the last one in the chat view area and then adds the class.

> Also the jsfiddle in docs don't work.

Just tried it and works fine for me.
