### ISSUE TITLE
avatar not loading in safari and firefox browser

### ISSUE THREAD

**Issue by martinmix** [conversejs/converse.js#1248]
After login my own avatar and  contacts avatar are not loading..Avatar loading only in chrome browser

**Comment by martinmix** [comment]
No..There is no svg avatar..Some of the avatar set by Conversations and dino messenger and converse also..none of the avatar is coming

**Comment by jcbrand** [comment]
Can you provide a screenshot? Are you self-hosting converse or using conversejs.org?

**Comment by martinmix** [comment]
I am using converse cdn

**Comment by martinmix** [comment]
@jcbrand  I got the problem.I am using webp avatar which is only support by chrome browser.That is why other browser not showing the avatar..Please close this if it is not possible to load webp in other browser

**Comment by jcbrand** [comment]
Thanks for letting me know.
