### ISSUE TITLE
Change favicon color when unread messages

### ISSUE THREAD

**Issue by Tomo59** [conversejs/converse.js#1250]
In fullscreen mode, it would be good to be able to change the color of the favicon to red  when you have unread messages. This would let people know just looking at the converse tab favicon that they have unread messages if they missed the notification.

If changing favicon color is not possible, maybe changing the title of the page would be a good alternative (but in this case, when the tab is pinned in Chrome, we won't be able to see it).

**Comment by Papyruse** [comment]
+1

**Comment by Tomo59** [comment]
Hello, I see that in current version of master branch we have now the title of the page (in fullscreen mode) changing to "Messages (1) converse" when we have a new message.
So part of this issue is solved.
Would it be possible to change the favicon at the same time (maybe a red colored version of the logo) ?

**Comment by koolok** [comment]
On Firefox, when the tab is minimized, a little blue dot appear below the favicon, this is the default behavior when a tab receives a notification.
![Capture d’écran de 2020-10-29 11-35-22](https://user-images.githubusercontent.com/17029055/97558089-eecee200-19db-11eb-8f65-783326434fc7.png)

**Comment by deleolajide** [comment]
> Would it be possible to change the favicon at the same time (maybe a red colored version of the logo) ?

This exists as a plugin right now. It might be good time to promote it to core code

![image](https://user-images.githubusercontent.com/110731/97564756-f8a51500-19dc-11eb-9cda-d25a3d1d795c.png)


https://github.com/conversejs/community-plugins/tree/master/packages/browsertab

**Comment by jcbrand** [comment]
@deleolajide Pull requests welcome.
