### ISSUE TITLE
Bubble up contacts with unread messages in the contact list.

### ISSUE THREAD

**Issue by guusdk** [conversejs/converse.js#1253]
I frequently miss new one-on-one messages, as my contact list is pretty long, and the 'unread message count' indicator is "below the fold", using the default 'any' filter. Switching to the 'unread' filter fixes the issue, but doesn't let me see my online users. I'd love for contact list entries that have unread messages to move up the contact list UI thingy.

A suggestion that JC made was to create an "unread messages" pseudo group. I'd be happy with that.

**Comment by licaon-kter** [comment]
Can you not duplicate the contact? If it's on top there's no need to have it lower too, but once I read it....pull it back in  place :)

**Comment by jcbrand** [comment]
I've wondered about that.

I don't like how in Slack a contact disappears because the chat is now at the top under the threads heading.
