### ISSUE TITLE
File-Upload not working in Version 4.0.3

### ISSUE THREAD

**Issue by worlword** [conversejs/converse.js#1261]
I've tried to send a File in a Single-User-Chat in converse.js 4.0.3. I used the paperclip symbol in the toolbar to open the dialog and selected a file. After that the progress-bar for the upload showed up. And that's it. Nothing else happens. I can still send Text afterwards and also try to upload new files (same result). 

System-Information:
XMPP-Server: eJabberd 18.04
Apache: 
  Server version: Apache/2.4.6 (CentOS)
  Server built:   Apr 20 2018 18:10:38
Test-File: 
  - HTML-File with "Hello World" as content
  - Size 11 Bytes
Browser: 
  - Chrome Version 69.0.3497.100 (Offizieller Build) (64-Bit)

The Browser-Console-Log shows an Error upon PUT-Request (see later screenshots) and atfer that there are some promise-Errors: 
![converse_4_0_3_promise_error_during_fileupload html](https://user-images.githubusercontent.com/38032700/47360174-198c4e80-d6cf-11e8-82a5-978f57718655.png)
Those Errors propably cause the progress-bar to stay forever.

The PUT-Request: 
![dateiuploadversion4_0_3](https://user-images.githubusercontent.com/38032700/47361069-5bb68f80-d6d1-11e8-9654-daf35aff1c69.png)

The actual Response says:
![dateiuploadversion4_0_3_response](https://user-images.githubusercontent.com/38032700/47360292-72f47d80-d6cf-11e8-900f-c03f59041c47.png)

When I use git to switch back to converse.js Version 4.0.1 and try that version, it works. The following is a screenshot of the same request with 4.0.1:
![dateiuploadversion4_0_1 html](https://user-images.githubusercontent.com/38032700/47361081-61ac7080-d6d1-11e8-98ea-74267b9f72d3.png)

I've tried with several diffrent files: .png, .jpeg, .mp4, .html, .txt. They all work with 4.0.1 but not with 4.0.3. I also tried 4.0.2 shortly. Here the same error occurs.

**Comment by laszlovl** [comment]
Can confirm, although it was working properly for me in 4.0.2 as well.

**Comment by jcbrand** [comment]
@worlword Would it be possible to give me a test account? File uploads work for me in 4.0.3 on my own server.

**Comment by licaon-kter** [comment]
Seeing the same on ejabberd 18.09

**Comment by jcbrand** [comment]
Well, if any of you can give me a test account I can check.

**Comment by licaon-kter** [comment]
Updated to HEAD, still error 413, but now ejabberd is rejecting the upload: https://gist.github.com/licaon-kter/8e596c86639ce8b3474b674dcfd93529

As others above, this works fine at least in 4.0.1.

**Comment by jcbrand** [comment]
@licaon-kter Yes, I heard last night in the chat. I'm not sure what the issue is, it's working for me locally with Prosody.

A test account would help me reproduce/debug.

**Comment by mightymop** [comment]
i can confirm this bug on openfire servers too
can not upload files.

1st Error on my Server with converse js Version from cdn:
> Uncaught (in promise) Error: Invalid arguments at filesize...
![err1](https://user-images.githubusercontent.com/24775073/47545863-cb559600-d8ee-11e8-9f23-b35a76d37d6b.JPG)

2nd error on converse js website logged in on my server:
> Error: Invalid arguments filesize.js:57

![bildschirmfoto vom 2018-10-26 07-05-01](https://user-images.githubusercontent.com/24775073/47545641-9b59c300-d8ed-11e8-8695-ec770f9a4bd2.png)

**Comment by worlword** [comment]
Hallo. Sorry for the late replay I was very busy the last Days. 
Sadly I cannot give a test-account because it is not possibly to reach the server from the outside.

Maybe I can look into it on the weekend to find out what causes the bug.

**Comment by laszlovl** [comment]
Can confirm it's still broken for me in master as well, using Ejabberd 18. I have a test account/setup ready at request.
