### ISSUE TITLE
How to disable MUC join/leave messages

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/converse.js#1263]
I have `muc_show_join_leave: false` yet either it doesn't work or it doesn't do what I want since I see continuous messages like:
```
xxx has entered the groupchat
xxx has left the groupchat
xxx has been given a voice again
xxxxx has left the groupchat
xxxxx has been given a voice again
xxxxx has entered the groupchat. " (Abwesend wegen Untätigkeit für mehr als 5 Minuten)"
xxxx has been given a voice again
```

**Comment by jcbrand** [comment]
I think this option broke with the 4.0.x release.

In any case, I think this option should be removed in favor of a more configurable one, as mentioned here: https://github.com/conversejs/converse.js/issues/1260
