### ISSUE TITLE
Server Broadcasts will not be shown

### ISSUE THREAD

**Issue by mightymop** [conversejs/converse.js#1274]
Server Broadcasts will not be shown.

What i have done:

I've extended the openfire broadcastplugin and tries to send server broadcasts to users or muc.
I tested it with Conversations. 

Message Packets:

>Users:
`DEBUG: <body xmlns="http://jabber.org/protocol/httpbind" ack="3232148937"><message from="mopsdom.de" xmlns="jabber:client"><subject>(broadcast)</subject><body>test</body></message></body>`

>MUC Room:
`DEBUG: <body xmlns="http://jabber.org/protocol/httpbind" ack="3232148936"><message type="groupchat" from="ccc@conference.mopsdom.de" to="mops@mopsdom.de/converse.js-88192652" xmlns="jabber:client"><body>test</body></message></body>
`

In Conversations Messenger: 
If the broadcast was send to user jids, a user with the xmpp domain as jid will be shown in the roster with the broadcast as a message.
Even in a MUC the broadcast message will be shown as send by the MUC room.

ConverseJS: 
I can see that the message arrives on conversejs (debug mode). But thats all?!

Furthermore a broadcast to a user jid will notify me via desktopnotification but then its gone.

**Comment by jcbrand** [comment]
Hi @mightymop, do you know in which XEP these are defined?

I would expect your first message to be of type `headline`, then it would work in Converse (in "overlayed" view mode).

**Comment by mightymop** [comment]
Type Headline also has no effect on conversejs.
On Conversations the message became a private one in MUC.

`DEBUG: <body xmlns="http://jabber.org/protocol/httpbind" ack="3705315253"><message id="372c3cc4-b93d-45cb-9d7e-2720add1afe8" from="ccc@conference.mopsdom.de" type="headline" to="mops@mopsdom.de/converse.js-30275537" xmlns="jabber:client"><body>test/body></message></body>`

I send standard messages ... with type "chat" or "groupchat" and a childelement "body" with the message as text.
The XMPP packet looks like this:

<message id="UNIQUE ID" from="channel@conference.xmppdomain or xmppdomain" type="groupchat or chat" to="user@xmppdomain/ressource" xmlns="jabber:client"><body>messagetext</body></message>

**Comment by jcbrand** [comment]
> Type Headline also has no effect on conversejs.

Headline messages appear in overlayed view mode, but not in fullscreen view mode.
https://conversejs.org/docs/html/configuration.html#view-mode

**Comment by mightymop** [comment]
ok.. but i need the fullscreen mode :/

**Comment by mightymop** [comment]
Its related to this issue:
[](https://github.com/conversejs/converse.js/issues/1021)
