### ISSUE TITLE
Change MUC nickname without rejoining

### ISSUE THREAD

**Issue by guusdk** [conversejs/converse.js#1280]
It'd be nice if it were possible to change the nickname that you're using in a MUC without having to explicitly leave the room and rejoin it.

**Comment by Nyco** [comment]
Yep.

Solution lies in adding an item in https://github.com/conversejs/converse.js/issues/1282 ?

**Comment by jcbrand** [comment]
You can change your nickname by typing `/nickname mynewnick`

**Comment by guusdk** [comment]
The room info modal is the first place where I looked to find the functionality, so given the current UI, that seems to be a logical place to me. :)

**Comment by jcbrand** [comment]
This is doable nowadays, there's a nickname modal with which you can change your nickname from within the MUC.
