### ISSUE TITLE
Edit Bookmark

### ISSUE THREAD

**Issue by guusdk** [conversejs/converse.js#1281]
There's no way to edit a bookmark, other than to remove it, and recreate it.

Recreating works, but also means that my bookmark temporarily disappears on the right-hand side (the room name, if modified, changes). Also, changing the nickname does not appear to have any effect until after you rejoin the room.
 
Not super-critical, but would be nice to have fixed properly.

**Comment by licaon-kter** [comment]
It's not super clear that touching the icon removes the bookmark, destructive actions should have a confirmation dialogue.

Maybe the bookmark icon could open the same "add bookmark" view to either edit (nick?) or via a new button delete the bookmark.

**Comment by Nyco** [comment]
Edit nick is here: https://github.com/conversejs/converse.js/issues/1280

1. Is the bookmark icon a toggle? "Bookmark this room" vs "Unbookmark this room"?

2. "Bookmark this room" should show a dialog "Input room name"?

3. "Unbookmark this room" should show a confirmation dialog?

4. Should "Unbookmark" and "Leave" be the same? Like in some (team) chats: "Leave and destroy/delete history"? (so that the user understands the implications, maybe)

**Comment by jcbrand** [comment]
> destructive actions should have a confirmation dialogue.

Agreed.

> Maybe the bookmark icon could open the same "add bookmark" view to either edit (nick?) or via a new button delete the bookmark.

Yes.

**Comment by jcbrand** [comment]
> Is the bookmark icon a toggle? "Bookmark this room" vs "Unbookmark this room"?

Currently it's a toggle but I agree it's not optimal.

> Should "Unbookmark" and "Leave" be the same? Like in some (team) chats: "Leave and destroy/delete history"? (so that the user understands the implications, maybe)

I don't think so. I regularly leave rooms and I then don't want to unbookmark the room.

**Comment by Nyco** [comment]
These 4 questions are rather asked to the current and target users, not to developers.

**Problem**

So we have that "bookmark" concept that seems quite specific to the XMPP/Jabber space.
This clearly belongs to the web browser space.
The transposition/translation/transcription from web to IM is uncomfortable, seems strange to users.
And it's not Converse-specific, this issues has always been there with XMPP clients.
It has proven to be disturbing to non-developers users, and non-XMPP-savvy people over the years.
People usually expect what we also find in most current and widely used IM systems, and a bookmark concept does not belong here.

**Potential solution**

The expected software behaviour is rather more or less the following way (with variations):

When a user joins a channel/groupchat, he/she get all the messages notified, in his/her history, in all his/her devices (but that is largely out of the scope of this ticket).

Focus on the subject of this thread, and specific to XMPP/Jabber:
Thus all groupchats should probably be persistent and **bookmarked** by default when joined/created.

**Comment by guusdk** [comment]
I don't dislike the idea of implicitly creating bookmarks. Let's take that out of scope of the issue described in this ticket though. Even if bookmarks are automatically created upon join, I'd still like an 'edit' function.

**Comment by stevenroose** [comment]
I think clicking the bookmark button should show the edit menu and have a "delete bookmark" button next to the save button.

**Comment by rodrigolzd** [comment]
+1 for editing bookmarks!

**Comment by jcbrand** [comment]
Closing, as it's now possible to edit a bookmark.
