### ISSUE TITLE
Send button in message input field

### ISSUE THREAD

**Issue by Nyco** [conversejs/converse.js#1283]
### Problem

There is no send button in message input field, thus on mobile or tablet, users are disturbed, as they expect a specific button, even though and CR/LF sends the message.

That is less an issue for desktops/laptops.

### Solution

Most (team) chat/IM provide this send button. This usually is not displayed when there is no text entered, it dynamically shows up when text is (being) entered, and is cleared when message is sent.

**Comment by jcbrand** [comment]
There is a `show-send-button` config setting for this, but I think it broke with the version 4 release.

https://conversejs.org/docs/html/configuration.html#show-send-button

**Comment by licaon-kter** [comment]
This is fixed now.

Should I open a new issue if I'd like this button to be moved on vertical?

**Comment by jcbrand** [comment]
> Should I open a new issue if I'd like this button to be moved on vertical?

Yes please.
