### ISSUE TITLE
Mobile: login and conversation list are cut

### ISSUE THREAD

**Issue by Nyco** [conversejs/converse.js#1285]
Samsung Galaxy S8 (SM-G950F), Android 8.0.0
NOK: Brave and Chrome latest
OK: Firefox latest

### Login screen

![screenshot_20181029-130553_chrome](https://user-images.githubusercontent.com/25348/47649486-b80c2a00-db7d-11e8-9f99-0bf237401e23.jpg)

### Conversation list

![screenshot_20181029-130602_chrome](https://user-images.githubusercontent.com/25348/47649481-b3477600-db7d-11e8-90b4-e7432312a6b8.jpg)

**Comment by Nyco** [comment]
Looks like I don't have this issue anymore.

**Comment by jcbrand** [comment]
I think this was fixed by #1572
