### ISSUE TITLE
Catching HTTP 403 response without body

### ISSUE THREAD

**Issue by laszlovl** [conversejs/converse.js#1287]
When uploading an avatar image, Ejabberd may return a HTTP 403 response without body. (Ejabberd logs don't reveal any information, but it looks like this happens when the image is too large).

When this happens, Converse gets in a broken state where it's still running, but your roster disappears and no new messages are processed.

Error log:

```
ERROR: request id 13.1 error 403 happened
_onRequestStateChange

XML Parsing Error: no root element found
Location: https://bosh.domain.com/http-bind
Line Number 1, Column 1:
```

**Comment by Echolon** [comment]
@laszlovl can you still reproduce this with the latest release?
