### ISSUE TITLE
Add back "me " and "" them " class back to differentiate between incoming message and outgoing message.

### ISSUE THREAD

**Issue by golangbu** [conversejs/converse.js#1288]
Can we have some difference between incoming message and outgoing message.May be different colour message bubble  or left side send message and right side receive message.

**Comment by martinmix** [comment]
WOW. nice idea.

**Comment by Nyco** [comment]
Quick investigation:

* Coloring me/them: it seems that modern team chats don't do that anymore, but only smartphone interpersonal chat keep on doing that
* Chat bubbles have completely disappeared from team chats

Thats seems to be some code to maintain and test for very few value.

**Comment by golangbu** [comment]
Actually I am asking for to add back "me " and "" them " class back .
If somebody like bubble they can change in css class.Right now it is not possible to differentiate the sender and receiver class because it use one class for both sender and receiver.

**Comment by jcbrand** [comment]
@golangbu There are now the classes `chat-msg__me` and `chat-msg__them` to help you differentiate between incoming and outgoing messages.

**Comment by golangbu** [comment]
@jcbrand  should I make a pull request for adding chat bubble and make it as optional parameter?
If you do not want chat bubble then I will work on some other issues.

**Comment by jcbrand** [comment]
@golangbu You're welcome to make another theme with chat bubbles, in the same way that @linkmauve did in  #1167

In your case, that would simply mean adding a new class and variables in `sass/_variables.scss`

Like here: https://github.com/conversejs/converse.js/blob/master/sass/_variables.scss#L176
