### ISSUE TITLE
XEP-0156 (Discovering Alternative XMPP Connection Methods)

### ISSUE THREAD

**Issue by koehn** [conversejs/converse.js#129]
If I have properly set up a BOSH server and configured my DNS to serve up a URL per XEP-0156 (e.g., `koehn.com`), there's no need to use a third-party connection manager. The system could check the DNS for a `TXT` record at the XMPP host with text starting with `_xmpp-client-xbosh` and use that as the connection manager. 

Trouble is I'm not sure how you do a `TXT` DNS resolution from the browser; you certainly could have a server-side component to do the discovery though, you'd just have to have a standard API to send the user's JID and get back the connection manager to use. The server-side component could get the domain of the JID, check the XEP-0156 DNS entries, and return either a default connection manager or the one used by the domain. 

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/17882044-xep-0156-discovering-alternative-xmpp-connection-methods?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github).
</bountysource-plugin>

**Comment by devurandom** [comment]
[XEP-0156](http://xmpp.org/extensions/xep-0156.html) (Discovering Alternative XMPP Connection Methods) also specifies a [pure HTTP discovery method](http://xmpp.org/extensions/xep-0156.html#http).

**Comment by Neustradamus** [comment]
Any news about this ticket?
5 years old already!

**Comment by poVoq** [comment]
https://github.com/jsxc/xmpp-connection-discovery-node

**Comment by poVoq** [comment]
Party!
