### ISSUE TITLE
Converse.JS 

### ISSUE THREAD

**Issue by RobT111** [conversejs/converse.js#1290]
I have been using Inverse from Ignite for quite sometime, but is seems to have been replaced my Converse.
Converse looks awesome, but the newest webRTC client does not seem to support Internet Explorer.

Is there any version that does.

Thanks

**Comment by licaon-kter** [comment]
Update to 4.0.4 and retry?

**Comment by jcbrand** [comment]
Converse < 4 works on IE11.
Converse >= 4 doesn't work on IE11.

"Inverse" was originally what the fullscreen version of converse was called, but we dropped the name.

**Comment by RobT111** [comment]
jcbrand ---- does < 4 look similar to the newer versions. Additionally, where can I download the openfire plugin for <4.

Thanks

**Comment by jcbrand** [comment]
@RobT111 I believe that's the Inverse plugin you mentioned.
