### ISSUE TITLE
Bootstrap Conflicts

### ISSUE THREAD

**Issue by vincent-white** [conversejs/converse.js#130]
Hi JC, first of all I love the script. Congratulations on the brilliant work so far.

I do seem to run into a problem with the program when using it with Bootstrap in which the add contact drop down box no longer appears. I spent a while tracing the problem back and the conflict seems to start if

//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.no-icons.min.css

Is included with the program. Is it possible to get a fix for this? I've tried with various different bootstrap css files and they all seem to create the same issue.

Cheers

**Comment by hinesmr** [comment]
I'm having this same issue again with bootstrap v3 . See my screenshot in #709
