### ISSUE TITLE
Identicons support

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/converse.js#1309]
While the "generic human head" SVC icon is pretty neat and all, I would like to be able to marginally discern between users that haven't setup an actual avatar.

Any chance to replace that icon with an identicon based on JID?

Eg. using https://github.com/dmester/jdenticon or something else

**Comment by jcbrand** [comment]
My current thinking is to use XEP-0392 Consistent Color Generation and then showing the JID initial in white, with the color as background.

**Comment by licaon-kter** [comment]
Right, as expected.

Maybe keep this as "future feature request" ;)

**Comment by jcbrand** [comment]
I'm not sure I understand, do you prefer identicons or CCG with initials?

**Comment by licaon-kter** [comment]
Not sure. got used to CCG initials. :)
