### ISSUE TITLE
ERROR: unrecognized expression in Safari

### ISSUE THREAD

**Issue by golangbu** [conversejs/converse.js#1312]
Old messages are not recovered in safari browser only but in chrome it is working fine.
Getting error 
  ERROR: Error or timeout while trying to fetch archived messages
On setting debug : true .I found these logs
 FATAL: error: undefined http://127.0.0.1:8000/dist/converse.js:43844 - Error: Syntax error, unrecognized expression: body, encrypted[xmlns="eu.siacs.conversations.axolotl
 2018-11-07T11:29:10+05:30 WARNING: Removing Strophe handlers due to uncaught exception: Syntax error, unrecognized expression: body, encrypted[xmlns="eu.siacs.conversations.axolotl – ""
log — converse.js:71855

**Comment by jcbrand** [comment]
@golangbu I believe it should be fixed now. The file `dist/converse.js` should contain the fix, could you perhaps check if it's fixed for you?

**Comment by golangbu** [comment]
@jcbrand ..fixed
