### ISSUE TITLE
cannot change Presence via API

### ISSUE THREAD

**Issue by firegore** [conversejs/converse.js#1320]
Greetings,

i tried to set the Presence via the API. (Picked out parts from https://conversejs.org/docs/html/other_frameworks.html and
https://conversejs.org/docs/html/developer_api.html)

as soon as i try to create a Plugin that sets the Presence, i get an error and the console initialization of ConverseJS stops.

`converse-core.js:259  FATAL: TypeError: Cannot read property 'sendPresence' of undefined    at Object.set (https://cdn.conversejs.org/dist/converse.js:73007:30)    at Object.initialize (http://localhost/index.html:23:44)    at PluginSocket.initializePlugin (https://cdn.conversejs.org/dist/converse.js:42532:51)    at arrayEach (https://cdn.conversejs.org/dist/converse.js:9007:11)    at Object.forEach (https://cdn.conversejs.org/dist/converse.js:17833:14)    at PluginSocket.initializePlugins (https://cdn.conversejs.org/dist/converse.js:42565:15)    at Object.initPlugins (https://cdn.conversejs.org/dist/converse.js:72811:25)    at finishInitialization (https://cdn.conversejs.org/dist/converse.js:72832:15)    at tryCatch (https://cdn.conversejs.org/dist/converse.js:5606:12)    at invokeCallback (https://cdn.conversejs.org/dist/converse.js:5621:13)`

Reproducable by:

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>App</title>
  <link rel="stylesheet" type="text/css" media="screen" href="https://cdn.conversejs.org/css/converse.min.css">
  <script src="https://cdn.conversejs.org/dist/converse.js"></script>
</head>
<body>
foobar
</body>
<script type="application/javascript">
    converse.plugins.add('conversejs-angular-service', {
        initialize: function () {
            console.log('Plugin Initialized');
            this._converse.api.user.status.set('online','foobar!');
        }
    });

    converse.initialize({
        show_controlbox_by_default: true,
        websocket_url: 'xxx',
        auto_login: true,
        authentication: 'login',
        jid: 'xxx',
        password: '',
        whitelisted_plugins: [
            'converse-bookmarks',
            'conversejs-angular-service'
        ],
        debug: true
    });
</script>
</html>

I originally tried with the headless Versions, but neither of them work.
I reproduced the Issue with ConverseJS 4.0.4 and 3.3.4, unfortunately i couldn't try the master version, as the build seems to fail under Windows.
I always tried the non-minified versions.

i hope this is an actual bug, and not me being too stupid to use the API.

Thanks

**Comment by jcbrand** [comment]
Please show the actual code that's calling `sendPresence`.

What I can say already is that if you're calling `sendPresence`, you're not using the API.

The api is available through `_converse.api`. Anything else is not the API and can change without notice.

To send a presence, you can set your status with `_converse.api.status.set('dnd', "I'm in a meeting")`

**Comment by firegore** [comment]
i called it via 
`converse.plugins.add('conversejs-angular-service', {
        initialize: function () {
            console.log('Plugin Initialized');
            this._converse.api.user.status.set('online','wubwub!');
        }
    });`
however i just noticed an example in the Documentation that works, wich apperently i missed, as i read the Documentation.

So, the issue is "closed" for me now, as the only issue was missing an important Part of the Documentation

As a side note:
on https://conversejs.org/docs/html/api/index.html
the links towards the old API is broken
it should state https://conversejs.org/docs/html/developer_api.html instead of https://conversejs.org/docs/htmls/developer_api.html

**Comment by jcbrand** [comment]
Thanks for letting me know about the broken link. I've committed a fix for it.
