### ISSUE TITLE
False mentions positives in URLs and Email addresses

### ISSUE THREAD

**Issue by jcbrand** [conversejs/converse.js#1327]
For example: https://mastodon.gamedev.place/@nickname/101075087356757315 or mail@nickname.info

**Comment by darnuria** [comment]
Hi @jcbrand , can I work on this? @linkmauve can mentor me on this.

**Comment by jcbrand** [comment]
@darnuria: yes please!

**Comment by darnuria** [comment]
@jcbrand I have no news from @linkmauve, I will open the pull-request and ask for review! :)
