### ISSUE TITLE
Text in consecutive messages is not aligned

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/converse.js#1346]
Using HEAD

![consequtive](https://user-images.githubusercontent.com/2282799/48939242-7b78e780-ef0b-11e8-87e0-2bd915e3f816.PNG)

/LE: Made issue clearer, the text should be aligned, and then the checkmark will be

**Comment by licaon-kter** [comment]
@linkmauve ?

**Comment by licaon-kter** [comment]
@deleolajide In [this picture](https://github.com/conversejs/converse.js/issues/1682#issuecomment-526129327) you don't seem to have this issue? How come?

**Comment by deleolajide** [comment]
@licaon-kter 
you just made me realise that the ticks for delivery confirmation are missing in Pade. Maybe that's why

**Comment by deleolajide** [comment]
I tried inverse.chat and the ticks/check-marks are not showing either. How come they are showing in first screenshot

![image](https://user-images.githubusercontent.com/110731/64048483-bf1f1280-cb69-11e9-93c1-1b12a5d0444e.png)

**Comment by jcbrand** [comment]
I removed them because they don't fit in the context of MUC. Instead, the message displays grey until it's reflected, when it will display normally

**Comment by deleolajide** [comment]
Aaahhh. Thanks @jcbrand

**Comment by licaon-kter** [comment]
Ok, so it's a browser thing?

![aligned](https://user-images.githubusercontent.com/2282799/64272032-0ae90780-cf2e-11e9-99bf-1633be120d17.png)

Firefox left / Chrome right

**Comment by jcbrand** [comment]
I tested https://github.com/conversejs/converse.js/commit/de583cbd32f346a3ec139bf70c153f375f853242 in Firefox (fullscreen mode), and they render aligned.

**Comment by licaon-kter** [comment]
Not fixed for me...

**Comment by jcbrand** [comment]
Unfortunately I can't fix what I can't reproduce.

**Comment by licaon-kter** [comment]
True, I can't either in a new fresh profile. So yeah, fixed I guess.
