### ISSUE TITLE
XEP-0392: Consistent Color Generation

### ISSUE THREAD

**Issue by stevenroose** [conversejs/converse.js#1349]
Tracking issue for XEP-0392 compliance

- [x] make MUC nicks use the XEP-compliant color
- [ ] (bonus: make them bold)
- [x] give users without avatar a XEP-compliant colored default avatar
- [x] (precondition: add avatars to the MUC list)
- [x] give MUCs without avatar a XEP-compliant colored default avatar

**Comment by stevenroose** [comment]
I think @Deleolajide (correct username?) has a plugin that partially implements the colored avatars

**Comment by deleolajide** [comment]
The [plugin ](https://github.com/igniterealtime/Pade/blob/master/extension/inverse/plugins/pade.js)does many other **non standard** requested things for Pàdé. For reference, the avatar creation is done by the function below that uses a canvas element to create a data URI.

```
function createAvatar(nickname, width, height, font)
{
    if (!width) width = 32;
    if (!height) height = 32;
    if (!font) font = "16px Arial";

    var canvas = document.createElement('canvas');
    canvas.style.display = 'none';
    canvas.width = width;
    canvas.height = height;
    document.body.appendChild(canvas);
    var context = canvas.getContext('2d');
    context.fillStyle = getRandomColor(nickname);
    context.fillRect(0, 0, canvas.width, canvas.height);
    context.font = font;
    context.fillStyle = "#fff";

    var first, last;
    var name = nickname.split(" ");
    var l = name.length - 1;

    if (name && name[0] && name.first != '')
    {
        first = name[0][0];
        last = name[l] && name[l] != '' && l > 0 ? name[l][0] : null;

        if (last) {
            var initials = first + last;
            context.fillText(initials.toUpperCase(), 3, 23);
        } else {
            var initials = first;
            context.fillText(initials.toUpperCase(), 10, 23);
        }
        var data = canvas.toDataURL();
        document.body.removeChild(canvas);
    }

    return canvas.toDataURL();
}

var nickColors = {}

function getRandomColor(nickname)
{
    if (nickColors[nickname])
    {
        return nickColors[nickname];
    }
    else {
        var letters = '0123456789ABCDEF';
        var color = '#';

        for (var i = 0; i < 6; i++) {
            color += letters[Math.floor(Math.random() * 16)];
        }
        nickColors[nickname] = color;
        return color;
    }
}
```

**Comment by Nyco** [comment]
Doesn't this present ticket include this other ticket #1350 ?

**Comment by deleolajide** [comment]
Since I had the createAvatar function and custom CSS working in Pade, I decided to see how the Slack roster UI with deterministic color fit with the Converse UI.

![image](https://user-images.githubusercontent.com/110731/48961402-0a1d5100-ef6c-11e8-99ee-2e2f40e3c928.png)

**Comment by licaon-kter** [comment]
@deleolajide Niiice

**Comment by stevenroose** [comment]
@deleolajide I was talking about the list of MUCs on the left...

**Comment by deleolajide** [comment]
>I was talking about the list of MUCs on the left.

oops!

**Comment by JohnXLivingston** [comment]
Hello,

I made a PR with a first implementation for user nickames:
https://github.com/conversejs/converse.js/pull/3347

I do not need avatar colors in my project, so i don't plan to add it myself. But it should be easy to do, now that the algorithm is available in ConverseJS code base.

**Comment by jcbrand** [comment]
This has now been implemented.

**Comment by JohnXLivingston** [comment]
> This has now been implemented. Thanks to @JohnXLivingston for getting the ball rolling and implementing colored nicknames.

And thank you for the colored avatars!
