### ISSUE TITLE
Username style - same size but bold

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/converse.js#1350]
Now the font of the JID is a different size, but still the same weight. Making it bigger looks a bit slimmer so in my view it fails to emphasis that it's a different thing, it blends with the actual post text.

Looking at Mattermost at least, usernames are bold.

Playing with the web tools:
![bold](https://user-images.githubusercontent.com/2282799/48947928-c35b3700-ef2a-11e8-8d75-12b220253642.png)

**Comment by Nyco** [comment]
Isn't this present ticket included in this other ticket #1349 ?
