### ISSUE TITLE
MUC: ">>" and "x" buttons

### ISSUE THREAD

**Issue by Nyco** [conversejs/converse.js#1351]
## Problem

In the right pane, in a groupchat, Converse uses two different symbols for the same action. In the text input filed, the "<<" vs ">>" buttons are dynamically, and in the upper-left corner of the pane (chat area) there is a "x". This is confusing users.

![capture d ecran 2018-11-23 a 17 45 34](https://user-images.githubusercontent.com/25348/48953919-c0bb0a80-ef47-11e8-866e-60775fdafd83.png)

## Possible solutions

* Replace the "x" with ">>"
* Remove the "x"
* Remove the  "<<" vs ">>" (like Slack) but then there should some actions/controls in the top car to open this pane

**Comment by Nyco** [comment]
It seems I have missed the change somehow, as this looks to me as resolved: the "X" cross in the top-right corner has been removed in 4.2.0 or earlier. Right or wrong?

**Comment by licaon-kter** [comment]
@Nyco those are still there

**Comment by jcbrand** [comment]
I had to re-add it due to #1530

**Comment by jcbrand** [comment]
I've removed the `>>` from the toolbar. To show the sidebar after it was closed, the top dropdown can be used.
