### ISSUE TITLE
Theming and editing 'published' template

### ISSUE THREAD

**Issue by Phanlanx** [conversejs/converse.js#1355]
Thank you for this awesome library.

I just have some questions regarding the theming.

I would like to be able to 'publish'(same like when publishing vendor view in Laravel/etc where I can edit the template) these templates to Resource folder(out of node_modules) and fetched by dependencies when being built.

This is what I have done, I have cloned this repo to an empty folder, edited some files under src/template and run "make" then "make serve", the template did change and it reflected when I viewed.

Then I installed this on a Laravel application via npm:
- Installed fresh Laravel
- Installed converse.js using npm by running "npm install converse.js --save-dev"
- Added converse.js in under resources/js and added converse.scss

converse.js
`import converse from 'converse.js';`
`window.converse = converse;`

converse.scss
`@import "~converse.js/css/converse.css";`
`@import "~converse.js/css/font-awesome.min.css";`
`@import "~converse.js/css/fonts.css";`

- Run Laravel mixer by running "npm run dev"

`mix.js('resources/js/app.js', 'public/js')`
`    .js('resources/js/converse.js', 'public/js')`
`    .sass('resources/sass/app.scss', 'public/css')`
`    .sass('resources/sass/converse.scss', 'public/css')`
`    .version();`

I also added the content of src/converse.js into app.js(Laravel mix entry point) and changing the path

`import "converse.js/src/converse-autocomplete";`
`import "converse.js/src/converse-bookmarks";       // XEP-0048 Bookmarks`
`import "converse.js/src/converse-caps";            // XEP-0115 Entity Capabilities`
`import "converse.js/src/converse-chatview";        // Renders standalone chat boxes for single user chat`
`import "converse.js/src/converse-controlbox";      // The control box`

But this gives me error 
`ERROR in ./node_modules/converse.js/src/converse-rosterview.js
Module not found: Error: Can't resolve '@converse/headless/converse-chatboxes'`

My questions are:
- is this theming possible with the current version? If yes, can you just give me advice how to do this?

Pros:
- Better theming editing of template
- Easily fetch any update by running "npm update"

**Comment by jcbrand** [comment]
Thanks @Phanlanx.

I haven't ever used Laravel, so can't say much when it comes to the framework.

> But this gives me error
ERROR in ./node_modules/converse.js/src/converse-rosterview.js Module not found: Error: Can't resolve '@converse/headless/converse-chatboxes'


[@converse/headless](https://www.npmjs.com/package/@converse/headless) is a separate package which converse.js depends on. It's mentioned as a dev dependency in the package.json of converse.js.

Maybe that's the problem, that you didn't install converse.js with its dev dependencies?

You can also do `npm install --save-dev @converse/headless` to see if that helps.

**Comment by Phanlanx** [comment]
@jcbrand Alright, but how can I publish the template to other folder outside of node_modules? Let's say I would like to publish it in App/public/assets/components/js/converse.js/

**Comment by jcbrand** [comment]
@Phanlanx You'll need your own webpack config and specify an `alias` which points to your new template.

**Comment by Phanlanx** [comment]
@jcbrand  noted. Will work on that. Thank you very much.
