### ISSUE TITLE
Missing invitation input field in MUC

### ISSUE THREAD

**Issue by mightymop** [conversejs/converse.js#1362]
Hello, i've got the following problem:

MUC Configuration on Server:
- room is for **members only**
- **member occupants are allowed to send invitations to others**

Problem: 
The input field for muc invitations is only available as a muc owner (form is in dom tree.)
**Administrators/Moderators and members don't have the input field** on top of the 
muc member list. (The form is not in the dom tree, so its not a css problem.)

Converse: 4.0.5
allow_bookmarks: true​
allow_chat_pending_contacts: true
​allow_non_roster_messaging: true
​allow_otr: false
​allow_public_bookmarks: true
​allow_registration: false
​auto_away: 60
​auto_join_on_invite: true
​auto_list_rooms: true
​auto_reconnect: true
​auto_subscribe: true
​auto_xa: 120
​blacklisted_plugins: Array [ "converse-minimize", "converse-dragresize" ]
csi_waiting_time: 180
debug: true
forward_messages: true
​i18n: "de"
idle_presence_timeout: 180
keepalive: false
locales_url: "/chat/inverse/locale/de/LC_MESSAGES/converse.json"
message_archiving: "always"
message_carbons: true
muc_nickname_from_jid: true
muc_show_join_leave: true
notify_all_room_messages: false
ping_interval: 180
play_sounds: true
priority: 0
​roster_groups: true
​show_controlbox_by_default: false
show_desktop_notifications: true
show_message_load_animation: false
sounds_path: "/chat/inverse/sounds/"
synchronize_availability: true
use_system_emojis: false
view_mode: "fullscreen"
whitelisted_plugins: Array(26) [ "converse-singleton", "converse-inverse", "converse-reconnect", … ]

Server: Openfire 4.2.3

**Comment by mightymop** [comment]
Any News ??

**Comment by jcbrand** [comment]
As far as I can tell this is fixed now.
