### ISSUE TITLE
release 4.0.6 still identifies as 4.0.5 in "about"

### ISSUE THREAD

**Issue by sleeksorrow** [conversejs/converse.js#1366]
When clicking the (i) icon, Converse.js 4.0.6 still identifies as 4.0.5.

```
# grep -rn "v4\.0\.5" *
dist/converse.js:62555:_converse.VERSION_NAME = "v4.0.5";
src/headless/converse-core.js:75:_converse.VERSION_NAME = "v4.0.5";

```

**Comment by licaon-kter** [comment]
Same here

**Comment by jcbrand** [comment]
This was due to a regex bug in the Makefile.

Unfortunately the release has been made, so it'll stay like this until the next release.
