### ISSUE TITLE
Each list-item in roster has full height

### ISSUE THREAD

**Issue by sleeksorrow** [conversejs/converse.js#1367]
Roster is broken in Chrome 71, each list-item has one page height.

Firefox 63 unaffected

This is caused by this deletion:
https://github.com/conversejs/converse.js/commit/90bf42a0023c61d2665734f2f37d246d5ea61f7d#diff-3e1ad1f7ddb32668692b363c34c36c9dL11247

**Comment by jcbrand** [comment]
Can you show a screenshot? Looks fine for me on Chromium 70.

**Comment by sleeksorrow** [comment]
Tested with Chrome 71 and Chromium 70 on Linux, no extensions. Next list item comes way below window edge.
![screenshot_20181207_140611](https://user-images.githubusercontent.com/390307/49649449-7ba7d580-fa29-11e8-98d8-7bd00bb295d1.png)

**Comment by jcbrand** [comment]
I'm not able to replicate this (using Chrome 70 on MacOS).

Do you have any other CSS on that page, or some other modification?

<img width="1440" alt="screen shot 2018-12-10 at 14 26 36 1" src="https://user-images.githubusercontent.com/683911/49735850-bb202d00-fc88-11e8-8c45-d46af7db72df.png">
<img width="801" alt="screen shot 2018-12-10 at 14 34 05" src="https://user-images.githubusercontent.com/683911/49735851-bb202d00-fc88-11e8-80ad-1458a95c1c30.png">

**Comment by sleeksorrow** [comment]
I will try to make a clean minimal setup from scratch and see if the issue is there, too. If yes, I will describe my minimal setup for reproduction purposes.

**Comment by jcbrand** [comment]
I already committed something which I think will fix it for your case as well.

https://github.com/conversejs/converse.js/commit/8ccf1da9d64edef31cd9ba2fe916bcfb3b014545

**Comment by sleeksorrow** [comment]
My minimal reproduction setup is:

Server:
```
cd /var/www/webroot/
git clone --depth=1 -b v4.0.6  https://github.com/conversejs/converse.js.git converse
cd converse
cat <<EOF >index.html
<html>
<head>
<link rel="stylesheet" type="text/css" media="screen" href="css/converse.css">
<script src="dist/converse.js" charset="utf-8"></script>
</head>
<body>
</body>
<script>
    converse.initialize({
        bosh_service_url: 'https://my.bosh.server/http-bind/',
        locales_url: "locale/{{{locale}}}/LC_MESSAGES/converse.json",
        view_mode: 'fullscreen',
    });
</script>
EOF
```

Client:
`google-chrome-stable --user-data-dir=$HOME/google-temp https://my.web.server/converse/`

Your fix resolves this issue for me. Actually this seems to be a slightly enhanced version of my workaround (reverting the forementioned deletion). Tho it's not clear to me why you could not reproduce this.

**Comment by jcbrand** [comment]
OK, thanks for checking
