### ISSUE TITLE
Fonts differ vastly between Chrome and Firefox

### ISSUE THREAD

**Issue by sleeksorrow** [conversejs/converse.js#1368]
Fonts differ vastly between Chrome and Firefox

Tested v4.0.6 with Firefox 63 (left) and Chrome 71 (right) on Linux. No extensions installed.
![screenshot_20181207_134744](https://user-images.githubusercontent.com/390307/49649120-7f872800-fa28-11e8-990f-10ce85a6cb6f.png)

**Comment by licaon-kter** [comment]
Is that a different font or a different rendering of said font?

Compare some random site in both...

**Comment by sleeksorrow** [comment]
This is a completely other font. My guess is that the web fonts don't load at all in Chrome and it falls back to some default.

**Comment by licaon-kter** [comment]
Console output of the error?

**Comment by sleeksorrow** [comment]
Fonts are being retrieved form the server, no errors in console that would explain that.
![screenshot_20181207_143053](https://user-images.githubusercontent.com/390307/49650570-eb6b8f80-fa2c-11e8-878b-9c0fe4c3e907.png)
(On the login page, the text on the login button shows best that it's not using the correct web font)

**Comment by jcbrand** [comment]
Should be fixed in the next release, where I'm using a new font and including it in the release.
