### ISSUE TITLE
Sync issue with Weblate?

### ISSUE THREAD

**Issue by Jibec** [conversejs/converse.js#1372]
hello,

there is some warnings for your project on weblate: https://hosted.weblate.org/projects/conversejs/translations/#alerts

Repository has changes.
The VCS repository has many changes compared to the upstream. Please merge the changes manually or set up push to automate this.

Repository outdated.
The VCS repository is not up to date with the upstream one. Please merge changes manually or set up hooks to automate this.

Is this temporary or reveal a bigger issue?

**Comment by jcbrand** [comment]
Nothing to worry about, I manually rebase all translations onto master every time I make a new release of Converse.
