### ISSUE TITLE
muc_domain config is present, but I have to complete @conference.domain anyway when creating a group chat

### ISSUE THREAD

**Issue by pabloglaserHub** [conversejs/converse.js#1373]
I want the users to create chat groups only by typing the name, so they don´t have to type name@conference.domain every time. 
I configured the converse.initialize call adding:
muc_domain: 'domain'
then
muc_domain: 'conference.domain'
and also 
muc_domain: '@conference.domain'

But no matter what, I always have to complete the @conference.domain when typing the name, or I'll get "Remote server not found" error

**Comment by jcbrand** [comment]
Related issue: #1284
