### ISSUE TITLE
Adding version in released asset filenames

### ISSUE THREAD

**Issue by joudinet** [conversejs/converse.js#1375]
Hi,

I've just packaged your project in Buildroot (see buildroot.org for more details). The only issue I have is the absence of version in the asset filenames you release in github. I suggest you add -version for all of them. For example:
https://github.com/conversejs/converse.js/releases/download/v4.0.7/converse-4.0.7.min.css
https://github.com/conversejs/converse.js/releases/download/v4.0.7/converse-4.0.7.min.js
https://github.com/conversejs/converse.js/releases/download/v4.0.7/webfonts-4.0.7.zip

Otherwise, the absence of such version in the filename makes it difficult to identify the version of a downloaded file. Thus, if I bump the version of this project in buildroot, the download infrastructure will think it has already downloaded the file and will not try to download the new version, because it has the same name.

Thanks. Best,

**Comment by jcbrand** [comment]
> Thus, if I bump the version of this project in buildroot, the download infrastructure will think it has already downloaded the file and will not try to download the new version, because it has the same name.

Are you sure this is true? The URLs are different between releases, so I would expect caching to not be an issue.

**Comment by joudinet** [comment]
Yes, I'm sure. The URLs do not matter as the sources might be retrieve from a mirror.
Here a discussion on the same issue but from another package in buildroot:
https://patchwork.ozlabs.org/patch/849230/

**Comment by jcbrand** [comment]
You can make a PR which updates the release recipe in the Makefile to copy the built files to numbered versions.

See here: https://github.com/conversejs/converse.js/blob/master/Makefile#L86

I'll then upload those versions in future.
