### ISSUE TITLE
Support for IE 11 and iOS Safari 9.3

### ISSUE THREAD

**Issue by joudinet** [conversejs/converse.js#1377]
Hi,

I've just tested converse.js on iOS Safari 9.3 (last available version on an iPad 2), and it does not work.
It does work on an old iPhone, which run a little less old iOS version: 10.1.
I suspect the problem to be the use of arrow functions, which are not supported in either Safari 9.3 nor IE 11:
https://caniuse.com/#feat=arrow-functions

I'm not sure you're interested in supporting these two browsers, but in case you do (estimated 13% of users), I could test it for you.

**Comment by jcbrand** [comment]
Converse uses quite a few features not supported by IE11, not just arrow functions. For example also CSS properties and webcrypto.

I don't think it's worth the effort to support it.

I appreciate that you're willing to test in these browsers, but it's not very helpful if things are broken and I have to then fix it without having access to those browsers.
