### ISSUE TITLE
Need to run converse.js from nginx server

### ISSUE THREAD

**Issue by boxerab** [conversejs/converse.js#138]
Hi,
My apologies for newbie question here:  I would like to host converse.js on my nginx server. I have copied the js and css converse files into my nginx html docs folder,
and I have modifed the default index.html file to match the index file in the repo:

https://github.com/jcbrand/converse.js/blob/master/index.html

But, I don't see the chat window.  What am I missing?

Thanks,
Aaron

**Comment by jcbrand** [comment]
@xmpppargat See here: https://conversejs.org/docs/html/setup.html?highlight=nginx#websocket
