### ISSUE TITLE
Converse.js reload & reconnects on every page refresh or any page navigation on web

### ISSUE THREAD

**Issue by hzzg6y** [conversejs/converse.js#1381]
I am using latest converse.js 4.0.6 along with Prosody 0.10.0.  I have installed Prosody 0.10.0 on CentOS 7.4 with SSL & used XMPP Bosh with apache. Users are added to prosody successfully by authentication method. Below is my snapshot.  However on my website www.example.com.. converse.js autoconnects to the user however it is taking long time re-connect & reloads on every page refresh or any page navigation. Customers are not going to get the seamless experience. 

Please advice on how to avoid the reloading or re-connecting the converse.js chat.  Customer should get very seamless kind of experience on website. 

Prosody is on other server with centos 7.4 along with Apache while Converse.js.zip full folder in extracted format is on server on which example.com website is hosted. 

`<script>
    jQuery.ajaxSetup({ cache: true });
    var unm = jQuery("#user_id_forchat").val();
    converse.initialize({
        bosh_service_url: 'https://example.com:5281/http-bind/', // Please use this connection manager only for testing purposes
        show_controlbox_by_default: true,
	    authentication: 'login',
        auto_login: true,
        jid: unm,
        password: 'password',
        keepalive: true,
        auto_away: 180,
        auto_xa: 600,
        auto_reconnect: true,
        play_sounds: false,
        hide_offline_users: false,
        play_sounds: false,
        hide_offline_users: false,
        allow_logout: false
    });
</script>`

**Comment by jcbrand** [comment]
Converse supports attaching to an existing BOSH session, so it should not be necessary to re-authenticate when the page reloads.

You haven't provided any information which can point the the possible cause of your problem.

Check your XMPP server's logs and the Converse logs in the browser console. Make sure to turn on debug logging in both cases.

**Comment by hzzg6y** [comment]
Hi

   Thanks for prompt response.  Below is snap of Prosody XMPP log when I navigate the page within the website. The whole Converse.js "Toggle Chat" disappears, then comes after sometime, reconnects & then appears on next page. 

Dec 17 04:45:48 mod_bosh        debug   BOSH body open (sid: 6761c7f5-e64d-4d84-8632-abb6b07e904e)
Dec 17 04:45:48 mod_bosh        debug   BOSH stanza received: <iq id='_bind_auth_2' type='set'>

Dec 17 04:45:48 bosh6761c7f5-e64d-4d84-8632-abb6b07e904e        debug   Received[c2s_unbound]: <iq id='_bind_auth_2' type='set'>
Dec 17 04:45:48 rostermanager   debug   load_roster: asked for: User123@example.com
Dec 17 04:45:48 bosh6761c7f5-e64d-4d84-8632-abb6b07e904e        debug   Resource bound: User123@example.com/converse.js-123028856
Dec 17 04:45:48 mod_bosh        debug   We have an open request, so sending on that
Dec 17 04:45:48 mod_bosh        debug   Request destroyed: table: 0x19c8b80
Dec 17 04:45:48 bosh6761c7f5-e64d-4d84-8632-abb6b07e904e        debug   BOSH session marked as inactive (for 60s)
Dec 17 04:45:48 mod_bosh        debug   Session 6761c7f5-e64d-4d84-8632-abb6b07e904e has 0 out of 1 requests open
Dec 17 04:45:48 mod_bosh        debug   and there are 0 things in the send_buffer:
Dec 17 04:45:48 http.server     debug   Firing event: POST example.com/http-bind/
Dec 17 04:45:48 mod_bosh        debug   Handling new request table: 0x19d0c60: <body rid="3999810117" sid="6761c7f5-e64d-4d84-8632-abb6b07e904e" xmlns="http://jabber.org/protocol/httpbind"><iq id="_session_auth_2" type="set" xmlns="jabber:client"><session xmlns="urn:ietf:params:xml:ns:xmpp-session"/></iq></body>
----------
Dec 17 04:45:48 mod_bosh        debug   BOSH body open (sid: 6761c7f5-e64d-4d84-8632-abb6b07e904e)
Dec 17 04:45:48 mod_bosh        debug   BOSH stanza received: <iq id='_session_auth_2' type='set'>

Dec 17 04:45:48 bosh6761c7f5-e64d-4d84-8632-abb6b07e904e        debug   Received[c2s]: <iq id='_session_auth_2' type='set'>
Dec 17 04:45:48 mod_bosh        debug   We have an open request, so sending on that
Dec 17 04:45:48 mod_bosh        debug   Request destroyed: table: 0x19d13b0
Dec 17 04:45:48 bosh6761c7f5-e64d-4d84-8632-abb6b07e904e        debug   BOSH session marked as inactive (for 60s)
Dec 17 04:45:48 mod_bosh        debug   Session 6761c7f5-e64d-4d84-8632-abb6b07e904e has 0 out of 1 requests open
Dec 17 04:45:48 mod_bosh        debug   and there are 0 things in the send_buffer:
Dec 17 04:45:48 http.server     debug   Firing event: POST example.com/http-bind/
Dec 17 04:45:48 mod_bosh        debug   Handling new request table: 0x19d8230: <body rid="3999810118" sid="6761c7f5-e64d-4d84-8632-abb6b07e904e" xmlns="http://jabber.org/protocol/httpbind"/>
----------
Dec 17 04:45:48 mod_bosh        debug   BOSH body open (sid: 6761c7f5-e64d-4d84-8632-abb6b07e904e)
Dec 17 04:45:48 mod_bosh        debug   Session 6761c7f5-e64d-4d84-8632-abb6b07e904e has 1 out of 1 requests open
Dec 17 04:45:48 mod_bosh        debug   and there are 0 things in the send_buffer:
Dec 17 04:45:48 mod_bosh        debug   Have nothing to say, so leaving request unanswered for now
Dec 17 04:45:49 socket  debug   server.lua: auto-starting ssl negotiation...
Dec 17 04:45:49 socket  debug   server.lua: attempting to start tls on tcp{client}: 0x19dd358
Dec 17 04:45:49 socket  debug   server.lua: accepted new client connection from 27.34.247.159:49902 to 5281
Dec 17 04:45:49 socket  debug   server.lua: ssl handshake done
Dec 17 04:45:49 http.server     debug   Firing event: POST example.com/http-bind/
Dec 17 04:45:49 mod_bosh        debug   Handling new request table: 0x19e5220: <body rid="3999810119" sid="6761c7f5-e64d-4d84-8632-abb6b07e904e" xmlns="http://jabber.org/protocol/httpbind"><iq id="1be270a0-7cc9-4051-a531-2c0aaccd7318:sendIQ" type="get" xmlns="jabber:client"><vCard xmlns="vcard-temp"/></iq><iq id="198bbcfc-5c00-41d3-a944-0f78564d283f:sendIQ" to="anjil-ap10036@example.com" type="get" xmlns="jabber:client"><vCard xmlns="vcard-temp"/></iq><presence xmlns="jabber:client"><priority>0</priority><c hash="sha-1" node="https://conversejs.org" ver="ahtu2rrUEb+RqYX3Qt3DvKpOdMM=" xmlns="http://jabber.org/protocol/caps"/></presence></body>
----------
Dec 17 04:45:49 mod_bosh        debug   BOSH body open (sid: 6761c7f5-e64d-4d84-8632-abb6b07e904e)
Dec 17 04:45:49 mod_bosh        debug   BOSH stanza received: <iq id='1be270a0-7cc9-4051-a531-2c0aaccd7318:sendIQ' type='get'>

Dec 17 04:45:49 bosh6761c7f5-e64d-4d84-8632-abb6b07e904e        debug   Received[c2s]: <iq id='1be270a0-7cc9-4051-a531-2c0aaccd7318:sendIQ' type='get'>
Dec 17 04:45:49 mod_bosh        debug   BOSH stanza received: <iq id='198bbcfc-5c00-41d3-a944-0f78564d283f:sendIQ' type='get' to='anjil-ap10036@example.com'>

Dec 17 04:45:49 bosh6761c7f5-e64d-4d84-8632-abb6b07e904e        debug   Received[c2s]: <iq id='198bbcfc-5c00-41d3-a944-0f78564d283f:sendIQ' type='get' to='anjil-ap10036@example.com'>
Dec 17 04:45:49 mod_bosh        debug   BOSH stanza received: <presence>

Dec 17 04:45:49 bosh6761c7f5-e64d-4d84-8632-abb6b07e904e        debug   Received[c2s]: <presence>
Dec 17 04:45:49 example.com:presence   debug   outbound presence probe from User123@example.com for anjil-ap10036@example.com
Dec 17 04:45:49 example.com:presence   debug   inbound presence probe from User123@example.com for anjil-ap10036@example.com
Dec 17 04:45:49 example.com:presence   debug   broadcasted presence of 0 resources from anjil-ap10036@example.com to User123@example.com/converse.js-123028856
Dec 17 04:45:49 datamanager     debug   Removing empty offline datastore for user User123@example.com
Dec 17 04:45:49 mod_bosh        debug   We have an open request, so sending on that
Dec 17 04:45:49 mod_bosh        debug   Request destroyed: table: 0x19d87d0
Dec 17 04:45:49 mod_bosh        debug   Session 6761c7f5-e64d-4d84-8632-abb6b07e904e has 1 out of 1 requests open
Dec 17 04:45:49 mod_bosh        debug   and there are 0 things in the send_buffer:
Dec 17 04:45:49 mod_bosh        debug   Have nothing to say, so leaving request unanswered for now
Dec 17 04:46:26 boshd908a938-c7c4-4c37-a248-016f6bb69754        debug   BOSH client inactive too long, destroying session at 1545021986
Dec 17 04:46:26 boshd908a938-c7c4-4c37-a248-016f6bb69754        debug   Destroying session for User123@example.com/converse.js-131535988 (User123@example.com): BOSH client silent for over 60 seconds
Dec 17 04:46:26 boshd908a938-c7c4-4c37-a248-016f6bb69754        debug   Received[c2s]: <presence type='unavailable'>
Dec 17 04:46:26 mod_bosh        debug   We have an open request, so sending on that
Dec 17 04:46:26 mod_bosh        debug   Request destroyed: table: 0x19e52b0
Dec 17 04:46:26 bosh6761c7f5-e64d-4d84-8632-abb6b07e904e        debug   BOSH session marked as inactive (for 60s)
Dec 17 04:46:26 http.server     debug   Firing event: POST example.com/http-bind/
Dec 17 04:46:26 mod_bosh        debug   Handling new request table: 0x19ff8a0: <body rid="3999810120" sid="6761c7f5-e64d-4d84-8632-abb6b07e904e" xmlns="http://jabber.org/protocol/httpbind"/>
----------
Dec 17 04:46:26 mod_bosh        debug   BOSH body open (sid: 6761c7f5-e64d-4d84-8632-abb6b07e904e)
Dec 17 04:46:26 mod_bosh        debug   Session 6761c7f5-e64d-4d84-8632-abb6b07e904e has 1 out of 1 requests open
Dec 17 04:46:26 mod_bosh        debug   and there are 0 things in the send_buffer:
Dec 17 04:46:26 mod_bosh        debug   Have nothing to say, so leaving request unanswered for now

**Comment by jcbrand** [comment]
Please fix the formatting in your comment.

**Comment by hzzg6y** [comment]
Done.. Pls help.

**Comment by hzzg6y** [comment]
I have not made any modification in converse.js files. I am not sure why BOSH session is getting destroyed for 60 sec idle time.  Pls help or advice

**Comment by hzzg6y** [comment]
Any pointer here will really help. Please help.

**Comment by jcbrand** [comment]
I already gave you a pointer. There's not much more I can say.

> You'll need to figure out why Converse takes more than 60 seconds to send a follow-up HTTP request to Prosody. This isn't something that happens normally.

You can look at the HTTP requests in the network tab of the browser developer console, and when you set `debug` to `true` when calling `converse.initialize` you can inspect all debug output including stanzas in the output console.

**Comment by FaizanZahid** [comment]
@jcbrand I am having the same issue.

1. When the internet changes, then my converse iframe crashes and i have to manually refresh the page to load it again.

2. When my xampp prosody server restarts, also then my converse iframe crashes and i have to manually refresh the page to load converse again, how can i stop this and reload is using ajax call without page refresh?

How can i re initlaize converse js in a new room after my page and converse has initially loaded?

What would be the JS command to execute if i want to dynamically load a new chatroom after my html page has already loaded with an existing anonymous auto join room using converse.initialize config? For e.g , user A loads my page and converse is initialised with anonymous room   abc with normal JS call , now when the same user presses a button on my page, i want to re initialize converse with ajax to load with a new room xyz. But i want to do this without html page refresh since all JS and CSS files on my page are already loaded. How do i do rerewnder my converse chat with a new chatroom without whole html page refresh?
