### ISSUE TITLE
Update the user manual

### ISSUE THREAD

**Issue by jcbrand** [conversejs/converse.js#1383]
The [user manual](https://conversejs.org/docs/html/manual.html) is very old and incomplete.

Tasks for this ticket:

* [ ] Replace all screenshots with modern versions.
* [ ] Also create similar screenshots for Converse in fullscreen [view_mode](https://conversejs.org/docs/html/configuration.html#view-mode)
* [ ] Expand the manual with more information (to be clarified)

# Technical information

The user manual is in It's in `./docs/source/manual.rst` in the Converse repo. 
See: https://github.com/conversejs/converse.js/blob/master/docs/source/manual.rst

The manual is written in [RestructuredText](http://docutils.sourceforge.net/docs/user/rst/quickstart.html) and generated with [Sphinx](http://www.sphinx-doc.org/en/stable/)

Sphinx uses Python, so you'll need to set up a Python virtual environment with Buildout to manage dependencies.

Follow the instructions here: https://github.com/conversejs/converse.js/blob/master/docs/source/documentation.rst

**Comment by lyabs243** [comment]
I started with the translation, I just had a converse language problem on my google chrome which is in English but converse was displayed in English and French at the same time

**Comment by jcbrand** [comment]
@lyabs243: Translation of what? The user manual? I think it's much more important to first update the user manual with newer screenshots and missing information than to work on translating it.

**Comment by jcbrand** [comment]
@lyabs243: If you're worried about English not being your mother tongue, don't worry, I'll proofread what you write and help you to correct spelling and grammatical mistakes.

**Comment by lyabs243** [comment]
@jcbrand  Sorry not the translation i wanted to say  the update of user manual i could n't take screenshot because my converse was in french even if my browser was in english

**Comment by jcbrand** [comment]
ah ok, I understand now. Have you been able to get buildout and sphinx installed and can you call `make html`?

**Comment by lyabs243** [comment]
Yes I installed Sphinx  and i can build html, for the moment the syntax of sphinx is not so familiar to me fortunately I refer to the rst files of the Converse doc to better understand

**Comment by jcbrand** [comment]
@lyabs243 I've decided to move the user manual out of this repo and into its own.

The user manual is now located here: http://github.com/conversejs/user-manual

Please make your changes there. The setup is pretty much the same. Please read the README of that repo and let me know if anything is unclear.

Thanks

**Comment by jcbrand** [comment]
I've now created a new ticket in the new repo: https://github.com/conversejs/user-manual/issues/1

Closing this one.
