### ISSUE TITLE
Green vs red (sidebar and conversation panel) [user test]

### ISSUE THREAD

**Issue by Nyco** [conversejs/converse.js#1385]
I ran some user tests again, focus on the use of colours (green vs red) in the left sidebar and the right/central conversation panel.

* PH
  * Conversation: red is too aggressive I think, so green, although not a fan
  * Sidebar: this does not shock me, I understand that we want to distinguish and this will apply somewhere else
* LK
  * I hesitate but I prefer green, I have the impression that it does not correspond to the same visual, identity, the colour may not mix happily
* VB
  * green is better I think
  * it's good to differentiate, the participants panel is very good as well
  * I can't see any more differences (I'm on my phone)
* HK
  * this makes me think of OK / NOK, good / not good, GO / STOP
  * if that's for giving an identity, I would choose other colours without those connotations
  * you already have green which means online, which is disturbing
* HV
  * I vote green
  * in collective imaginary un green frame = good and red frame = no good
* SG
  * it's more orange that red on my screen, but I think both are OK, thus I have no preference
  * it's readable, but (without knowing anything) I would have put personal in red and general in green, so the opposite
* PC
  * Both are cool
  * you have to know what emotion you want to communicate
  * will that be configurable by the user?
  * The colour that change according to context, that's cool

Results:
* Differentiating groups from personal chats is a good idea
* Applying same colour on the sidebar and in the conversation is a good idea
* Green and red should not be used, as these are related to sentiment (good vs bad), presence (online vs do not disturb), road light (stop vs go)

Other considerations: colours-only differentiators is not accessible

Recommandations:
* Do not use red and green colours
* Use screen readable differentiators
  * Slack, RocketChat: "#" sharp sign or hashtag for groups, dots for individuals
  * Telegram, WhatsApp, Messenger: no differentiators
  * To consider: the "@" sign is generally used for mentions to individuals

**Comment by jcbrand** [comment]
Hi @Nyco, thanks for doing some user testing and providing feedback.

What you call "red" is actually supposed to be orange. Perhaps it has too much of a reddish hue, but it's meant to be orange.
