### ISSUE TITLE
Server did not yet offer a supported authentication mechanism. Sending a blank poll request.

### ISSUE THREAD

**Issue by gstlouisgit** [conversejs/converse.js#1387]
I am trying to setup using the converse demo fullpage, just so I can get online using Prosody.  I have done this before but a long time ago using the proxy method.

This time I figured I would try learning another approach.  I have Prosody setup and connecting using adium on mac for instance.

I have loaded a converse environment and in the initialization 
```
    converse.initialize({
        authentication: 'login',
        debug: true,
        auto_away: 300,
        auto_reconnect: true,
        bosh_service_url: 'http://192.168.10.6:5280/http-bind/', // Please use this connection manager only for testing purposes
        message_archiving: 'always',
        view_mode: 'fullscreen'
    }).then(function () {
        setTimeout(function () {
            document.querySelector('.converse-content').style = '';
        }, 1000);
    });
```

From there I went into prosody.cfg.lua and added globally 
`cross_domain_bosh = true`

all services restarted I try to connect using the chrome and I get this error:

> WARNING: Server did not yet offer a supported authentication mechanism. Sending a blank poll request.

I do not have any CORS errors, which I am more familiar with ( at least I think I am ).

I haven't really touched Prosody settings besides the basics:
set admin - admins = {"me@whatever.ca" }
modules_enabled{
//   these were not enable by default
"bosh"; -- Enable BOSH clients, aka "Jabber over HTTP"
}

The auth. method that was there by default is
`authentication = "internal_hashed"`

I have a self-signed certs and everything connected fine with adium on mac

What am I doing wrong for auth over web?

**Comment by gstlouisgit** [comment]
I have also tried in httpd.conf 
        # BOSH endpoint proxy START
```
        <IfModule mod_proxy.c>
                <IfModule mod_proxy_http.c>
                        ProxyRequests Off
                        ProxyPass /http-bind http://localhost:5280/http-bind/
                        ProxyPassReverse /http-bind http://localhost:5280/http-bind/
                </IfModule>
        </IfModule>
```

if I do 
`curl -i http://localhost/http-bind/`
I received the 'It works' from prosody

But I still keep getting in the browser the error

> WARNING: Server did not yet offer a supported authentication mechanism. Sending a blank poll request.

**Comment by jcbrand** [comment]
The error message is quite clear. Your server is not offering a SASL authentication mechanism that's supported by your instance of Converse.

Perhaps what's happening is that you're server is only advertising support for SASL PLAIN, but you're not using TLS (e.g. HTTPS) for BOSH, so PLAIN is not allowed.

You'll have to look into the supported SASL mechanisms of your XMPP server.
