### ISSUE TITLE
Missing file upload button when local/session storage is empty

### ISSUE THREAD

**Issue by joudinet** [conversejs/converse.js#1389]
Whenever the local/session storage is empty (either because it is the first time I connect or because I've just cleared it), the file upload button is missing.
I've run FF debugger on converse.js and find out that the difference is here:
```
async addFileUploadButton(options) {
        const result = await _converse.api.disco.supports(Strophe.NS.HTTPUPLOAD, _converse.domain);

        if (result.length) {
          this.el.querySelector('.chat-toolbar').insertAdjacentHTML('beforeend', templates_toolbar_fileupload_html__WEBPACK_IMPORTED_MODULE_19___default()({
            'tooltip_upload_file': __('Choose a file to send')
          }));
        }
      },
```
When the local/session storage is empty, result.length is equal to 0 in the if condition. If I reload the page, it becomes equal to 1 and the file upload button is present and it works.
I've modified my local copy of converse.js to comment out this condition and show the button every time. I successfully uploaded a file.
I'm not sure how this async/await stuff works but it looks like a race condition to me.
Here is the response to the disco#info query:
```
<iq xml:lang="en" to="3330230797301032417707@gnyoi.com/63420928906131686101730"
from="upload.gnyoi.com" type="result"
id="6ee5ac78-a013-471c-a2d4-353b081124fd:sendIQ" xmlns="jabber:client">
  <query xmlns="http://jabber.org/protocol/disco#info">
    <identity name="HTTP File Upload" type="file" category="store"/>
    <feature var="urn:xmpp:http:upload"/>
    <feature var="urn:xmpp:http:upload:0"/>
    <feature var="eu:siacs:conversations:http:upload"/>
    <feature var="http://jabber.org/protocol/disco#info"/>
    <feature var="http://jabber.org/protocol/disco#items"/>
    <x type="result" xmlns="jabber:x:data">
      <field var="FORM_TYPE" type="hidden">
        <value>urn:xmpp:http:upload</value>
      </field>
      <field var="max-file-size" type="text-single" label="Maximum file size">
        <value>104857600</value>
      </field>
    </x>
    <x type="result" xmlns="jabber:x:data">
      <field var="FORM_TYPE" type="hidden">
        <value>urn:xmpp:http:upload:0</value>
      </field>
      <field var="max-file-size" type="text-single" label="Maximum file size">
        <value>104857600</value>
      </field>
    </x>
    <x type="result" xmlns="jabber:x:data">
      <field var="FORM_TYPE" type="hidden">
        <value>http://jabber.org/network/serverinfo</value>
      </field>
    </x>
  </query>
</iq>
```
So it does contain the feature "urn:xmpp:http:upload:0".

The client is Converse 4.0.6 and the server Ejabberd 18.09.

**Comment by jcbrand** [comment]
> I'm not sure how this async/await stuff works but it looks like a race condition to me.

One of the reasons for using  promises (e.g. async/await) is to avoid race conditions (which might happen when using events).

Perhaps the method returns without a promise (due to a bug).

**Comment by deleolajide** [comment]
I encounter a similar or perhaps same bug when an MUC is autojoined at startup via stored book marks. I think the method addFileUploadButton is called earlier than expected. My workaround hack is wrap it in a setTimeout.
```
    var that = this;
    setTimeout(function(){
        that.renderToolbar();
    })
```

**Comment by licaon-kter** [comment]
Seeing the same for a while now ( after https://github.com/conversejs/converse.js/issues/1622 I guess)

I can repro on Chrome stable (incognito window) and Vivaldi Snapshot (incognito window).
I **can't** repro on Chrome stable (not-incognito) and Vivaldi Snapshot (not-incognito).

Steps:
*    login
*    (don't have autojoined rooms)
*    click on 2 MUCs bookmarks & join them
*    close the browser tab
*    undo close tab
*    (you are now forced to) relogin

Expected result:
*    see 2 MUCs as "Open Groupchats" or closed as "Bookmarks"

Actual result:
*    see 2 MUCs as "Open Groupchats"
*    select one
*    see only the emoji picker

Note that if I logout properly, on relogin: MUCs are not joined, just appear as Bookmarks (https://github.com/conversejs/converse.js/issues/1630)

Debug log from Firefox after undo->login: https://gist.github.com/licaon-kter/9125e76f98614e1f62c9aee1173a2780

**Comment by joudinet** [comment]
This bug doesn't occur anymore since conversejs-6.0.0. Should I close this issue or someone else still has a missing file upload button?

**Comment by jcbrand** [comment]
I'll close, thanks for confirming.

**Comment by mishadaut** [comment]
I've a similar problem using converse 8.0.1

If I close a chat browser tab( auto_login:true and view_mode: 'fullscreen') without logout and reopen in the new tab, upload button is missing.
I fixed it as joudinet  recommended:

` //const http_upload_promise = api.disco.supports(toolbar_Strophe.NS.HTTPUPLOAD, shared_converse.domain);
    //buttons.push(T`${until_o(http_upload_promise.then(is_supported => this.getHTTPUploadButton(is_supported)), '')}`);
    buttons.push(this.getHTTPUploadButton(true));`    

Is it a bug or anything wrong on my side?

**Comment by jcbrand** [comment]
@mishadaut: Sounds like a bug. Can you please make a new bug report for it?

**Comment by mishadaut** [comment]
Done #2668
