### ISSUE TITLE
Toggle chat opens with auto_join_rooms

### ISSUE THREAD

**Issue by tyler71** [conversejs/converse.js#1402]
**Issue:**
With `auto_join_rooms` set to a room, `auto_login` set to true and auth set to anonymous in overlayed view-mode, it will open up the chat even though `show_controlbox_by_default` is false
**Expected behavior:**
Toggle chat should stay closed even if it joined a groupchat
Ideally it wouldn't login automatically unless clicked on to show the chat

**Config:**
```
    converse.initialize({
        authentication: 'anonymous',
        auto_login: 'true',
        jid: "domain.tld",
        auto_reconnect: true,
        websocket_url: 'wss://domain.tld:5443/ws',
        message_archiving: 'never',
        view_mode: 'overlayed',
        auto_join_on_invite: true,
        show_controlbox_by_default: false,
        auto_join_rooms: [{'jid': 'chat@room.domain.tld', 'nick': 'anon'}]
```

**Comment by jcbrand** [comment]
'false' is not a valid boolean value, it's a string which is truthy.

**Comment by tyler71** [comment]
Yes that was it, not a bug.
Messed up on the config and missed that 'false' is a true string
@jcbrand thanks for the help
