### ISSUE TITLE
Status of contacts list are not displayed properly

### ISSUE THREAD

**Issue by srgcdev** [conversejs/converse.js#1405]
Using last version of converse 4.1.0 (previous version 4.0.6 had the same problem), when I connect to converse in full screen, the status of the contacts on the left are not properly displayed, some of them appear as offline where they are online.

I don't mark the check for "trusted device" when I connect to converse in the login screen.
The problem is not always reproducible, sometimes I had to go offline and connect again.

**Comment by jcbrand** [comment]
Does the problem go away if you click the `refresh` icon next to the "Contacts" heading?

Unfortunately there isn't enough information here for me to know what's going on.

**Comment by srgcdev** [comment]
If I click the refresh button nothing happens.

**Comment by jcbrand** [comment]
hmmm, that might be related...

Seems like there's something specific about your config that causes converse-omemo to not initialize.

Can you paste your `converse.initialize` config?

**Comment by srgcdev** [comment]
`converse.initialize({
        authentication: 'login',
        auto_away: 300,
        auto_reconnect: true,
	default_domain: 'example.org',
        bosh_service_url: 'https://example.org/http-bind/',
        view_mode: 'fullscreen',
	theme: 'concord'
    });`

**Comment by srgcdev** [comment]
I can reproduce the error in https://conversejs.org, some contacts are displayed offline but they are online. If they change their status, then converse.js displays well their status, for example, one contact goes offline and the online, and converse.js shows the contact as online.

But in conversejs.org, the error:
`ERROR: e.devicelists is undefined converse.min.js:157:106333`
is not shown.

**Comment by laszlovl** [comment]
I'm seeing the same thing, without the `e.devicelists` error. It's 100% reproducable on first login (with an empty cache/localstorage), subsequent logins do sometimes work properly.

Seems to be caused by https://github.com/conversejs/converse.js/commit/cc3735ff089ca271e42954f5e7086cc556c2db71

**Comment by srgcdev** [comment]
Maybe that's why I always can reproduce the problem. I remove automatically the cookies on the browser when I close the tab, so every time I login I have an empty cache/localstorage.

**Comment by samjunction** [comment]
Change in contact status is not reflecting in roster view. Any change in contact status is correctly displayed in desktop/html5 notification but roster UI still shows old status. User online/offline is not reflected in UI most of the time. I have noticed that notification plugin uses contactPresenceChanged event for showing contact status and which works perfectly.
