### ISSUE TITLE
Can we port it to react native

### ISSUE THREAD

**Issue by saibharani** [conversejs/converse.js#1409]
HI i am trying to create xmpp based chat app in react native can we port this to react native

**Comment by jcbrand** [comment]
Converse.js doesn't use React, so you'd have to create a new UI on top of the headless build.

https://www.npmjs.com/package/@converse/headless

**Comment by shubham1164** [comment]
Hi, do you find any way to use it with react-native and is it working fine?

**Comment by chronikum** [comment]
would be also interested in a solution
