### ISSUE TITLE
XEP-0184: Message Delivery Receipts

### ISSUE THREAD

**Issue by manishjodhpur** [conversejs/converse.js#141]
Hi JCBrand,
 can you plz explain, how to send delivery stanza using converse,js

thanks

**Comment by chihanlin** [comment]
XEP-0184, plus XEP-0198 together will make the Message deliver become a very reliable way.  From my own opinion, the most important features of a messaging system should do its best to make sure a message being able to be delivered end to end without lost any message. If these two (0184, 0198) being implemented, other missing feature (for example, not be able to  always keep-alive for typical web application, will not be an critical defect.) Therefore, XEP-0184, 0198 should be in the higher priority among other enhancements. The earlier converse.js can have these two implemented, the preference of this converse.js will be.

**Comment by devurandom** [comment]
Strophe.js claims to support this: https://github.com/strophe/strophejs-plugins/tree/master/receipts

**Comment by vcarro** [comment]
+1

**Comment by robert-scheck** [comment]
Are there any plans for XEP-0184 support, ideally in combination with support for XEP-0198?

**Comment by jcbrand** [comment]
Relevant pull request #1304
