### ISSUE TITLE
When registering in converjs fullscreen, reload required

### ISSUE THREAD

**Issue by rusher7** [conversejs/converse.js#1411]
Browser: FireFox 64 bit
OS: Windows 7

When attempting to register a new account at conversejs.org/fullscreen , on the conversejs.org server , if you are returned 'The requested username already exists', you cannot register a different unused username without reloading the page.

Steps to reproduce:
1) Attempt to register account name 'test' with password 'test' under conversejs.org
2) Receive 'already exists' warning
3) Without reloading the page, attempt to create a different, non-taken, username.
4) Witness nothing happen

Possible interfering issues: uBlock (disabled on the site for test), performed in a private window, LastPass extension, website (dark mode) styling extension (set disabled).

**Comment by jcbrand** [comment]
Thanks for a good bug report. I've seen something similar to this happen when the BOSH terminates server-side, so I think there is some kind of bug that prevents re-establishing a session under certain circumstances.

**Comment by jcbrand** [comment]
I tested this with the latest code in the `master` branch and it works.
