### ISSUE TITLE
Clicking on avatar should show bigger version of avatar

### ISSUE THREAD

**Issue by guusdk** [conversejs/converse.js#1419]
I frequently find myself clicking on a users' avatar, in the hope of getting a better picture of the auto-cropped/smallish photo. Sadly, clicking does not have any effect in 4.1.0 (other than make me look silly).

**Comment by hairarrow** [comment]
@guusdk Hey, I'm trying to tackle a couple of issues for Hacktoberfest. Let me know if I can contribute.

**Comment by guusdk** [comment]
I fail to see any reason why you wouldn't be able to contribute!

**Comment by jcbrand** [comment]
@hairarrow take a look at `src/converse-modal.js` and the code that uses modals. You should be able to implement this feature fairly easily with a modal.
