### ISSUE TITLE
MUC: don't retrieve member list if not a member/admin/owner

### ISSUE THREAD

**Issue by guusdk** [conversejs/converse.js#1426]
https://xmpp.org/extensions/xep-0045.html#getmemberlist describes how the memberlist of a room can be retrieved. Converse 4.1.0 appears to unconditionally execute such queries (one for each type of affiliation).

https://xmpp.org/extensions/xep-0045.html#affil-priv describes that the 'retrieve member list' privilege is reserved for members, admins and owners only.

Converse should not retrieve the member list when the local user is not a member, admin or owner.

**Comment by licaon-kter** [comment]
@guusdk Can you retry with HEAD? Looks fixed for me.

**Comment by guusdk** [comment]
With 5.0.4, I'm not seeing any `muc#admin` query anymore when (re)joining a MUC room - not even when I'm an admin. Does that sound right?

**Comment by jcbrand** [comment]
@guusdk: Do you have `muc_fetch_members` set to `true`?

**Comment by guusdk** [comment]
Ah, thanks for the pointer. That has been explicitly set to `false`. If I toggle it to `true`, then the problem returns: Three requests (for `member`, `admin` and `owner`_ go out when I join a room. If i'm an owner of that room, that's OK. Sadly, the queries also go out when I am a room that I'm not an owner of.

**Comment by guusdk** [comment]
I believe that the problem persists with 8.0.1, yes.

When logging into a MUC room in which I am not a member, admin or owner, this is being logged to the browser console:

```
log.js:66  2021-11-04T14:31:00.844Z WARNING: Error: not allowed to fetch member list for MUC test@conference.example.org 
log.js:66  2021-11-04T14:31:00.845Z WARNING: <iq xmlns="jabber:client" type="error" id="372212d5-5968-46ca-977c-b1d18e795f14:sendIQ" from="test@conference.example.org" to="john@example.org/converse.js-127508716"><query xmlns="http://jabber.org/protocol/muc#admin"><item affiliation="member"/></query><error code="403" type="auth"><forbidden xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/><text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">You don't have authorization to perform this request.</text></error></iq> ```

**Comment by licaon-kter** [comment]
👍
