### ISSUE TITLE
Cannot read property 'properties' of undefined.

### ISSUE THREAD

**Issue by paul5hc** [conversejs/converse.js#1429]
Cannot find solution to 'make dist' error as follows: 

./node_modules/.bin/npx  webpack --mode=development
Cannot read property 'properties' of undefined
Makefile:191: recipe for target 'dist/converse.js' failed
make: *** [dist/converse.js] Error 1

Any help would be very much appreciated.

**Comment by jcbrand** [comment]
Did you modify any files before running `make dist`?

**Comment by paul5hc** [comment]
Solution found by updating webpack-cli. Running the following command solved the issue for me.

npm i -D webpack-cli @webpack-cli/update
