### ISSUE TITLE
Groupchat invitation textbox only showing when user is owner of room

### ISSUE THREAD

**Issue by deleolajide** [conversejs/converse.js#1434]
In this chatroom, there should be an invitation textbox because the room is open

![image](https://user-images.githubusercontent.com/110731/52279481-91fede80-2951-11e9-8fd3-4ac7fd0d3645.png)

I think the problem is here in converse-muc-views.js
```
            shouldInviteWidgetBeShown () {
                return _converse.allow_muc_invitations &&
                    (this.chatroomview.model.get('open') ||
                        this.chatroomview.model.get('affiliation') === "owner"
                    );
            },
```

this.chatroomview.model.get('open')  should be this.chatroomview.model.features.get('open')

**Comment by jcbrand** [comment]
Just checked the code. This is fixed.
