### ISSUE TITLE
Cannot connect to Openfire server

### ISSUE THREAD

**Issue by paul5hc** [conversejs/converse.js#1435]
I believe I have my Openfire server setup correctly to allow BOSH connections from my converse client. When I attempt to login to converse (providing username: admin@localhost, password: *******), the following is outputted in the console:

![screenshot from 2019-02-04 21-00-03](https://user-images.githubusercontent.com/25330735/52292436-9edcfb80-296c-11e9-99a4-e4b868a4ca09.png)

The following appears in the Openfire logs at the same time:

![screenshot from 2019-02-04 21-02-31](https://user-images.githubusercontent.com/25330735/52292460-ac928100-296c-11e9-90ca-33eb94d1d47c.png)

If anybody had any pointers of how to overcome this issue I would really appreciate it :)

**Comment by jcbrand** [comment]
What are the settings you're passing to `converse.initialize`? Also, set `debug` to `true` and then show the output in your browser console again.

**Comment by paul5hc** [comment]
**Solution Found:** 

Realized I didn't need the XAMPP server running in the background for what I needed so I turned this off. Changed my converse.initialize() to the following: 

```
converse.initialize({
      connection_options: {
          'mechanisms': [
              converse.env.Strophe.SASLMD5,
              converse.env.Strophe.SASLPlain
          ]
      },
      auto_away: 300,
      i18n: 'en',
      view_mode: 'fullscreen',
      archived_messages_page_size: '500',
      notify_all_room_messages: [
          'discuss@conference.conversejs.org'
      ],
      bosh_service_url: 'http://localhost:7070/http-bind/',
      message_archiving: 'always',
      debug: true
  });
```

The following link was of particular help to me: https://github.com/conversejs/converse.js/issues/751

Thanks for all the help!
