### ISSUE TITLE
Duplicate MUC participant listing

### ISSUE THREAD

**Issue by guusdk** [conversejs/converse.js#1439]
The MUC in the screenshot shows the user `gdt` to be in the room three times. This is using Converse 4.1.0.

They all appear to be different anonymous sessions (which sounds about right, given how this person, @GregDThomas, interacts with the room).

Server side (Openfire 4.3.2), the MUC reported to have just one `gdt`, which had exactly one XMPP session. I'm assuming that this person reloaded its web client a couple of times, which introduced the problem.

![screenshot from 2019-02-11 10-58-20](https://user-images.githubusercontent.com/4253898/52556161-10450000-2dec-11e9-8cad-c2021d58d99f.png)

**Comment by jcbrand** [comment]
Closing since this is a very old ticket and I haven't seen duplicated MUC participants since a long time.

**Comment by guusdk** [comment]
2019, very old? You clearly haven't seen _our_ issue tracker! ;)

I have not seen this issue again, either.
