### ISSUE TITLE
MUC read receipts causing empty lines

### ISSUE THREAD

**Issue by laszlovl** [conversejs/converse.js#1442]
The client is Chatsecure, so it could very well be that the format receive is invalid. Still, there shouldn't be any empty lines because of it and I'm sure this is a regression compared to an older Converse version.

![bug](https://user-images.githubusercontent.com/12112486/52580496-c9293000-2e28-11e9-9206-97f05399bba4.png)

The XML we receive:

```xml
<message xml:lang="en" to="user@domain.com/converse.js-57308413"
         from="room@conference.domain.com/user" type="groupchat" xmlns="jabber:client">
    <received xmlns="urn:xmpp:receipts" id="DC545AFB-FFC3-434C-BB6A-22F9F5069518"/>
    <origin-id xmlns="urn:xmpp:sid:0" id="CE08D448-5ED8-4B6A-BB5B-07ED9DFE4FF0"/>
</message>
```

**Comment by laszlovl** [comment]
I suspect https://github.com/conversejs/converse.js/commit/e1f8d53c46b43d025e326b155ae1c0abe98036da

**Comment by jcbrand** [comment]
Hmm, I thought I fixed this recently. Are you on the latest commit on the master branch?

**Comment by jcbrand** [comment]
Maybe I only fixed it for private chats...

**Comment by laszlovl** [comment]
Yeah, this is in the latest master. So far what I've got is that `handleReceipt()` isn't even called for these messages. Yet it generates a normal looking HTML:

```
<div class="message chat-msg groupchat chat-msg--followup" data-isodate="2019-02-11T18:34:30+01:00" data-msgid="" data-from="room@conference.domain.com/user" data-encrypted="">
```

**Comment by jcbrand** [comment]
>  So far what I've got is that `handleReceipt()` isn't even called for these messages. Yet it generates a normal looking HTML:

Yes, IIRC I only added this for one-one-one chats, probably with the intention of still adding it to MUCs. I've had a crazy-busy last two weeks.

**Comment by laszlovl** [comment]
Right, I mostly figured it out. The message isn't handled by converse-chatboxes `onMessage`, but by converse-muc `onMessage`. The latter currently doesn't check for receipts at all, if I copy & paste some code into it, like

```
const receipt = sizzle(`received[xmlns="${Strophe.NS.RECEIPTS}"]`, stanza).pop();
                    if (receipt) { ... }
```

it does detect that the message is a receipt.

Any thoughts on how to fix this nicely without duplicating code (and why the problem didn't appear to exist in previous versions? The commit I linked doesn't really explain that since mucs were left untouched)

**Comment by jcbrand** [comment]
> Any thoughts on how to fix this nicely without duplicating code

`handleReceipt` needs to be called for MUC messages as well. `ChatRoom` inherits `handleReceipt` from `ChatBox`, so it can be called on the chatroom object.
