### ISSUE TITLE
Doesn't show some emoticons in Chrome

### ISSUE THREAD

**Issue by wrooot** [conversejs/converse.js#1444]
Using https://xmpp.igniterealtime.org:7483/inverse/# (which should have recent converse version). If i type : ) or select Blush from icon picker it shows square image in the first case and regular emoticon in the second in Chrome. While in Firefox it shows smiley and blush smiley. Maybe that's Chrome's issue. Windows 7.

**Comment by jcbrand** [comment]
I think it's using system emojis in that case, which means that your system Win7 doesn't have that emoji.

**Comment by wrooot** [comment]
Yeah, on Windows 10 it shows emoji from Windows 10 emoji selection. I guess Firefox uses some built-in emojis.
