### ISSUE TITLE
Make call the method of converse.js from outer javascript

### ISSUE THREAD

**Issue by jitui2i** [conversejs/converse.js#145]
HI ,
  Here am facing i have one existing system like login means it have to login to xmpp and  on click on chat tab it should list me the roster and on click roster it need to initiate chat..

So here i connected via converse.js successfully.

But the problem is that , I want to make call onConnected method of converse.js that will give me the list of roster for the logged in users.

But i understnd from the code they are emiting onReady when the roster is being ready so i try below like in my javascript

require(['converse'], function (converse) {
                console.log(converse.on);
                //console.log(converse.emit);
                converse.on('onReady', function(){
                    console.log("----this is the helll m tensed yaar");
                });
                //converse.emit('onReady-chat');
            });

But that console.log never work for me...

Could anyone plz help me out of this ....

**Comment by xDaizu** [comment]
>@jcbrand
>
>Converse.js already has the following API methods:
>
>    initialize
>    getRID
>    getSID
>    once
>    on
>    off

Where are those documented? It feels like they should be at https://conversejs.org/docs/html/development.html#developer-api but they're not.

**Comment by jcbrand** [comment]
The API has changed somewhat since I wrote that:

https://conversejs.org/docs/html/development.html#initialize
https://conversejs.org/docs/html/development.html#tokens-grouping
https://conversejs.org/docs/html/development.html#listen-grouping
