### ISSUE TITLE
Bookmarks inconsistency

### ISSUE THREAD

**Issue by srgcdev** [conversejs/converse.js#1457]
I have notice that there is an inconsistency in bookmarks. Tested in the latest relase of converse 4.1.2.
In the list of group chats in the left is working well because converse.js show you the icon to unbookmark the group chat. In the other hand, when you have the group chat open, in the top of the screen, converse shows the icon to bookmark again the group chat.

I always connect to converse.js like an untrusted device and I always remove cookies when I close the browser, so it is like if always is the first time I enter the application.

![bookmarks1](https://user-images.githubusercontent.com/24658184/53296164-25695800-380a-11e9-900f-c9bd354e0eaa.png)
![bookmarks2](https://user-images.githubusercontent.com/24658184/53296165-25695800-380a-11e9-8c8a-6d0877f56a66.png)

**Comment by jcbrand** [comment]
That icon shows that the room is already bookmarked (that's why it is orange on a white background, otherwise it would be white on orange) and when you click it, you will remove the bookmark.

So it's working as intended.

If it's too confusing, we can think about having a different icon.

**Comment by srgcdev** [comment]
So the problem here is that the icons are differents, the icon in the list on the left and the top icon in the conversation are differents. The tooltip for the icon in the left it is ok but the tooltip for the icon on the top of the screen is confusing because suggests you to bookmark the room.

**Comment by srgcdev** [comment]
I attached some new images with the tooltips in english:
![image1](https://user-images.githubusercontent.com/24658184/53393424-9b9dc400-399c-11e9-808d-fe3b2535ea42.png)
![image2](https://user-images.githubusercontent.com/24658184/53393426-9d678780-399c-11e9-97da-2ab61925d831.png)
