### ISSUE TITLE
Contact name inconsistency

### ISSUE THREAD

**Issue by srgcdev** [conversejs/converse.js#1458]
I have noticed some inconsistency in the name of the contacts. In the contact list in the left and the title in the top screen is ok, but in the chat, I see the xmpp address instead of the contact name.

I remember I renamed this contact and maybe he doesn't set his name on his profile.

I always connect to converse.js like an untrusted device and I always remove cookies when I close the browser, so it is like if always is the first time I enter the application.

![contactname](https://user-images.githubusercontent.com/24658184/53296263-f2c05f00-380b-11e9-9478-8be9bc9c822d.png)

**Comment by jcbrand** [comment]
There isn't enough information here in order to write a test that reproduces the bug, so that it can be fixed.

If you can reliably reproduce this bug, perhaps you can send me the stanzas of that session?

**Comment by srgcdev** [comment]
@jcbrand, I sent you the info in private.
Thanks.

**Comment by srgcdev** [comment]
I think it is fixed in 5.0.1.
Thanks.
