### ISSUE TITLE
Large rooms will eat RAM until killed by the OS

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/converse.js#1459]
Eg.
![bigroomfail](https://user-images.githubusercontent.com/2282799/53333944-03ea9800-3900-11e9-8aff-e1891ea5e963.png)

Steps? Join `xmpp:#matrix#matrix.org@bridge.xmpp.matrix.org?join` ~5k users

FYI, Conversations (at least 2.4.0 or later) and apparently Yaxim handle these ok.

**Comment by darnuria** [comment]
I made a performance snapshot in firefox 67.0a1 (2019-03-06) (64-bit) before it become unusable.

![perf_issue_1459](https://user-images.githubusercontent.com/2827553/53990682-1ac39280-4129-11e9-942e-1b99a5ad9ccd.png)

Here the link to the performance snapshot (1.3 Mb compressed 8.1Mb uncompressed) it can be loaded in performance tab of firefox devtools.
https://framadrop.org/r/yXGF9VPBpl#zQRp+XTfDtkvPrCeTtLRaRkVDeoQMCGzQCumtd3Hya8=

**Comment by jcbrand** [comment]
@licaon-kter, @darnuria: looks like bridge.xmpp.matrix.org is no longer running, do you have a different bridge I could try?

**Comment by licaon-kter** [comment]
None that I know unfortunately.

**Comment by poVoq** [comment]
"muc_fetch_members: false" setting might be a temporary solution, but it seems like this isn't respected in ConverseJS version 5.0.5.

**Comment by licaon-kter** [comment]
The bridge is back, new syntax: `xmpp:#matrix#matrix.org@matrix.org?join`

Beware, use a disposable account as https://github.com/matrix-org/matrix-bifrost/issues/53 is not yet fixed

**Comment by licaon-kter** [comment]
Looks like on HEAD it's not leaking any more (at least with the current <3k users), it did jump to 1.5Gb RAM for Firefox, but after the roster was loaded is backed down to 500Mb.

Good job @jcbrand

**Comment by jcbrand** [comment]
Thanks, I'm closing this then.
