### ISSUE TITLE
Cannot disable controlbox by removing related plugin

### ISSUE THREAD

**Issue by jordila** [conversejs/converse.js#1460]
Hi, i'm  trying to disable the ControlBox altogether by removing the converse-controlbox plugin, [following the documented steps, and created a new build for](https://conversejs.org/docs/html/builds.html#creating-custom-bundles). 

When adding the blacklisting code snippet like this :  

`

converse.initialize({
     // more code here 		    
     debug: true

     blacklisted_plugins: [

	 'converse-controlbox'

     ],

 });

`
I'm getting a blank screen on my browser .

---
version : ConverseJS v4.

¿ What am i missing ?

**Comment by jcbrand** [comment]
You don't have a comma between `debug: true` and `blacklisted_plugins`

**Comment by jordila** [comment]
Yes, indeed . Fine now .
Just correcting the syntax error did the job. I succesfully removed the 'controlbox' , as per  the documentation.
Thanks for your support and for ConverseJS .
