### ISSUE TITLE
locked-domain should allow more than one host

### ISSUE THREAD

**Issue by disk0x** [conversejs/converse.js#1464]
Using converse.js (v4.1.2) as a Prosody module, if I set the option locked-domain, I can't give it a list (in prosody's lua config file) as value. It won't fail, but it will concatenate the two hosts and check against an invalid hostname and disallow any login.

There's benefit in locking an instance of conversejs to more than one host. In my case, I have two hostnames I use with prosody, and plan to add a third. Other users may want to whitelist friendly servers in addition to their own. 

If this feature is not desired, converse.js should fail in an obvious way.

**Comment by jcbrand** [comment]
This doesn't really make sense. What if you're trying to log in with only the node part of a JID but you have two locked domains? How do you know which domain to use?

I'm in favour of making Converse.js configurable, but I think there must be a limit somewhere. Making everything configurable to the nth degree complicates the code, requires many extra test-cases and makes it difficult to refactor, fix bugs or add new features. You can modify Converse.js with a plugin for your particular use-case if it deviates enough from the norm. If it proves popular and simple enough, it could be merged to core.

Concerning making things fail in an obvious way, it would be nice if we had better type checking for configuration values, but that should go into a new ticket then.

**Comment by disk0x** [comment]
> What if you're trying to log in with only the node part of a JID but you have two locked domains? How do you know which domain to use?

I believe that is handled by the option default_domain.

>  You can modify Converse.js with a plugin for your particular use-case if it deviates enough from the norm

Fair enough.

**Comment by jcbrand** [comment]
> I believe that is handled by the option default_domain.

Ok, I can see why you'd think so and it would make sense, but that's not how it's coded.

I was looking at these settings yesterday, because I added a `locked_muc_domain` setting, and I thought that ideally `locked_domain` would just be a boolean which determines whether `default_domain` is locked or not. Currently, it's quite confusing because `locked_domain` also takes a string value.

**Comment by disk0x** [comment]
> d I thought that ideally `locked_domain` would just be a boolean which determines whether `default_domain` is locked or not.

Yes, I see that if that's the eventual goal for this option, my proposal isn't compatible. Certainly these points being better clarified in the documentation (eg "it accepts only a string") would help.

For my use, I will explore the possibility of a pre-login form that will check the JID domain against a whitelist, and initiate the conversejs script with a different locked_domain value. I will see if I can then turn this into a plugin, I am not familiar with Javascript at the moment.
