### ISSUE TITLE
Inconsistent color for "Away" state

### ISSUE THREAD

**Issue by foss-** [conversejs/converse.js#1465]
When a user is away, the color indicator changes from green to orange. The inconsistency is, that when that chat is selected, the color of that user being away switches to green.

Expected: should stay orange, even when chat is selected.

![away unselected](https://user-images.githubusercontent.com/5708172/53478100-5e0d6980-3a76-11e9-98b4-b8aef90ee06c.png)
![away selected](https://user-images.githubusercontent.com/5708172/53478101-5e0d6980-3a76-11e9-95de-85a4e434f297.png)

**Comment by foss-** [comment]
Does https://github.com/conversejs/converse.js/commit/1be9958aa10954fceae8affcb1053d256aaf541e address this?

**Comment by jcbrand** [comment]
Yes, I forgot there was a bug report for this already.
