### ISSUE TITLE
Messages duplicating on reload on 4.1.2 w/ Prosody 0.11

### ISSUE THREAD

**Issue by cthu1hoo** [conversejs/converse.js#1483]
Opening new issue as requested, here's relevant stuff from closed issue #1087

https://github.com/conversejs/converse.js/issues/1087#issuecomment-469669968

Using Prosody 0.11 from Stretch backports via websockets (no difference with BOSH).

My Converse.js configuration can be seen here: https://xmpp.fakecake.org/index-test.html

**Comment by jjrh** [comment]
Same issue here - to replicate receive message, refresh page and there should be two messages. 
jcbrand mentioned in chat that this might be MAM related.

> ‎[04:43]‎jcbrand‎: jjrh: Please make a ticket, I think I've seen this before, and I think the issue is upon page refresh, the MAM result includes the last sent/received message

**Comment by cthu1hoo** [comment]
For me all stored messages duplicate every reload (I guess they are pulled from archive on login, I'm not really very familiar with how XMPP works)

**Comment by jjrh** [comment]
Someone suggested to include the converse init just in case. 
It was mentioned this might not occur with ejabberd. 
` converse.initialize({
    authentication: 'login',
    auto_away: 300,
    auto_reconnect: true,
    bosh_service_url: "https://example.com:5281/http-bind",
    message_archiving: 'always',
    view_mode: 'fullscreen',
    auto_list_rooms: true,
    allow_non_roster_messaging: true,
    allow_public_bookmarks: true,
    auto_list_rooms: true,
    whitelisted_plugins : ['converse-bookmarks'] 
})'`

**Comment by darnuria** [comment]
Hi, it's s
till present in `v4.2.0` in

**Comment by jcbrand** [comment]
Should be fixed by now.

**Comment by rodcaseribe** [comment]
ainda com bug, mensagens duplicadas aparecem para usuário
