### ISSUE TITLE
Unable to build on linux

### ISSUE THREAD

**Issue by kalabantas** [conversejs/converse.js#1484]
Unable to build with 4.1.2
whenever I try to make release or make dev (all), I get these errors:
I followed the instructions in here `https://m.conversejs.org/docs/html/development.html`
When I ran npm install, the directory headless was empty, so I had to run:
`npm install -save-dev @converse/headless`
which got rid of the headless related errors, and now I get these errors:

`ERROR in ./node_modules/@converse/headless/templates/field.html 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
> <field var="{{{o.name}}}">
| {[ if (o.value.constructor === Array) { ]}
|     {[ o.value.forEach(function (arrayValue) { ]}<value>{{{arrayValue}}}</value>{[ }); ]}
 @ ./node_modules/@converse/headless/utils/form.js 10:0-48 30:8-17
 @ ./src/converse-register.js
 @ ./src/converse.js

ERROR in ./node_modules/@converse/headless/templates/vcard.html 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
> <vCard xmlns="vcard-temp">
|     <FN>{{{o.fn}}}</FN>
|     <NICKNAME>{{{o.nickname}}}</NICKNAME>
 @ ./node_modules/@converse/headless/converse-vcard.js 9:0-47 98:49-58
 @ ./src/converse.js
`

**Comment by kalabantas** [comment]
Hello, and thanks for the prompt answer. I am using node 11.8

**Comment by jcbrand** [comment]
The reason why you didn't have `@converse/headless` is because `lerna bootstrap --hoist` wasn't called, the solution is NOT to manually install it with `npm install -save-dev @converse/headless` and you also don't have to manually run `npm install`. Instead, the Makefile already does everything you need.

Just run `make clean && make dist`

**Comment by kalabantas** [comment]
Thanks JCBrand for the prompt reply, and the excellent software, with organized code, and great plugin structure. It helps a lot in organizing the code, and isolating devlopers work from the main plugin. Hope that this turns to an industry standard.
I tried the make clean && make dist , yes, it got the @converse/headless however. I get this error:


ERROR in ./node_modules/@converse/headless/templates/field.html 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
> <field var="{{{o.name}}}">
| {[ if (o.value.constructor === Array) { ]}
|     {[ o.value.forEach(function (arrayValue) { ]}<value>{{{arrayValue}}}</value>{[ }); ]}
 @ ./node_modules/@converse/headless/utils/form.js 10:0-48 30:8-17
 @ ./src/converse-register.js
 @ ./src/converse.js

ERROR in ./node_modules/@converse/headless/templates/vcard.html 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
> <vCard xmlns="vcard-temp">
|     <FN>{{{o.fn}}}</FN>
|     <NICKNAME>{{{o.nickname}}}</NICKNAME>
 @ ./node_modules/@converse/headless/converse-vcard.js 9:0-47 98:49-58
 @ ./src/converse.js


Any ideas?

**Comment by jcbrand** [comment]
Thank you for the compliments 🙏😊

Did you modify the webpack configuration at all? It looks like the lodash template loader is not active.

**Comment by kalabantas** [comment]
Thanks for your reply. I started all over by deleting the folder and cloning a fresh copy from git. 
make dist succeeded with no errors, however
make dev, make release,  fails with the following errors:  
ERROR in ./src/converse-rosterview.js
Module not found: Error: Can't resolve '@converse/headless/converse-chatboxes' in '/home/user/converse.js/src'
 @ ./src/converse-rosterview.js 7:0-47
 @ ./src/converse.js

ERROR in ./src/converse-chatboxviews.js
Module not found: Error: Can't resolve '@converse/headless/converse-chatboxes' in '/home/user/converse.js/src'
 @ ./src/converse-chatboxviews.js 6:0-47
 @ ./src/converse-chatview.js
 @ ./src/converse.js

ERROR in ./src/converse.js
Module not found: Error: Can't resolve '@converse/headless/converse-core' in '/home/user/converse.js/src'
 @ ./src/converse.js 44:0-56 46:19-27 48:0-8 49:6-14 58:15-23

ERROR in ./src/converse-caps.js
Module not found: Error: Can't resolve '@converse/headless/converse-core' in '/home/user/converse.js/src'
 @ ./src/converse-caps.js 6:0-56 7:22-30 46:0-8
 @ ./src/converse.js

ERROR in ./src/converse-embedded.js
Module not found: Error: Can't resolve '@converse/headless/converse-core' in '/home/user/converse.js/src'
 @ ./src/converse-embedded.js 7:0-56 8:22-30 11:0-8
 @ ./src/converse.js

ERROR in ./src/converse-fullscreen.js
Module not found: Error: Can't resolve '@converse/headless/converse-core' in '/home/user/converse.js/src'
 @ ./src/converse-fullscreen.js 11:0-56 13:22-30 16:0-8
 @ ./src/converse.js

ERROR in ./src/converse-headline.js
Module not found: Error: Can't resolve '@converse/headless/converse-core' in '/home/user/converse.js/src'
 @ ./src/converse-headline.js 7:0-56 9:22-30 12:0-8
 @ ./src/converse.js

ERROR in ./src/converse-push.js
Module not found: Error: Can't resolve '@converse/headless/converse-core' in '/home/user/converse.js/src'
 @ ./src/converse-push.js 10:0-56 11:22-30 16:0-8
 @ ./src/converse.js

ERROR in ./src/converse-autocomplete.js
Module not found: Error: Can't resolve '@converse/headless/converse-core' in '/home/user/converse.js/src'
 @ ./src/converse-autocomplete.js 8:0-56 9:22-30 12:10-18 13:0-8
 @ ./src/converse.js

ERROR in ./src/converse-dragresize.js
Module not found: Error: Can't resolve '@converse/headless/converse-core' in '/home/user/converse.js/src'
 @ ./src/converse-dragresize.js 11:0-56 13:10-18 22:0-8
 @ ./src/converse.js

ERROR in ./src/converse-notification.js
Module not found: Error: Can't resolve '@converse/headless/converse-core' in '/home/user/converse.js/src'
 @ ./src/converse-notification.js 9:0-56 10:22-30 14:10-18 15:0-8
 @ ./src/converse.js

ERROR in ./src/converse-roomslist.js
Module not found: Error: Can't resolve '@converse/headless/converse-core' in '/home/user/converse.js/src'
 @ ./src/converse-roomslist.js 10:0-56 14:22-30 20:10-18 21:0-8
 @ ./src/converse.js

ERROR in ./src/converse-minimize.js
Module not found: Error: Can't resolve '@converse/headless/converse-core' in '/home/user/converse.js/src'
 @ ./src/converse-minimize.js 7:0-56 12:22-30 18:10-18 19:0-8
 @ ./src/converse.js

ERROR in ./src/converse-bookmarks.js
Module not found: Error: Can't resolve '@converse/headless/converse-core' in '/home/user/converse.js/src'
 @ ./src/converse-bookmarks.js 13:0-56 19:22-30 26:10-18 27:0-8
 @ ./src/converse.js

ERROR in ./src/converse-controlbox.js
Module not found: Error: Can't resolve '@converse/headless/converse-core' in '/home/user/converse.js/src'
 @ ./src/converse-controlbox.js 14:0-56 21:22-30 27:10-18 62:0-8
 @ ./src/converse.js

ERROR in ./src/converse-register.js
Module not found: Error: Can't resolve '@converse/headless/converse-core' in '/home/user/converse.js/src'
 @ ./src/converse-register.js 14:0-56 24:22-30 43:0-8
 @ ./src/converse.js

ERROR in ./src/converse-rosterview.js
Module not found: Error: Can't resolve '@converse/headless/converse-core' in '/home/user/converse.js/src'
 @ ./src/converse-rosterview.js 11:0-56 20:22-30 27:10-18 28:0-8 1099:10-18 1100:8-16 1101:8-16 1102:8-16 1103:15-23
 @ ./src/converse.js

ERROR in ./src/converse-omemo.js
Module not found: Error: Can't resolve '@converse/headless/converse-core' in '/home/user/converse.js/src'
 @ ./src/converse-omemo.js 8:0-56 10:22-30 21:10-18 70:0-8
 @ ./src/converse.js

ERROR in ./src/converse-chatview.js
Module not found: Error: Can't resolve '@converse/headless/converse-core' in '/home/user/converse.js/src'
 @ ./src/converse-chatview.js 11:0-56 29:22-30 39:0-8
 @ ./src/converse.js

ERROR in ./src/converse-muc-views.js
Module not found: Error: Can't resolve '@converse/headless/converse-core' in '/home/user/converse.js/src'
 @ ./src/converse-muc-views.js 9:0-56 33:22-30 45:10-18 47:0-8 565:52-60 590:52-60 770:52-60 1392:45-53 1418:45-53 1599:47-55 1670:86-94 1855:51-59 1857:58-66 2046:50-58 2229:47-55
 @ ./src/converse.js

ERROR in ./src/converse-singleton.js
Module not found: Error: Can't resolve '@converse/headless/converse-core' in '/home/user/converse.js/src'
 @ ./src/converse-singleton.js 18:0-56 19:22-30 22:10-18 35:0-8
 @ ./src/converse-fullscreen.js
 @ ./src/converse.js

ERROR in ./src/converse-profile.js
Module not found: Error: Can't resolve '@converse/headless/converse-core' in '/home/user/converse.js/src'
 @ ./src/converse-profile.js 13:0-56 19:22-30 26:10-18 27:0-8
 @ ./src/converse-controlbox.js
 @ ./src/converse.js

ERROR in ./src/converse-modal.js
Module not found: Error: Can't resolve '@converse/headless/converse-core' in '/home/user/converse.js/src'
 @ ./src/converse-modal.js 8:0-56 10:22-30 14:0-8
 @ ./src/converse-rosterview.js
 @ ./src/converse.js

ERROR in ./src/converse-chatboxviews.js
Module not found: Error: Can't resolve '@converse/headless/converse-core' in '/home/user/converse.js/src'
 @ ./src/converse-chatboxviews.js 9:0-56 13:22-30 38:0-8
 @ ./src/converse-chatview.js
 @ ./src/converse.js

ERROR in ./src/converse-message-view.js
Module not found: Error: Can't resolve '@converse/headless/converse-core' in '/home/user/converse.js/src'
 @ ./src/converse-message-view.js 6:0-56 16:22-30 20:0-8
 @ ./src/converse-chatview.js
 @ ./src/converse.js

ERROR in ./src/converse.js
Module not found: Error: Can't resolve '@converse/headless/converse-mam' in '/home/user/converse.js/src'
 @ ./src/converse.js 5:0-41

ERROR in ./src/converse-embedded.js
Module not found: Error: Can't resolve '@converse/headless/converse-muc' in '/home/user/converse.js/src'
 @ ./src/converse-embedded.js 6:0-41
 @ ./src/converse.js

ERROR in ./src/converse-fullscreen.js
Module not found: Error: Can't resolve '@converse/headless/converse-muc' in '/home/user/converse.js/src'
 @ ./src/converse-fullscreen.js 7:0-41
 @ ./src/converse.js

ERROR in ./src/converse-roomslist.js
Module not found: Error: Can't resolve '@converse/headless/converse-muc' in '/home/user/converse.js/src'
 @ ./src/converse-roomslist.js 11:0-50
 @ ./src/converse.js

ERROR in ./src/converse-bookmarks.js
Module not found: Error: Can't resolve '@converse/headless/converse-muc' in '/home/user/converse.js/src'
 @ ./src/converse-bookmarks.js 14:0-50
 @ ./src/converse.js

ERROR in ./src/converse.js
Module not found: Error: Can't resolve '@converse/headless/converse-ping' in '/home/user/converse.js/src'
 @ ./src/converse.js 7:0-42

ERROR in ./src/converse.js
Module not found: Error: Can't resolve '@converse/headless/converse-pubsub' in '/home/user/converse.js/src'
 @ ./src/converse.js 9:0-44

ERROR in ./src/converse-rosterview.js
Module not found: Error: Can't resolve '@converse/headless/converse-roster' in '/home/user/converse.js/src'
 @ ./src/converse-rosterview.js 6:0-44
 @ ./src/converse.js

ERROR in ./src/converse.js
Module not found: Error: Can't resolve '@converse/headless/converse-vcard' in '/home/user/converse.js/src'
 @ ./src/converse.js 11:0-43

ERROR in ./src/converse-profile.js
Module not found: Error: Can't resolve '@converse/headless/converse-vcard' in '/home/user/converse.js/src'
 @ ./src/converse-profile.js 9:0-43
 @ ./src/converse-controlbox.js
 @ ./src/converse.js

ERROR in ./src/converse-controlbox.js
Module not found: Error: Can't resolve '@converse/headless/lodash.fp' in '/home/user/converse.js/src'
 @ ./src/converse-controlbox.js 15:0-46
 @ ./src/converse.js

ERROR in ./src/utils/html.js
Module not found: Error: Can't resolve '@converse/headless/templates/field.html' in '/home/user/converse.js/src/utils'
 @ ./src/utils/html.js 12:0-64
 @ ./src/converse-message-view.js
 @ ./src/converse-chatview.js
 @ ./src/converse.js

ERROR in ./src/converse-chatview.js
Module not found: Error: Can't resolve '@converse/headless/utils/emoji' in '/home/user/converse.js/src'
 @ ./src/converse-chatview.js 27:0-47 109:23-24 110:32-33 111:26-27 215:19-20 236:8-9 249:8-9 570:28-29 594:26-27 601:25-26 638:30-31 679:129-130 681:102-103 686:16-17 713:52-53 744:13-14 744:52-53 745:10-11 752:13-14 753:10-11 755:10-11 768:13-14 768:40-41 783:12-13 790:58-59 883:8-9 889:10-11 896:8-9 920:39-40 965:27-28 976:34-35 1068:10-11 1070:10-11 1087:8-9 1150:8-9 1172:12-13 1261:12-13 1266:8-9 1270:8-9 1300:8-9 1320:12-13
 @ ./src/converse.js

ERROR in ./src/converse-message-view.js
Module not found: Error: Can't resolve '@converse/headless/utils/emoji' in '/home/user/converse.js/src'
 @ ./src/converse-message-view.js 14:0-47 57:28-29 76:10-11 106:55-56 107:8-9 124:20-21 137:77-78 137:116-117 137:156-157 137:196-197 151:51-52 151:111-112 151:197-198 151:214-215 151:242-243 154:24-25 167:20-21 198:28-29 206:20-21 247:15-16
 @ ./src/converse-chatview.js
 @ ./src/converse.js

ERROR in ./src/converse-register.js
Module not found: Error: Can't resolve '@converse/headless/utils/form' in '/home/user/converse.js/src'
 @ ./src/converse-register.js 22:0-50 515:54-59 635:21-26
 @ ./src/converse.js

ERROR in ./src/converse-muc-views.js
Module not found: Error: Can't resolve '@converse/headless/utils/muc' in '/home/user/converse.js/src'
 @ ./src/converse-muc-views.js 10:0-53
 @ ./src/converse.js

**Comment by jcbrand** [comment]
I think those errors are related to Lerna and `lerna bootstrap --hoist` not being called.

Should be fixed by now. Please reopen if you still have the same problem with the latest version in the master branch.
