### ISSUE TITLE
Users rights status

### ISSUE THREAD

**Issue by rodrigolzd** [conversejs/converse.js#1486]
I find unnecessary to have the users rights in the room to be show with the full wording. It is too large. Perhaps just and image or the initial of the status if you must have it. O = Owner, M = Moderator. A mouse hover over the icon/letter should indicate what it means

There is no need to show the "Member" status, it's just pollution, if it must show this type of status, it should show that someone is not a member.

Originally posted on pade
https://github.com/igniterealtime/Pade/issues/59

**Comment by jcbrand** [comment]
You can't hover with a mouse on mobile.

**Comment by rodrigolzd** [comment]
True, but you could have the information about the letters show somewhere else, some other panel like the information panel. It would save space anyway. Is the user experience on both mobile and desktop exactly the same?

**Comment by jcbrand** [comment]
It's the same UI for mobile and desktop.

You're welcome to propose a concrete change or make a pull request. Good UX is hard and we don't have enough UX experts contributing to the project.
