### ISSUE TITLE
Busy-loop when fetching registration form fails

### ISSUE THREAD

**Issue by weiss** [conversejs/converse.js#1490]
At least with a `registration_domain` specified, Converse.js busy-loops when requesting a registration form and the server responds with e.g. the following error:

```xml
<iq xml:lang='en' from='example.com' type='error' id='d9917b7a-588f-4ef6-8a56-0d6d3ad538ae:sendIQ'>
  <query xmlns='jabber:iq:register'/>
  <error code='500' type='wait'>
    <resource-constraint xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>
    <text xml:lang='en' xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>Too many CAPTCHA requests</text>
  </error>
</iq>
```

It spits out [`ERROR: Problem during registration: Strophe.Status is REGIFAIL`][1].

Even though the error is of `type='wait'`, I think it would be better to just abort the request and display the error message.

(Can easily be reproduced by setting `registration_domain: 'conversations.im'` and reloading the registration dialog a few times.)

[1]: https://github.com/conversejs/converse.js/blob/76bff83ca31d7f955023401b54cb15a1376911bd/src/converse-register.js#L409

**Comment by jcbrand** [comment]
@weiss When I enter 'conversations.im' in the server field (the step before the registration form is fetched), then I get an error that a connection could not be established. Does conversations.im still allow in-band registration?

**Comment by jcbrand** [comment]
I believe I've fixed the issue. Would be great if you could double-check.

**Comment by licaon-kter** [comment]
Seeing this for while too.

**Comment by jcbrand** [comment]
No, it's back because the "fix" broke other stuff.
