### ISSUE TITLE
Ignore newlines prior to content in a message

### ISSUE THREAD

**Issue by guusdk** [conversejs/converse.js#1494]
When a message body starts with a newline, that newlines shouldn't be displayed when rendering the message. The message body should always be displayed on the first line.

**Comment by Ppjet6** [comment]
On March 14, 2019 10:37:51 AM UTC, Guus der Kinderen <notifications@github.com> wrote:
>When a message body starts with a newline, that newlines shouldn't be
>displayed when rendering the message. The message body should always be
>displayed on the first line.

Why would you not have the message displayed as it arrives and fix the issue on the other side rather?

**Comment by guusdk** [comment]
> Why would you not have the message displayed as it arrives and fix the issue on the other side rather?

Because I can't force people that use misbehaving clients to update, but I can update my client.

**Comment by Ppjet6** [comment]
On 2019/03/17, Guus der Kinderen wrote:
> > Why would you not have the message displayed as it arrives and fix the issue on the other side rather?
> 
> Because I can't force people that use misbehaving clients to update, but I can update my client.

What if that whitespace has meaning? :/

-- 
Maxime “pep” Buquet

**Comment by guusdk** [comment]
It won't have for 99%+ of the occurrences, and people that would have liked
to somehow use it, won't be surprised if it didn't work (as Conversations
also trims leading newline characters)

Op zo 17 mrt. 2019 12:43 schreef Maxime Buquet <notifications@github.com>:

**Comment by jcbrand** [comment]
> What if that whitespace has meaning? :/

Spoken like a Python programmer
