### ISSUE TITLE
API for sending out messages

### ISSUE THREAD

**Issue by irvingwa** [conversejs/converse.js#1496]
Hello all. I use the below code to send a message to bob. Bob receives the message and can see the message in his chat box. The person who sent the message never sees the message in his chat log but Bob does.
``` _converse.api.chats.open('bob@test.com');
                    var msg = converse.env.$msg({
                        'from': _converse.connection.jid,
                        'id': _converse.connection.getUniqueId(),
                        to: 'bob@test.com',
                        type: 'chat'
                    }).c('body').t('hello world').up();
                    _converse.api.send(msg);

**Comment by jcbrand** [comment]
`_converse.api.send` is a fairly low-level API call that simply sends an XML stanza, it's not applicable to only messages, but also to `presence` and `IQ` stanzas.

So when you use it to send a stanza, the chatbox of your sending user is not aware that a message was sent out.

Looks like there isn't yet an API method for sending out messages in the way that you expected. We should fix this.

For now, I think your best bet is to use the [sendMessage](https://github.com/conversejs/converse.js/blob/5b4ce87a4d1ae6998ce1bc90e792697309b58a28/src/headless/converse-chatboxes.js#L528) method on the `ChatBox` model.

**Comment by jcbrand** [comment]
I've now documented the [sendMessage](https://github.com/conversejs/converse.js/blob/27557d6a04ae731e6ed8c41e7b67eb4037527876/src/headless/converse-chatboxes.js#L515) method as an official API method for sending out messages.

For more info, see here: https://github.com/conversejs/converse.js/issues/1504#issuecomment-475388636
