### ISSUE TITLE
Preview MUC logs before entering

### ISSUE THREAD

**Issue by poVoq** [conversejs/converse.js#1500]
There is this open pull request to allow previewing a MUC:
https://github.com/conversejs/converse.js/pull/1266
(works by adding guest users, I think)

And it would be nice if there would be some sort of easy to customize portal page around it, where you can add links to various channels and some explanations etc. all in a similar design/theming to InverseJS so that the user doesn't have a hugely different view once logging in.

Also see this proposal for a similar but slightly different implementation idea:
https://github.com/conversejs/community-plugins/issues/4

**Comment by jcbrand** [comment]
This feature request is too vague for me to know what you really want.

**Comment by poVoq** [comment]
basically something like this: https://wikisuite.chat/XMPP just officially in ConverseJS fullscreen, so that you can have non-logged in users have a preview of the MUC discussion.

**Comment by jcbrand** [comment]
I'm restricting the scope of this ticket to only showing the a preview of MAM logs for a MUC, before actively joining it.

How you want to expose that your site is then a matter of configuration.

**Comment by pdurbin** [comment]
> There is this open pull request to allow previewing a MUC:
> #1266

This has been merged now. Hooray! 🎉

**Comment by jcbrand** [comment]
Indeed! Closing.
