### ISSUE TITLE
Custom JID template

### ISSUE THREAD

**Issue by kevinfaguiar** [conversejs/converse.js#1505]
Currently converse.js headless attach, to the user JID, "/converse-randomnumber". 
Example JID:
`kevin.aguiar@chat/converse-5151516`
My question is: it is possible to customize this client info part of the jid ("converse-5151516")? I found this issue https://github.com/conversejs/converse.js/issues/687 but it is related to domain, not to the client identification...

**Comment by jcbrand** [comment]
Yes, you can [override](https://conversejs.org/docs/html/plugin_development.html#overrides) the [generateResource](https://github.com/conversejs/converse.js/blob/27557d6a04ae731e6ed8c41e7b67eb4037527876/src/headless/converse-core.js#L535) method.

So you would do something like this (untested):

```javascript
converse.plugins.add('myplugin', {
    overrides: {
        generateResource ()  {
            return `/${Math.floor(Math.random()*139749528).toString()}`
        }
    }
});
```

Remember to [whitelist](https://conversejs.org/docs/html/configuration.html#whitelisted-plugins) your plugin.
