### ISSUE TITLE
Minimized bookmarked chatboxes are always maximized after page reload

### ISSUE THREAD

**Issue by fabiomontefuscolo** [conversejs/converse.js#1508]
https://github.com/conversejs/converse.js/blob/10da92ec5b51a3d2275e202494a234d7e3ab881a/src/converse-bookmarks.js#L256

Should it be? 
```javascript
                    if (!(groupchat.get('hidden') || groupchat.get('minimized'))) {
                        groupchat.trigger('show');
                    }
```

**Comment by jcbrand** [comment]
Yes, I think that's the fix for the bug. Will you please make a PR?

**Comment by guusdk** [comment]
I don't claim to understand the issue or fix, but I've happily provided a PR with Fabio's changes in https://github.com/conversejs/converse.js/pull/1510
