### ISSUE TITLE
Browser locks/freezes with many roster users

### ISSUE THREAD

**Issue by ffPjrZUGXfcxuAj** [conversejs/converse.js#151]
with 500 user in the roster converjs lock the browser

**Comment by jcbrand** [comment]
> Does items change from callback to callback?

Yes. The items change when a roster contact removes you from their roster.

I've made a commit to at least stop calling ``_.pluck`` for ever iteration of the for loop.

To really fix this, strophe.muc needs to be checked out and instead the roster code needs to be written inside converse.js using the same Backbone models.
