### ISSUE TITLE
Sort Groups by mention and Search

### ISSUE THREAD

**Issue by fingertips-solutions** [conversejs/converse.js#1518]
Hi,

I want to sort groups by latest mentions. can you please let me know how can i sort groups ? 

I have checked some code but didn't get a clue. if you tell me how can we sort groups that will be great. 

Also do converse support searching a chat or searching a group ? 

Thanks

**Comment by jcbrand** [comment]
Sorry, we don't help with development in the issue tracker, we simply don't have the time and energy for it.

The issue tracker is for bug reports and feature requests.
