### ISSUE TITLE
4.2.0 - omemo issue

### ISSUE THREAD

**Issue by mwlczk** [conversejs/converse.js#1520]
TypeError: a is undefined[Learn More] converse-omemo.js:546:20

'preKey': {
   'keyId': prekey.id, // <Number>  

involved Clients: 
Chatpartner: Conversations latest version 
me: Conversations (latest version), Gajim (latest versions), Converse 4.2.0

It is a 1:1 chat.
I can see the encrypted messages from my other devices (conversations and gajim) decrypted in converse.
I cannot send encrypted messages from converse. input field of chat window gets stuck/grayed out.
I receive encrypted messages from my chat-partner, but cannot read them decrypted. I see only the standard text about "there is an OMEMO encrypted message..."  

BTW: it is marek from the sprint last weekend here.
Thanks for your work. I'll be happy to help find that bug.

**Comment by licaon-kter** [comment]
Seeing the same here.

**Comment by jcbrand** [comment]
> TypeError: a is undefined[Learn More] converse-omemo.js:546:20

Hi Marek, where are you testing this?

**Comment by mwlczk** [comment]
I see this on my own installation, and on the official website of conversejs.org

**Comment by mwlczk** [comment]
Happy Easter JC,
is this [comment](https://github.com/conversejs/converse.js/issues/1520#issuecomment-480397895) enough information? Can I contribute anything more?

**Comment by jcbrand** [comment]
Hi Marek, unfortunately I don't have time to look into OMEMO issues currently. We'll have to organize another sprint!

**Comment by solus-hq** [comment]
Same here, input field is greyed out, but when I chat over Conversations everything is fine, messages are displayed via message carbons in Converse..

**Comment by jcbrand** [comment]
This might be a duplicate of #1524 which was just resolved.

**Comment by mwlczk** [comment]
I pulled the master (https://github.com/conversejs/converse.js/commit/2fca442f57f64d1f0b174db21d879c170b866168) and was able to build it myself. This problem is solved. But there is another smaller one. which I am going to open a new issue for.
