### ISSUE TITLE
Drop down list for inviting new participants stopped working in ver 4.2.0

### ISSUE THREAD

**Issue by deleolajide** [conversejs/converse.js#1522]
dele: Testing 4.2.0. The participants pull down list does not seem to be working. Anyone else noticed?

jc: For invites? Yeah, looks like it

jc: Dele Olajide, did you fix the invite dropdown issue?

dele: Nope. I though adding the missing lib will fix it, but no dice. I think it will require your attention. Shall I raise an issue?

jc: yes please

**Comment by jcbrand** [comment]
Works in master (not sure what fixed it).
