### ISSUE TITLE
Busy loop during login Wordpress/Git

### ISSUE THREAD

**Issue by danjde** [conversejs/converse.js#1523]
VPS Debian Stretch, Prosody 0.11, Fail2ban 0.9.6-2, Shorewall 5.0.15.6-1, Apache 2.4.25, modsecurity 3.0.0-3, php7 7.0.33, Converse.js v4.2.0.

Hi Developers,
I'm experiencing a strange behavior:

A few days ago I've installed Converse.js v4.1.4 from git and all seemed working fine, then I decided to install [Converse Wordpress plugin ](https://it.wordpress.org/plugins/conversejs/) same version and from that moment both stop working, only the login screen but no possibility to login, only the spinning wheel.

Then I decided to delete the Converse 4.1.4 directory and "re-git" Converse.js v4.2.0. 
From that point the Converse git version continues to work.

So I decided to install the Converse Wordpress Plugin, in the meantime passed to 4.2.0. It still does not work, same behavior as before, spinning wheel on login.

On Wordpress site I've installed Wordfence plugin, but on "learning mode". I've try to delete all (same domain) wordfence .htaccess entry, but nothing change.
Actually I'm using "fullscreen.html" into wordpress iframe and it is working fine; on the same page I've "mobile.html" that doesn't permit login, same version.
I've write to the WordPress developer, where he says it is a Converse.js problem.
In fact, the previous git version did not allow me to log in, independently of the plugin installed/uninstalled.
It is also true that after installing the plugin the git 4.1.4 version also stopped working.

I've look into server logs, but I'm unable to see anything to interesting.

If you want I can give (in private) all URLs.

Thanks!

Davide

**Comment by jcbrand** [comment]
The wordpress plugin is not part of the official project. Please contact the developer of that plugin directly or via the appropriate channel.
