### ISSUE TITLE
OMEMO libsignal-protocol.js Invalid signature

### ISSUE THREAD

**Issue by danjde** [conversejs/converse.js#1524]
Hi Dev,
I've just installed (from git) on VPS Debian Stretch, Prosody 0.11, Fail2ban 0.9.6-2, Shorewall 5.0.15.6-1, Apache 2.4.25, modsecurity 3.0.0-3, php7 7.0.33, Converse.js v4.2.0.

Then I've enabled OMEMO, as described from @licaon-kter [here](https://github.com/conversejs/converse.js/issues/1245#issuecomment-480012668),
the green padlock is present but trying to send in OMEMO mode I get the following error:

`Error: Invalid signature libsignal-protocol.js:25278:28`

and obviously the message does not start.

I've try to exit, re-enter in untrusted device mode and back in trusted device as suggested [here](https://github.com/conversejs/converse.js/issues/1242) with no changes.

[Here](https://converse.3x1t.org/fullscreen.html) my Converse installation.

Thanks!

Davide

**Comment by licaon-kter** [comment]
Seeing the same with gray stuck inputbox if I regenerate the key.

**Comment by philfry** [comment]
Same here. I cannot send omemo messages (input box turns grey and freezes). Receiving omemo-encrypted messages is not a problem, though.
Using https://cdn.conversejs.org/3rdparty/libsignal-protocol.min.js .

**Comment by danjde** [comment]
I've try from the[ developer Converse.js page](https://conversejs.org/fullscreen.html), and the behaviour seems the same:
`
Error: Invalid signature libsignal-protocol.min.js:1:718658 `

**Comment by chee** [comment]
I downgraded to 4.1.2 on my server and OMEMO messages send again. This was introduced in 4.2.0

**Comment by rscmbbng** [comment]
A new installation via Prosody's mod_conversejs, where the files are loaded via cdn.conversejs.org also has this issue.

**Comment by licaon-kter** [comment]
Can someone with ejabberd (besides me) test?

**Comment by jcbrand** [comment]
@licaon-kter: I've run into this issue myself. I'll try to include a fix with the next release.

**Comment by orbitz** [comment]
After doing some bisecting, I've tracked the introduction of this bug to this commit:

https://github.com/conversejs/converse.js/commit/1dfdb36d200ce8652ebf2877ece8926cf8daa221

**Comment by orbitz** [comment]
Reverting that change in 4.2.0 resolved the issue for me.

**Comment by jcbrand** [comment]
Thank you @orbitz, that's very helpful! I'm working on a commit to fix this.

**Comment by danjde** [comment]
Hi Devs,
I've merged into my converse.js 4.20 the @orbitz changes, exit, re-enter in untrusted device mode and back in trusted device as suggested [here](https://github.com/conversejs/converse.js/issues/1245#issuecomment-480012668) and now this message error appear:

```
ERROR: IQError@https://www.converse.3x1t.org/dist/converse.js:56083:5
fetchBundleFromServer@https://www.converse.3x1t.org/dist/converse.js:57052:17
  converse.js:63317:5
	["./src/headless/converse-core.js"]/_converse.log https://www.converse.3x1t.org/dist/converse.js:63317:5
	handleMessageSendError https://www.converse.3x1t.org/dist/converse.js:56403:11
	wrappedOverride https://www.converse.3x1t.org/dist/converse.js:32507:20
	apply https://www.converse.3x1t.org/dist/converse.js:8332:12
	wrapper https://www.converse.3x1t.org/dist/converse.js:13177:16
	sendMessage https://www.converse.3x1t.org/dist/converse.js:56426:13
```
and:

`

Unable to send an encrypted message due to an unexpected error.

<iq xmlns="jabber:client" to="cosmogonia@3x1t.org/converse.js-136910396" type="error" id="656f086a-6d3a-4031-bffd-e6c56baa4530:sendIQ"><error type="cancel"><item-not-found xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></iq>
`

Thanks!

**Comment by jcbrand** [comment]
@danjde: That error seems to indicate that your contact doesn't have a published OMEMO bundle.

It doesn't indicate that there's a bug in Converse.js.

**Comment by orbitz** [comment]
@danjde Do you know what the other side of your communication is using for OMEMO?  According to the OMEMO XEP, how converse.js is discovering OMEMO support is correct (query for device list for the contact).  So it sounds like the other side is presenting devices but not publishing a bundle.

**Comment by danjde** [comment]
> @danjde: That error seems to indicate that your contact doesn't have a published OMEMO bundle.
> 
> It doesn't indicate that there's a bug in Converse.js.

Strange, I've try using the same contacts that daily I chat with Dino and Conversations (with OMEMO).

**Comment by danjde** [comment]
> @danjde Do you know what the other side of your communication is using for OMEMO? According to the OMEMO XEP, how converse.js is discovering OMEMO support is correct (query for device list for the contact). So it sounds like the other side is presenting devices but not publishing a bundle.

Could you publish your

```
dist/converse.js
spec/omemo.js
src/converse-omemo.js
```

please?

Many thanks ;-)

**Comment by orbitz** [comment]
My src/converse-omemo.js is the one in the repo.

**Comment by licaon-kter** [comment]
@danjde Put all your files on your server, edit your index to load them from /dist and not `cdn....min....`

**Comment by danjde** [comment]
> @danjde Put all your files on your server, edit your index to load them from /dist and not `cdn....min....`

Well, I will check my system as you suggest.
But my doubt is: if I encounter this problem on the official Converse page too, the problem should be independent from my system. Could be what I tell right? :-\

Thanks!

**Comment by licaon-kter** [comment]
Independent of server, maybe your browser is broken? Maybe the CDN is blocked in $COUNTRY, dunno
