### ISSUE TITLE
Mobile display problem

### ISSUE THREAD

**Issue by jimmc929** [conversejs/converse.js#1527]
Hi Guys,
Am having a problem with the latest build of ConverseJS in displaying view_mode = "mobile." Since I am just getting started with Converse, it's probably something simple I'm missing. What happens is that when the page renders, there is a little "Toggle Chat" button in the lower left. When I click on that, it disappears and the screen is blank. Only a tiny hint of a line is visible at the extreme bottom of the page. Nothing else is visible. I have tested this in Edge, Chrome (windows), Safari (iPad) and Chrome (iPad), all with the same results. I am attaching a picture to show you. 
![screenshot](https://user-images.githubusercontent.com/23711972/55693926-8e9ec800-597f-11e9-8848-093388f3f494.jpg)
My code is super simple and I'm hoping the problem is easy to spot for you more advanced Converse developers. This page works perfectly if I choose "overlay" or "fullscreen" for view_mode. Here is the HTML for the page (with dashes over private values):

```html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head id="j_idt2">
        <title>Messaging</title>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <link rel="stylesheet" type="text/css" media="screen" href="https://cdn.conversejs.org/4.2.0/css/converse.min.css" />
        <script src="https://cdn.conversejs.org/4.2.0/dist/converse.min.js" charset="utf-8"></script>
</head>
<body>
        
        <script type="text/javascript">
            $(document).ready(function () {
                converse.initialize({
                    bosh_service_url: "https://-------------------------------:7443/http-bind/", 
                    default_domain: "-------------------------",
                    muc_domain: "conference.----------------------",
                    auto_login: true,
                    jid: "---------------------------------",
                    password: "-------------------------",
                    nickname: "--------------------------",
                    auto_subscribe: true,
                    message_archiving: 'always',
                    show_only_online_users: true,
                    view_mode: "mobile"
                });
            });
        </script>
</body>
</html>

**Comment by jcbrand** [comment]
Have you looked at [mobile.html](https://github.com/conversejs/converse.js/blob/master/mobile.html) ?

The mobile version of the site looks OK, so I'm not sure what the issue is:
https://m.conversejs.org/

**Comment by jimmc929** [comment]
Thanks for your reply! I have been studying your pages. Actually, the mobile site is not working all that smoothly. For example, on an iPhone, when I hit "Toggle chat," the login dialog appears with the top part cut off, hidden under the URL bar, as shown in this picture:
![iphone](https://user-images.githubusercontent.com/23711972/55970045-d27a2180-5c4c-11e9-9dff-faf25f944f30.png)
I can't scroll it down to reveal the top of the dialog.

Also, when I access the m.conversejs.org site on a normal desktop browser such as Chrome and click "Toggle chat," the Toggle chat button disappears and nothing else appears. Granted, this is not a mobile device, but still it would seem unfortunate for the dialogs, etc., to completely disappear? It looks like they are trying to be displayed at the extreme lower left of the screen where the prior picture showed a faint horizontal line. Perhaps the css screen size calculations are off?

Converse is a terrific module- thanks for looking into this!
Jim

**Comment by jimmc929** [comment]
In looking at this a little more deeply, it seems that the page is displaying the converse-chatboxes div at the lower left of the screen with a height of 1 pixel. When I use Developer Tools to forcibly override the height and make it some reasonable value (e.g., 300px), the box displays correctly at the lower left of the screen. Could there be a problem with the calculation of height for the controlbox? (P.S. this is the same way my page displays on an iPhone- i.e., with the 1-pixel-high box at the lower left.)

**Comment by jcbrand** [comment]
@jimmc929 The converse-chatboxes div needs to be 1px, otherwise it'll cover up other elements in the page, making them non-clickable.

I don't have any time or capacity to look into these issues currently. Perhaps you can modify the mobile styles accordingly and make a pull request? This is an open source project, so we're a do-ocracy ;) If you need something done, you're invited to do it yourself and contribute it back.

The mobile `.converse-mobile` class on the `#conversejs` element enables mobile-specific styles, and the Sass files are in ./src/sass.

You can run `make watchcss` to automatically generate CSS whenever any of the Sass files change.

**Comment by mckaygerhard** [comment]
hi @jcbrand .. i have some quiestions here: looking for the mobile version noted that if i opened in a browser the chat window dissapear if the normal browser have a size larger than 400px (aprox) .. why? there's one way to force and see always the mobile version?

**Comment by jcbrand** [comment]
@mckaygerhard I don't know why it disappears on larger screens, but I don't really consider it much of a problem since the mobile view isn't meant for larger screens and using it there doesn't make much sense.
