### ISSUE TITLE
4.2.0 — OMEMO not detected

### ISSUE THREAD

**Issue by solus-hq** [conversejs/converse.js#1528]
There's a problem with OMEMO detection by Converse

First, my server is 100% compliant 

https://compliance.conversations.im/server/xmpp.tf/

Second, when we try to use Converse.js it can't detect OMEMO support

<img width="511" alt="Screen Shot 2019-04-08 at 11 45 48" src="https://user-images.githubusercontent.com/26515805/55710710-e4ad5300-59f3-11e9-99bb-eaa34c3fefe0.png">

**Comment by licaon-kter** [comment]
What is "NZ (Aenigma)" ? A contact? What client does it use?

**Comment by solus-hq** [comment]
> What is "NZ (Aenigma)" ? A contact? What client does it use?

Yes, he's in my contact list. And we're both using inverse.chat

**Comment by licaon-kter** [comment]
Server config in a gist?

**Comment by solus-hq** [comment]
> Server config in a gist?

Sure!

https://gist.github.com/solus-hq/9be7576104c7167e0a597d9cc4c3becb

And I'm linking @nordurljosahvida as an author of this config and ejabberd installation bundle.

**Comment by licaon-kter** [comment]
@solus-hq As expected OMEMO support is not enabled

Read line 223: https://github.com/processone/ejabberd/blob/master/ejabberd.yml.example#L223

**Comment by solus-hq** [comment]
@licaon-kter Well, I can't admit you're 100% correct since:

1. When testing same server with Conversations everything **works just fine**, OMEMO is activated instantly.
2. Server is 100% compliant as per https://compliance.conversations.im/server/xmpp.tf/
3. The line you're referring to is meant to disable or enforce OMEMO on clients but it doesn't enable it per se as far as we can in read in documentation.
4. We have tried both "whitelist" and "open" and compliance.conversations.im specifically instructs to remove this line in order to be 100% compliant.

**Comment by licaon-kter** [comment]
@solus-hq I'm not sure Converse "opens" that yet.

**Comment by solus-hq** [comment]
@licaon-kter I guess this is my stupid mistake which has nothing to do with server configuration. 

I just had to enable this when logging in. 

<img width="339" alt="Screen Shot 2019-04-09 at 11 25 34" src="https://user-images.githubusercontent.com/26515805/55784985-5354e400-5aba-11e9-83f1-cb54afab7ab6.png">

**Comment by jcbrand** [comment]
Thanks for handling this issue @licaon-kter
