### ISSUE TITLE
Messages from MAM missing in view

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/converse.js#1534]
...but not in cache

![mamissue2](https://user-images.githubusercontent.com/2282799/56030089-acc04b80-5d24-11e9-89c8-62df8fe9eb0f.jpg)

Under the today line it shows messages from 12:40 onwards... that's connect time.

Above the today line it shows messages from April 05 and older, but if I scroll up I won't be getting every day of the past but some days from April, some from March then some from February.

Now, if I use the [Search plugin](https://github.com/conversejs/community-plugins/tree/master/search) it will find messages from today that are not actually shown on screen.

My `index.html` config is seen here: https://gist.github.com/licaon-kter/54d4656cc753b98e1dc0d81a59a73faa

Converse from HEAD: 1328168d1ef92d1d1606ab24375dfeacaaa0224e

**Comment by jcbrand** [comment]
Thanks for reporting. I'm aware of this issue but didn't yet put it in the issue tracker.

I think the solution is to simply show that there is a gap and to provide a clickable link to load the missing messages. This is how Slack does it.

**Comment by jcbrand** [comment]
I think this issue is now resolved with 5f04176929cce755e8873aa9dcafad700abbf86f
