### ISSUE TITLE
Button to destroy a muc

### ISSUE THREAD

**Issue by meaz** [conversejs/converse.js#1535]
Converse.js is just awesome! One important missing feature is the ability to destroy a muc you own. It is possible on gajim for example.

**Comment by ChaosKid42** [comment]
It's possible by entering `/destroy`

**Comment by meaz** [comment]
@jcbrand I don't think this issue should be closed.
I agree that typing /destroy is easy.
However, how can someone know that command? 
Here is an user case: I showed converse.js to a lot of teachers in order to motivate them to use it with the pupils. That was already a big change for them, they have to learn of concept. They enjoyed converse.js because it is simpler than a lot of XMPP client. 
But they still had a lot of questions, and one of them, for privacy concerns, was how to destroy a room at the end of project. I could just tell them the command /destroy, but I'm pretty sure that they will forget about it. And then, if they also motivate other people to join it, how would those new users would know? 

So I think a button somewhere, for example in the muc details, to destroy a muc would be really an improvement for non tech-saavy people.

**Comment by jcbrand** [comment]
Ok :)

**Comment by Nyco** [comment]
We'll take a look at his need, and propose a UX/UI.

**Comment by licaon-kter** [comment]
Also respect destroy, right now Converse just rejoins and becomes owner, while it should delete autojoin flag, output a message with "room has been destroyed" and maybe block input area.

**Comment by jcbrand** [comment]
In think it already does all those things unless you have a bookmark with autojoin enabled.
