### ISSUE TITLE
 there was an error while trying to add contact.

### ISSUE THREAD

**Issue by kamireddymanasa** [conversejs/converse.js#1536]
hi , getting alert
while refreshing or reloading page getting an alert message  like Sorry, there was an error while trying to add  contact.

**Comment by jcbrand** [comment]
You'll have to provide more information. Where are you using Converse.js? If you're hosting it yourself, then you can set `debug` to `true` when calling `converse.initialize`.

See here: https://conversejs.org/docs/html/troubleshooting.html
