### ISSUE TITLE
Converse might be bring prosody service down

### ISSUE THREAD

**Issue by hzzg6y** [conversejs/converse.js#1537]
I am on Centos 7 with Linux VM of 1 GB having Prosody 11.0 on Bosh with SSL Letsencrypt & mysql for storage... I use converse.js for website & conversations android to connect various users from my website & APP.  I have created a groups for Roster however prosody service is going down every 2nd day. I have enable IPtables as well... Debug logs of Prosody & Apache logs I check.. I don't know why prosody service is getting killed ... how to understand who is kiling & why....   My suspicion is number of offline users scrolling / loading to show online users could be reason.. but not sure though.

I am suspecting the Website client converse.js is scrolling & checking all the offline & online users everytime which is creating load on Prosody due to which prosody as service is getting killed.  Please advice on how to tackle such problem & catch the reason in debug log....

**Comment by hzzg6y** [comment]
%dmesg         ( show below. ) 

[4129011.050976] Out of memory: Kill process 27563 (lua) score 376 or sacrifice child
[4129011.051047] Killed process 27563 (lua) total-vm:584004kB, anon-rss:378476kB, file-rss:0kB, shmem-rss:0kB

**Comment by jcbrand** [comment]
Looks like you don't have enough RAM or something. Doesn't appear to be related to Converse.js.
