### ISSUE TITLE
Allow adding self as contact

### ISSUE THREAD

**Issue by tyler71** [conversejs/converse.js#1538]
When attempting to add myself it shows this message

> You cannot add yourself as a contact

Adding yourself has legitimate uses comparatively to emailing yourself. This lets you communicate information and files between your devices.
It would be great to permit this
___

It appears this was changed to disallow in 4.2.0

>Prevent user from adding themselves as contact

Removing this in `src/converse-rosterview.js` returns that functionality:

```
                } else if (Strophe.getBareJidFromJid(jid) === _converse.bare_jid) {
                    el.textContent = __('You cannot add yourself as a contact')
                    u.addClass('d-block', el);
                    return false;
```

**Comment by Menelmacar** [comment]
Still doesn't work? Or doesn't work anymore at least?
