### ISSUE TITLE
Cannot use end-to-end encryption because ***** uses a client that doesn't support OMEMO.

### ISSUE THREAD

**Issue by AlexIsNice** [conversejs/converse.js#1545]
Hello,i am trying to communicate with someone that has OTR however doesnt have OMEMO,can i somehow select to encrypt with OTR insteadOMEMO?

**Comment by licaon-kter** [comment]
No

**Comment by AlexIsNice** [comment]
My apologizes,i meant INSTEAD OF OMEMO

**Comment by licaon-kter** [comment]
IIRC OTR was removed after version 4

**Comment by jcbrand** [comment]
Converse no longer supports OTR since version 4.
