### ISSUE TITLE
Add contactPresenceFetched event

### ISSUE THREAD

**Issue by nick-denry** [conversejs/converse.js#1546]
Hi!

I'm using first `contactPresenceChanged` event to display and hide loading spinner on my desktop electron/converse.js app. Without a spinner app look a little bit "frozen" before converse display presence status for roster contacts.

So atm the logic is:
```js
//show spiner on startup

if (contacts > 0) {
    // once contactPresenceChanged
    // hide loading spiner
}
else {
    // hide loading spiner immediately
}
```

There are two problems:

- contactPresenceChanged is not fired on reload
- all contacts cound be offline, so `contactPresenceChanged` won't fired

Maybe I could use [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) to watch if roster html changed, but this is not bullet proof anyway.

Is it possible to add an event for converse finished trying to get contacts presenece statuses (even if there is no changes)?

**Comment by nick-denry** [comment]
Maybe it's similar to https://github.com/conversejs/converse.js/issues/101 onRosterViewUpdated, can't get it working too.

**Comment by jcbrand** [comment]
This is where presences are fetched: https://github.com/conversejs/converse.js/blob/master/src/headless/converse-roster.js#L935

You can add a `success` handler and hook in there.

**Comment by nick-denry** [comment]
Thanks. Would you like me to create a PR?

**Comment by jcbrand** [comment]
Yes, a PR would appreciated, thanks.
