### ISSUE TITLE
registation form not load

### ISSUE THREAD

**Issue by supun19** [conversejs/converse.js#1556]
if I log out and try register to a new account the registration form won't load.
https://github.com/conversejs/converse.js/blob/master/src/converse-register.js#L139

**Comment by Nyco** [comment]
I confirm this one. When I close the tab and cancel this, the form is loaded.

Good catch.
Is it a common pattern of use?

**Comment by chaizeg** [comment]
if you try to open it in a new tab, it works, so i'm guessing it's a javascript issue..
