### ISSUE TITLE
Don't clear localStorage and sessionStorage

### ISSUE THREAD

**Issue by dickverweij** [conversejs/converse.js#1561]
We are currently testing the conversejs script "embedded" in our site. We found out than the script can call localStorage.clear() which deletes all of our own persistent data.

Is there a way to disable this behavior?  Using localStorage is fine, but only clean what is used by converse....

**Comment by jcbrand** [comment]
I'm aware of this issue and did some work in a branch to only clear the actual data from Converse and not everything else. However, it's not yet in master and will take some more time to get working properly.
