### ISSUE TITLE
How to modify open groupchats room name

### ISSUE THREAD

**Issue by fingertips-solutions** [conversejs/converse.js#1562]
Hi,

I am using converse and providing chat facility so different companies can chat... I am creating room for each company but now i want to append company name after room name. 

can you just give me some hint and which method i have to over ride with my own plugin ? 

the company names are in php database. 

Thanks

**Comment by jcbrand** [comment]
Sorry, we don't have the capacity to also help people with developing their own custom add-ons. This issue tracker is for bug reports and feature requests.

**Comment by fingertips-solutions** [comment]
I am not asking you to develop. But there should be proper documentation for your script so people can understand it well..
  

  
That looks rude behaviour to me...
  

  
  

  
  
>

**Comment by jcbrand** [comment]
https://conversejs.org/docs/html/index.html
