### ISSUE TITLE
Overriding Core Plugin Functions not working

### ISSUE THREAD

**Issue by fingertips-solutions** [conversejs/converse.js#1563]
Hi, 

I am trying to override bookmarks plugin functions but its not working... its not calling my createBookmarks function. 

'overrides': {

        'createBookmark': function () {

            var _converse = this;
           converse.__super__.createBookmark.apply(this,{
          'jid': name+'@conference.mydomain.com',
          'autojoin': true,
          'name': name,
          'nick': 'Test Nick'
        }); // 

        }
      }

I have a alert in create bookmark function its not called. 
can you tell me whats wrong here ?

**Comment by jcbrand** [comment]
You need to whitelist your plugin. https://conversejs.org/docs/html/plugin_development.html#whitelisting-of-plugins

**Comment by fingertips-solutions** [comment]
I already have whitelisted my custom plugin... here is full example.. 

// custom plugin for bookmarks
converse.plugins.add('customBookmarks', {
dependencies: ["converse-chatboxes", "converse-muc", "converse-muc-views"],
   initialize: function () {
        var _converse = this._converse;
        var allStakeholders = '<?php echo $collonJids;?>';
        var stakeHoldersArray = allStakeholders.split(':'); // converting collon seperated to array
      },

      overrides: {
        'customCreateBookmark': function () { // i have created own function// 
            var _converse = this;
           converse.__super__.bookmarks.customCreateBookmark.apply(this,{
          'jid': waybill+'@conference.k-w-h.com',
          'autojoin': true,
          'name': waybill,
          'nick': 'Test Nick'
        }); // end customCreateBookmark

        }
      }


  });

   converse.initialize({
        authentication: 'anonymous',
        allow_registration: false,
        auto_away: 300,
        registration_domain: 'k-w-h.com',
        default_domain: 'k-w-h.com', // so on login page you don't have to specify username with domain
        auto_reconnect: true,
        bosh_service_url: 'http://www.k-w-h.com:5280/bosh/', // Please use this connection manager only for testing purposes
        message_archiving: 'always',
        play_sounds: true,
        notify_all_room_messages: true,
        sounds_path: '/bbchat/converse/sounds/',
        view_mode: 'fullscreen',
        auto_login: true,
        debug: false,
        auto_join_on_invite: true,
        jid: 'k-w-h.com',
        auto_join_rooms: [{'jid': waybill+'@conference.k-w-h.com', 'nick': receiver_name }],
            notify_all_room_messages: [
                waybill+'@conference.k-w-h.com',
            ],
        whitelisted_plugins: ['customLogout'],
        whitelisted_plugins: ['customBookmarks'],
        whitelisted_plugins: ['converse-bookmarks']
    }).then(function () {
        setTimeout(function () {
            document.querySelector('.converse-content').style = '';
        }, 1000);
    });

**Comment by jcbrand** [comment]
Then I don't know. Like I said in the previous ticket, we don't have the capacity to help people with developing their own custom plugins. The documentation is quite extensive in this regard.
