### ISSUE TITLE
No more files until a release?

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/converse.js#1566]
Since https://github.com/conversejs/converse.js/commit/c2a09996270dc2a0769b1a06135eb12b52134447 I can't update to the latest version since `dist/converse.js` and `css/converse.css` don't exists anymore.

Do I need to install npm and whatever deps to generate those?

**Comment by jcbrand** [comment]
Yes, you'll need to run `make dist` to generate the dist directory and files.

**Comment by licaon-kter** [comment]
@jcbrand That's unfortunate as I can't setup a dev environment for this, so I won't be able to test anything before an actual release.

Any reason for this change?

**Comment by jcbrand** [comment]
You should be able to just run `make dist` inside the repo checkout. 

Including the dist files bloats the repo and the commit diffs. Generally you don't include builds inside a repo. 

If you run into problems with running `make dist` let me know and I'll help you.
