### ISSUE TITLE
Registation not proceed

### ISSUE THREAD

**Issue by supun19** [conversejs/converse.js#1569]
when clicking the registration button it gives an error
POST http://link-im.com:7070/http-bind/ 404 (Invalid SID value.)
ERROR: request id 3.1 error 404 happened.
ERROR: Problem during registration: Strophe.Status is DISCONNECTED

**Comment by jcbrand** [comment]
`Invalid SID value` means that you're not providing a valid BOSH SID token.

That's all I can say from the info provided.
