### ISSUE TITLE
Ipad web view pulled up

### ISSUE THREAD

**Issue by supun19** [conversejs/converse.js#1571]
in ipad safari web view pulled up
[https://imgur.com/a/l859ZCI](url)

**Comment by jcbrand** [comment]
The imgur URL doesn't work

**Comment by chee** [comment]
@jcbrand this is the imgur link: [imgur link](https://imgur.com/a/l859ZCI)

this is the image: 

![the image](https://i.imgur.com/SMEQtD1.jpg)

I'm not sure i understand the issue, however

**Comment by jcbrand** [comment]
Thanks @chee, should be fixed now due to a PR from @supun19
