### ISSUE TITLE
sessionStorage is filled with feauture data

### ISSUE THREAD

**Issue by dickverweij** [conversejs/converse.js#1574]
Considering that we have only about 10MB of sessionStorage. When running converjs on our site we it is filled with converse.features... like values .. Why is this needed, and can we turn it off?

**Comment by jcbrand** [comment]
There's a PR I'm working on (#1470) to add support for IndexedDB, which doesn't have a 10MB limit.

> Why is this needed

to avoid querying the XMPP for all data every time the page loads.

> and can we turn it off?

You could perhaps update Backbone.BrowserStorage to not write anything to the browser storage. It's not something you can turn off just with config.
