### ISSUE TITLE
MUC nickname not remembered

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/converse.js#1577]
HEAD https://github.com/conversejs/converse.js/commit/886ff1bd192a9126d63dccafd1e784ce2e55934e

Steps:
* press add MUC
* paste MUC address 
* enter a nick
* ok
* press bookmark ~~(auto join doesn't matter)~~
* ok
* logout
* see bookmarked chat
* try to join it
* see dialogue asking you to enter nick

/LE: Looks like those with auto-join remember the nick

**Comment by jcbrand** [comment]
Thanks, bug reports like this after I've made some changes are very helpful.

**Comment by licaon-kter** [comment]
Appears fixed in https://github.com/conversejs/converse.js/commit/9cb915126525e3792956c565a11d12e0d7700a44 Thanks
