### ISSUE TITLE
Emoji not shown

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/converse.js#1578]
HEAD https://github.com/conversejs/converse.js/commit/886ff1bd192a9126d63dccafd1e784ce2e55934e

Steps:
* open emoji picker (or write by hand eg. `:metal:`)
* chose one

Expected:
* send emoji
* show emoji on screen

Actual result:
* emojis are send
* Converse itself doesn't show them
* other clients (eg. Conversations) show them

/LE: After logout and login it loads them from the previous conversation
Also new ones appear just fine. :-|

/LE2: later, again emoji not shown

**Comment by jcbrand** [comment]
Hmmm, they show for me... I made some more fixes recently. Can you please check again?

**Comment by licaon-kter** [comment]
I can't repro this now on HEAD, so...
