### ISSUE TITLE
Major pain points of Converse after a small user test series

### ISSUE THREAD

**Issue by Nyco** [conversejs/converse.js#1580]
Philosophy: an issue or a problem spotted in a simple user test is a good news, because it is a potential improvement to be made.

We have conducted a little user research, with this in mind.
We made 12 user tests, in "do what you want" mode.
The split is half techies, half regular non-tech users.
We just observed them and took notes for 30 min.
Then we classified the issues they reported in a big spreadsheet:

![Capture d’écran 2019-05-21 à 15 41 15](https://user-images.githubusercontent.com/25348/58100928-e9fae180-7bde-11e9-9db7-a431b7ae3aaf.png)

The conclusion to this is the major pain points of Converse are the following:

* (9) Channel join/create: why an ID? why a nickname? why query what? why configure afterwards? why not smart defaults?
* (9) XMPP/JID/address: I don't know what ID to type in, I don't want to type ID, I try but fail (0% tests passed)
* (4) Presence: why isn't presence clickable? why a pencil? why a message? Sounds old school
* (4) Owner/moderator: what's the difference? how can I change it?
* (4) Persistent: what is persistent? why ask me? why must I configure this? because yes, persistent, of course! that's what I expect
* (4) MUC config: wow, too many options? what do those mean?
* (4) Mentions: there is no mention. oh wow, "@"+tab and I gotta guess that?
* (3) Bookmark: why bookmarks? I mean that should be bookmarked by default (handled in #1342)
* (3) Contact profile: why is the avatar clickable while the name is not? why this "i" (it is confusing)?
* (3) Desktop notifications: ok, I got notifs but can't click them?
* (3) Quit/exit chat: why does it even exist?

The number in parenthesis is the number of people reporting this problem.

Here are the notes from 1 to 5 (1 worst 5 best):
![Capture d’écran 2019-05-21 à 16 59 23](https://user-images.githubusercontent.com/25348/58107569-6c3cd300-7bea-11e9-87b1-a6eb59e77e27.png)

Users profiles.

![Capture d’écran 2019-05-23 à 16 36 22](https://user-images.githubusercontent.com/25348/58261717-26fadb80-7d79-11e9-82f9-2a027f29058f.png)

**Comment by Nyco** [comment]
We immediately start working on an improved "create and join channel" UX.

**Comment by mwild1** [comment]
> (4) Mentions: there is no mention. oh wow, "@"+tab and I gotta guess that?

Out of curiosity, what were the users who failed this looking for? What did they attempt?

**Comment by jcbrand** [comment]
Thanks for doing and sharing your research @Nyco, this is very helpful!

As you're probably aware, quite a few of the complaints are really due to XMPP peculiarities and the fact that we don't do enough to shield users from XMPP's warts.

**Comment by Nyco** [comment]
@mwild1 
> Out of curiosity, what were the users who failed this looking for? What did they attempt?

Ah, right, forgot to describe, sorry. Here we go, ticket fixed as well.

A | Dev, intern
B | Graphical designer, UX designer
C | Product Owner
D | CEO
E | Lawyer
F | Lawyer
G | CEO
H | Lawyer
I | Cognitive scientist
J | Entrepreneur
K | Sysadmin
L | CTO/CIO

@Zash 
> This being an all-or-nothing setting doesn't seem completely sensible these days. It can probably be hidden away in the server-side configuration. Possibly transformed into some kind of timeout.

Probably. We've uncovered a problem. We'll ideate many solutions, select and test a few. We'll come back with specifications.

@jcbrand 
> Thanks for doing and sharing your research @Nyco, this is very helpful!

You're welcome. We'll go on in iterations.

> As you're probably aware, quite a few of the complaints are really due to XMPP peculiarities and the fact that we don't do enough to shield users from XMPP's warts.

Agree. We usually map the protocol to the UI and UX. That's cool for a protocol geek perspective. That's wrong from regular user perspective. And the number of regular user is far, far greater than the number of protocol geeks.

**Comment by Nyco** [comment]
> > (4) Mentions: there is no mention. oh wow, "@"+tab and I gotta guess that?
> 
> Out of curiosity, what were the users who failed this looking for? What did they attempt?

* they didn't find the "@" sign was the starting point
  * those who found out couldn't carry on with TAB
* clicking on the nicknames in the participants list on the right column does not add an "@" sign
* globally, this use or lack of "@" is inconsistent across Converse
  * worse, it is inconsistent across chat apps (XMPP/Jabber clients)

Likewise, we'll ideate solution, select a few, test them with real users, and finally do specs.

**Comment by ltrls** [comment]
>     * they didn't find the "@" sign was the starting point
>       
>       * those who found out couldn't carry on with TAB

Here we found that you don't need to press TAB after "@" in Chrome, only in Firefox. It would be nice if the Firefox behaviour could get fixed :)
