### ISSUE TITLE
Open rooms list is hidden

### ISSUE THREAD

**Issue by fingertips-solutions** [conversejs/converse.js#1581]
Hello,

When i logout and login again my open rooms list is not showing. when i inspect it i can see open-rooms-list has a hidden class that is making it invisible with opacity 0. 

How can i show it always ?

**Comment by jcbrand** [comment]
What version of Converse are you using?

**Comment by fingertips-solutions** [comment]
I am not sure. how can i find current version ?

**Comment by jcbrand** [comment]
Where did you get the file from?
