### ISSUE TITLE
Unread message by group

### ISSUE THREAD

**Issue by fingertips-solutions** [conversejs/converse.js#1591]
Hi,

I want to get unread counter based on group. e.g if i have group abc i want to know if this group messages are read or unread by user. 

can you please tell me if this can be possible with converse ?

**Comment by jcbrand** [comment]
The `ChatRoom` model has a `num_unread` attribute which indicates the number of unread messages.

**Comment by fingertips-solutions** [comment]
How can i accesa indviual group chatbox model ? I want to access it for abc group?
  

  
  

  
  
>

**Comment by jcbrand** [comment]
Use `_converse.api.rooms.get`  https://conversejs.org/docs/html/api/-_converse.api.rooms.html#.get
