### ISSUE TITLE
Docker for Converse

### ISSUE THREAD

**Issue by Nyco** [conversejs/converse.js#1595]
Here is a Docker for Converse: https://github.com/odajay/conversejs-devenv-docker

Please play with it.

Jonathan is willing to let go, and will be happy if the community takes it over, for maintenance and evolution.

**Comment by alexanderadam** [comment]
Did you try the `nginx:alpine` image as a base as well?

#1427 and #453 are related, aren't they?

**Comment by odajay** [comment]
Hey there, I have built this project on top of the two projects you mentionned and other ones. I didn't try the alpine version yet but there will be some changes for sure, it is something that might be worth taking some time on it.

Did you try to use this repo? If yes, how was your experience deploying it?

There is still a good amount of work to do on this repo to improve it. The simple fact that I'm doing everything in sudo is not great. Also and between other tasks, my versions are not fixed, my ENV declared too early on top etc. However, I believe that it's a good base to start working fast on a Converse server.

**Comment by Nyco** [comment]
So, all and @jcbrand, do you want to take it over, under the umbrella of the Converse.js organisation?

**Comment by jcbrand** [comment]
Hi @Nyco, sure, just create a new repo for it under this organization, set it as the new remote and push all the commits here.

@odajay Thanks a lot for your work on this.
