### ISSUE TITLE
Unable to save or get profile data

### ISSUE THREAD

**Issue by fingertips-solutions** [conversejs/converse.js#1596]
Hi,

I am trying to set nickname but its giving me error that  Sorry, an error happened while trying to save your profile data. check developer console.

when i check developer console i am getting following error.

TypeError: Cannot read property 'digest' of undefined

ERROR: <iq xmlns="jabber:client" xml:lang="en" to="saee_agent_mahmoud.a_32@34.196.203.66/converse.js-25083907" from="jc00406772ks@conference.34.196.203.66" type="error" id="4f6800cb-1a27-452b-9bdf-aadb9bdd6a7f:sendIQ"><query xmlns="http://jabber.org/protocol/muc#admin"><item affiliation="admin"/></query><error code="403" type="auth"><forbidden xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/><text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" xml:lang="en">Administrator privileges required</text></error></iq>

and i think this is happening only on chrome not on firefox. 

can you please let me know whats causing this issue.

**Comment by jcbrand** [comment]
The browser's cryptography API [crypto.subtle] is only available on `localhost` or via `https`.

That seems to be the issue here. You're hosting via only http and not on localhost.

**Comment by fingertips-solutions** [comment]
can you tell me if i have to change the config file for ejabbered ? i am using ip and localhost in hosts attribute.

**Comment by fingertips-solutions** [comment]
@jcbrand our converse is on one server and ejabberred is installed on another server..
