### ISSUE TITLE
when profile image upload in safari

### ISSUE THREAD

**Issue by supun19** [conversejs/converse.js#1597]
when I browser the profile image on safari I got this error 
<img width="1437" alt="Screen Shot 2019-06-03 at 2 53 58 PM" src="https://user-images.githubusercontent.com/8381016/58792379-b02fcf00-8611-11e9-990a-8d5da4288646.png">

**Comment by Echolon** [comment]
@supun19 do you still experience this error?

**Comment by Echolon** [comment]
@supun19  I will close this as there is release 8.x so far. Please comeback if it is still existent!
