### ISSUE TITLE
MUC members panel reappears at random

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/converse.js#1600]
HEAD (ca4b509d87f1bef1875a8b2441a8b8278b115163)

Steps:
1. Join a MUC
2. Hide members panel by pressing `>>`
3. `>>` becomes `<<` and the panel is hidden
4. resize the window (tiling manager) several times

Expected:
Panel stays off

Actual:
1. Panel reappears
2. The panel button icon is still '<<' (aka closed)
3. pressing the button will only transform `<<` in `>>`
4. Pressing a second time, `>>` becomes `<<` and the panel is hidden

**Comment by Nyco** [comment]
Seem like I can't reproduce this one. :'(

Software env:
* macOS latest
* Chrome latest, Firefox latest, Opera latest
* Converse latest

**Comment by licaon-kter** [comment]
This was in Windows w/ Firefox 67, fyi

**Comment by licaon-kter** [comment]
Since https://github.com/conversejs/converse.js/issues/1622 got fixed, when I login my MUCs are opened, the occupants view is open but the icon is `<<`, so I press once and it becomes `>>` (panel still visible), then I press again and it becomes `<<` (panel closed)

**Comment by licaon-kter** [comment]
Appears fixed in HEAD
