### ISSUE TITLE
Update message while editing

### ISSUE THREAD

**Issue by krot3232** [conversejs/converse.js#1601]
If the message is edited, then for the rest of the participants, when they first log in to the chat, the message will be displayed as not edited, but after updating the page it will be displayed.
https://drive.google.com/file/d/1GRKh742ETiAK_y7qh4_P_O34vf9Dk3t9/view?usp=sharing

**Comment by jcbrand** [comment]
Thanks, I've submitted a fix. Older messages won't be fixed, but new corrections will appear correctly.

**Comment by krot3232** [comment]
sendMessage (text, spoiler_hint) by adding 'origin_id': _converse.connection.getUniqueId (), this did not solve the problem.
Messages shows both old and new, old ones should be replaced.
Also, if you edit messages and clear the cache, the messages are rearranged to the beginning
https://drive.google.com/open?id=10GTd3ye1MeQAuuMcz0c9HzluLB7LL9c4

**Comment by jcbrand** [comment]
You're testing on https://conversejs.org but the fix hasn't been released yet, so you're still testing the old code.
