### ISSUE TITLE
MAM history not fetched on re-login

### ISSUE THREAD

**Issue by laszlovl** [conversejs/converse.js#1603]
Use a websocket connection and **don't** use `enable_smacks`. Login to Converse with at least one MUC set to autojoin. Converse will automatically retrieve the last 50 messages from that MUC.

Now refresh the page (and re-enter your credentials if applicable). Converse will automatically join this MUC again, but the chat window remains empty.

**Comment by jcbrand** [comment]
Appears to be fixed.
