### ISSUE TITLE
Can't upload 0byte file

### ISSUE THREAD

**Issue by mmizab** [conversejs/converse.js#1607]
As the titles said it not possible to send 0byte file, Where it can be fixed this problems,
Best regards.

**Comment by jcbrand** [comment]
When would it ever make sense to send a 0 byte file?

**Comment by mmizab** [comment]
Correct, but at last show an error. Because now it stucks on uploading.

**Comment by jcbrand** [comment]
I'm tempted to close this issue with a `wontfix`. This is a very unlikely edge-case and I have only limited time. Not sure it's worth it to look into this.

**Comment by chaizeg** [comment]
I tried sending a 0byte file, it actually worked. Maybe the version you're using is not the latest?
