### ISSUE TITLE
when signout converse i got  error

### ISSUE THREAD

**Issue by supun19** [conversejs/converse.js#1610]
converse-core.js:262  ERROR: Error: A "url" property or function must be specified    at urlError (http://localhost:8000/chatapp/dist/converse.js:2943:11)    at child.url (http://localhost:8000/chatapp/dist/converse.js:1565:9)    at Function.result (http://localhost:8000/chatapp/dist/converse.js:28609:44)    at child.Backbone.sync (http://localhost:8000/chatapp/dist/converse.js:2430:22)    at child.Backbone.sync (http://localhost:8000/chatapp/dist/converse.js:349:40)    at child.sync (http://localhost:8000/chatapp/dist/converse.js:1306:28)    at child.destroy (http://localhost:8000/chatapp/dist/converse.js:1552:20)    at child.close (http://localhost:8000/chatapp/dist/converse.js:56792:16)    at child.close (http://localhost:8000/chatapp/dist/converse.js:44398:20)    at child.close (http://localhost:8000/chatapp/dist/converse.js:48706:47)    at http://localhost:8000/chatapp/dist/converse.js:44777:16    at http://localhost:8000/chatapp/dist/converse.js:19879:15    at baseForOwn (http://localhost:8000/chatapp/dist/converse.js:17964:24)    at http://localhost:8000/chatapp/dist/converse.js:19848:18    at child.forEach (http://localhost:8000/chatapp/dist/converse.js:24312:14)    at child.Overview.<computed> [as forEach] (http://localhost:8000/chatapp/dist/converse.js:650:28)    at child.closeAllChatBoxes (http://localhost:8000/chatapp/dist/converse.js:44772:14)    at child.wrappedOverride (http://localhost:8000/chatapp/dist/converse.js:32980:22)    at apply (http://localhost:8000/chatapp/dist/converse.js:8145:15)    at child.wrapper [as closeAllChatBoxes] (http://localhost:8000/chatapp/dist/converse.js:10637:12)    at Object.<anonymous> (http://localhost:8000/chatapp/dist/converse.js:43003:74)    at triggerEvents (http://localhost:8000/chatapp/dist/converse.js:1194:57)    at triggerApi (http://localhost:8000/chatapp/dist/converse.js:1182:19)    at eventsApi (http://localhost:8000/chatapp/dist/converse.js:970:16)    at Object.Events.trigger (http://localhost:8000/chatapp/dist/converse.js:1172:5)    at Object.trigger (http://localhost:8000/chatapp/dist/converse.js:59562:23)    at Object.clearSession (http://localhost:8000/chatapp/dist/converse.js:59007:19)    at Object.logOut (http://localhost:8000/chatapp/dist/converse.js:59011:15)    at child.logOut (http://localhost:8000/chatapp/dist/converse.js:52687:21)    at HTMLDivElement.handler (http://localhost:8000/chatapp/dist/converse.js:507:13)

**Comment by jcbrand** [comment]
Does this happen every time you log out, or only this one time?

**Comment by supun19** [comment]
every time it happen

**Comment by supun19** [comment]
Got another when logout and login

converse-core.js:268  FATAL: Error: A "url" property or function must be specified    at urlError (http://localhost:8000/chatapp/dist/converse.js:2943:11)    at child.url (http://localhost:8000/chatapp/dist/converse.js:1565:9)    at Function.result (http://localhost:8000/chatapp/dist/converse.js:28609:44)    at child.Backbone.sync (http://localhost:8000/chatapp/dist/converse.js:2430:22)    at child.Backbone.sync (http://localhost:8000/chatapp/dist/converse.js:349:40)    at child.sync (http://localhost:8000/chatapp/dist/converse.js:1306:28)    at child.save (http://localhost:8000/chatapp/dist/converse.js:1519:22)    at child.onResourcesChanged (http://localhost:8000/chatapp/dist/converse.js:64040:16)    at triggerEvents (http://localhost:8000/chatapp/dist/converse.js:1196:57)    at triggerApi (http://localhost:8000/chatapp/dist/converse.js:1182:19)    at eventsApi (http://localhost:8000/chatapp/dist/converse.js:970:16)    at child.Events.trigger (http://localhost:8000/chatapp/dist/converse.js:1172:5)    at child.set (http://localhost:8000/chatapp/dist/converse.js:1801:16)    at child.add (http://localhost:8000/chatapp/dist/converse.js:1674:19)    at child.create (http://localhost:8000/chatapp/dist/converse.js:1935:23)    at child.addResource (http://localhost:8000/chatapp/dist/converse.js:64076:26)    at child.presenceHandler (http://localhost:8000/chatapp/dist/converse.js:64828:28)    at H.Handler.handler (http://localhost:8000/chatapp/dist/converse.js:63906:26)    at H.Handler.run (http://localhost:8000/chatapp/dist/converse.js:36650:18023)    at http://localhost:8000/chatapp/dist/converse.js:36650:26463    at Object.forEachChild (http://localhost:8000/chatapp/dist/converse.js:36650:9678)    at H.Connection._dataRecv (http://localhost:8000/chatapp/dist/converse.js:36650:26296)    at r.Bosh._onRequestStateChange (http://localhost:8000/chatapp/dist/converse.js:36650:46209)

**Comment by jcbrand** [comment]
I'm unable to reproduce this error and the tracebacks you pasted don't provide any useful information.

Please set `debug` to `true` and use an unminified version of Converse when testing so that the error tracebacks are useful. Also specify exactly which version of Converse you're using.
