### ISSUE TITLE
Error fetch roster from server

### ISSUE THREAD

**Issue by fingertips-solutions** [conversejs/converse.js#1616]
Hi,
Not all the time but suddenly i can see this error in console. when i switch browser or after turning off my pc came back it works again. below are console errors i am getting. 

it does not show groupchats on left side.

can you please have a look into this. 
 
ERROR: null converse.js:62953:12
 ERROR: Error while trying to fetch roster from the server converse.js:62953:12
 ERROR: null
converse.js:62953:12
uncaught exception: null

I can also see this error for my chat user...

 `ERROR: <iq xmlns="jabber:client" xml:lang="en" to="saee_agent_mahmoud.a_35@myip/converse.js-139523605" from="jc00440988ks@conference.myip" type="error" id="6c24fc11-8f66-466e-8389-e903c8187255:sendIQ"><query xmlns="http://jabber.org/protocol/muc#admin"><item affiliation="admin"/></query><error code="403" type="auth"><forbidden xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/><text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" xml:lang="en">Administrator privileges required</text></error></iq>`

**Comment by fingertips-solutions** [comment]
anything about above error ?

**Comment by jcbrand** [comment]
You're trying to give a user the `admin` affiliation and this is not allowed because you're not an admin yourself.

https://xmpp.org/extensions/xep-0045.html#example-200

**Comment by fingertips-solutions** [comment]
@jcbrand I am not setting anything just using default converse functions... 

Can you please point where the actual problem is ?

**Comment by jcbrand** [comment]
Looking at the error stanza again, it appears as if Converse is querying for admin users (instead of trying to make a user an admin user), and the XMPP server says this is not allowed.

This isn't necessarily a problem. If you want to show users with the `admin` affiliation in your groupchats, then you need to configure your XMPP server appropriately.

**Comment by fingertips-solutions** [comment]
I am using ejabbered rest api to get all online rooms by muc_online_rooms function of api... then i am appending those groups to openchat groups of converse.. it was working before but suddenly i am getting error...
