### ISSUE TITLE
migrating from 4.2.0 to master -> roster is gone

### ISSUE THREAD

**Issue by dickverweij** [conversejs/converse.js#1618]
I upgraded our converse.js from 4.2.0 to the master version, 

I noticed that my roster was empty. I could not add users which were already added in version 4.2.0 but i could add new ones, the new ones appeared in the roster. 

later I switched back all to 4.2.0 the contacts on the roster were all back including the ones i added with the master function.

**Comment by jcbrand** [comment]
I use the master branch every day and the roster shows fine for me.

You'll have to provide more info in order to debug this.

**Comment by dickverweij** [comment]
It is not the problem that the roster doesnot display on the master branch. it does not display old ones from earlier version someway.

First I worked with the 4.2.0 version, and added users to my roster. they appeared in converse and also on the server (ejabberd)

Then i upgraded to the master version and now all my earlier users were gone, when I tried to add them i got an error. If i tried to add users who were not on my roster to begin with they would be added.

I downgraded to the 4.2.0 branch now all the previous users were back.

Would you like my config?

**Comment by jcbrand** [comment]
> Perhaps it has something to do witch caching of the roster ??

Yes, sounds like it could be something like that.

There is a button next to the "Contacts" heading which you can click to refresh the entire roster. Please check whether that "fixes" the problem for you.

![Screenshot from 2019-06-26 10-45-13](https://user-images.githubusercontent.com/683911/60165468-9f810c00-97ff-11e9-81a1-7c6da066a5e0.png)

**Comment by dickverweij** [comment]
that works thanks!..
