### ISSUE TITLE
Only occupants are allowed to send queries to the conference

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/converse.js#1622]
HEAD https://github.com/conversejs/converse.js/commit/bb94891621bc41e601c52cfdb8a722e468a4a127

Steps:
* login
* (don't have autojoined rooms)
* click on 2 MUCs bookmarks & join them
* close user list
* close the browser tab
* undo close tab
* _(you are now forced to)_ relogin

Expected result:
* see 2 MUCs as "Open Groupchats" or closed as "Bookmarks"

Actual result:
* see 2 MUCs as "Open Groupchats"
* select one
* see the history load ok
* see that the user list is closed
* open the user list, see that it is blank, no user listed
* try to post (or just write without pressing send), see red text: `Your message was not delivered because you're not present in the groupchat.`

Note that if I logout properly, on relogin:
* MUCs are not joined, just appear as Bookmarks
* MUC user list status (opened/closed) is not remembered, always opened

Debug log: https://gist.github.com/licaon-kter/e49bc77294af6bb4fd7a33727da78b47

**Comment by jcbrand** [comment]
I'm quite surprised by this, because this line should ensure that you rejoin the chatroom when restoring it from cache:
https://github.com/conversejs/converse.js/blob/bb94891621bc41e601c52cfdb8a722e468a4a127/src/headless/converse-muc.js#L313

**Comment by licaon-kter** [comment]
Yup, rebuilding daily, will try to backtrack few commits and pinpoint (I guess)

**Comment by licaon-kter** [comment]
`git bisect ...`
```
1dc73c1c313fb47979a7a451c7b107cd72f0606b is the first bad commit
commit 1dc73c1c313fb47979a7a451c7b107cd72f0606b
Author: JC Brand <jc@opkode.com>
Date:   Tue Jun 18 16:46:55 2019 +0200

    For chatboxes, use the web storage determined by `_converse.trusted`

:040000 040000 a34559e9cd90df1bf2033b890716ac9010e50146 b56221376b17677354a28f627e7be6694ffcb60d M      src
```

On Firefox, before this commit if I close tab, reopen, relogin... the MUCs are disconnected, I reconnect, all ok.

After this commit, on Firefox, when I relogin... MUCs appear connected, fetches history ok, but I can't write, nor will I get new messages.

**Comment by jcbrand** [comment]
Thanks, should be fixed now.

**Comment by licaon-kter** [comment]
Confirmed fixed, thanks
