### ISSUE TITLE
How to access updateRoomsList method

### ISSUE THREAD

**Issue by fingertips-solutions** [conversejs/converse.js#1625]
Hi,

I need to get list of all group chats. this function sends iq stanza i need to call this method to get all groups chats list. can you please let me know how can i call it. or how can i get all server groupchats. 

Thanks

**Comment by fingertips-solutions** [comment]
any update please ?

**Comment by jcbrand** [comment]
This issue tracker is for bug reports and feature requests, not open-ended support questions.

I'm struggling to get to everything as it is and don't have enough time to also help stuff like this.

**Comment by jcbrand** [comment]
This should work:

`_converse.api.rooms.get()`

https://conversejs.org/docs/html/api/-_converse.api.rooms.html#.get

**Comment by fingertips-solutions** [comment]
In result array i am getting error.. 
TypeError: "_converse.connection is undefined"

Here is what i am passing in IQ

$admin_username has full jid with domain name... 

const iq = $iq({
          'to': "conference.k-w-h.com",
          'from': '<?php echo $admin_username ?>',
          'type': "get"
        }).c("query", {
          xmlns: Strophe.NS.DISCO_ITEMS
        });
