### ISSUE TITLE
open chat urlError

### ISSUE THREAD

**Issue by krot3232** [conversejs/converse.js#1627]
When you click on the contact does not open the chat.
`TypeError: message is undefined
converse-chatview.js:842:27
 ERROR: urlError@http://test.com/dist/converse.js:2954:11
url@http://test.com/dist/converse.js:1576:9
result@http://test.com/dist/converse.js:28585:44
./node_modules/backbone/backbone.js/</</Backbone.sync@http://test.com/dist/converse.js:2441:22
./node_modules/backbone.browserStorage/backbone.browserStorage.js/</Backbone.sync@http://test.com/dist/converse.js:349:40
sync@http://test.com/dist/converse.js:1317:28
destroy@http://test.com/dist/converse.js:1563:20
initialize/<@http://test.com/dist/converse.js:60468:20
converse-core.js:269:15
too much recursion
backbone.js:401
too much recursion
converse-core.js:1431:30
too much recursion
es6-promise.auto.js:867
too much recursion
backbone.js:305
too much recursion
backbone.js:760
too much recursion
converse-core.js:1431:30
too much recursion
backbone.js:760
too much recursion
backbone.js:401
`

**Comment by jcbrand** [comment]
I'm unable to reproduce this, you'll need to provide more information. What version of Converse.js are you using?

When does it happen? Have you looked at converse-chatview.js line 842 to try and see what's going on?

**Comment by krot3232** [comment]
The version of the conversejs is the newest, compiled today.
Mistake:
Error: "A" url "property or function must be specified"
onMessage
`const msg = chatbox.correctMessage (attrs) || chatbox.messages.create (attrs);
               chatbox.incrementUnreadMsgCounter (msg); `
It occurs if an empty body returns to mam
example:
`	<message xmlns="jabber:client" from="1042@localhost" to="1042@localhost/converse.js-139719390" id="29734054-0cfd-4302-92bd-248b28c448bf">
		<result queryid="6ec8105d-8a3d-4d86-b69d-01421e8975e4" xmlns="urn:xmpp:mam:2" id="B3152DORAQG1">
			<forwarded xmlns="urn:xmpp:forward:0">
				<delay xmlns="urn:xmpp:delay" stamp="2019-06-25T12:29:11Z" from="1042@localhost/converse.js-128415385" />
				<message from="1042@localhost/converse.js-128415385" xmlns="jabber:client" xml:lang="en" id="2a50ce13-1a22-40db-a4e8-2edffcae7c2b" to="1049@localhost" type="chat">
					<body />
					<active xmlns="http://jabber.org/protocol/chatstates" />
					<request xmlns="urn:xmpp:receipts" />
					<origin-id id="2a50ce13-1a22-40db-a4e8-2edffcae7c2b" xmlns="urn:xmpp:sid:0" />
				</message>
			</forwarded>
		</result>
	</message>`

**Comment by jcbrand** [comment]
Unable to replicate.
