### ISSUE TITLE
Set `autojoin` flag when opening/closing bookmarks

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/converse.js#1630]
HEAD (fa3c6604ac3ae6afc94288b6a2e7b31c24462ff7), Firefox 67/Vivaldi snapshot

**To Reproduce**
1. login
2. see bookmarks, no open chats
3. open MUCs

**Press logout**
1. login back
2. see bookmarks, no open chats
3. open MUCs
4. see MUCs ok, see occupants view open

**Close the tab** (in Firefox I can close the browser then reopen to repro)
1. Undo close tab
2. login back
3. see MUCs as Open Groupchats
4. see MUCs ok, see occupants view open, [broken << button](https://github.com/conversejs/converse.js/issues/1600#issuecomment-508685310)

**Comment by jcbrand** [comment]
I don't see anything to do here, logging out and closing the tab are two different actions with different implications.

If you want certain MUCs to always be open when you log in, then set the `autojoin` flag.

Converse should ideally set the `autojoin` flag when opening/closing chats from bookmarks (like Conversations does) but it doesn't yet.

**Comment by jcbrand** [comment]
I've decided to hijack this issue :)

**Comment by licaon-kter** [comment]
> Converse should ideally set the autojoin flag when opening/closing chats from bookmarks 

Yeah, that's the expected behaviour, from my perspective, eg. It was open when I've logged out/closed tab... I want it open when I come back.

**Comment by jcbrand** [comment]
Closing in favor of #2623
