### ISSUE TITLE
show old chat data??

### ISSUE THREAD

**Issue by singhsandeepsln** [conversejs/converse.js#1632]
please let us know which function to execute for showing old data. I am getting data after sending Ajax but not able to show those data in chatbox.

Thanks

**Comment by jcbrand** [comment]
This issue tracker is for bug reports and feature requests, not for general programming help.

**Comment by singhsandeepsln** [comment]
> This issue tracker is for bug reports and feature requests, not for general programming help.

boss you are in too hurry to close issue
