### ISSUE TITLE
credentials_url not fetching JID

### ISSUE THREAD

**Issue by s-sokolko** [conversejs/converse.js#1635]
**Describe the bug**
When initializing converse using credentials_url config parameter conversejs fetches and uses the password provided, but it keeps looking for JID in config params rather than use the JID provided by credentials_url response

**To Reproduce**
Init converse like that:
```javascript 
converse.initialize({
	    authentication: 'login',
	    auto_away: 300,
	    auto_reconnect: true,
	    keepalive: true,
	    auto_list_rooms: true,
	    websocket_url: 'wss://xmpp.o-it-s.ru:5280/websocket/',
	    message_archiving: 'always',
	    view_mode: 'overlayed',
	    allow_logout: false,
	    allow_registration: false,
	    play_sounds: true,
	    locales_url: '/locale/' + language + '/LC_MESSAGES/converse.json',
	    auto_login: true,
	    credentials_url: 'http://localhost/creds.php',
	    debug: true,
	});
```

Here https://github.com/conversejs/converse.js/blob/master/src/headless/converse-core.js#L1272 
and here https://github.com/conversejs/converse.js/blob/master/src/headless/converse-core.js#L1287
one can see that credentials.jid is not used

**Expected behavior**
Converse is expected to pull both jid and password according to the docs https://conversejs.org/docs/html/configuration.html#credentials-url

**Screenshots**

**Environment (please complete the following information):**
I use desktop PC with Google Chrome web browser. ConverseJS is latest master (sha 5c88d3e836d347dbbd5afc0bbd1cb5fb3348ddc6).

**Additional context**

**Comment by jcbrand** [comment]
@s-sokolko: I use `credentials_url` a lot in various projects, and I just checked why I don't seem to have the problem you reported.

In `fetchLoginCredentials` we call `setUserJID` which sets `this.jid` and also creates a JID resource if one wasn't provided by the `credentials_url` endpoint.
See here: https://github.com/conversejs/converse.js/blob/8a405ee88cf8ba277a3a04bf04b7185f2f1562db/src/headless/converse-core.js#L618

That last point is important, thats why we use `this.jid` here:
https://github.com/conversejs/converse.js/blob/8a405ee88cf8ba277a3a04bf04b7185f2f1562db/src/headless/converse-core.js#L1288

What is actually the problem that you're having? Is `this.jid` undefined when calling `this.connection.connect`?

Based on line 618, which I link to above, I don't see any problem and it is correct that `this.jid` is used later on.

Can you put a `debugger` statement on line 617 and check that the user JID is set properly?

**Comment by s-sokolko** [comment]
@jcbrand I am trying to debug conversejs, but stuck with the setup. I've successfully built dev version using the instruction https://conversejs.org/docs/html/dependencies.html What do I do next? I mean which file can I include in my test hatml page to start debugging and develpoing conversejs? Sorry for such a lame question: I'm quite new to modern front-end technologies...

**Comment by jcbrand** [comment]
Run `make watch` in your checkout of this repo and then put a `debugger` statement just before `setUserJID` is called, as I explained in my previous comment.

Then reload the tab and your statement should get triggered in the browser console (if you've set a `credentials_url` value).

**Comment by s-sokolko** [comment]
@jcbrand Thank you for your help, it worked!
As far as I understand here https://github.com/conversejs/converse.js/blob/8a405ee88cf8ba277a3a04bf04b7185f2f1562db/src/headless/converse-core.js#L618 should be an 'await' statement as the function is async.
It all works fine if https://github.com/conversejs/converse.js/blob/8a405ee88cf8ba277a3a04bf04b7185f2f1562db/src/headless/converse-core.js#L529 happens quickly, but if it slows down, connect is called before this line https://github.com/conversejs/converse.js/blob/8a405ee88cf8ba277a3a04bf04b7185f2f1562db/src/headless/converse-core.js#L539 is reached. This leaves this.jid (_converse.jid) undefined

**Comment by s-sokolko** [comment]
I've proposed new solution in https://github.com/conversejs/converse.js/pull/1638

**Comment by jcbrand** [comment]
Congratulations on finding and fixing the bug. Merged!
