### ISSUE TITLE
Can't scroll up (get older messages)

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/converse.js#1637]
...for `ejabberd@conference.process-one.net` using HEAD (https://github.com/conversejs/converse.js/commit/5c88d3e836d347dbbd5afc0bbd1cb5fb3348ddc6)

**Comment by licaon-kter** [comment]
**git bisect**
```
6bfa69ab3b0ab0062f682a48e21fbcca0222210a is the first bad commit
commit 6bfa69ab3b0ab0062f682a48e21fbcca0222210a
Author: JC Brand <jc@opkode.com>
Date:   Mon Jul 8 13:22:21 2019 +0200

    Bugfix. Wait for members before fetching messages

:040000 040000 b359a2653509d7ea6d64f3969b4a28e7f5e16a7fc5cfa131808d8cbd5ef7d9960e8c1302322daa74 M      src
```

**Comment by licaon-kter** [comment]
Appears fixed in bda567ca01423cb1655f44326ccc6b29fce10743 was this intentional?

**Comment by jcbrand** [comment]
>  was this intentional?

Nope, but I'll take it.

**Comment by licaon-kter** [comment]
Can we reopen this? Can't scroll up with HEAD on Firefox 77 and Vivaldi Snapshot.
