### ISSUE TITLE
Add option to hide participant list by default

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/converse.js#1642]
...but keep the toggle of course.

@deleolajide 
> I use a plugin to ensure that 

Link?

Related to https://github.com/conversejs/converse.js/issues/1416 but not quite the same thing, _eg. even if I keep the list on by default, it makes sense to hide it in mobile view anyway given the space constraints_

**Comment by poVoq** [comment]
Awesome. Thanks a lot for adding this! Was my personal pet peeve with ConverseJS for a long time now :)

**Comment by jcbrand** [comment]
Now you can pick a new pet peeve!

**Comment by licaon-kter** [comment]
MY pet peeve list is still long enough :+1: 
Thanks
