### ISSUE TITLE
Adding Media/File encryption

### ISSUE THREAD

**Issue by tigexplorer** [conversejs/converse.js#1648]
**Is your feature request related to a problem? Please describe.**
It would be nice, if additionally to the OMEMO encryption of the text message, also attached files like pictures are encrypted.

**Describe the solution you'd like**
IMHO inputMICE has descripted a proposal for realizing this 
https://xmpp.org/extensions/inbox/omemo-media-sharing.html

**Comment by linkmauve** [comment]
Thanks for the feature request, but this is a duplicate of #1182 so I’m closing it.
