### ISSUE TITLE
XEP-0402: Bookmark sync

### ISSUE THREAD

**Issue by foss-** [conversejs/converse.js#1649]
**Is your feature request related to a problem? Please describe.**
Beagle.im and Siskin.im (both Tigase) use xep-0402 for bookmark sync. Currently bookmarks created in converse.js do not show in siskin or beagle.

**Describe the solution you'd like**
Tigase mentioned they use xep-0402, so supporting that should hopefully provide working bookmark sync.

**Additional context**
https://xmpp.org/extensions/xep-0402.html

**Comment by jcbrand** [comment]
Closing in favour of #2586
