### ISSUE TITLE
Chatbox headers simplification, drop down menu

### ISSUE THREAD

**Issue by Nyco** [conversejs/converse.js#1651]
**Is your feature request related to a problem? Please describe.**

* Target: all tested users (regular, non-tech users)
* Problem 1: People do not feel at home with the banner
  * Consequences 1: unease, disturbance, questions, doubts
* Solution 1: Make it look more like mature team chats
  * Benefits 1: users do no ask questions, they're productive from 1st minute of use
* Problem 2: People are mostly confused by the Quit/Exit/Leave button
  * Consequences 2: at best they don't know what to do with it, at worst they click on it and don't know how to get it back
* Solution 2: Put it in a menu, not displayed at first sight, hidden behind a click/tap, like Slack
  * Benefits 2: no more first-sight confusion, consistency across one-to-one and channels/MUC/groupchats
* Why: simplify, zenify the information architecture, leave room and screen estate for useful info

**Describe the solution you'd like**

*Channels chatbox header, drop down menu*

Move all inline icons from header into a new gear menu, "cog" symbol:

* "Channel info": current "info-circle" dialog
* "Configure channel": current wrench dialog
* "Bookmark": current "bookmark" dialog
* "Invite: "user-plus" symbol [for later implem?]
* "Groups": add/manage groups [for later implem?]
* "Quit": add an "Are you sure?" confirmation, not a JS alert

*One-to-one chatbox header, drop down menu*

Move all inline icons from header into a new gear menu, "cog" symbol:

* "Contact info": current "id-card" dialog
* "Create channel": will open the "Create channel" dialog, and automatically invite this contact [for later implem?]
* "Remove contact": trash-alt symbol
* "Groups": add/manage groups [for later implem?]
* "Encryption keys": list of OMEMO keys, "key" symbol [for later implem?]
* "Quit": add a "Are you sure?" confirmation, not a JS alert

*Optionally later*

In the chatbox header at first sight, without a click/tap:

* Add avatar in channels
* Add number of participants in channels
* Display JID, title, description in channels
* Display Full Name, nick, role in one-to-one

**Describe alternatives you've considered**

* Toolbars are confusing users: choice of default buttons, why put some in a menu, leave room for useful info (user tested)

**Additional context**

Modal vs chatbox: in order to satisfy all Converse view modes (`overlay`, `fullscreen`, `embedded`, `mobile`), we keep all the dialogs as they are today.

**UI Preview**

* Channel menu off

![03_groupchat_menu_off](https://user-images.githubusercontent.com/25348/61309428-7b0ec300-a7f2-11e9-89d8-2e1ba01e623d.png)

* Channel menu on

![04_groupchat_menu_on](https://user-images.githubusercontent.com/25348/61309445-806c0d80-a7f2-11e9-93be-af3da7e0e6de.png)

* One-to-one menu off

![05_one_one_one_chat_menu_off](https://user-images.githubusercontent.com/25348/61309456-8530c180-a7f2-11e9-8e26-943e9218f2b2.png)

* One-to-one menu on

![06_one_one_one_chat2_menu_on](https://user-images.githubusercontent.com/25348/61309465-87931b80-a7f2-11e9-9088-a904cfc45f22.png)

**Comment by yashjaiswal1** [comment]
Hi @Nyco , is this issue still open? I'm just a beginner but I'd like to try my hands on this specific issue.

**Comment by jcbrand** [comment]
Hi @yashjaiswal1, this ticket is still open. Your contribution is appreciated.

**Comment by jcbrand** [comment]
This has been done in 3400acbfebb2b3816456a9d3b94caba5634cdf68
