### ISSUE TITLE
[i18n] Adding Occitant to the language list

### ISSUE THREAD

**Issue by Quenty31** [conversejs/converse.js#1654]
Hello,
I'd like to translate ConverseJS into Occitan, in its standard/central form but this language is not avaible for translation on your Weblate.
Would it be possible to add it so I can start translating?
Best regards

Quentin

**Comment by jcbrand** [comment]
Hi, you can add the language yourself and make a pull request.

See here:
https://conversejs.org/docs/html/translations.html#making-translations-file-for-a-new-language

It should also  be possible to add the language via Weblate, but I can't seem to find where to do that (although I'm sure other people have added languages there in the past).
https://hosted.weblate.org/projects/conversejs/

**Comment by jcbrand** [comment]
I found it, you can add a new language here:
https://hosted.weblate.org/new-lang/conversejs/translations/
