### ISSUE TITLE
Need help with connecting converse js to openfire

### ISSUE THREAD

**Issue by PSP789456** [conversejs/converse.js#1657]
Hello! What should I change in converse js files to connect it to openfire deployed on ubuntu server?

**Comment by licaon-kter** [comment]
@PSP789456 why not use the special Openfire module instead?

**Comment by PSP789456** [comment]
@licaon-kter because with full version I can change design of chat and plugin doesn't allow me to do that

**Comment by jcbrand** [comment]
@PSP789456 You need to set the bosh_service_url or websocket_url config values to those provided by your XMPP server.

https://conversejs.org/docs/html/configuration.html?highlight=bosh_service_url#bosh-service-url

**Comment by PSP789456** [comment]
Before I had some problems with apache configuration and converse tried to log me in through global server. Now after entering login@hostname and password loading spinner appears for a second and shows me empty login window.
Here is my websocket configuration:
converse.initialize({
        websocket_url: 'ws://192.168.5.115',
        show_controlbox_by_default: true,
})

I'm using ubuntu server 18.04 with apache and openfire. 192.168.5.115 is my server in local network. Have no idea what should I change to make it work fine in local environment.

**Comment by PSP789456** [comment]
@jcbrand You were right, changed websocket_url to  'ws://192.168.5.115:7070/ws/' and it's working now
