### ISSUE TITLE
Problem with modifying converse fullscreen

### ISSUE THREAD

**Issue by turb01** [conversejs/converse.js#1659]
Hello! I have a problem with modifying converse fullscreen version. I can modify easily default version (index.html) but can't do any changes to fullscreen version of converse. When I'm checking sources in google devtools it says that all files are loaded from localhost. I'm using XAMPP to run converse on local machine. Which files should I modify to change appearance of fullscreen converse?

**Comment by jcbrand** [comment]
The source files are in the `src/` directory. You can run `make watch` to automatically regenerate the bundle when you change a source file.
