### ISSUE TITLE
Add a shutdown function to destroy the whole ConverseJs initialization

### ISSUE THREAD

**Issue by reda-alaoui** [conversejs/converse.js#1661]
ConverseJs 4.2.0 can only be used as a global variable.
On a single page application, with ConverseJs embedded in as a destructible component, converse.initialize could be called multiple time in the same page context.

On component destruction,it would be useful to have a public function allowing to destroy the whole ConverseJs context, as if *initialize()* was never called.

**Comment by jcbrand** [comment]
Try calling `_converse.api.connection.disconnect()`, that should tear everything down properly.

You should be able to put `import converse from converse.js` into your component's JS module and thereby have a separate copy of it for each component.

**Comment by reda-alaoui** [comment]
Thanks I will try that.

`import converse from converse.js` does not work because the project performs import that are considered as node modules imports in most webpack configuration.

For example in converse.js:
```
import "converse-caps";  
```
By default, this makes webpack lookup for node module named `converse-caps`.
It would have to take this form to work with the node resolution (default in webpack):
```
import "./converse-caps";  
```

Secondly, since `converse` is const, there is still a unique instance of Converse in the whole application, is it not?

**Comment by reda-alaoui** [comment]
Sorry for the import, I was talking about importing from src/converse.js to avoid loading the webpacked form.

**Comment by jcbrand** [comment]
> Secondly, since converse is const, there is still a unique instance of Converse in the whole application, is it not?

Yes, but I think you can safely ignore that. I'm not sure how to nicely avoid that in your case.

**Comment by reda-alaoui** [comment]
When using auto reconnect `_converse.api.connection.disconnect()` ends up with a reconnect.
Issue fixed with `this._converse.api.user.logout();`.

**Comment by lunika** [comment]
Hi,

I would like to know if now there is a new solution to deal with this issue ? Because if `this._converse.api.user.logout();` is called, then the user must choose a new nickname every time he access to the chat.

Thanks.

**Comment by jcbrand** [comment]
@lunika: If you want your user to keep the nickname, then why log out in the first place? It's possible to create components in such a way that you don't have to shutdown Converse when the component unmounts.

**Comment by lunika** [comment]
My problem is when the component is mounted/unmounted several times in a same "session". The second time the component is mounted, I always have an error saying that the session is not restorable and the chat is not displayed. 

Maybe looking at the code itself you will see what is wrong: https://github.com/openfun/marsha/blob/6f933abf2f9dbefdc69b7adf3e778d68f85c1f42/src/frontend/components/Chat/index.tsx 

Thanks

**Comment by jcbrand** [comment]
Don't initialize Converse in the same component that's mounted and unmounted, instead create a separate component just for initializing Converse and keep that component in the DOM at all times.

**Comment by lunika** [comment]
Great, thank you for your help! I will try with `insertInto` first.
