### ISSUE TITLE
Blacklisting converse-profile makes the control box totally blank

### ISSUE THREAD

**Issue by reda-alaoui** [conversejs/converse.js#1664]
**Describe the bug**
Blacklisting converse-profile makes the control box totally blank

**To Reproduce**
1. Blacklist converse-profile

**Expected behavior**
I was expecting to prevent the show-profile modale from being displayed.

**Environment (please complete the following information):**
 - Desktop
 - Chrome 75
 - Converse.js 4.2.0

**Comment by reda-alaoui** [comment]
This is a follow up of #1662

**Comment by jcbrand** [comment]
Thanks for making a bug report for this.
