### ISSUE TITLE
Embedded mode looks like full screen

### ISSUE THREAD

**Issue by wrooot** [conversejs/converse.js#1673]
I have tried to update converse.js links to 5.0.0 on our page with an embedded MUC, but it opens with a side panel (on the left) like in full screen mode. Have tried to compare our page with the demo page, but not sure what i'm missing. Our page https://github.com/wrooot/IgniteRealtime-Website/blob/master/src/main/webapp/support/converse.jsp

**Comment by jcbrand** [comment]
Converse was changed somewhat to allow embedding the entire app as well, instead of only a particular chat.

Did you set `singleton` to `true`?
https://conversejs.org/docs/html/configuration.html#singleton

**Comment by wrooot** [comment]
I don't see this setting in our page's code, so i guess i will try adding this later today.

**Comment by wrooot** [comment]
singleton: 'true'

fixed this issue, although i see this is marked as a bug

**Comment by jcbrand** [comment]
@Nyco thanks for labeling the tickets, however please don't label tickets as bugs until it's 100% clear that they are.

**Comment by Nyco** [comment]
OK, clear.
