### ISSUE TITLE
Offline users still being shown

### ISSUE THREAD

**Issue by wrooot** [conversejs/converse.js#1674]
I have updated our page to 5.0.0 and also added hide_offline_users setting, as now offline users are being shown by default and we don't need them. Set it to true, but still see the offline users. Do i miss something? https://github.com/wrooot/IgniteRealtime-Website/blob/master/src/main/webapp/support/converse.jsp

Also, after adding this setting i have to refresh my page additional time to get the nickname page, otherwise it loads an empty embed screen. Maybe this is just some caching issue and the fact that i test by building our site locally and running on tomcat.

**Comment by wrooot** [comment]
Actually, it looks like it only shows offline admins and owners. Still, i think they should be covered by the same option. And these offline users are shown with full jids instead of only nicknames, so they take more space in participants list.

**Comment by jcbrand** [comment]
Oh, you're talking about MUC participants? `hide_offline_users` is for the roster and has nothing to do with MUC participants.

If you don't want to show these participants, then set `muc_fetch_members` to `false`.

**Comment by wrooot** [comment]
muc_fetch_members: 'false' didn't do the trick
![image](https://user-images.githubusercontent.com/7195609/62889256-aa5d1500-bd49-11e9-866f-6005d0c9f47e.png)

**Comment by wrooot** [comment]
Oh, after chaning from 'fetch' to just fetch it works. I think all settings should use the same format..

**Comment by guusdk** [comment]
They do: json! ;)
