### ISSUE TITLE
Native desktop version with NodeGUI?

### ISSUE THREAD

**Issue by poVoq** [conversejs/converse.js#1682]
https://github.com/nodegui/nodegui

A bit like react-native, but should work also with Converse.

Would be a cool additional way to run Converse and probably much better than the Electron version someone was working on.

**Comment by deleolajide** [comment]
Dos that mean all the HTML templates have to be ported to QT5?

**Comment by Nyco** [comment]
@poVoq you know it, but there is also https://github.com/nick-denry/Chimeverse which is based on Electron, and only for macOS. It would be nice to port it to Linux and Windows as well.

**Comment by deleolajide** [comment]
I still think using a browser extension to implement Converse as a Native desktop client is more efficient than Electron and even NodeGUI for the following reasons.

1. Browser engine is already installed and running on desktop. No need to reload browser from bloated code. Startup is faster as there is less code to load.
2. All users install the same single native application from the browser vendor web store for all platforms (OSX, Windows, Linux) with automatic updating on all deployed desktops.
3. Converse runs in a privilege mode with access to desktop features like system tray, USB ports, co-operative binary code, unlimited storage, native windows, full desktop notifications with separation of front-end and background processing without incurring the overhead of running node in memory.

**Comment by Nyco** [comment]
Not sure I get it: a browser extension still runs in a browser, right?

The users' needs we address here is the need for a "fat client/app", that has its own lifecycle (launch, stop/kill, update, notifications, etc.) independant from a browser.

Anyway, both solutions offer more variety of choice for the users.

The question also needs answers regarding the mobile.

**Comment by deleolajide** [comment]
> Not sure I get it: a browser extension still runs in a browser, right?

![image](https://user-images.githubusercontent.com/110731/63933496-43ca3d80-ca51-11e9-97dc-1dde7cbe6311.png)

Not really. It runs in its own native O/S window and is auto-started at O/S user login if preferred.

**Comment by deleolajide** [comment]
> The users' needs we address here is the need for a "fat client/app", that has its own lifecycle (launch, stop/kill, update, notifications, etc.) independant from a browser.

The use case for *background* browser extensions was designed for this. They run as independent processes from the main browser window and have no cause to show the main browser window. 

The multi-platform support and easy deployment/update cycle directly via the browser vendor makes them more compelling than manually building multi-platform packages with chromium/node embedded as required with Electron.

**Comment by Nyco** [comment]
## Browser extension

At OS restart, having a browser extension automatically launched is a big problem. First, it launches the browser and thus consumes RAM and CPU. Second, the browser is in the OS task list, even though to browser window is launched. Third, there is no entry in OS apps menus. The list can go long, I am not exhaustive here.

I am telling you this as a user, many of us just don't like this type of extensions running in a third party window, badly emulating an app. Of course you can find extension lovers to balance this.

## Independant app (from browser)

The goal *AND* user need is also for some users to have two (or more) totally independant types of desktop apps: web browsers and chat clients.

Examples based on Electron:
* https://github.com/RocketChat/Rocket.Chat.Electron
* https://github.com/mattermost/desktop
* https://github.com/zulip/zulip-electron
These are all available on the pure web as well, (and on mobile, but that's another story).
And yes: Slack, Discord, MS Teams, Riot as well (and WhatsApp).

So NodeGUI/Electron-type of web app packaging is cool. Maybe add NW.js (node-webkit) to this list. This said we all keep in mind that Electron is known to consume lots of resources. And NodeGui is quite young.

Still users' preferences count first.

## User choice

These solutions just address different problems, needs and constraints for the users. Also a matter of who's going to do and maintain it.

As a user, I'd be happy to use and contribute to both, whichever comes first. For example, I'm quite happy with the above-mentioned Chimeverse.

**Comment by deleolajide** [comment]
> I am telling you this as a user, many of us just don't like this type of extensions running in a third party window, badly emulating an app. Of course you can find extension lovers to balance this.

I use Converse everyday as a browser extension and I have happy users of Converse running as a browser extension.  I disagree that a browser extension runs in a third party window and badly emulates an app any more than Electron which is an embedded Chromium browser does exactly the same thing.

Everything has pros and cons. I was only giving my two-pence opinion from my experience of professionally developing browser extensions for paying customers.

**Comment by poVoq** [comment]
Chimeverse with Electron does the job.
