### ISSUE TITLE
Build package not available on packagist

### ISSUE THREAD

**Issue by fabiomontefuscolo** [conversejs/converse.js#1685]
**Describe the bug**
Before version 5.0.0, I was able to run `composer require jcbrand/converse.js` and ConverseJS dist files. But now all I get are the source files, not dist files anymore.

**To Reproduce**
1. Install the latest `composer` tool
2. Go to an empty folder to avoid mess the current one
3. Type `composer require jcbrand/converse.js v5.0.1`
4. Check dist files by typing `ls vendor/jcbrand/converse.js/dist`

**Expected behavior**
We should find ConverseJS dist files. Before we had 

```
$ ls vendor/jcbrand/converse.js/dist
converse.js
```

**Screenshots**
![image](https://user-images.githubusercontent.com/162023/63366596-805eb080-c350-11e9-8fce-ad7e30ab0405.png)

**Environment (please complete the following information):**
 - packagist
 - composer
 - Converse.js version >= 5.0.0

**Additional context**
I'm trying to add conversejs 5.0.1 as requirement for TikiWiki CMS.

**Comment by marclaporte** [comment]
Also need to think of 55k installs that will want to upgrade: https://packagist.org/packages/jcbrand/converse.js/stats

**Comment by marclaporte** [comment]
Here is an example of how it's done for Chosen:
https://github.com/harvesthq/chosen-package
https://github.com/harvesthq/chosen/blob/master/publish-package.sh

**Comment by marclaporte** [comment]
Related: https://gitlab.com/tikiwiki/tikiwiki-diagram-builder

**Comment by marclaporte** [comment]
We see drop in daily downloads:
![2020-01-02_163800](https://user-images.githubusercontent.com/1004261/71694869-7b8a1e80-2d7e-11ea-82e4-5e8f85ea1087.png)

I will work with team to propose a solution.

**Comment by marclaporte** [comment]
Workaround: https://asset-packagist.org/package/detail?fullname=npm-asset/converse.js

**Comment by marclaporte** [comment]
For the record, we are moving away from Packagist for JavaScript projects like Converse.js
https://gitlab.com/tikiwiki/tiki/-/merge_requests/4365

**Comment by marclaporte** [comment]
For the record, here is info about when Converse.js was first added to Packagist.org: https://github.com/conversejs/converse.js/issues/755
