### ISSUE TITLE
Simplify join/create group chat room

### ISSUE THREAD

**Issue by andypl** [conversejs/converse.js#1690]
**Is your feature request related to a problem? Please describe.**
When a user wants, to join or create a group chat conversation, Converse force enter a full jid of it, for example: conterence_name@conference.example.tld. This solution is not very good because, not experienced user sometimes dont know what to enter. 

**Describe the solution you'd like**
I think Converse should simplify this process by auto add conference serwer name, to provided room name.

Maybe this field should be splitted into room name part, and room address part? In a room address part Converse should put a user server default, and if user server should not have any group chat service a appropriate error message should be shown, and user should type alternative group chat server?

Getting a muc room name of a server is possible via Disco: https://xmpp.org/extensions/xep-0045.html#disco-service-features

**Describe alternatives you've considered**
If user server does not have a group chat service, Converse should shown a window with message like: "Your server does not provide group chat service. Please provide room name with server part."

**Comment by Echolon** [comment]
@andypl I will close this as duplicate. Please refer to the posted issue.

Anyway, thanks for reporting!
