### ISSUE TITLE
ConverseJS 5.0.1 does not auto_load room on embdded mode

### ISSUE THREAD

**Issue by fabiomontefuscolo** [conversejs/converse.js#1694]
**Describe the bug**
The JID comparison is case sensitive. From section **2.3 Node Identifier** in XEP 0029, I understand the comparison should be case insensitive.

I'm pretty sure the error happens at https://github.com/conversejs/converse.js/blob/master/src/headless/converse-chatboxes.js#L408 (src/headless/converse-chatboxes.js line 408). The function `_.includes` compare in case sensitive mode.

**To Reproduce**
1. Set mode to **embedded**
1. Have a lower-cased xmpp room to join, like `wikisuite@conference.wikisuite.chat`
2. Set up `auto_join_rooms` to join `WikiSuite@conference.wikisuite.chat`
```
"auto_join_rooms": [
    "WikiSuite@conference.wikisuite.chat"
],
```
3. Set `singleton: true`

**Expected behavior**
A warning containing the error message will appear in the console, probably when conversejs has the debug flag to true.

```
WARNING: wikisuite@conference.wikisuite.chat is not allowed because singleton is true and it's not being auto_joined 
```

**Screenshots**
![image](https://user-images.githubusercontent.com/162023/63886449-e1216500-c9b0-11e9-9d02-9d65f3c4f50f.png)

**Environment (please complete the following information):**
 - Desktop
 - Chrome and Firefox
 - Converse.js 5.0.1

**Additional context**
This problems started after upgrading ConverseJS to 5.0.1 from 4.2.1.

**Comment by licaon-kter** [comment]
Already fixed in HEAD I guess: https://github.com/conversejs/converse.js/pull/1681

**Comment by deleolajide** [comment]
@fabiomontefuscolo It might fix your use case as that was the same error and it occurs because the chat room name in the XMPP stanza did not match any of the names in the list. In my case it was a server-generated random name and in your case it was a case sensitive mismatch.
