### ISSUE TITLE
Concord theme: Poor contrast when hovering on roster entries

### ISSUE THREAD

**Issue by Zash** [conversejs/converse.js#1695]
**Describe the bug**
The background of roster entries when hovering is close to the color of the text, making it hard to read.

**To Reproduce**
1. Enable concord theme
2. Point at a roster entry
3. Try to read text
4. Squint really hard

**Expected behavior**
The text should be readable even if the colors change to highlight the item.

**Screenshots**
![image](https://user-images.githubusercontent.com/197474/63972492-2cb73a00-caa9-11e9-86a0-07cf72d7e8ed.png)

**Environment (please complete the following information):**
 - Desktop
 - Firefox 60.8.0esr
 - Converse.js version 5.0.1

**Comment by marclaporte** [comment]
"Squint really hard"   hahahahhahahaha. Good one!

**Comment by Zash** [comment]
Changing `--list-item-link-hover-color` to something darker almost works but there's some area in the padding where the text color is the same as the background because the background color is applied to an outer `<div>` that's larger than the `<a>` where the text color is applied.

**Comment by jcbrand** [comment]
This is fixed in master.
