### ISSUE TITLE
Emoji messed up in Chrome

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/converse.js#1699]
HEAD (778fb4e65d3efed0cb0ad66e7bef4382e9eb6822) / Windows 7

Firefox 
![emojiff](https://user-images.githubusercontent.com/2282799/64272203-60bdaf80-cf2e-11e9-959c-636763a73a44.PNG)

vs

Chrome
![emojich](https://user-images.githubusercontent.com/2282799/64272209-687d5400-cf2e-11e9-8006-f0c87140cab2.PNG)

What am I missing?

**Comment by jcbrand** [comment]
I think the issue is that Windows 7 doesn't have system emojis and Firefox ships with its own set.

**Comment by licaon-kter** [comment]
Which one? Same as on Linux, Noto?

**Comment by jcbrand** [comment]
I don't understand your question.

**Comment by jcbrand** [comment]
I don't think there's anything for me to do here. You can use the twemoji images to work around this issue.

https://conversejs.org/docs/html/configuration.html#use-system-emojis

**Comment by licaon-kter** [comment]
> Not all operating systems support (all) emojis. So alternatively you can let Converse render the emojis with [Twemoji](https://twemoji.twitter.com/). See also emoji_image_path.

Ok, lets

> emoji_image_path
If you’ve run make dev, then these files are also available in ./node_modules/twemoji/2/, which means you can avoid the CDN and host them yourself if you wish.

So, `make dev`:
```
#:~/converse.js/node_modules/twemoji$ find -follow
.
./LICENSE
./package.json
./README.md
./dist
./dist/twemoji.amd.js
./dist/twemoji.min.js
./dist/twemoji.js
./dist/twemoji.esm.js
./dist/twemoji.npm.js
./LICENSE-GRAPHICS
./node_modules
./node_modules/jsonfile
./node_modules/jsonfile/LICENSE
./node_modules/jsonfile/package.json
./node_modules/jsonfile/CHANGELOG.md
./node_modules/jsonfile/README.md
./node_modules/jsonfile/index.js
```
...ummm, where are they? Or what should I do exactly so I can host them?

**Comment by jcbrand** [comment]
> ..ummm, where are they? Or what should I do exactly so I can host them?

By default it uses the Twemoji CDN, if you want to self-host you'll have to consult the twemoji docs

**Comment by licaon-kter** [comment]
So the documentation is wrong and/or incomplete, right?

**Comment by jcbrand** [comment]
In what way?

**Comment by licaon-kter** [comment]
> If you’ve run make dev, then these files are also available in ./node_modules/twemoji/2/, which means you can avoid the CDN and host them yourself if you wish.

These files are not available in that path.

**Comment by jcbrand** [comment]
Indeed, I removed that line now.
