### ISSUE TITLE
Suggestion: unify the stub messages for encrypted messages

### ISSUE THREAD

**Issue by stevenroose** [conversejs/converse.js#1702]
This is a screen I logged into recently:
![screenshot-2019-09-10-11-38-46](https://user-images.githubusercontent.com/853468/64607615-bd065080-d3c0-11e9-9ab1-ab5d915232a3.png)

It's a bit ugly that when users converse in different clients, they all send different stub messages. And since this is often what users see on their first ever time joining an XMPP chat, it's a bit sad.

Using [XEP-0380](https://xmpp.org/extensions/xep-0380.html) one could fairly easily unify the stub messages and even format the messages differently so they don't look like actual messages. (Grey them out or lower font or something f.e.) Because in a good UX, these **should** only happen when joining a private group chat, they can be made smaller.

**Comment by jcbrand** [comment]
We didn't unify these messages, but they're now ephemeral, so they are auto-removed after a few seconds.
