### ISSUE TITLE
Crash after hibernating

### ISSUE THREAD

**Issue by liori** [conversejs/converse.js#1705]
**Describe the bug**
The anonymous instance converse.js at https://xmpp.org/chat?xsf crashes when suspending and waking up my PC.

**To Reproduce**
1. Go to https://xmpp.org/chat?xsf and type some nickname.
2. Suspend PC.
3. Wake PC after few hours.

**Expected behavior**
The client reconnects and works.

**Screenshots**
https://imgur.com/a/Ay4VIVn

**Environment (please complete the following information):**
 - Ungoogled Chromium, from the About window: Version 72.0.3626.122 (Official Build) built on Debian stretch/9.9, running on Debian stretch/9.9 (64-bit)
 - Converse.js version 5.0.1

**Comment by jcbrand** [comment]
I'm not exactly sure what the cause is, but I see `this.roomspanel` was undefined, so I added an accessor method to make sure it gets returned when needed. Hopefully that fixes it.
