### ISSUE TITLE
Path changes in 5.0.2 breaks external loading of resources

### ISSUE THREAD

**Issue by heurekus** [conversejs/converse.js#1709]
The path changes in 5.0.2 seem to break my Prosody based Converse.js installation which is as follows:

 * Prosody running on a.com and Converse is served from https://a.com:5281/conversejs (mod_conversejs)

 * The converse distribution is located at https://b.com/converse

Problems after upgrading to 5.0.2:

 * b.com/converse no longer works, converse now expects files at b.com/dist and b.com/css. I could change the directories but I use b.com for other purposes as well so having everything in the root directory is not nice at all. Yes, I could compile dist myself but I really don't want to do that.

 * Converse now tries to load files such as emoji... from a.com:5281 instead of from b.com. That won't work at all and I don't see how I could fix this myself.

Any ideas? Thanks!

**Comment by jcbrand** [comment]
For the build served via the CDN, I've now updated the `publicPath` setting to point to the CDN.

Sorry, I'm not aware of anything else I can do to help you with this.

**Comment by heurekus** [comment]
Thanks very much for the additional explanation! I finally figured out how to get it working with Prosody and _mod_conversejs_: 

Apart from moving the installation from _/converse/dist_ to _/dist_ in my case (easy part) and corresponding changes in _prosody.conf.lua_, I was stuck with the problem that emojis.js was not requested from _b.com/dist_ but from _a.com:5281_, i.e. from the domain I use for my Prosody server and thus the wrong domain and wrong port. This can be changed with the following additional config line in _prosody.conf.lua_ below the config to load the libsignal Javascript library for OMEMO (if so desired):

        conversejs_tags = {
          -- Load libsignal-protocol.js for OMEMO support (GPLv3; be aware of licence implications)
          [[<script src="https://xyz.com/dist/libsignal-protocol.min.js"></script>]];
        
          -- Since Conversejs 5.0.2, emojis.js is loaded but from the wrong domain. Force it to the right domain:
          [[<script src="https://xyz.com/dist/emojis.js"></script>]]
        }

I will ping the maintainer of _mod_conversejs_, perhaps he wants to either put this in the code of the module as everyone is likely to require this if he wants to make Conversjs work in its current revision with Prosody or mention it in the documentation.

Thanks!

**Comment by jcbrand** [comment]
Thanks for sharing your solution. I think if you serve converse.js via a webserver like nginx, then you won't have the problem of emoji.js being fetched from the "wrong" URL.
