### ISSUE TITLE
TypeError: plugin._features is not a function

### ISSUE THREAD

**Issue by Zash** [conversejs/converse.js#1712]
**Describe the bug**

Saw this in the console while attempting to reproduce some other issue:
```
 FATAL: onDiscoInfoRequest@https://cdn.conversejs.org/5.0.2/dist/converse.js:52893:7
run@https://cdn.conversejs.org/5.0.2/dist/converse.js:45503:22
_dataRecv/<@https://cdn.conversejs.org/5.0.2/dist/converse.js:46744:29
forEachChild@https://cdn.conversejs.org/5.0.2/dist/converse.js:44501:17
_dataRecv@https://cdn.conversejs.org/5.0.2/dist/converse.js:46733:9
_onMessage@https://cdn.conversejs.org/5.0.2/dist/converse.js:49233:9
 converse.js:50665:5
 FATAL: error: undefined https://cdn.conversejs.org/5.0.2/dist/converse.js:52893 - TypeError: plugin._features is not a function converse.js:50665:5
	converse_core_converse.log https://cdn.conversejs.org/5.0.2/dist/converse.js:50665:5
	setUpXMLLogging/converse_core_Strophe.log https://cdn.conversejs.org/5.0.2/dist/converse.js:51062:5
	fatal https://cdn.conversejs.org/5.0.2/dist/converse.js:45063:9
	_handleError https://cdn.conversejs.org/5.0.2/dist/converse.js:44971:13
	run https://cdn.conversejs.org/5.0.2/dist/converse.js:45505:13
	_dataRecv/< https://cdn.conversejs.org/5.0.2/dist/converse.js:46744:29
	forEachChild https://cdn.conversejs.org/5.0.2/dist/converse.js:44501:17
	_dataRecv https://cdn.conversejs.org/5.0.2/dist/converse.js:46733:9
	_onMessage https://cdn.conversejs.org/5.0.2/dist/converse.js:49233:9

```
**To Reproduce**
Happens on https://chat.prosody.im/ which has configuration like this:
```javascript
	converse.initialize({
		"allow_bookmarks" : false,
		"hide_muc_server" : true,
		"allow_contact_requests" : false,
		"allow_dragresize" : false,
		"allow_muc_invitations" : false,
		"authentication" : "anonymous",
		"auto_join_on_invite" : true,
		"auto_join_rooms" : [
			"chat@conference.example.com
		],
		"auto_login" : true,
		"auto_reconnect" : false,
		"show_controlbox_by_default":false,
		"blacklisted_plugins" : [
			"converse-carbons",
			"converse-bookmarks",
			"converse-omemo",
			"converse-register",
			"converse-controlbox"
		],
		"bosh_service_url" : "/bosh",
		"debug" : false,
		"jid" : "anon.prosody.im",
		"keepalive" : true,
		"message_carbons" : false,
		"show_send_button" : false,
		"use_emojione" : false,
		"view_mode" : "fullscreen",
		"websocket_url" : "wss://chat.example.org/ws"
	});
```

**Screenshots**

**Environment (please complete the following information):**
 - Firefox 60.9 ESR
 - Converse.js version 5.0.2

**Comment by MotoGP-Fan** [comment]
Hi JC,
in addition to Zash's report: I also receive this error message - see first pic.

- Prosody 0.11.2
- Converse 5.0.3  on local installation
- tested with **non minified** js+css
- Firefox 69.0 + Chrome 77.0.3865.75

![2019-09-14_Converse503-Fullscreen_Error-non-minified](https://user-images.githubusercontent.com/30147533/64900635-836c6880-d692-11e9-8e1b-344a7c470d3e.png)
<br>
- 2nd test with **minified** js+css leads to another error. 1st error is not displayed anymore - pic 2.

![2019-09-14_Converse503-Fullscreen_Error-minified](https://user-images.githubusercontent.com/30147533/64900644-9a12bf80-d692-11e9-9042-e6285ad0417f.png)
<br>
converse.initialize({
    debug: true,
    authentication: 'login',
    bosh_service_url: 'https://example.de/http-bind',
    locked_domain: 'example.de',
    allow_registration: false,
    show_send_button: true,
    use_emojione: false,
    roster_groups: true,
    archived_messages_page_size: 25,
    message_carbons: true,
    theme: 'default',
    view_mode: 'fullscreen',
});

**Comment by laszlovl** [comment]
I'm guessing this is related to the following commit: https://github.com/conversejs/converse.js/commit/768ed4a5777ff1f3a96caa10c9e2f32f5e74a486#diff-43e51bd411c01988f495ddaaece16b2fL324

**Comment by mreid0345** [comment]
I think its a different issue. Its failing on n._features not plugin._features

**Comment by ThoreKr** [comment]
Will there be a release with this fix in the near future?
