### ISSUE TITLE
Need Help!

### ISSUE THREAD

**Issue by MothGirlMusic** [conversejs/converse.js#1713]
Hi. this isn't a bug but i also dont know where else to post or ask this question. the converse.js setup instructions seems to only talk about the full-page demo... however i require set up instructions fro the "embedded" demo... found here: https://conversejs.org/demo/embedded.html where you can anonymously log into an embedded chat on the website. any help... or a link to a page i may have missed would be great!

**Comment by jcbrand** [comment]
The embedded usecase is similar to the fullscreen one except that you use a different [view_mode](https://conversejs.org/docs/html/configuration.html#view-mode) setting.

The code for the demo is available for you to study:
https://github.com/conversejs/converse.js/blob/master/demo/embedded.html
