### ISSUE TITLE
A web page is slowing down your browser. What would you like to do?

### ISSUE THREAD

**Issue by ulsaramana** [conversejs/converse.js#1717]
Dear Team,

When we login to our XMPP account immediately the web page is going down the browser.
We tried multiple browser and still the same issues, Kindly suggest us ASAP

Best Regards
Ramana Ulsa

**Comment by licaon-kter** [comment]
What browser? What exetensions?

Eg. If I enable CanvasBlocker in Firefox it will slow down on login.

**Comment by ulsaramana** [comment]
Hi there,
We tested on all the browsers, we are not suing any ad blockers.
Firefox,
Chrome
Microsoft Edge

**Comment by jcbrand** [comment]
This can sometimes happen on older less powerful computers. I don't have a specific solution for this right now except to try and make the code more efficient and performant in general.

**Comment by ulsaramana** [comment]
Sure JC, Thank you so much!
