### ISSUE TITLE
Latest everything applyed plugin._feature fix. up to date w repo.

### ISSUE THREAD

**Issue by mreid0345** [conversejs/converse.js#1725]
Ive tried a barebones config w latest cdn
ive tried a webpack built dist for converse.min.js latest src doublechecked your foreach is in there
im still getting this error
<img width="692" alt="Untitled" src="https://user-images.githubusercontent.com/55162602/65284660-d9f8fd00-daff-11e9-960e-3d51ac58ce06.png">

**Comment by mreid0345** [comment]
this was not solved in the plugin._features issue, might be something w webpack?
but im assuming n is uglified plugin. It doesn't work. Please advise.

**Comment by jcbrand** [comment]
The latest CDN doesn't include changes that haven't been released yet.

You can test the trunk CDN but it's definitely not recommended to use this in production because it always tracks the latest code: https://cdn.conversejs.org/trunk/dist/converse.js

**Comment by mreid0345** [comment]
Fixed it; basically some of the Strophe Namespaces dont exist with different configurations of a server.

so i wrapped them in an isArray test.

heres my code for converse-disco.js

function addClientFeatures () {
            // See https://xmpp.org/registrar/disco-categories.html
            _converse.api.disco.own.identities.add('client', 'web', 'Converse');

            if (Strophe.NS.BOSH && Array.isArray(Strophe.NS.BOSH)) {
                _converse.api.disco.own.features.add(Strophe.NS.BOSH);
            }
            if (Strophe.NS.CHATSTATES && Array.isArray(Strophe.NS.CHATSTATES)) {
                _converse.api.disco.own.features.add(Strophe.NS.CHATSTATES);
            }
            if (Strophe.NS.DISCO_INFO && Array.isArray(Strophe.NS.DISCO_INFO)) {
                _converse.api.disco.own.features.add(Strophe.NS.DISCO_INFO);
            }
            if (Strophe.NS.ROSTERX && Array.isArray(Strophe.NS.ROSTERX)) {
                _converse.api.disco.own.features.add(Strophe.NS.ROSTERX); // Limited support
            }
            if (_converse.message_carbons && Strophe.NS.CARBONS && Array.isArray(Strophe.NS.CARBONS)) {
                _converse.api.disco.own.features.add(Strophe.NS.CARBONS);
            }

**Comment by mreid0345** [comment]
[converse-disco.zip](https://github.com/conversejs/converse.js/files/3637111/converse-disco.zip)

**Comment by jcbrand** [comment]
Thanks @mreid0345, however I don't understand why you made the above change.

> basically some of the Strophe Namespaces dont exist with different configurations of a server.

Can you explain how the server configuration can determine whether Strophe namespaces are available? The namespaces are all defined in converse-core and shouldn't at all be dependent on the server configuration.

**Comment by mreid0345** [comment]
All i know is some of those namespaces were crashing on one of the namespaces being parsed by foreach .

I assumed it was because our configuration was different then urs.

Im building on a copy of ubuntu. Using npm to install and webpack.dev.js. for webpack

This code i sent here does fix the issue and keep it from crashing

**Comment by jcbrand** [comment]
> were crashing on one of the namespaces

Do you know which one in particular?

**Comment by mreid0345** [comment]
I actually dont. I can debug it for our instance of converse and figure out
which one. Ill have the answer for u tomorrow. I think honestly a test for
undefined in forEach probable would fix it accross everything. Ill nail
down which namespace was coming back undefined

**Comment by jcbrand** [comment]
> I can debug it for our instance of converse and figure out which one

Thank you, that would be great.

> I think honestly a test for undefined in forEach probable would fix it accross everything. 

The namespace shouldn't be undefined and adding a check for each one simply masks the underlying problem. So it's not a proper solution IMO.

**Comment by mreid0345** [comment]
I added an else to each of those conditions i wrapped the feature additions in,,,

all of them failed, every one. Its gotta be how we have our configuration going, im going to send you my init also,

converse.initialize({
            trusted: true,    
            auto_away: 300,
            auto_reconnect: true,
            message_archiving: 'always',
            view_mode: 'fullscreen',
            allow_logout: true, // No point in logging out when we have auto_login as true.
            allow_muc_invitations: false, // Doesn't make sense to allow because only
            allow_contact_requests: false, // Contacts from other servers cannot,
            authentication: 'login',
     	    credentials_url: 'https://54.188.25.226/chat/chatjson.php',
            allow_contact_requests: true,
            auto_login: 'true',
            //auto_join_rooms: [
              //  'anonymous@conference.nomnom.im',
            //],
            //notify_all_room_messages: [
              //  'anonymous@conference.nomnom.im',
            //],
            bosh_service_url: 'https://54.188.25.226:5281/http-bind/', // Please use this connection manager only for testing purposes
            //jid: 'nomnom.im', // XMPP server which allows anonymous login (doesn't
                              // allow chatting with other XMPP servers).
            keepalive: false,
    	    auto_reconnect: true,
    	    debug: true,
            play_sounds: true,
            show_controlbox_by_default: true,
            strict_plugin_dependencies: false,
            notification_icon: 'images/logo.svg',
            notification_delay: 5000,
            show_toolbar: true,
            show_desktop_notifications: true,
            visible_toolbar_buttons: {
                call: true,
                spoiler: true,
                emoji: true,
                toggle_occupants: true
            },
            show_send_button: true,
            autocomplete_add_contact: true,
            whitelisted_plugins: ['addon']
        });

**Comment by mreid0345** [comment]
weve noticed that there are a ton of modules for prosody, were installing discoitems and testing to see if thats why that ns was failing.
