### ISSUE TITLE
New message notifications for a minimized chat stack on top of each other

### ISSUE THREAD

**Issue by MitchellBrooks** [conversejs/converse.js#1733]
**Describe the bug**
When a chat is minimized and messages from that user are sent, the unread notifications stack in an odd way. 

**To Reproduce**
1. Use "overlayed" view_mode
2. As user A, minimize a chat with user B
3. Send 1 or more messages from user B to user A

**Screenshots**
![minimizedChatBug](https://user-images.githubusercontent.com/11617258/65636149-c0e4c600-dfaf-11e9-8c2c-355fd8bc74c4.PNG)

![minimizedChatBug2](https://user-images.githubusercontent.com/11617258/65636585-92b3b600-dfb0-11e9-86ee-1c0b8381f8a3.PNG)

**Environment**
 - Desktop
 - Windows 10
 - Chrome 76.0.3809.132 and Firefox 69.0.1
 - Converse.js version 5.0.3

**Comment by jcbrand** [comment]
Thanks for reporting, should be fixed now in master.
