### ISSUE TITLE
Messenger Converse.js issue

### ISSUE THREAD

**Issue by ulsaramana** [conversejs/converse.js#1734]
Dear Team,

Every day we are facing so many issue in Converse.js application which are listed below. This is not only for specific almost every single person facing below issues once in a day or sometime back to back on their PC.

We need a permanent solution on this. Request you please take a serious action on this & resolve these issues permanently.

1. Message not sent notification.

2. Delivery Pending.

3. Message history not showing.

4. Previously saved contacts disappear.

5. XMPP error.
![Converjs](https://user-images.githubusercontent.com/48724095/65640360-2f2d8680-dfb8-11e9-9c50-6d1d9743f9fc.PNG)

6. Trying to send.

7. Reply of previous message not comes in trail messages.

8. Application takes so much time to load in browser if having maximum saved contacts.

Environment
==========
 - Desktop
 - Browser [Chrome, Firefox, Microsoft Edge]
 - Converse.js Latest version 
![Converjs2](https://user-images.githubusercontent.com/48724095/65640551-9814fe80-dfb8-11e9-8114-9094752d6992.PNG)

**Comment by ulsaramana** [comment]
Application takes so much time to load in browser if having maximum saved contacts.
![Conversj3](https://user-images.githubusercontent.com/48724095/65641074-d6f78400-dfb9-11e9-9fca-1c4ffe3665db.PNG)

**Comment by licaon-kter** [comment]
Can you split this in separate issues? Can you attach console logs with `debug: true`?

**Comment by ulsaramana** [comment]
OMG it's going to be take more time

**Comment by licaon-kter** [comment]
Yes, but this info (steps how to reproduce, debug console output, etc) is needed to track down and fix each issue.

**Comment by jcbrand** [comment]
Like @licaon-kter said, this needs to be broken down into separate issues. When creating issues, please use the **bug report** template and fill it out properly so that we get all the relevant information.
