### ISSUE TITLE
Conversejs With AMD and require.js

### ISSUE THREAD

**Issue by rheman** [conversejs/converse.js#1737]
Hi everyone,
I am working with the latest release of conversejs and I want to integrate it in elgg (https://elgg.org/) elgg is and open source social networking engine.

Elgg only supports JavaScript libraries declare as AMD module. 

So could someone help me ? How can I define or build the converse AMD module ?

Regards,

**Comment by jcbrand** [comment]
Sorry, this issue tracker is for bug reports and feature requests, not for support requests.
