### ISSUE TITLE
Allow webpack's `publicPath` to be specified at runtime.

### ISSUE THREAD

**Issue by jcbrand** [conversejs/converse.js#1738]
Currently the `publicPath` is set to `/dist`, causing all kinds of angst, confusion and frustration.

Ideally it should be settable via `converse.initialize`, but it doesn't look like this is possible.

The webpack documentation gives an example of how you can set it "on the fly". https://webpack.js.org/guides/public-path/#on-the-fly
From what I can tell, this still won't let us set the path via `converse.initialize`, because the variable needs to be set as the bundle gets loaded.

**Comment by joudinet** [comment]
It looks like some people have found a workaround in the bug discussion related to this issue on webpack: https://github.com/webpack/webpack/issues/2776
In particular, I think this solution is what you're looking for: https://github.com/webpack/webpack/issues/2776#issuecomment-424719954
