### ISSUE TITLE
API for unread messages count

### ISSUE THREAD

**Issue by mreid0345** [conversejs/converse.js#1740]
I would like to formally request that you make an integer of count of unseen messages for a user accessible from _converse.api 

Were using converse.js as our chat with a few cusomizations built adjacent to the code.

I need to populate our other interface with number of unseen messages. Please advise

**Comment by antoniomorais360** [comment]
I am using Rambox and the count of unread messages it is very useful.Tks

**Comment by jcbrand** [comment]
You can do:
```
const contact = await _converse.api.contacts.get('friend@xmppserver.net');
const unread_messages_count  = contact.get('unread_messages');
```
