### ISSUE TITLE
Close button on chat windows for mobile

### ISSUE THREAD

**Issue by mreid0345** [conversejs/converse.js#1741]
Ive tried using the mobile version on my Moto G6 android. 

I click the controlbox to open chat window. chat window opens i send message. i click back button because there is no x, back button takes me out of converse.js chat page and back to where i was previously. Currently there is no way to get back to the controlbox on mobile. at least not on mine.

Please advise.

**Comment by licaon-kter** [comment]
What version exactly? Index setup? What browser?

**Comment by jcbrand** [comment]
> What version exactly? Index setup? What browser?

I'm going to start closing bug reports that don't use the relevant template, otherwise volunteers have to waste their time continuously asking these questions.
