### ISSUE TITLE
5.0.4 doesn't show font icons

### ISSUE THREAD

**Issue by t2d** [conversejs/converse.js#1751]
**Describe the bug**
When using  `https://cdn.conversejs.org/5.0.4/dist/converse.min.css` and `https://cdn.conversejs.org/5.0.4/dist/converse.min.js` no icons are shown. If I use 5.0.3, everything runs smoothly.

**To Reproduce**
1. Install via Github releases (https://conversejs.org/docs/html/quickstart.html#option-2-download-the-builds-from-github)
2. Load current version of `converse.min.[css|js]` and put into `/dist`
3. You don't see any icons

**Screenshot**
![Screenshot from 2019-10-09 17-19-47](https://user-images.githubusercontent.com/1834580/66495595-c6ff9a00-eab9-11e9-8d8b-11504395de81.png)

**Expected behavior**
I should see icons.

**Environment (please complete the following information):**
 - Desktop or Mobile - both
 - Browser: Safari, FF, Chrome
 - Converse.js version: 5.0.4

**Additional context**
[index.html.j2](https://paste.systemli.org/?5cb456ae5bed315d#G9U6g1brjwFpcqGZZRjRDHE4uZcWXTgYQa2HaooJSyBw)

**Comment by jcbrand** [comment]
@t2d: Can you please check again? I've updated the paths in the builds served by the CDN. You'll need to do a hard refresh of your browser (<ctrl>-<shift>-r).

**Comment by t2d** [comment]
Much better now. Thanks!

**Comment by mase76** [comment]
I still cannot see the icons. I am using the prosody module, but I serve my own cdn. Neither built myself, nor downloaded a release build shows icons.

**Comment by jcbrand** [comment]
@mase76: If you're serving your own CDN, then you need to set the ASSET_PATH when you build your own bundle.

See item 10 here: https://github.com/conversejs/converse.js/blob/master/RELEASE.md

**Comment by mase76** [comment]
Now I am with the release prebuild. I get emojis and all other symbols when I specify the assets_path in the prosody options for mod_conversejs. However still no font icons.

**Comment by t2d** [comment]
Did you copy the files in the `/dist` dir? This path is built-in hard, I think.

**Comment by mase76** [comment]
The files are already in dist in the release build.

**Comment by jcbrand** [comment]
@mase76 Check the network tab in the browser console to see at which path Converse is trying to load the webfonts. That can help you debug what's going on.

**Comment by mase76** [comment]
I solved it by adding this to the location in nginx:

location ~* \.(eot|ttf|woff|woff2)$ {
    add_header Access-Control-Allow-Origin *;
}
