### ISSUE TITLE
Option hide list of occupants

### ISSUE THREAD

**Issue by krot3232** [conversejs/converse.js#1753]
If the group in more 10,000 people, I had to finish the plugin so as not to request all the occupants.
It would not be bad if you added the option to request participants or not, and show|hide the participants panel (div occupants col-md-3 col-4 -> add class hidden).

**Comment by jcbrand** [comment]
Thanks for the feedback.

MUC occupants aren't requested, they're sent automatically by the XMPP server as soon as you enter the MUC.

If you don't want the occupants to be sent, then you'll need to update the XMPP server.

Concerning hiding the occupants sidebar, as you've shown it's very easy to do this via CSS, I therefore don't think it's necessary to have yet another configuration option.
