### ISSUE TITLE
Messages not shown on Mobile (Chrome/Safari)

### ISSUE THREAD

**Issue by ThoreKr** [conversejs/converse.js#1757]
When trying to use converse on mobile devices (5.0.4) Chrome as well as Safari do not open any MUC channels. Instead it keeps showing the list of contacts and rooms.
When tapping on the room name the keyboard opens and apparently messages are sent to the room but you can not open the view mode with the content of a room.

This issue occurs on chrome and safari and only on mobile devices.
When requesting the desktop version the room content is visible.

Firefox behaves as expected, showing the room content when tapping on a room name.

![image](https://user-images.githubusercontent.com/5465291/66700474-12e85400-ecf1-11e9-988e-db4c1b25da2a.png)

**Environment (please complete the following information):**
 - Mobile
 - Browser: Chrome (77.0.3865.92), Safari 13
 - Converse.js version 5.0.4

**Additional context**
Since upgrading to 5.0.4 chrome logs no connection errors any more. Before we were blocked by #1712

**Comment by ThoreKr** [comment]
@jcbrand Thank you for fixing, is there a rough schedule for a release?

**Comment by jcbrand** [comment]
>  is there a rough schedule for a release?

No. The next release contains many breaking changes which need to first stabilize and I want to add more breaking changes before the the release.
