### ISSUE TITLE
Demo cannot load due to require in JS code

### ISSUE THREAD

**Issue by rugk** [conversejs/converse.js#1759]
**Describe the bug**
the demo at https://conversejs.org/demo/ is apparently broken…
The JS still has some NodeJS "require" in it… 

**To Reproduce**
1. Visit https://conversejs.org/demo/.

-> totally broken website (big SVG at the top)

**Expected behavior**
work

**Screenshots**
![grafik](https://user-images.githubusercontent.com/11966684/67044741-3e25d580-f12d-11e9-9060-b23c1d1994e7.png)

**Environment (please complete the following information):**
 - Desktop or Mobile? desktop
 - Browser: Firefox 69
 - Converse.js version dunno, demo

**Additional context**
This issue tracker was hard to find from the website. Maybe make the link (thee is one, I guess?) more prominent… :thinking:

**Comment by jcbrand** [comment]
Thanks, should be fixed now.

**Comment by rugk** [comment]
Can confirm it works again.
