### ISSUE TITLE
Dark mode/theme

### ISSUE THREAD

**Issue by 2secslater** [conversejs/converse.js#1761]
**Is your feature request related to a problem? Please describe.**
I think that for folks like me who always use a dark mode/theme, the current static light theme can be eyesore.

**Describe the solution you'd like**
I, along with other people I would assume, would love it if there was a choice to switch between a light and dark mode.

**Comment by mreid0345** [comment]
Saw this and remembered
![Screenshot_20191113-133317](https://user-images.githubusercontent.com/55162602/68797491-51d43700-061a-11ea-8846-b1ca81db655f.png)

**Comment by poVoq** [comment]
https://gitlab.com/maxigaz/converse-dark
While maybe slightly outdated, this should work with the browser plugin and maybe also as a CSS overwrite in your index.html

**Comment by coughingmouse** [comment]
If this is implemented, the option to select according to the theme of the os should also be added (and be selected as default).
