### ISSUE TITLE
Passing username/password to PHP prebind code

### ISSUE THREAD

**Issue by MaidenRevenge** [conversejs/converse.js#1763]
Ok.. after ripping my hair out for two days, here we go.. I got this thing working if I put in static details, simply using the XmppPrebind class that was linked on your site, if the details of $username and $password is added MANUALLY inside the php file, it works beautifully, passes the login/password to all my tabs, re-logins in. However I have NO CLUE how to PASS anything *dynamically* to this script as the username and password I'm trying to extract always returns undefined or nothing within any callbacks/listens/waits. So this detail of it "working" is useless for anybody but me if I can only get it working with static details. Right now I have, what is probably the most hack way to TRY to do this as I've been banging my head against any reason or method to GET the username and password of the user TO the prebind URL, so I created this mess with no errors but no returned data for the username/password, it simply just won't get them so every opened new tab asks me to login again:

These values for the converse user/pass boxes will NOT pass as they read as undefined.
```javascript
$.ajax({
    'url': 'prebind_that_works_with_static_details/prebind.php?username=' + $("#converse-login-jid").val() + '&pass=' + $("#converse-login-password").val(),
    // Ideally, above, would be great to have these values already but they are returning undefined, so by the time initialize hits, we get nothing.
    'success': function(data) {
        data = JSON.parse(data);
        console.log(data);
        converse.initialize({
            authentication: 'prebind',
            prebind_url: 'prebind_that_works_with_static_details/prebind.php?username=' + $("#converse-login-jid").val() + '&pass=' + $("#converse-login-jid").val(),
            auto_login: true,
            prebind: true,
            rid: data.rid,
            sid: data.sid,
            jid: data.jid,
            bosh_service_url: 'proxy_bosh_url_that_works_great/http-bind',
            default_domain: 'xmpp_server',
            locked_domain: 'xmpp_server',
            keepalive: true,
            debug: false,
            whitelisted_plugins: ['converse-go']
        });
        console.log('SID: ' + data.sid);
        console.log('JID: ' + data.jid);
    }
});
```
of course, those SID and JID logs come out undefined. So I went further since nothing was passing. I just need to know what element, what callback, something to extract the username and password to pass to this thing when a xmpp user clicks "Login". So I tried to read directly from the login/password box and capture the event of CLICKING the login.. for some reason that won't trigger. It WON'T capture it. If I capture clicks on EVERY input and all my own non-converse website input's trigger the event, but not Converse's. Even inView jQuery library won't see Converse's elements when they are visible and this library works on everything else on my site (I use it to lazy loading images and other elements that trigger ajax).

converse-go plugin is a multitude of listeners of me trying to capture the event that finally sees the username and password to pass to the prebind_url, but I'm getting nothing right down the line. I can't get it to extract it from the text inputs at all until the page is fully loaded and even then when I try to capture the "login" click event it won't so even having the info isn't helping at that point.

```javascript
_converse.api.waitUntil('pluginsInitialized').then(() => { 
```
Returns nothing w/ converse user/pass boxes rather than 'undefined' like the previous callbacks
```javascript
_converse.api.listen.on('clientConfigInitialized', () => {
```
Pretty sure this isn't triggering
```javascript
console.log('Pass1: ' + _converse.password); 
```
Nothing
```javascript
_converse.api.listen.on('connecting', function (data) {
```
Nothing

I have some listeners outside of the plugin, but nothing
```javascript
window.addEventListener('controlBoxPaneInitialized', function() {
```
```javascript
window.addEventListener('converse-loaded', function() {
```
All of these are just trying to read 
```javascript
console.log('username='+$("#converse-login-jid").val()+' Pass='+$('#converse-login-password').val());
```
Undefined all the way down. If I wait for the page to load, my saved details for login show up in the browser's devtools console by simply typing in $("#converse-login-jid").val()+' Pass='+$('#converse-login-password').val()

So at that point, they exist. If I could GET those details by the time a user clicks LOGIN in converse, then I could pass the details to the prebind, seems like THAT would work but for the life of me I cannot get converse to agree to give me these details or some click event for the login button to read those details before we try to get the initial prebind information so I can create something for those details to be repetitively passed. I'm reading through the source, trying to find the one event that can trigger this for me and I'm going nuts now. :P Almost none of this code matters because I cannot get the details the user provides to pass to the prebind_url.

For no reason I'll add some of my debugging stuff from that plugin and listener functions outside of it.
```javascript
window.addEventListener('controlBoxPaneInitialized', function() {
    console.log("Controlboxpane Init");
    console.log('cBI: username=' + {
        $xuser
    } + ' Pass=' + {
        $xpass
    });
});
window.addEventListener('converse-loaded', function() {
    console.log("Loaded converse");
    console.log('cL: username=' + {
        $xuser
    } + ' Pass=' + {
        $xpass
    });
});

converse.plugins.add('converse-go', {
    initialize() {
        const {
            _converse
        } = this;
        window._converse = _converse;
        _converse.api.waitUntil('pluginsInitialized').then(() => {
            console.log("Plugins Initialized");
            console.log('plInit: username=' + {
                $xuser
            } + ' Pass=' + {
                $xpass
            });
        });
        _converse.api.listen.on('clientConfigInitialized', () => {
            console.log("clientConfig Initialized");
            console.log('ccI: username=' + {
                $xuser
            } + ' Pass=' + {
                $xpass
            });
        });
        console.log(this);
        console.log('Pass1: ' + _converse.password);
        //console.log('Pass2: ' + _converse.connection.pass);


        _converse.api.listen.on('connecting', function(data) {
            console.log("Connecting");
            console.log(data);
        });
        console.log('PluginLaunched: username=' + {
            $xuser
        } + ' Pass=' + {
            $xpass
        });
    }
});
```

**Comment by MaidenRevenge** [comment]
I'd like to mention too, if I manually pass what I *want* to pass in the username/password (i.e. /prebind.php?username=test&pass=test) $_GET to the backend php xmpp prebind file, it does work. Same as having my details in there static. So once that is done, it just needs the initial details to pass to the prebind php file. After that I create a cookie, which right now might not be the slickest path but it's the one I'm going for right now as I can further encrypt the cookie and give it back to the user that way instead. Right now it's just base64 holding both values in a serialized array. I simply can't figure out what step GETS the details to USE with the prebinding. Sorry if I'm reiterating, but I'm at this point where I'm kinda confused why these details are so difficult to nail down and I wanna make sure I'm making it clear I just wanna basically send the user/pass from the login procedure to pass to the prebind.php file.

**Comment by jcbrand** [comment]
Please fix the formatting in your post

**Comment by jcbrand** [comment]
This issue tracker is not for general support, it's for bug reports and feature requests.

I've written that last sentence probably a dozen times already in this tracker. That said, I'll try to give you some advice.

Looks like you're trying to let the user log in and then send those credentials to the backend so that they can be sent to a prebind script. This is unsafe (the password is being sent as part of the URL, making it readable whenever the URL gets logged anywhere) and totally unnecessary.

Prebind is meant for server-side authentication when you **already** have the credentials, not when you're getting the credentials client-side. Also, it's BOSH-only and it's probably better to start using websockets instead.

If you have a custom login form, and want to log the user in with the credentials entered there, then you can just pass the username and password to `converse.initialize` via the [jid](https://conversejs.org/docs/html/configuration.html#jid) and `password` options, together with `auto_login` which I see you already set to `true` (but which doesn't make sense when you're using prebind).

If the user is not entering the full JID, but something from which the JID can be derived, then you of course need to do that first before passing the value to `converse.initialize`.

**Comment by jcbrand** [comment]
Also, if you need support with Converse, you can hang out in our MUC: discuss@conference.conversejs.org

You can join by clicking here:
https://inverse.chat/#converse/room?jid=discuss@conference.conversejs.org

It might take a while before someone (often me) responds, so it's good to just generally hang out there for a while instead of just asking a question and then leaving 5 minutes later.

**Comment by MaidenRevenge** [comment]
Sorry, first rodeo asking for help here. I added my debugging plugin, sorry if it's ugly. It was flattened cuz I have a method going w/ PHP EOB echo and it hates pretty code (crashes it) but funnily useful for formatting when you don't want too much ".." concat but use {$var} and hash it out pretty raw. *shrug*

**Comment by jcbrand** [comment]
Unfortunately I don't have the time and capacity to help everyone who struggles with setting up or integrating Converse. I'm riding on the edge of burnout since months already as it is.
