### ISSUE TITLE
Error when rebuild the dist files with make dist

### ISSUE THREAD

**Issue by PIWAL** [conversejs/converse.js#1768]
Hi everyone,
I am using converjs 5.0.4 under ubuntu 18.04
I am trying to rebuild the dist files with make dist. But I have some errors when try to rebuild the dist files from converse.js source code.
Here are the errors I am getting.

`ERROR in ./sass/converse.scss (./node_modules/css-loader/dist/cjs.js??ref--9-1!./node_modules/postcss-loader/src!./node_modules/sass-loader/dist/cjs.js??ref--9-3!./node_modules/mini-css-extract-plugin/dist/loader.js!./node_modules/css-loader/dist/cjs.js??ref--12-1!./node_modules/postcss-loader/src!./node_modules/sass-loader/dist/cjs.js??ref--12-3!./sass/converse.scss)
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: ENOENT: no such file or directory, scandir '/home/pessek/Downloads/converse.js-5.0.4-/converse.js-5.0.4/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:904:18)`

`ERROR in ./node_modules/@converse/headless/i18n.js
Module not found: Error: Can't resolve '../../locale' in '/home/pessek/Downloads/converse.js-5.0.4-/converse.js-5.0.4/node_modules/@converse/headless'`

`ERROR in ./node_modules/@converse/headless/converse-emoji.js
Module not found: Error: Can't resolve './emojis.json' in '/home/pessek/Downloads/converse.js-5.0.4-/converse.js-5.0.4/node_modules/@converse/headless'`

`ERROR in ./node_modules/@converse/headless/templates/field.html 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <field var="{{{o.name}}}">
| {[ if (o.value.constructor === Array) { ]}
|     {[ o.value.forEach(function (arrayValue) { ]}<value>{{{arrayValue}}}</value>{[ }); ]}
 @ ./node_modules/@converse/headless/utils/form.js 10:0-48 31:8-17
 @ ./src/converse-register.js
 @ ./src/converse.js
 @ ./src/entry.js
`

`ERROR in ./node_modules/@converse/headless/templates/vcard.html 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <vCard xmlns="vcard-temp">
|     <FN>{{{o.fn}}}</FN>
|     <NICKNAME>{{{o.nickname}}}</NICKNAME>
 @ ./node_modules/@converse/headless/converse-vcard.js 11:0-47 232:57-66
 @ ./node_modules/@converse/headless/headless.js
 @ ./src/converse.js
 @ ./src/entry.js
`
`ERROR in ./sass/converse.scss (./node_modules/css-loader/dist/cjs.js??ref--12-1!./node_modules/postcss-loader/src!./node_modules/sass-loader/dist/cjs.js??ref--12-3!./sass/converse.scss)
    Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
    Error: ENOENT: no such file or directory, scandir '/home/pessek/Downloads/converse.js-5.0.4-/converse.js-5.0.4/node_modules/node-sass/vendor'
`

Regards,

**Comment by bhattaxay** [comment]
@PIWAL Just download the .zip of converse js and go to inside directory path in terminal where you have extract the .zip of converse.js and just simply run the `make dist` command. After make dist just simply run the `make dev` command. It will run. And still it will not run than try with `npm install` command. It will definately work.
