### ISSUE TITLE
_converse.api.contact.add(jid, nick) fails, says not a function

### ISSUE THREAD

**Issue by mreid0345** [conversejs/converse.js#1772]
**Describe the bug**

_converse.api.contacts.add('matthew711' + '@' + BASE_URL, 'Matthew Reid'); throws

 Uncaught (in promise) TypeError: e.RosterContacts.addAndSubscribe is not a function
    at Object.add (converse-roster.js:1072)

**To Reproduce**
1. converse-headless build js
2. init is as follows:
        converse.initialize({
          trusted: true,    
          auto_away: 300,
          allow_chat_pending_contacts: false,
          auto_reconnect: true,
          auto_login: 'true',
          message_archiving: 'always',
          allow_logout: true, // No point in logging out when we have auto_login as true.
          allow_muc_invitations: false, // Doesn't make sense to allow because only
          allow_contact_requests: false, // Contacts from other servers cannot,
          authentication: 'login',
 	      credentials_url: '
          bosh_service_url: '
          default_domain: BASE_URL,
          locked_domain: BASE_URL,
          keepalive: false,
	      debug: false,
          play_sounds: true,
          show_controlbox_by_default: true,
          strict_plugin_dependencies: false,
          notification_icon: '/images/logo.svg',
          notification_delay: 5000,
          show_desktop_notifications: true,
          show_controlbox_by_default: true,
          allow_registration: false,
          autocomplete_add_contact: false,
          archived_messages_page_size: 200,
          /*enable_smacks: true,,*/
          allow_message_corrections: 'last',
          message_carbons: true,
          sounds_path: '/sounds/',
          sticky_controlbox: true,
          time_format: 'hh:mm a',
          whitelisted_plugins: ['chat-head'],                 
        });
3. when attempting to run _converse.api.contact.get() it is working fine and im not having issues,
 however when running _converse.api.contact.add(jid, nick) from the same scope, it fails.
4.  Uncaught (in promise) TypeError: e.RosterContacts.addAndSubscribe is not a function
    at Object.add (converse-roster.js:1072)

**Expected behavior**
Im expecting it to add a contact to the contact list so that when i do launch the fullscreen chat, it is on the contact list

**Environment (please complete the following information):**
 - Desktop
 - Browser Chrome,
 - Converse.js version [5.0.4]

**Comment by jcbrand** [comment]
Thanks, should be fixed now in master.

**Comment by mreid0345** [comment]
i got the code to fire with
_converse.RosterContacts.prototype.addAndSubscribe(jid, nick); but now it says it cant find the _converse.api.sendIQ? i don't know why i have to use .prototype. it wouldn't work without it.

**Comment by mreid0345** [comment]
perfect thank you just got your message
