### ISSUE TITLE
converse-headless.min.js:92 Uncaught TypeError: I.a.patch is not a function

### ISSUE THREAD

**Issue by mreid0345** [conversejs/converse.js#1773]
**Describe the bug**
Throwing an error on build I.a.patch 

I did a fresh git pull of the whole converse.js repo to my ubuntu
I copied node_modules that i was working with.
I did a webpack --config webpack.headless.js
No errors finished everything
I copied the new 570kb ish headless build to my dev server
ran my build and its not reading converse object for my init because of the following error

converse-headless.min.js:92 Uncaught TypeError: I.a.patch is not a function
    at Module.<anonymous> (converse-headless.min.js:92)
    at i (converse-headless.min.js:1)
    at converse-headless.min.js:1
    at converse-headless.min.js:1

**Expected behavior**
the headless build i was using before was working fine with the new plugin and _converse.api.contacts.get() so i know it was working fine with the last 300kb version i had, i know there have been a lot of changes my build is from around 10/21
Thanks in advance

 - Desktop 
 - Browser Chrome
 - Converse.js version [ 5.4.0]

**Comment by jcbrand** [comment]
Can you please try with the non-minified build so that we can get a better traceback?

**Comment by mreid0345** [comment]
yes doing it now, there is no headless unminified so ill use converse.js and see if that gives me the same error. unless theres a webpack config i could build that will have headless unminified?

**Comment by mreid0345** [comment]
![image1](https://user-images.githubusercontent.com/55162602/68143122-64ea5700-fef6-11e9-9293-e312f63e6f75.png)

This is what im getting in my browser::
bootstrap:63 Uncaught (in promise) TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (bootstrap:63)
    at __webpack_require__.t (bootstrap:161)
    at async Object.initialize (converse-muc.js:1900)

**Comment by mreid0345** [comment]
this is w /dist/converse.js

**Comment by jcbrand** [comment]
That error looks like something unrelated. I have a suspicion the `patch` error is due to this: https://github.com/conversejs/converse.js/blob/530e29810d9e955f6476c44fc106f68e76d2f57c/src/headless/converse-core.js#L29

You should run `make dev` again to get the latest version of  Backbone.BrowserStorage

**Comment by mreid0345** [comment]
its working now thank you
