### ISSUE TITLE
backbone.js:2083 Uncaught (in promise) Error: A "url" property or function must be specified

### ISSUE THREAD

**Issue by mreid0345** [conversejs/converse.js#1774]
**Describe the bug**
crashing under current config, still runs after dom crash but is erroring looking for a url of somekind here.

**To Reproduce**
init:
 converse.initialize({
          trusted: true,    
          auto_away: 300,
          allow_chat_pending_contacts: false,
          auto_reconnect: true,
          auto_login: 'true',
          message_archiving: 'always',
          allow_logout: true, // No point in logging out when we have auto_login as true.
          allow_muc_invitations: false, // Doesn't make sense to allow because only
          allow_contact_requests: true, // Contacts from other servers cannot,
          authentication: 'login',
 	      credentials_url: '
          bosh_service_url: '
          default_domain: BASE_URL,
          locked_domain: BASE_URL,
          keepalive: false,
	      debug: false,
          play_sounds: true,
          show_controlbox_by_default: true,
          strict_plugin_dependencies: false,
          notification_icon: '/images/logo.svg',
          notification_delay: 5000,
          show_desktop_notifications: true,
          show_controlbox_by_default: true,
          allow_registration: false,
          autocomplete_add_contact: false,
          archived_messages_page_size: 200,
          /*enable_smacks: true,,*/
          allow_message_corrections: 'last',
          message_carbons: true,
          sounds_path: '/sounds/',
          sticky_controlbox: true,
          time_format: 'hh:mm a',
          whitelisted_plugins: ['chat-head'],                 
        });

2. the only command launching by default is _converse.api.contacts.get()

3.attached is screenshot

**Expected behavior**
Everything else is running really well and headless is working with my api calls otherwise, thank you

Please Note: i have ran 'make dev' two days ago, im working with the latest code
**Screenshots**
![image 11](https://user-images.githubusercontent.com/55162602/68308476-8ec88880-0072-11ea-8ad1-ed72e0fa6112.png)

**Environment**
 - Desktop
 - Browser [Chrome]
 - Converse.js version [e.g. 5.4.0] repo date 11/2/2019

**Additional context**
i see its backbone.js crashing, if there is something i should be doing on my web pack builds let me know but at this point im just using make dev

thanks

**Comment by jcbrand** [comment]
I had a look at the code, I don't see any obvious issues.

That error is very low-level and can happen for a variety of reasons. Often it's related to a timing issue. Check whether the problem goes away when you call `_converse.api.contacts` later.
