### ISSUE TITLE
Input field contains a newline after sending message

### ISSUE THREAD

**Issue by Zash** [conversejs/converse.js#1775]
**Describe the bug**
After typing out a message (on a single line) to a chatroom and pressing Enter to send it, the input field ends up with a single newline and the cursor on line 2.

**To Reproduce**
1. Type message
2. Press Enter
3. Observe cursor on line 2

**Expected behavior**
After sending a message the input field should be empty.

**Screenshots**

**Environment (please complete the following information):**
 - Desktop Windows 10
 - Firefox 70.0.1
 - Private Window
 - Converse.js version 5.0.4

**Not** observed on Firefox 68 ESR on Debian.

Unclear how reproducible this is.

**Comment by jcbrand** [comment]
Haven't seen this in a long time. Closing.
