### ISSUE TITLE
how to auto save GROUPCHATS to server?

### ISSUE THREAD

**Issue by zmhweb** [conversejs/converse.js#1776]
I want to created the GROUPCHATS at the same time save GROUPCHATS to server。 So how to auto save GROUPCHATS to server?

**Comment by jcbrand** [comment]
Groupchats can only be saved per user, not globally and that's done by bookmarking them. There isn't currently a way to automatically bookmark groupchats.

**Comment by zmhweb** [comment]
> Groupchats can only be saved per user, not globally and that's done by bookmarking them. There isn't currently a way to automatically bookmark groupchats.

I modified the source code。
![image](https://user-images.githubusercontent.com/16442336/68479945-7b820c80-026e-11ea-8b8d-b55461e0a497.png)

**Comment by jcbrand** [comment]
This makes me realise that we still want to update the code to automatically create a bookmark when a chat is opened and set `auto_join` to true. When it gets closed, we'll keep the bookmark but at `auto_join` to false.

Is this similar to what you want?

**Comment by zmhweb** [comment]
> This makes me realise that we still want to update the code to automatically create a bookmark when a chat is opened and set `auto_join` to true. When it gets closed, we'll keep the bookmark but at `auto_join` to false.
> 
> Is this similar to what you want?

yes. Users do not need to enter Groupchats addresses every time they enter a room. Saved in the database at the beginning of creation.
