### ISSUE TITLE
ejabberd 18 vs OMEMO 5.0.4

### ISSUE THREAD

**Issue by dscaravaggi** [conversejs/converse.js#1777]
I'm a newbie but I did not found the exact combination of
ejabberd.yml & conservejs initialization script for enbling OMEMO .

ejabberd is version: 18.12.1-2 arch debian buster

` converse.initialize({
        bosh_service_url: "https://********/bosh/", // Please use this connection manager only for testing purposes
        show_controlbox_by_default: true,
        whitelisted_plugins: [
                "converse-chatview",
                "converse-pubsub", "converse-profile",
                "converse-omemo"
        ]
    });
`

**Comment by licaon-kter** [comment]
Gist of your config?

**Comment by dscaravaggi** [comment]
> Gist of your config?
> 
> This section specifically
> https://github.com/processone/ejabberd/blob/master/ejabberd.yml.example#L182

here it is: https://gist.github.com/dscaravaggi/9d6d4488592a2f041a490a367efd2869

**Comment by licaon-kter** [comment]
Could you setup your index.html like this: https://gist.github.com/licaon-kter/54d4656cc753b98e1dc0d81a59a73faa ? _(scroll to the right section, change only domain.tld and replace websockets with bosh, fix scripts paths on top)_

Your ejabberd config looks ok, you don't have to comment out that section: https://gist.github.com/dscaravaggi/9d6d4488592a2f041a490a367efd2869#file-ejabberd-yml-L263 as it's even better to have it there.

**Comment by dscaravaggi** [comment]
@licaon-kter thanks for your support,

after some debugging I found that for some reason the browsers are generating new OMEMO fingerprint.
I switched from BOSH to WS but I got same problems.
This week I will try to debug a session with full version installed locally instead of using cdn minified version.

**Comment by Echolon** [comment]
@dscaravaggi long time no see. Have you experienced the issue again?

**Comment by dscaravaggi** [comment]
> @dscaravaggi long time no see. Have you experienced the issue again?

Sorry for my late answer, the problem disappeared after upgrading ejabberd
