### ISSUE TITLE
Version 5.0.x and Libsignal (documentation)

### ISSUE THREAD

**Issue by danjde** [conversejs/converse.js#1780]
H Devs,
in the newest releases seems that the Libsignal is picked up from "https://cdn.conversejs.org/3rdparty/libsignal-protocol.min.js"

So what does this change involve?
Is it still necessary to take the libsignal library from github?

`git clone https://github.com/signalapp/libsignal-protocol-javascript`

The following is a part of [your documentation](https://conversejs.org/docs/html/dependencies.html?highlight=omemo#dependencies):

> Libsignal
> 
> If you want OMEMO encryption, you need to load libsignal separately in your page.
> 
> For example:
> 
> <script src="3rdparty/libsignal-protocol-javascript/dist/libsignal-protocol.js"></script>
> 
> The reason libsignal needs to be loaded separately is because it’s released under the GPLv3 which requires all other dependent JavaScript code to also be open sourced under the same license. You might not be willing to adhere to those terms, which is why you need to decide for yourself whether you’re going to load libsignal or not.

Thanks for your wonderful work!!

Davide

**Comment by licaon-kter** [comment]
Necessary? Do as you wish...

**Comment by jcbrand** [comment]
It's the same version of libsignal, the one in the CDN is just there for convenience.

**Comment by danjde** [comment]
Well, but I just thought could be fine add two lines of explanation on this aspect for who approaches Converse.js/OMEMO documentation ;-)

**Comment by jcbrand** [comment]
@danjde: The documentation is editable for anyone who reads it and has a Github account.

In the top right you'll see a "Edit me on Github" link. You're invited to add an improvement to the docs.
