### ISSUE TITLE
Own nick not used in leftside info

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/converse.js#1784]
Open profile, set nick, in the left pane, near the avatar, still seeing the full JID instead.

HEAD (https://github.com/conversejs/converse.js/commit/e85afc9c7c74bb81c6b002897c56c0faef4ae399)

**Comment by bernard-ng** [comment]
@licaon-kter How do I **open profile** in conversejs ?

**Comment by licaon-kter** [comment]
Press you avatar/icon.

![click](https://user-images.githubusercontent.com/2282799/94815911-98758000-03ea-11eb-80e8-cdb8828108cf.png)

**Comment by bernard-ng** [comment]
I tried to reproduce the bug, it seems that it's already fixed, the value used is not the "nickname" but "full name".
**HEAD : [8ef3b10](https://github.com/conversejs/converse.js/commit/8ef3b10d39902ddbbd892770f212ada4aa0a8c08)**

![conversejs-screenshots (2)](https://user-images.githubusercontent.com/31113941/94817506-5e61a980-03fd-11eb-9d1a-c76bd6036191.png)

**Comment by licaon-kter** [comment]
It used to be nick...mmmkay
