### ISSUE TITLE
embedded mode on mobile shows on every page

### ISSUE THREAD

**Issue by rototom** [conversejs/converse.js#1786]
I configured converse.js to load only on a specific page on my website (contact) with the view "embedded" and the DOM on that page which works perfectly on every tested browser.
Unfortunatly on my mobile browsers (ff, brave, chrome) converse comes up on every page of my site.

**Comment by jcbrand** [comment]
Don't load the JavaScript on pages you don't want it loaded or at least don't call `converse.initialize`.
