### ISSUE TITLE
Make creating a new chatroom more user friendly.

### ISSUE THREAD

**Issue by guusdk** [conversejs/converse.js#1790]
When a user wants to create a new group chat with a number of its friends, the UX in 5.0.4 requires a user to have an understanding if XMPP fundamentals. If we can make "creating groupchats" easier for the novice user, it'll help Converse adoption.

(Note that I have zero experience with UX design, I'm just trying to imagine what novice users go through).

I think that most users would have no problem with getting started. There's a button with a plus sign, that feels like a natural way to add something.

![image](https://user-images.githubusercontent.com/4253898/69434739-7dec6800-0d3e-11ea-92d8-4e86206d7fc7.png)

So far, so good. I think that for people not familiar with XMPP, the screen that comes next is very confusing:

![image](https://user-images.githubusercontent.com/4253898/69434829-b0966080-0d3e-11ea-8a3c-bc6442dc5e57.png)

Most users will have no idea what address to fill out, and I suspect they give up.

I think we can improve things a lot by splitting the functionality, and replacing the one "+" button with two buttons

- a button to create a new chat.
- a  button to join an existing chat.

I don't think that there are many "power users" that are interested in creating a new, named MUC room. The dialog under the "create" button doesn't need an address at all. Let's just have a random JID for the room. What instead would be very useful is a way to add a list of people to invite into the new room, as that's generally what people want to do: create a group chat with other people. If that all goes into the first dialog, most users will have no problems creating a new chat, I believe.

The new button ("join") could still have the text input field for an address (which might be populated by auto-discovered rooms in the future, perhaps).

**Comment by Nyco** [comment]
Create/join channel (groupchat) #1593

**Comment by guusdk** [comment]
Well. yes. Do that. :)
