### ISSUE TITLE
auto_focus set to false only works on initial connection to MUC

### ISSUE THREAD

**Issue by poVoq** [conversejs/converse.js#1791]
**Describe the bug**
I am testing `auto_focus` set to false in view-mode `mobile` to prevent the on-screen keyboard popping up, and it seems to do the trick when I first connect to a MUC. However on subsequent switching to already opened MUCs it seem to fail.

**To Reproduce**
1. open mobile view mode in a mobile browser
2. open a MUC from a bookmark and see it work (no OSK pop up)
3. navigate back to the controlbox
4. click on previously opened MUC to re-enter and see the OSK pop up immediately

**Expected behavior**
OSK should really only be activate when the user clicks the chat input field

**Environment (please complete the following information):**
 - Desktop or Mobile? Mobile
 - Browser: Android Firefox and Ubuntu Touch Morph (chromium based)
 - Converse.js version: 5.0.5

**Comment by poVoq** [comment]
Any chance this could be fixed for 6.0?

Probably the most annoying bug on mobile right now :(

Thanks!

**Comment by jcbrand** [comment]
Why don't you try and see whether you can contribute a fix yourself?

**Comment by poVoq** [comment]
Well... for this one I wouldn't even know where to look. But yeah :(

**Comment by jcbrand** [comment]
Search through the code (for example with `grep`) for `auto_focus` and see where it's used. Most likely the necessary changes need to be made in converse-chatview.js or converse-muc-views.js.

**Comment by poVoq** [comment]
Thanks a lot!
