### ISSUE TITLE
Modal overlays do not have scrollbars

### ISSUE THREAD

**Issue by poVoq** [conversejs/converse.js#1792]
**Describe the bug**
On small screens (with limited vertical resolution) overlay modals like the profile are not usable as it is impossible to reach the "save and close" button at the bottom.

**To Reproduce**
1. Resize browser window
2. Click on click on profile overlay modal
3. Realize that there is no (optional) scrollbar

**Environment (please complete the following information):**
 - Desktop or Mobile? Both
 - Browser [e.g. Chrome, Firefox] Firefox
 - Converse.js version [e.g. 4.2.0] 5.0.5

**Comment by licaon-kter** [comment]
Like #1666 ?

**Comment by poVoq** [comment]
Yeah I think so, just in general.

This seems to work for me if I overwrite the CSS:

```
#conversejs .modal-body {
    overflow-y: auto;
    height: auto;
    max-height: 600px;
}
```

**Comment by jcbrand** [comment]
Should be fixed now, can you please confirm @poVoq?

**Comment by poVoq** [comment]
Ahhmm, I actually need to get around getting a working dev setup for ConverseJS :(
Right now I am working with the official releases only and thus can't test it easily.

**Comment by jcbrand** [comment]
> Ahhmm, I actually need to get around getting a working dev setup for ConverseJS

It's really not that hard, as long as you're using Linux or Mac.

Just run `make dev` and then `make watch`. Then open http://localhost:8008/dev.html

**Comment by licaon-kter** [comment]
Works for me.
