### ISSUE TITLE
TypeError: Cannot read property 'show' of undefined

### ISSUE THREAD

**Issue by mreid0345** [conversejs/converse.js#1796]
SecondLevelDomains.js:1 Uncaught TypeError: Cannot read property 'show' of undefined

**To Reproduce**
view_mode: mobile
click on the arrow in upper left that goes back, im running singleton and i believe it should be invisible, im going to display:none it for now but i thought you should know it should be hidden for singleton
click on arrow in upper left
see error screenshot

**Expected behavior**
this should be hidden for singleton

**Screenshots**
![ss](https://user-images.githubusercontent.com/55162602/69679420-b0af9c80-106d-11ea-8f33-4d1137e21407.png)

**Environment (please complete the following information):**
 -  Mobile
 - Browser [Chrome]
 - Converse.js version [5.0.4]
-singleton

Im just going to hide it for now

**Comment by jcbrand** [comment]
Thanks for reporting, should be fixed now.
