### ISSUE TITLE
Move MUC invite out of participants list and add web-invite link?

### ISSUE THREAD

**Issue by poVoq** [conversejs/converse.js#1797]
**Is your feature request related to a problem? Please describe.**
Currently the MUC invite feature is very cramped in the somewhat buggy MUC participant side-panel and does not work very well in embedded mode, and even worse in mobile view mode on small screen. It is also lacking a nice on boarding experience.

**Describe the solution you'd like**
Since it is already possible to configure this MUC invite input field, why not add an option to have it as a separate overlay modal or include it in the MUC info modal?

It would be also cool if it was combined with an easy way to create an onboarding link (XEP-0401 ?), i.e. something like this https://github.com/ge0rg/easy-xmpp-invitation

**Additional context**
I am working on a ConverJS based mobile app for Ubuntu Touch and since OMEMO encrypted group-chats need to be members-only, it would be good to have an easy to use invite option. However I had to disable this input field as it is not usable on small mobile screens.
For my specific case it would be better to be able to specify an external website for the easy onboarding link, as obviously the mobile app would not allow an integrated one, but for other setups it might be nice to have it build into ConverseJS.

**Comment by jcbrand** [comment]
I've moved the invite link into a modal. I'm working on also adding it to a dropdown menu instead of having it in the sidebar.

The easy XMPP invitation request should go into a separate ticket.
