### ISSUE TITLE
Group conversations issue Converse.js v5.0.4

### ISSUE THREAD

**Issue by danjde** [conversejs/converse.js#1800]
Hi Devs,
using Converse.js v5.0.4 from Firefox or Seamonkey or Chromium (Linux environment) there is a difficulty in group chats accessing.

In particular, the group chat is not automatically recognized, as it happens with other desktop clients, for example Dino.
I don't know if it is intentional or it may depend on a configuration problem. Maybe DNS record not properly configured?

ACTUAL CONFERENCE DNS RECORD

```
_xmpp-server._tcp.conference          1800 IN SRV    0 5 5269 server.3x1t.org.
_xmpp-server._tcp.conference          1800 IN SRV    0 5 5269 3x1t.org.
_xmpp-server._tcp.conference.server   1800 IN SRV    0 5 5269 server.3x1t.org.
_xmpp-server._tcp.conference.server    360 IN SRV    0 5 5269 3x1t.org.
```
Actually if I query the server at this address: server.3x1t.org or 3x1t.org obtain three group conversations:

```
upload.3x1t.org
server.3x1t.org
The 3x1t.org Jammer chatrooms server
```
But none due to the actual existing group chatroom.
Only if I go to "add a new group conversation" (plus sign) and entering the exact (server assigned) name of the group I can access it.

Please, could you tell me if do not automatically detect group conversations is the Converse.js normal behavior or if it could be depend by a dns misconfiguration (or something other)?

Many thanks!

Davide

**Comment by licaon-kter** [comment]
Your SRVs are rather odd....why not a single conference.3x1t.org domain instead?

**Comment by danjde** [comment]
Wonderful! 
The problem was "only" the follow missing DNS entry:

`_xmpp-server._tcp.conference          1800 IN SRV    0 5 5269 conference.3x1t.org.`

and consequently:

```
www.converse                           360 IN A      5.189.129.55
www.converse                           360 IN AAAA   2a02:c207:2023:4846:0000:0000:0000:0001
```

Now all groups are correctly detected!
..here we say: _"to get lost in a glass of water!"_

Many thanks again!

Davide
