### ISSUE TITLE
MUC - two upload icons available

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/converse.js#1806]
...and usable

HEAD (0082c0ce604853a11d030bb577dc2cffc227797f)
ejabberd HEAD
Firefox 70.0.1 or Vivaldi Snapshot

**Comment by jcbrand** [comment]
Yeah, I've noticed this as well.

**Comment by licaon-kter** [comment]
Not fixed for me in HEAD (0d8b3e18391581e7eadd003a930e5085be77270c)

**Comment by jcbrand** [comment]
I think the `if` statement must go after the asynchronous `supports` check.

**Comment by licaon-kter** [comment]
Better :)
