### ISSUE TITLE
Enabling clear_messages_on_reconnection causes missed messages

### ISSUE THREAD

**Issue by laszlovl** [conversejs/converse.js#1807]
**Describe the bug**
Using Converse 5.0.5, discovered with https://github.com/conversejs/converse-integration-tests

If you enable `clear_messages_on_reconnection`, MUC messages sent to you while you are offline/disconnected will go missing. My guess is that the `clear_messages_on_reconnection` code will clear some messages _after_ the MAM/Smacks/whatever code runs.

Thinking about this, I'm not sure if we still really need this option in the first place.

> For example, if you want to prevent the chat history from getting too long or if you want to avoid gaps in the chat history (for example due to MAM not returning all messages since the last cached message).

* To prevent the chat history from getting too long, it would be better to clear messages on Converse _initialization_ instead of _reconnection. That way there won't be any interactions with other code.

* The issue with MAM paging has since been fixed, afaik.

I currently use the following workaround to clear messages on Converse initizalization. Perhaps this can be added as a `clear_messages_on_initizalization` option?

```js
    var arr = [];

    for (var i = 0; i < localStorage.length; i++){
        if (localStorage.key(i).substring(0,23) == 'local/converse.messages') {
            arr.push(localStorage.key(i));
        }
    }

    for (var i = 0; i < arr.length; i++) {
        localStorage.removeItem(arr[i]);
    }
```

**To Reproduce**
Run https://github.com/conversejs/converse-integration-tests with `clear_messages_on_reconnection: true`.

```
:~/converse-tests$ ./test.py 
We are online! Waiting 1 second before commencing
Testing 25 online messages with disconnect delay 1..
Testing 25 offline messages with disconnect delay 1..
Traceback (most recent call last):
  File "./test.py", line 165, in checkMucMessage
    raise Exception("MUC message %s was not received" %(message))
Exception: MUC message b3df5df8b0e04a37b8f0f849b51ecd20 was not received

:~/converse-tests$ ./test.py 
We are online! Waiting 1 second before commencing
Testing 25 online messages with disconnect delay 0..
Testing 25 offline messages with disconnect delay 1..
Traceback (most recent call last):
  File "./test.py", line 165, in checkMucMessage
    raise Exception("MUC message %s was not received" %(message))
Exception: MUC message a299563b2a704ef7907842c90645dd60 was not received
```

**Comment by jcbrand** [comment]
> Using Converse 5.0.5...

Can you please test against the `master` branch instead of against the 5.0.5 release?
There are LOTS of changes to the `master` branch that aren't in the 5.0.5 release.

> To prevent the chat history from getting too long, it would be better to clear messages on Converse initialization instead of _reconnection. That way there won't be any interactions with other code.

No it won't be better because then whenever you reload the page you'll end up without any MUC history.

Are you 100% sure that SMACKS is enabled server side? It looks suspiciously like this is not the case.

**Comment by laszlovl** [comment]
I can still reproduce this with the current master. Always after sending 3 messages, which is probably not a coincidence since I have `archived_messages_page_size` set to 2.

> No it won't be better because then whenever you reload the page you'll end up without any MUC history.

MUC history after page reload can/should come from MAM. With the current `clear_messages_on_reconnection` option you'd also lose history on page reload if you didn't have MAM?

```
 ./test.py 
We are online! Waiting 1 second before commencing
Testing 1 online messages with disconnect delay 1..
Testing 1 offline messages with disconnect delay 4..
Testing 1 online messages with disconnect delay 3..
Testing 2 offline messages with disconnect delay 2..
Testing 1 online messages with disconnect delay 5..
Testing 3 offline messages with disconnect delay 2..
Traceback (most recent call last):
  File "./test.py", line 270, in <module>
    test.test_offline(start_count + i)
  File "./test.py", line 138, in test_offline
    self.checkMucMessages(muc_messages)
  File "./test.py", line 177, in checkMucMessages
    self.checkMucMessage(message)
  File "./test.py", line 241, in checkMucMessage
    raise Exception("MUC message %s was not received" %(message))
Exception: MUC message 41b4e6af760444a6abb05349e938e9f5 was not received


 ./test.py 
We are online! Waiting 1 second before commencing
Testing 1 online messages with disconnect delay 3..
Testing 1 offline messages with disconnect delay 1..
Testing 1 online messages with disconnect delay 5..
Testing 2 offline messages with disconnect delay 1..
Testing 1 online messages with disconnect delay 1..
Testing 3 offline messages with disconnect delay 2..
Traceback (most recent call last):
  File "./test.py", line 270, in <module>
    test.test_offline(start_count + i)
  File "./test.py", line 138, in test_offline
    self.checkMucMessages(muc_messages)
  File "./test.py", line 177, in checkMucMessages
    self.checkMucMessage(message)
  File "./test.py", line 241, in checkMucMessage
    raise Exception("MUC message %s was not received" %(message))
Exception: MUC message f6bb3a8e46514f618cc87713d75a16e8 was not received
```

**Comment by jcbrand** [comment]
> I can still reproduce this with the current master. Always after sending 3 messages, which is probably not a coincidence since I have archived_messages_page_size set to 2.

Have you tried with a larger page size?

If the XMPP server returns XEP-0059 RSM data in the MAM IQ result, then Converse should be querying for the next page.

> MUC history after page reload can/should come from MAM.

On some deployments of Converse users might navigate around in the site, causing page (re)loads every time. You don't want to do a fresh MAM query every time that happens.

> With the current clear_messages_on_reconnection option you'd also lose history on page reload if you didn't have MAM?

Yes, but that generally happens much less than page reloads.

**Comment by laszlovl** [comment]
> If the XMPP server returns XEP-0059 RSM data in the MAM IQ result, then Converse should be querying for the next page.

The exact same setup without `clear_messages_on_reconnection` works without problems, hence my hypothesis that they are paged correctly but cleared after they were retrieved. E.g., the clear_messages_on_reconnection() code is executed too late.

> > With the current clear_messages_on_reconnection option you'd also lose history on page reload if you didn't have MAM?
> 
> Yes, but that generally happens much less than page reloads.

Ah, I get what you mean, you're referring to BOSH + "embedded" viewmode. My usecase is mostly websockets + "fullscreen" where it's the opposite: reloads are rare (users will keep the tab open all day long) but reconnections are common (internet glitch, put laptop to standby). In that setup, it makes much more sense to clear on _reload_ than on _reconnect_.

**Comment by jcbrand** [comment]
> The exact same setup without clear_messages_on_reconnection works without problems, hence my hypothesis that they are paged correctly but cleared after they were retrieved. E.g., the clear_messages_on_reconnection() code is executed too late.

It really sounds like you don't have SMACKS enabled server-side. If that was the case, then this would make perfect sense.

I'll ask again, are you 100% sure it's enabled server-side?

> you're referring to BOSH + "embedded" viewmode

No, I'm referring to `overlayed` viewmode and it's irrelevant whether BOSH or websockets (with SMACKS) are used.

**Comment by laszlovl** [comment]
I'm 100% sure SMACKS is enabled server-side:

`<0.699.0>@mod_stream_mgmt:handle_resume:435 (websocket|<0.698.0>) Resumed session for XXX`

Additionally, if it weren't, I wouldn't see huge differences between `enable_smacks` true/false (#1808).

**Comment by jcbrand** [comment]
> I'm 100% sure SMACKS is enabled server-side:

OK. 

> hence my hypothesis that they are paged correctly but cleared after they were retrieved

Looking at the code, the MAM query is only made once `enteredNewRoom` has fired, which is definitely after `clear_messages_on_reconnection`.

It seems what's happening is that Converse doesn't request the next page. That's why I asked whether you've tried increasing the page size.

**Comment by jcbrand** [comment]
Can you open the inspector and look at debug logs in the browser that's being managed by Selenium?

If so, you can save the logs to a file and send that to me.

**Comment by jcbrand** [comment]
This is the test you're running right? https://github.com/conversejs/converse-integration-tests/blob/e4a6689b19ab6b8f1c3b2e3db741ddc075431cb1/test.py#L109

It looks to me like the result you're getting is correct and not a bug.

If you set `clear_messages_on_reconnection` to `true`, then when reconnecting or *when entering a MUC for the first time*, only the `archived_messages_page_size` will be fetched from MAM and no more.

That's why you only get 2 messages instead of 3, because the page size is set to 2.

Converse has the same behavior when you have `clear_messages_on_reconnection` set to `false` but enter a MUC for which you have zero cached messages. In this case, only the page size amount of messages will be fetched from MAM and no more.

So... I don't see how this is actually a bug.

**Comment by laszlovl** [comment]
I was working on getting some debug logging, but in that case I'll pause and reply here instead.

Increasing the mam pagesize definitely makes a difference but it just shifts the problem; with a pagesize of 10 the 11th message is missed, etc.

Good to see that we're getting somewhere, but this cannot be considered proper behavior, can it? If somebody sends 51 messages to a MUC while I'm offline (given the default value of archived_messages_page_size = 50), the 51th message is missing and permanently inaccessible?

**Comment by jcbrand** [comment]
To be clear, this is proper behaviour when entering a new MUC without locally cached history, or when entering a MUC with `clear_messages_on_reconnection`.

The missing message isn't permanently inaccessible. You can scroll up to load it. Now, granted... if you can't scroll because there aren't enough messages, then you have a problem, but that's a different issue :). To fix that, we need to add a clickable link to load older messages.

But for now, if the page size is large enough, the chat area is scrollable and you can load older messages by scrolling up.

**Comment by jcbrand** [comment]
> If somebody sends 51 messages to a MUC while I'm offline

What if 10 000 messages were sent in the MUC, do you really want to load all of them?

**Comment by laszlovl** [comment]
Right, right. :)

I said "permanently inaccessible" because I couldn't get to the remaining messages by scrolling or clicking anything either. I think I understand the rationale now; accessing them is actually possible if there are enough messages in the MUC to cause a scrollbar. Having `archived_messages_page_size` set to 50 is supposed to cause a scrollbar on most screens, alleviating the problem.

It's a bit tricky to rely on that. On my monitor I can fit 45 messages without needing to scroll, so I'm sure some people have a bigger monitor and are affected by this. Or perhaps someone set `archived_messages_page_size` to a lower value without realising this side effect. Maybe it could at least be documented there?

Also I'm not sure why `clear_messages_on_reconnection` would affect this behavior. So without `clear_messages_on_reconnection = true`, we *will* actually load 10.000 messages?

FWIW, I personally agree with the rationale for initial MUC joins, but after reconnecting I would expect to simply receive everything that was sent while I was offline.

**Comment by jcbrand** [comment]
> because I couldn't get to the remaining messages by scrolling or clicking anything either

Yes, so we need a clickable link to load more messages if the scrollbar doesn't show. I've been aware of this problem for years, but it never seemed to be high enough priority to do anything about it.

>  So without clear_messages_on_reconnection = true, we will actually load 10.000 messages?

If you have cached messages, then it will load all messages since the last cached message (i.e. filling the gap). This can also be problematic if the gap contains 10k messages... so long-term we need a proper strategy there as well.

If you don't have cached messages, then it will fetch the page size.

> FWIW, I personally agree with the rationale for initial MUC joins, but after reconnecting I would expect to simply receive everything that was sent while I was offline.

That is what happens (or at least is supposed to), when you have `clear_messages_on_reconnection` set to `false`.

**Comment by PrakashPaul** [comment]
> To be clear, this is proper behaviour when entering a new MUC without locally cached history, or when entering a MUC with `clear_messages_on_reconnection`.
> 
> The missing message isn't permanently inaccessible. You can scroll up to load it. Now, granted... if you can't scroll because there aren't enough messages, then you have a problem, but that's a different issue :). To fix that, we need to add a clickable link to load older messages.
> 
> But for now, if the page size is large enough, the chat area is scrollable and you can load older messages by scrolling up.

Hi,
in my case scrolling is working fine for one o one chat but not working for group chat, is there any suggestion for setting or code?
