### ISSUE TITLE
Using websocket without enable_smacks causes missed messages

### ISSUE THREAD

**Issue by laszlovl** [conversejs/converse.js#1808]
**Describe the bug**
Tested using Converse 5.0.5.

I'll keep this brief since this option is enabled by default since 4 days ago: https://github.com/conversejs/converse.js/commit/dffe3d1a2688c7e5a680a4a67348455ca5fd0aba

Having an option that causes missed messages is still dangerous though, so perhaps `enable_smacks` should be removed and smacks support should be impossible to disable?

**To Reproduce**
Run https://github.com/conversejs/converse-integration-tests against a converse 5.0.5 without `enable_smacks`.

```
~/converse-tests$ ./test.py 
We are online! Waiting 1 second before commencing
Testing 25 online messages with disconnect delay 0..
Traceback (most recent call last):
  File "./test.py", line 184, in checkPrivateMessage
    raise Exception("Private message %s was not received" %(message))
Exception: Private message cbf68f356f3d43b89b8cb4179c5c8992 was not received


~/converse-tests$ ./test.py 
We are online! Waiting 1 second before commencing
Testing 25 online messages with disconnect delay 0..
Testing 25 offline messages with disconnect delay 1..
Traceback (most recent call last):
  File "./test.py", line 165, in checkMucMessage
    raise Exception("MUC message %s was not received" %(message))
Exception: MUC message 5e26ebc21d4c432983983ca0a27b7fc0 was not received
```

**Comment by jcbrand** [comment]
> so perhaps enable_smacks should be removed and smacks support should be impossible to disable?

Yes, we can probably just remove it. However, currently the tests need `enable_smacks` set to `false`, otherwise we need to mock disco traffic for every single test.

So to remove this config setting we'd first have to figure out what to do with the tests.
