### ISSUE TITLE
Minimized chat in Mobile

### ISSUE THREAD

**Issue by joweste** [conversejs/converse.js#1811]
**Describe the bug**
I have used converse 3.3.4 because it is the latest version that works with my app.
When I use  converse.js in my desktop I can minimize your  icon and when the forms are reloaded
the chat  stays minimized.
But, when using in a mobile, after I minimize the chat clicking on minimize buuton and reload the form in the browser, the chat is not minimized any more.

**To Reproduce**
1. Using in a mobile, after I minimize the chat clicking on minimize button and reload the screen, the chat is not minimized any more.

**Expected behavior**
I´d like the chat stays minimized in mobile such as in desktop mode.

**Environment (please complete the following information):**
 - Desktop or Mobile: Desktop and Mobile
 - Browser: Chrome
 - Converse.js version 3.3.4

**Comment by jcbrand** [comment]
We're no longer doing any further work on the 3.x.x branch.
