### ISSUE TITLE
Don't download linked files or show a preview if you do

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/converse.js#1815]
[aTalk has an issue](https://github.com/cmeng-git/atalk-android/issues/84), so while I see a plain link in my chat (both Conversations and Converse)... looking at the browser logs/networking I see that Converse actually downloaded that file.

Converse HEAD (8b6c902c4cc93b9d2b0e2edb0fb325cf24dd83aa)

**Comment by jcbrand** [comment]
That's the browser doing that, nothing (AFAIK) that we can do about it.

Files are simply rendered as links: https://github.com/conversejs/converse.js/blob/da319604b6d20c296ff30abe63bf6fc435b2a1d0/src/templates/file.html#L1
