### ISSUE TITLE
debug: true not working

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/converse.js#1817]
HEAD (da319604b6d20c296ff30abe63bf6fc435b2a1d0)

I should have hundreds of events, yet true or false it's the same output in logs.

**Comment by jcbrand** [comment]
`debug` has been removed in favor of `loglevel` which can be set to `debug`.

**Comment by licaon-kter** [comment]
Where? https://m.conversejs.org/docs/html/configuration.html#configuration-settings

**Comment by jcbrand** [comment]
The docs are only updated with the next release. You can read the docs source code however.

https://github.com/conversejs/converse.js/blob/master/docs/source/configuration.rst#loglevel
