### ISSUE TITLE
Is there a function I can call to completely close converse.js?

### ISSUE THREAD

**Issue by vcmiranda** [conversejs/converse.js#1827]
I'm using converse.js with AngularJS. When a user logs in into the system, converse.js starts and it connects that user.
When a user disconnects from the system, this user is sent back to login page, however, converse.js doesn't disconnect, still showing chat box on login page.

How can I disconnect and completely shut it down converse.js? Is there a function like converse.initialize that I can use?

**Comment by jcbrand** [comment]
Try [_converse.api.user.logout()](https://conversejs.org/docs/html/api/-_converse.api.user.html#.logout)

**Comment by vcmiranda** [comment]
I did, it logs out, but it did not remove the tab from the bottom.

![image](https://user-images.githubusercontent.com/13787480/71785389-e29d1280-2fcc-11ea-81d0-9db219028477.png)

**Comment by jcbrand** [comment]
Logging out does stop execution. You can write some custom JavaScript that listens for the `logout` event and then removes or hides the toggle.
