### ISSUE TITLE
HTTP Upload  CORS error

### ISSUE THREAD

**Issue by PIWAL** [conversejs/converse.js#1830]
Hi,
I am getting `Cross-Origin Request Blocked` in my browser console when trying sending files. I enabled CORS in my apache. ([https://enable-cors.org/server_apache.html](https://enable-cors.org/server_apache.html)).
I got the same error under the following conversejs version. 6.0.0 and 5.0.5.

Here are some screenshots of my firefox console.

![Screenshot from 2020-01-13 08-58-32](https://user-images.githubusercontent.com/56436396/72240015-1edefd00-35e3-11ea-8e4d-21cec648d67d.png)

![Screenshot from 2020-01-13 08-58-58](https://user-images.githubusercontent.com/56436396/72240032-230b1a80-35e3-11ea-9666-ccea0960a80e.png)

![Screenshot from 2020-01-13 08-59-16](https://user-images.githubusercontent.com/56436396/72240041-269ea180-35e3-11ea-8e9e-b9351d77ea5a.png)

![Screenshot from 2020-01-13 08-59-44](https://user-images.githubusercontent.com/56436396/72240046-2c948280-35e3-11ea-8b0b-02c51c9dfaa2.png)

![Screenshot from 2020-01-13 08-59-47](https://user-images.githubusercontent.com/56436396/72240050-30c0a000-35e3-11ea-875f-0f0bfe5cf69d.png)

I really don't know what is going wrong.

Regards,

**Comment by jcbrand** [comment]
Looks like you need to enable CORS for the HTTP upload service as well.

Here's what we have in the documentation: https://conversejs.org/docs/html/troubleshooting.html?highlight=cors#file-upload-is-not-working

Sorry, I can't help you much more than that.

**Comment by PIWAL** [comment]
I have seen the documentation. But still have the same error.

**Comment by jcbrand** [comment]
The point is that the upload service is a separate service and you probably need to configure CORS for it as well and not just in Apache. Or perhaps you need to add another CORS configuration in Apache for the `/upload` path.

**Comment by PIWAL** [comment]
Thanks a lot @jcbrand. I just have to allow CORS in my ejabberd config. By adding the following code in `mod_http_upload`.

   ```
 custom_headers:
      "Access-Control-Allow-Origin": "*"
      "Access-Control-Allow-Methods": "HEAD, PATCH, DELETE, PUT, GET, POST, DELETE, OPTIONS"
      "Access-Control-Allow-Headers": "Content-Type, Origin, X-Requested-With, Accept"
```

Regards,

**Comment by jcbrand** [comment]
Thanks for letting us know what fixed it for you.
