### ISSUE TITLE
How to use "web manifest"

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/converse.js#1831]
It doesn't appear to be working even on conversejs.org, eg. Testing with Firefox Fennec on Android

**Comment by jcbrand** [comment]
I think we still need to register a service worker to cache resources in case the device is offline.

**Comment by licaon-kter** [comment]
Until then....I don't even have the actual action in the browser to make the site "an app like icon" which the manifest should trigger.

Do you have that?

**Comment by jcbrand** [comment]
Should that be on any browser or only on mobile? I'm still learning about PWAs

**Comment by licaon-kter** [comment]
I don't know for sure, I did see these on mobile for certain
