### ISSUE TITLE
Display vcard data in roster items

### ISSUE THREAD

**Issue by bhattaxay** [conversejs/converse.js#1835]
I have set the vcard data using [https://docs.ejabberd.im/developer/ejabberd-api/admin-api/#set-vcard](ejabberd_set_vcard) this api. Like user PHOTO and URL in vcard. 

I also able to get that data by [https://docs.ejabberd.im/developer/ejabberd-api/admin-api/#get-vcard](ejabberd_get_vcard) this api.

But i am not able to get those vcard data in roster_item.html page. Let me know how this is possible in converse js.

**Comment by Echolon** [comment]
I think this is a duplicate of https://github.com/conversejs/converse.js/issues/1130

**Comment by jcbrand** [comment]
#1130 is per MUC, and this one is per user.

**Comment by jcbrand** [comment]
This has been done long ago already.
