### ISSUE TITLE
Include list of public chats from search.jabber.network

### ISSUE THREAD

**Issue by ericschdt** [conversejs/converse.js#1841]
It's so comfortable to have a list of well known public MUCs like in Conversations to choose from, that I really miss having feature in Converse.js :)

You may also go to the website, but 1) you have to know about it, 2) it's still at least 5 clicks more. ;)

**Comment by deleolajide** [comment]
This feature request has also been mention [here](https://github.com/conversejs/community-plugins/issues/41)

**Comment by PawBud** [comment]
> This feature request has also been mention [here](https://github.com/conversejs/community-plugins/issues/41)

Thanks for bringing it to my attention, I believe @Echolon can decide which issue to close

**Comment by Echolon** [comment]
@PawBud happy to support your preparations!

**Comment by PawBud** [comment]
> @PawBud happy to support your preparations!

Thanks, btw, I believe the [HTTP API](https://search.jabber.network/docs/api) shall suffice, let me try to implement it.

**Comment by PawBud** [comment]
@Echolon 
<img width="504" alt="Screen Shot 2022-04-15 at 6 34 56 PM" src="https://user-images.githubusercontent.com/48093317/163574116-e4cd6681-62ad-48fe-80eb-a395fd9f79c2.png">
I feel like the menu would be displayed when the `show popular public groupchats` button is clicked

**Comment by jcbrand** [comment]
@PawBud: Thanks for looking into this. I think search.jabber.network should be used to provide autocomplete suggestions when you join a MUC via the add-chatroom modal, not via a button in the list-chatrooms modal that you show above.

Converse has a component `converse-autocomplete` that can be used to create inputs with auto-complete suggestions.

See here:
https://github.com/conversejs/converse.js/blob/7cb86638b5e2e7fd3832ceecf7b1a8fefeba51ef/src/shared/autocomplete/component.js#L7

You pass it a `getAutoCompleteList` function which returns the autocomplete suggestions.

Here's an example of where the `converse-autocomplete` component is being used:
https://github.com/conversejs/converse.js/blob/7cb86638b5e2e7fd3832ceecf7b1a8fefeba51ef/src/plugins/muc-views/templates/ad-hoc.js#L22

The goal for this ticket would be to replace the `input` in the add-modal template, with a `converse-autocomplete` component.
https://github.com/conversejs/converse.js/blob/7cb86638b5e2e7fd3832ceecf7b1a8fefeba51ef/src/plugins/muc-views/templates/add-muc.js#L37

**Comment by jcbrand** [comment]
@PawBud Can you please include a screenshot here of what the feature looks like?

**Comment by Echolon** [comment]
@jcbrand even this might be a different task: But showing a list of MUCs, maybe with its topic, might be a nice thing. Conversation does it, too.

**Comment by PawBud** [comment]
> @PawBud Can you please include a screenshot here of what the feature looks like?

![Screen Shot 2022-06-02 at 3 27 20 PM](https://user-images.githubusercontent.com/48093317/171605584-c9e087f1-fbcc-4cab-af63-32063d7d9a70.png)

something like this?

**Comment by jcbrand** [comment]
Looks like the suggestions are cut off? Perhaps a CSS z-index bug?

**Comment by licaon-kter** [comment]
So this has been implemented, right? https://github.com/conversejs/converse.js/commit/320f11f7957776d4055bd5bd9f5ca89fa51e4d96

Nice, but what I didn't see was a dialogue that informs me that
> Channel discovery uses a third party service called <a href="https://search.jabber.network">search.jabber.network</a>.<br><br>Using this feature will transmit your IP address and search terms to that service. See their <a href="https://search.jabber.network/privacy">Privacy Policy</a> for more information.

...or something like that :)

**Comment by jcbrand** [comment]
Where would you expect to see that?

**Comment by jcbrand** [comment]
I guess it could go into the `About` modal for Converse.

**Comment by licaon-kter** [comment]
Before accessing these external services, of course.

That text is from Conversations, which opens a dialogue that I can cancel if I don't agree.

> I guess it could go into the About modal for Converse

So my only choice is either accept s.j.n terms or NOT use Converse? Rather limiting and odd...

**Comment by jcbrand** [comment]
The query to search.jabber.network is made via XMPP, not HTTP, so your IP address isn't leaked to it.

**Comment by licaon-kter** [comment]
Oh, right, saw the console output but did not connect the dots. Then sorry for the noise.
