### ISSUE TITLE
Pre-fill nickname field at the "join MUC" popup

### ISSUE THREAD

**Issue by ericschdt** [conversejs/converse.js#1842]
If you want to join a MUC, you are asked to enter a MUC address and a nickname. Both are empty, but it would be convenient if the nickname field were pre-filled with the JID's nick (the part before the @).

**Comment by jcbrand** [comment]
You can use the [muc_nickname_from_jid](https://conversejs.org/docs/html/configuration.html#muc-nickname-from-jid) config setting.
