### ISSUE TITLE
Message history translation string is weird

### ISSUE THREAD

**Issue by wrooot** [conversejs/converse.js#1844]
#: dist/converse-no-dependencies.js:8866
msgid "No message history available."

The construction of this sentence is weird and is hard to translate (also don't know the context and where and when this is shown).

It feels like it should be "Message history is not available". But as No is in front, it sounds like there was an attempt to search and not one item of history was found. Then it should say that this error is a result of a failed search.

Is it for the whole server/service or just one conversation/room? I haven't seen this message in Converse.js when using it.

**Comment by jcbrand** [comment]
This message appears when you open a MUC and there aren't any history to display.

I think it's fine the way it is.
