### ISSUE TITLE
localization in 5.0.3

### ISSUE THREAD

**Issue by ColinRyan** [conversejs/converse.js#1853]
**Describe the bug**
I'm passing in a configuration option for localization but localization isn't taking effect.
I set i18n to 'fr' when I initalize but everything stays English and I don't get any explicit localization errors in the console. I'm using 5.0.3 via cdn.

**To Reproduce**
use 5.0.3 via cnd and initialize localization via the i18n config option with a value of 'fr'

**Expected behavior**
I expect to see french language

**Environment (please complete the following information):**
 - Desktop
 - Chrome
 - Converse.js version 5.0.3

**Comment by licaon-kter** [comment]
The browser asks for french? eg https://browserleaks.com/ip see under the Agent string

**Comment by ColinRyan** [comment]
no, when I initialize convers.js I'm setting the i18n option to fr explicitly so I'm expecting to see french language for the labels of the converse.js pop-up

**Comment by jcbrand** [comment]
Check in your browser console's Network tab whether the French translations are successfully downloaded.

**Comment by ColinRyan** [comment]
nothing. I see no request for the french translations. Actually I decided to debug a little and found that when it tries to fetch the translation an error occurs ```FATAL: __webpack_require__(...) is not a function```.

**Comment by jcbrand** [comment]
Why are you using 5.0.3? There are newer releases in the 5.x.x branch as well as a 6.0.0 release.

**Comment by ColinRyan** [comment]
When I attempt to use 5.0.5 or 6.0.0. I get ```Error: plugin with name "whatever" has already been registered!``` when I load my website so I've avoided updating.

**Comment by jcbrand** [comment]
I recommend figuring out what's going on there and seeing if the problem persists.

We're no longer fixing anything (except security bugs) on the 5.x.x branch
