### ISSUE TITLE
Modifying stanza

### ISSUE THREAD

**Issue by bhattaxay** [conversejs/converse.js#1854]
I am trying to modifying stanza as below but i can not find any way how to modify it. Can you help me out how to modify message stanza in converse Js. Below is my current stanza:

```
<message to="xyz@localhost" type="chat" id="20200124062540">
    <body>
        Hello
    </body>
</message>
```

And i want to add <subject></subject> in that as below how it is possible: 

`<message to="xyz@localhost" type="chat" id="20200124062540">
    <body>
        Hello
    </body>
    <subject>
        {"Type":"Text","Platform":"iOS","Username":"xyz","msgDetail":"{\"messageId\":\"LMi2E-CWd\",\"from\":\"abc\",\"messageDate\":\"1579870540\",\"message\":\"Hello\",\"thumbUrl\":\"\",\"username\":\"xyz\",\"to\":\"xyz@localhost\",\"messageType\":0,\"url\":\"\"}"}
    </subject>
</message>`

**Comment by jcbrand** [comment]
Use Strophe to create and/or modify stanzas.

**Comment by bhattaxay** [comment]
My i modify the file converse-chatview.js for modifying the stanza? Or it will be effect anywhere?

**Comment by jcbrand** [comment]
I'm sorry, I don't understand the question

**Comment by bhattaxay** [comment]
Hii Sorry for late reply. My question is if i want to modify the stanza than in which file i have to make changes in converse js?

**Comment by bhattaxay** [comment]
Right now i am trying to modify stanza  in converse-chatview.js but it's not help me. Also my offline messages are not saved on xmpp.

```if (message) {
                    /**
                     * Triggered whenever a message is sent by the user
                     * @event _converse#messageSend
                     * @type { _converse.Message }
                     * @example _converse.api.listen.on('messageSend', message => { ... });
                     */
                    message.attributes.subject = '{"Type":"Text","Platform":"web","Username":"'+message.attributes.nickname+'"}';
                    console.log( message );
                    _converse.api.trigger('messageSend', message);
                }```

**Comment by jcbrand** [comment]
Instead of setting `message.attributes.subject`, you should use `message.set('subject', 'XXX')`.

However, you shouldn't be sticking JSON into the subject, that sounds like a bad idea.

**Comment by bhattaxay** [comment]
Hii I am able to set the parameter as you said, but i am not getting this change in my stanza. I want to make my stanza as mentioned above in first comment. You suggest me to use strophe.js it is fine but i am not getting where strophe.js  is used inside our converse.js and where i have to make change for modifying the stanza.

**Comment by jcbrand** [comment]
Read the source code and the relevant documentation: https://conversejs.org/docs/html/development.html

This issue tracker is for bug reports and feature requests, it's not a support channel.

**Comment by bhattaxay** [comment]
Okay. Let me checkout with you given documentation.

**Comment by bhattaxay** [comment]
@jcbrand I read you documentation but that is reagarding to implementing new feature inside converse js. My qustion is i want to modify the message stanza as i mentioned above. Let me add the new one as below : How to add this line ```<subject>"Platform":"iOS","Type":"Text","Username":"xyz","msgDetail":"\"from\":\"131_user\",\"message\":\"ss\",\"messageDate\":1585292914,\"messageId\":\"WXtZr-205\",\"messageType\":0,\"thumbUrl\":\"\",\"to\":\"125_user\",\"url\":\"\",\"username\":\"xyz\"}"}</subject> ``` in my existing stanza

```
<message xml:lang='en'  to='125_user@localhost' from='131_user@localhost/Android'  type='chat'  id='WXtZr-205'     xmlns='jabber:client'>
  <archived by='125_user@localhost'
            id='1585292913857845'
            xmlns='urn:xmpp:mam:tmp'/>
  <stanza-id by='125_user@localhost'
             id='1585292913857845'
             xmlns='urn:xmpp:sid:0'/>
  <request xmlns='urn:xmpp:receipts'/>
  <active xmlns='http://jabber.org/protocol/chatstates'/>
  <body>ss</body>
  <subject>{"Platform":"iOS","Type":"Text","Username":"xyz","msgDetail":"{\"from\":\"131_user\",\"message\":\"ss\",\"messageDate\":1585292914,\"messageId\":\"WXtZr-205\",\"messageType\":0,\"thumbUrl\":\"\",\"to\":\"125_user\",\"url\":\"\",\"username\":\"xyz\"}"}</subject>
</message>
