### ISSUE TITLE
Various stability issues

### ISSUE THREAD

**Issue by laszlovl** [conversejs/converse.js#1858]
After running on cde6b093c057e453242dbb3e8a034163b344bd1d for over a week, me and other users are unfortunately still suffering from various stability issues; which I haven't been able to reproduce in https://github.com/conversejs/converse-integration-tests immediately.

I don't plan to tackle them by myself so I'm leaving this list as a reference, but if this is too vague, feel free to just close this.

1. Duplicated messages (repeatedly) when running on an unstable internet connection. Having Converse open for 2 hours on spotty train wifi resulted in (MUC and private) messages being repeated 5 to 10 times.
2. Unknown conditions cause Converse to "hang" after initial connection: ending up in a blue screen, and no MUC rooms/bookmarks are being loaded. Refreshing the page sometimes triggers this.
3. After having Converse open for a while (possibly after reconnects), online status of roster users is not in sync anymore.
4. After reconnecting, Converse jumps to a random different MUC/conversation than the one you had open before; sometimes to the bottom (most recent message) but sometimes to a random point in history.
5. HTTP upload button randomly disappears after a while (possibly after reconnects) for some - but not all - conversations.
6. I once ended up in a state where carbon copies were not displayed anymore while Converse was still functioning properly otherwise. Didn't investigate this one deeply.
7. Other reported cases of missing messages; could be due to carbons (see above) but not sure.

**Comment by jcbrand** [comment]
Putting a bunch of unrelated stuff (some of which is already covered in other tickets) in a single ticket isn't helping much.

Also, I've created bug report and feature request templates, please use those.
