### ISSUE TITLE
MUC nickname 'undefined' when using bookmark without nick element.

### ISSUE THREAD

**Issue by guusdk** [conversejs/converse.js#1860]
A user that joins a MUC using a bookmark that does _not_ have the optional `nick` element, has observed to be joining the room using the nickname 'undefined'.

Converse should check if the `nick` element is present in the bookmark. If not, it should either prompt for a nickname, or use the node-part of the JID.

**Comment by guusdk** [comment]
Additional nicknames to be considered: https://xmpp.org/extensions/xep-0172.html

**Comment by deleolajide** [comment]
https://github.com/conversejs/converse.js/blob/17b86f0491deb76f06481e4f3869403f5ebb5a43/src/headless/converse-bookmarks.js#L218

**Comment by Zash** [comment]
Also relevant: [ModernXMPP guides on MUC nicknames](https://docs.modernxmpp.org/client/groupchat/#user-nickname)
