### ISSUE TITLE
Empty avatar message on group join

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/converse.js#1886]
HEAD (bcbde0453073b48839f623c92032ad0de1fc0bcd)

![empty avatar](https://user-images.githubusercontent.com/2282799/74643436-9bc63f00-516c-11ea-884c-af5d3e9bcdbf.PNG)

In Firefox console it says:
`<canvas class="avatar chat-msg__avatar" height="36" width="36"></canvas>`

Did I miss place some image during the latest folders swapping ?

**Comment by jcbrand** [comment]
No, I've noticed this as well. Must be some kind of bug.

**Comment by licaon-kter** [comment]
Umm still seeing this on HEAD

![cnvrsempty](https://user-images.githubusercontent.com/2282799/74950747-7ac54e80-53f7-11ea-8a25-867fe5193a21.PNG)
