### ISSUE TITLE
Feature request: Allow pasting as JPG/Webp from clipboard

### ISSUE THREAD

**Issue by Gatak** [conversejs/converse.js#1887]
Currently, converse.js supports pasting images from the clipboard as `png` files. Sometimes it would be better to be able to paste as a lossy format like `jpeg` or `webp`, instead of having to save in an image editor, export as jpeg and then upload as file.

**Comment by jcbrand** [comment]
Maybe @Zash would be willing to take a look

**Comment by Zash** [comment]
I believe that the format is determined by either the browser, the source application that produced the clipboard data or the whatever OS component handles clipboards. Image conversion in JS isn't something I'm interested in doing.

**Comment by Gatak** [comment]
Fair enough. I only tried on Windows 10 on some different browsers. I noticed the png was very large when pasting a screenshot of an aerial view map on a 4K screen.
