### ISSUE TITLE
Bookmark management UI inconsistency - conflicting tooltips and icons

### ISSUE THREAD

**Issue by foss-** [conversejs/converse.js#1890]
**Describe the bug**
Conflicting bookmark icons and tooltip text for setting / removing bookmark for MUC.

**Expected behavior**
The bookmark icon should be identical as should be the tooltip.
From my limited I would expect the icons to be idencial. I can either add a bockmark or remove it and there should be one icon for each state (either filled or not filled).

**Current behavior**
Left icon: Filled Bookmark Icon, Tooltip "Create bookmark for this Groupchat" (translated)
Right icon: Unfilled Bookmark Icon, Tooltip "Remove bookmark for this Groupchat" (translated)

So which is it? Do I have a bookmark set for this room and remove is correct or is no bookmark set and I can add one?

**Screenshots**
![bookmark management](https://user-images.githubusercontent.com/5708172/75266133-2f91ae00-57f2-11ea-8740-58163a5eba90.png)

**Environment (please complete the following information):**
 - macOS 10.15.3
 - Firefox 73.0.1
 - Converse.js 6.0.1 on inverse chat

**Comment by jcbrand** [comment]
This should be fixed by now.
