### ISSUE TITLE
Build doesn't work on windows

### ISSUE THREAD

**Issue by Posnakidesd** [conversejs/converse.js#1895]
Based on Documentation provided https://conversejs.org/docs/html/index.html both Linux and Windows build should be possible.

**Describe the bug**
"webpack --config webpack.dev.js" on windows fails

**To Reproduce**
clone the repo in windows and run "npm install"

**Expected behavior**
Build should succeed similarly to Linux

**Environment (please complete the following information):**
 - Win 10
 - Converse.js version tryed both 5 and 6

**Additional context**
WARNING in ./locale/af/LC_MESSAGES/converse.po 1:0
Module parse failed: Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
\> # Afrikaans translations for Converse.js package.
| # Copyright (C) 2013 Jan-Carel Brand
| # This file is distributed under the same license as the Converse.js package.
 @ ./locale lazy ^\.\/.*\/LC_MESSAGES\/converse\.po$ namespace object ./af/LC_MESSAGES/converse.po
 @ ./src/headless/i18n.js
 @ ./src/converse-bookmark-views.js
 @ ./src/converse.js
 @ ./src/entry.js
.....
....

ERROR in ./src/templates/error_message.html
Module not found: Error: Can't resolve 'C:projectconverse.js
ode_moduleslodashescape.js' in 'C:\project\converse.js\src\templates'
 @ ./src/templates/error_message.html 1:16-79
 @ ./src/converse-chatview.js
 @ ./src/converse.js
 @ ./src/entry.js

**Comment by Posnakidesd** [comment]
It looks like the problem is in lodash-template-webpack-loader loader. This loader doesn't process the windows path separator correctly. I've replaced this loader with underscore-template-loader and it works fine now. But i haven't tested it in Linux.

**Comment by jcbrand** [comment]
@Posnakidesd: Please make a pull request and I'll test it in Linux.

**Comment by Posnakidesd** [comment]
@jcbrand Just want to emphasize that although the build was success I find some issue on template processing.

**Comment by Posnakidesd** [comment]
I've fount the following settings working for me. 

`
...
 var webpack = require('webpack');
...
           {
                test: /\.(html|svg)$/,
                exclude: /node_modules/,
                use: [{
                    loader: "underscore-template-loader",
                    query: {
                        escape: '\\{\\{\\{(.+?)\\}\\}\\}',
                        evaluate: '\\{\\[([\\s\\S]+?)\\]\\}',
                        interpolate: '\\{\\{(.+?)\\}\\}',
                        variable: 'o',
                        prependFilenameComment: __dirname
                    }
                }]
            },`

**Comment by mreid0345** [comment]
Idk if ull get this msg but im on win 10 and i use the new wsl. A sublayer
of ubuntu installed. It works amazimgly well

**Comment by mreid0345** [comment]
I have built it on windows 10

Install wsl ununtu sublayer. Do git to pull files

/mnt/c/

Thats the path to ur root

Thats all you need

**Comment by jcbrand** [comment]
I'm in the process of removing lodash templates with lit-html.

This might still take a while, but I don't currently see a good reason to mess around with how templates are loaded, given that you can build Converse on WSL.
