### ISSUE TITLE
Sending receipts for messages fetched from the archive

### ISSUE THREAD

**Issue by deleolajide** [conversejs/converse.js#1896]
**Describe the bug**
Every time you re-open a chatbox (one-to-one chat) and recieve a message from the MAM archive, Converse is generating one more receipt for this messages. The consequence is that the archive gets filled with receipts until only receipts are sent back instead of actual messages.

**To Reproduce**
1. Go to conversejs.org and login. 
2. Open a chatbox to another user
3. Type in a few messages.
4. Open and close the chatbox several times.

**Expected behavior**
The chat history of the messages just typed. Instead, you will see the chat messages diminishing until the chat history is empty. At this point, only receipts are being sent.

**Comment by deleolajide** [comment]
On investigating this, I think the IF statement for sendReceiptStanza needs to check if the original stanza isMAMMessage.

https://github.com/conversejs/converse.js/blob/34c4b2aa5e2824386e82480b0288f2b4977bd781/src/headless/converse-chat.js#L814

**Comment by jcbrand** [comment]
Thanks @deleolajide, looks like you're right: https://xmpp.org/extensions/xep-0184.html#when-archive

**Comment by vampik** [comment]
@jcbrand It seems that this issue is not fixed.

I observe the same behaviour on self-hosted conversejs build which is built from the current master.

**Comment by jcbrand** [comment]
Thanks @vampik, I think I've fixed the issue now, could you please double check?

**Comment by vampik** [comment]
@jcbrand this seemed to work until I unchecked "This is a trusted device". Now the archive continues to be filled on every login...

**Comment by jcbrand** [comment]
> @jcbrand this seemed to work until I unchecked "This is a trusted device". Now the archive continues to be filled on every login...

I don't see anything in the code to indicate that trusted mode is related to sending receipts to MAM messages.

**Comment by vampik** [comment]
> 
> I don't see anything in the code to indicate that trusted mode is related to sending receipts to MAM messages.

I think in trusted mode the history is cached. If trusted mode is off than the history is not cached and is loaded from the server on every login, causing sending receipts on every login.

**Comment by jcbrand** [comment]
The whole point of this bugfix is to not send receipts for MAM messages, so your issue should be fixed by it.

**Comment by vampik** [comment]
But every time I log in with "This is a trusted device" unchecked, the messages are fetched from the archive and receipts for them are sent. That's what I'm talking about.

**Comment by jcbrand** [comment]
Did you actually test this fix? https://github.com/conversejs/converse.js/commit/b511f1d950c9016e069ed2823967ae54ce38ef15

It should prevent receipts from being sent when messages are fetched from the archive.

**Comment by vampik** [comment]
> 
> 
> Did you actually test this fix? [b511f1d](https://github.com/conversejs/converse.js/commit/b511f1d950c9016e069ed2823967ae54ce38ef15)

Yes, this is my latest build:

```
# git log --oneline
83da03d6e (HEAD -> master, origin/master, origin/HEAD) [Security] Bump websocket-extensions from 0.1.3 to 0.1.4
a2d33ce3b Bump uglify-js from 3.8.1 to 3.9.1
b511f1d95 Updates #1896: Use right flag to checked if message is archived
```

**Comment by vampik** [comment]
Any ETA on fixing this? I need a web client very much, but it is unusable until this is fixed.

**Comment by anyuta1166** [comment]
Hello. Any news on fixing the critical bug?

**Comment by jcbrand** [comment]
@anyuta1166: I think it's fixed now, can you please check?
