### ISSUE TITLE
this.messages is undefined Error when fetching MAM archive

### ISSUE THREAD

**Issue by rheman** [conversejs/converse.js#1899]
I everyone,

I just migrated from 5.0.5 to 6.0.1.

I am using ejabberd-19.09 with mod MAM.
 
Under 5.0.5 my users are able to retrieve(see) archive message. But Since I have enabled 6.0.1 they are not able to see any archive message.

Please could someone tell me what's wrong with my setting ?

Regards,

**Comment by licaon-kter** [comment]
No errors in logs?

Works for me with these settings (scroll down): https://gist.github.com/licaon-kter/54d4656cc753b98e1dc0d81a59a73faa

**Comment by rheman** [comment]
Hi @licaon-kter  

I have enable debug mode. 

Here is the error I got in my console.

TypeError: this.messages is undefined   converse-chat.js:533:33

![Screenshot from 2020-03-02 14-47-39](https://user-images.githubusercontent.com/4598772/75686905-df549900-5c94-11ea-987a-434909a92d54.png)

Regards,

**Comment by licaon-kter** [comment]
Shows up your Converse config params.

**Comment by jcbrand** [comment]
@rheman: I think this is a race-condition bug and I also think what I'm working on currently might fix this. I'll mention this ticket in my commit message.

**Comment by rheman** [comment]
Thanks @jcbrand

**Comment by jcbrand** [comment]
Should be fixed in master now.

**Comment by rheman** [comment]
Thanks a lot @jcbrand.
It works now.
But after setting` show_client_info: false` 
The client info is not displayed but `false` is displayed on the screenshot as you can see in the following screenshot.

![Screenshot from 2020-04-06 14-15-44](https://user-images.githubusercontent.com/4598772/78568347-81761c80-7811-11ea-9fb7-c34ded2805a7.png)


regards,

**Comment by jcbrand** [comment]
Thanks @rheman, should be fixed now.

**Comment by rheman** [comment]
Thanks @jcbrand,
Sorry But there is still something wrong.
After enabling master version, user information is not displayed (Vcard data may not be rendered) (Full Name or Nickname, and avatar etc.).

Take a look at the next two screenshots you will see the difference between v 6.0.1 and the master.

1- Screenshots with master version enabled

![Screenshot from 2020-04-08 08-52-39](https://user-images.githubusercontent.com/4598772/78765891-227ee780-7978-11ea-90ec-8c7cd10afc94.png)


2- Screenshots with v 6.0.1 enabled

![Screenshot from 2020-04-08 08-54-15](https://user-images.githubusercontent.com/4598772/78765918-2ad72280-7978-11ea-9220-f9ba8175af33.png)


Regards,

**Comment by jcbrand** [comment]
Please make a new issue for this.

**Comment by rheman** [comment]
I did it
Regards,
