### ISSUE TITLE
Converse 5.0.5 how to display avatar in roster_item

### ISSUE THREAD

**Issue by rheman** [conversejs/converse.js#1901]
Hi everyone,

I am using converse 5.0.5 with ejabberd 19.x

I want to display user's avatar (picture) on roster_item. So I edited the roster_item.html template, and I added the following code.
`<canvas class="avatar" height="30" width="30"></canvas>`

So my roster_item.html template looks as followed.

`<a class="list-item-link cbox-list-item open-chat w-100 {[ if (o.num_unread) { ]} unread-msgs {[ } ]}"
   title="{{{o.desc_chat}}}" href="#">

    <canvas class="avatar" height="30" width="30"></canvas>
    <span class="{{{o.status_icon}}}" title="{{{o.desc_status}}}"></span>
    {[ if (o.num_unread) { ]}
    <span class="msgs-indicator">{{{ o.num_unread }}}</span>
    {[ } ]}
    <span class="contact-name {[ if (o.num_unread) { ]} unread-msgs {[ } ]}">{{{o.display_name}}}</span></a>
{[ if (o.allow_contact_removal) { ]}
<a class="list-item-action remove-xmpp-contact far fa-trash-alt" title="{{{o.desc_remove}}}" href="#"></a>
{[ } ]}`

Then I generated dist directory via "make dist".
But after uploading the new generated files in my app, I got empty images (avatars) for all my users as you can see in the following images.

![Screenshot from 2020-03-02 13-47-37](https://user-images.githubusercontent.com/4598772/75682070-b7613780-5c8c-11ea-8d71-6d19c8c5720e.png)

Please could someone tell me what I did wrong,

Regards,

**Comment by licaon-kter** [comment]
Update to 6.0.1, they are already included.

**Comment by rheman** [comment]
I know that 6.0.1 already included it. But when I upgrade from 5.0.5 to 6.0.1 my users cannot see archive message.

Regards,

**Comment by licaon-kter** [comment]
I've asked you something in the other issue.

**Comment by rheman** [comment]
I have just replied.

Regards,

**Comment by jcbrand** [comment]
We don't have dev capacity to handle support questions in the Github issue tracker.
