### ISSUE TITLE
build error: Can't resolve 'skeletor.js/src/view.js

### ISSUE THREAD

**Issue by tanglinhai** [conversejs/converse.js#1905]
**Describe the bug**
when i build the project, then report error message:
ERROR in ./src/converse-modal.js
Module not found: Error: Can't resolve 'skeletor.js/src/view.js' in '/home/app/web/converse.js/src'
 @ ./src/converse-modal.js 6:0-47 28:31-35
 @ ./src/converse-profile.js
 @ ./src/converse.js
 @ ./src/entry.js

**To Reproduce**
npm run build

**Environment (please complete the following information):**
 - linux centos
 - Browser [e.g. Chrome, Firefox]
 - Converse.js version [e.g. 4.2.0]

**Comment by jcbrand** [comment]
Run `make dist` to build, not `npm run build`.

**Comment by tanglinhai** [comment]
Thank you for your reply
when i run make dist , report message: 
"touch stamp-npm
process_begin: CreateProcess(NULL, touch stamp-npm, ...) failed.
make (e=2):
Makefile:117: recipe for target 'stamp-npm' failed
make: *** [stamp-npm] Error 2"

What causes this？

**Comment by jcbrand** [comment]
Looks like you can't run the `touch` command. This is a pretty standard GNU coreutils command.

**Comment by tanglinhai** [comment]
thanks! the error is solved.
but another error is report:

E:\repo\converse.js>make dist
npm run lerna

> converse.js@6.0.0 lerna E:\repo\converse.js
> lerna bootstrap --hoist --ignore-scripts

lerna notice cli v3.20.2
lerna info Bootstrapping 2 packages
lerna info Installing external dependencies
lerna info hoist Installing hoisted dependencies into root
lerna info hoist Pruning hoisted dependencies
lerna info hoist Finished pruning hoisted dependencies
lerna info hoist Finished bootstrapping root
lerna info Symlinking packages and binaries
lerna success Bootstrapped 2 packages
touch stamp-npm
Can not find file:stamp-npm
npm run dev && npm run build && make dist/website.css && make dist/website.min.css

> converse.js@6.0.0 dev E:\repo\converse.js
> webpack --config webpack.dev.js

Browserslist: caniuse-lite is outdated. Please run next command `npm update`
(node:26544) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
Building unminified package for Native JavaScript for Bootstrap 4 v2.0.27 ..
Included modules: Alert, Button, Collapse, Dropdown, Modal, Popover, Tab, Toast, Tooltip
Build complete!

.......
     |     + 75 hidden modules
    + 63 hidden modules

ERROR in ./src/converse-rosterview.js
Module not found: Error: Can't resolve '@converse/headless/converse-chatboxes' in 'E:\repo\converse.js\src'
 @ ./src/converse-rosterview.js 6:0-47
 @ ./src/converse.js
 @ ./src/entry.js

**Comment by tanglinhai** [comment]
help me~!

**Comment by licaon-kter** [comment]
Is this even buildable on Windows?

**Comment by tanglinhai** [comment]
I'm compiling in the window environment, but I haven't succeeded yet

**Comment by tanglinhai** [comment]
@jcbrand can you help me?

**Comment by jcbrand** [comment]
No, I don't use Windows.

Refs #1895
