### ISSUE TITLE
No converse.js-6.0.1.tgz in releases

### ISSUE THREAD

**Issue by heurekus** [conversejs/converse.js#1909]
Hi, 

is there a reason why there the source code archives but no converse.js-6.0.1.tgz that can be deployed in the releases?

Cheers!
Heurekus

**Comment by licaon-kter** [comment]
It was changed some versions ago, you need to build now.

**Comment by jcbrand** [comment]
Looks like I forgot to make and upload the tarfile.

**Comment by jcbrand** [comment]
Fixed.
