### ISSUE TITLE
Inline Images in Electron always render as Download Links instead of Images

### ISSUE THREAD

**Issue by koalaKoolaid** [conversejs/converse.js#1910]
I am running Converse.js 6.0.1 from npm in Electron and getting weird behavior when trying to display inline images within chat messages.
I am expecting a thumbnail to be generated but only get the link      Download file: "filename.png"

I investigated and it seems that my window.location.protocol is always set to "file:", and it will only ever display images in chat messages if the protocol is http: or https:

I went into /dist/converse.js for fun and added a clause to the checkTLS(uri) function to also allow the browser to use the file: protocol and that resolved the issue, but this seems like a bad fix.

Does anyone know a way to set my window.location.protocol to https: instead of file: ? Since node is calling Electron and Electron is loading a local file, is it hard-set to file?

Was there a reason converse.js only displays inline images when the browser protocol is set to http: or https: ?

Some additional info, let me know if I should supply files/screenshots!

NPM package.json
"dependencies": {
    "analytics.js": "^2.9.1",
    "bytebuffer": "^5.0.1",
    "converse.js": "^6.0.1",
    "electron": "^8.1.1",
    "electron-builder": "^22.4.0",
    "electron-packager": "^14.2.1",
    "electron-rebuild": "^1.10.0",
    "protobufjs": "^6.8.8"
  },
  "devDependencies": {
    "electron": "^8.1.1"
  }

**Comment by jcbrand** [comment]
> Was there a reason converse.js only displays inline images when the browser protocol is set to http: or https: ?

Yes, allowing images loaded via `file:` doesn't make sense for a web-app and might be a potential security risk.

You'll have to modify Converse accordingly for your needs if Electron works differently.
