### ISSUE TITLE
After anonymous login, refresh the page, then how to let the login account exit before refresh?

### ISSUE THREAD

**Issue by tanglinhai** [conversejs/converse.js#1914]
**Describe the bug**
After anonymous login, refresh the page, then how to let the login account exit before refresh?

**Environment (please complete the following information):**
 - Desktop or Mobile?
 - Browser [e.g. Chrome, Firefox]
 - Converse.js version [e.g. 6.2.0]

**Comment by jcbrand** [comment]
I don't understand the question. Besides that, the issue tracker is for bug reports and feature requests, not for support questions. Sorry, but it's mostly just me who can answer technical questions and I don't have enough time in the day to do so.

**Comment by tanglinhai** [comment]
@jcbrand 
Step 1: use anonymous login, the system generates an anonymous account, and use a nick name: join to enter the room
Step 2: refresh the page. At this time, the system generates another anonymous account and still uses nick name: join to enter the room

At this time, because the last anonymous account is still in the room and uses nick name: join, and the new anonymous account also uses nick name: join, it cannot enter

My idea is:
(1) When I refresh the page, can I use the last anonymous account to log in?
(2) Can I kick the last user out of the room when I enter?
But I don't know what to do
