### ISSUE TITLE
How to get historical messages through the ﹣ converse. API?

### ISSUE THREAD

**Issue by tanglinhai** [conversejs/converse.js#1919]

**Comment by tanglinhai** [comment]
When I query messages through the API, I get the following WARNING: Did not fetch MAM archive for 9999999999@conference.test2.365trade.com.cn because it doesn't support urn:xmpp:mam:2 
How can I get historical information?

**Comment by jcbrand** [comment]
I already wrote to you yesterday that this issue tracker is not for support questions.

**Comment by tanglinhai** [comment]
@jcbrand Thank you for your reply

**Comment by tanglinhai** [comment]
My server does not support getting historical messages.
But why converse.js can get it in the chatroomview dialog?
How to get historical information?
