### ISSUE TITLE
Only shows "Connecting" when trying externally

### ISSUE THREAD

**Issue by BBloke** [conversejs/converse.js#1927]
Hi All,

I'm trying to get this to work with our openfire server (4.51).  Everything I have setup is working, http-bind, proxy etc and I'm able to connect within my network through my webserver.  My webserver and openfire and on different servers.  I can connect via pidgin on PC and xabber on android externally but Converse just says "connecting" when I try from an outside IP.

I can see my connection requesting the login page on the webserver, I can also see the http-bind port open on the openfire server but it never successfully signs in.

Would anyone have any idea on why this may be happening?

Thanks,
BBloke

PS: This is the same if I use inVerse for openfire.

**Comment by licaon-kter** [comment]
There's no websocket support?

**Comment by BBloke** [comment]
That is one thing I look at but I couldn't find anything on it.  I know the plugin in openfire is outdated and not suitable for 4.5 and I couldn't find it there is something built in.  My attempts at checking the websocket on the openfire server has always failed.

**Comment by BBloke** [comment]
I'm not sure what is going on as I've changed nothing that springs to mind but it appears to be working internally and externally.  If I find out why I will post up.

@licaon-kter you've been inspirational
