### ISSUE TITLE
Option to disable 'Add a new groupchat' link

### ISSUE THREAD

**Issue by rrjanbiah** [conversejs/converse.js#1929]
**Is your feature request related to a problem? Please describe.**

Next to group chats list, we have a '+' option to create a new groupchat. There is no configuration to disable it. 

![Screenshot](https://user-images.githubusercontent.com/4253898/69434739-7dec6800-0d3e-11ea-92d8-4e86206d7fc7.png)

As mentioned in #1790, it is not very clear for users. And so, option to disable it will be good.

**Describe the solution you'd like**

Need a config, say `allow_create_groupchat` or something

**Comment by jcbrand** [comment]
Sorry, we have more than enough options, I don't want to unnecessarily add more.

You can hide the button with CSS if you don't want it.

**Comment by rrjanbiah** [comment]
@jcbrand Makes sense. Now, using:

```html
<style>
#conversejs #controlbox a.show-add-muc-modal {
	display: none;
}
```
