### ISSUE TITLE
fullscreen view mode to work with all configs

### ISSUE THREAD

**Issue by rrjanbiah** [conversejs/converse.js#1930]
**Is your feature request related to a problem? Please describe.**

When view mode is set to `fullscreen`, `auto_join_rooms` with `'minimized': true` is not working. It is also confusing if there are more auto join rooms.

**Comment by jcbrand** [comment]
You cannot minimize chats in fullscreen mode, so setting `'minimized': true` doesn't make any sense.

I don't see the need to make any changes based on this issue.

**Comment by jcbrand** [comment]
Giving this more thought... I guess you want to open a chatroom in the background?

Have a look whether passing in `'hidden': true` works.

**Comment by rrjanbiah** [comment]
@jcbrand Tried `'hidden': true` but can't find any differences.

But, I think, in all view modes, minimize is essential, otherwise it completely closes the chat. Also, in conferences, it completely exits the room.
