### ISSUE TITLE
Groupchats listing similar to contacts

### ISSUE THREAD

**Issue by rrjanbiah** [conversejs/converse.js#1931]
**Is your feature request related to a problem? Please describe.**
Currently even when certain configs are set, accessing groupchats / conferences need 'unnecessary' UI interactions/steps. 

**Describe the solution you'd like**
Display groupchats listing similar to contacts, at least when:
```json
muc_domain: 'example.com',
locked_muc_domain: 'hidden',
auto_list_rooms: true,
```

**Additional context**

Please check this screenshot with above config:

![converse-groupchats](https://user-images.githubusercontent.com/4907427/77879711-a221fd80-7278-11ea-96ce-53da75a5c72d.png)

**Comment by Tomo59** [comment]
For info, it was working fine in v4.2.0

**Comment by licaon-kter** [comment]
Group chat would appear there if you have them in your bookmarks.

**Comment by Tomo59** [comment]
> Group chat would appear there if you have them in your bookmarks.

Indeed, I can confirm that in version 6.0.1 it was a problem of bookmark, I got the following error in the console:
`ERROR: Error: timeout while fetching bookmarks`

I just tried master branch and I don't have this error and the group chats list is correctly displayed. As for me, you canclose this issue.

**Comment by jcbrand** [comment]
Thanks for confirming @Tomo59

**Comment by rrjanbiah** [comment]
FYI @jcbrand 

The issue/feature I reported is different from what @Tomo59 and @licaon-kter are discussing here. 

I reported the 'unnecessary' step for the group chat (Ideally groups should display under Groupchats heading without needing to click add and query, etc)

What they're discussing is about bookmark which looks completely a different issue.

**Comment by licaon-kter** [comment]
Read my post again please. That place is not for "local server existing groups" but for "bookmarks".

**Comment by jcbrand** [comment]
@rrjanbiah: Some servers have thousands of rooms. It doesn't make sense to automatically show all of them in the sidebar.
