### ISSUE TITLE
Double error text prefix

### ISSUE THREAD

**Issue by Zash** [conversejs/converse.js#1934]
**Describe the bug**

Got this error message:

> The reason given is: "The explanation given is: "Server-to-server connection failed: connection refused".".

"The reason given is" and "The explanation given is" seem redundant. The inner quote comes from the server.

**To Reproduce**
1. Try to join a groupchat like <xmpp:test@reject.badxmpp.eu>
2. See error

**Expected behavior**
A single instonce of "The reason was"-ish text should be enough for everyone!

**Environment:**
 - Debian desktop
 - Firefox ESR
 - Converse.js v6.0.1
**Additional context**

**Comment by jcbrand** [comment]
The text `The explanation given is` no longer occurs in the code.
