### ISSUE TITLE
Add smooth scroll to scrollDown

### ISSUE THREAD

**Issue by deleolajide** [conversejs/converse.js#1939]
When a chatbox is opened, the user is first presented with the chat scrolled to the top, and then suddenly brought to the very bottom in a split of a second. This effect has been described by a user as making them nauseous :-)

A simple way to remove that effect is to smoothly animate the scroll position, instead of a straight jump with the CSS scroll-behavior property.  In JavaScript, that would be adding
```
this.content.style.scrollBehavior = "smooth";
```
to the _scrollDown function

To keep the existing behavior, I propose a new boolean setting called **smooth_scroll** with default value *false*

**Comment by jcbrand** [comment]
I haven't seen what the smooth scrolling looks like (maybe it's better), but given that it's just a CSS setting, I think it can just be changed in the stylesheet.

I don't want to keep on adding new configuration variables for every tiny little details, especially not when the change can be made in a small snippet of CSS.

**Comment by deleolajide** [comment]
> I don't want to keep on adding new configuration variables for every tiny little details, especially not when the change can be made in a small snippet of CSS.

In that case, I happy to withdraw the [PR ](https://github.com/deleolajide/converse.js/commit/30fe48df8c92105426df58fc66a98fbc3e55c80f)and replace it with an unconditional CSS change

**Comment by jcbrand** [comment]
I had a look at the smooth-scrolling behavior. It's too slow for a chat with a very large history.

If someone can configure Converse.js, then they can also add their own CSS rule for smooth scrolling, if so desired. I therefore don't think that yet another configuration option is warranted and I'll close the related PR. Thanks nevertheless for submitting it.

**Comment by jcbrand** [comment]
I've found what I think is a reasonably good compromise. Smooth scrolling is enabled for short distances, but disabled for longer one.
