### ISSUE TITLE
make dev - Error in Linux

### ISSUE THREAD

**Issue by mkeli** [conversejs/converse.js#1942]
144 verbose optional Failed at the sleep@3.0.1 install script.
2144 verbose optional SKIPPING OPTIONAL DEPENDENCY: This is probably not a problem with npm. There is likely additional logging output above.
2145 verbose stack Error: node-sass@4.12.0 install: `node scripts/install.js`
2145 verbose stack spawn ENOENT
2145 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v13.12.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
2145 verbose stack     at ChildProcess.emit (events.js:315:20)
2145 verbose stack     at maybeClose (internal/child_process.js:1026:16)
2145 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
2146 verbose pkgid node-sass@4.12.0
2147 verbose cwd /home/sathya.ramakrishnan@IQOR.QOR.COM/conversejs/converse.js
2148 verbose Linux 3.10.0-1062.el7.x86_64
2149 verbose argv "/root/.nvm/versions/node/v13.12.0/bin/node" "/root/.nvm/versions/node/v13.12.0/bin/npm" "install"
2150 verbose node v13.12.0
2151 verbose npm  v6.14.4
2152 error code ELIFECYCLE
2153 error syscall spawn
2154 error file sh
2155 error errno ENOENT
2156 error node-sass@4.12.0 install: `node scripts/install.js`
2156 error spawn ENOENT
2157 error Failed at the node-sass@4.12.0 install script.
2157 error This is probably not a problem with npm. There is likely additional logging output above.
2158 verbose exit [ 1, true ]

**Comment by jcbrand** [comment]
Which Linux distro and version number are you using?
