### ISSUE TITLE
chats "forget' about file upload feature

### ISSUE THREAD

**Issue by poVoq** [conversejs/converse.js#1945]
**Describe the bug**
Sometimes 1:1 chats (and also MUCs?) forget that the file upload feature (paper clip) is available. It might be related to the auto_reconnect feature? But manually closing a chat via the top right X and reopening it works to bring back the paperclip.

**Environment (please complete the following information):**
 - Desktop or Mobile? Both I think
 - Browser [e.g. Chrome, Firefox] embedded chromium and Firefox
 - Converse.js version [e.g. 4.2.0] 6.0.1

**Additional context**
I definitely observe this on my Ubuntu Touch mobile app that uses auto_reconnect and SMACKS, but I think I also observed this on a desktop webclient using Firefox in the past.

**Comment by FaizanZahid** [comment]
i can confirm the same thing, yes it is happening sometimes that the clip disappears.

**Comment by poVoq** [comment]
I think this is fixed in master for the upcoming 7.0.

**Comment by poVoq** [comment]
Sorry actually that still happens.

**Comment by robjloranger** [comment]
If this still an issue with v9.x?
