### ISSUE TITLE
question: how to block chat message viewing (from other anonymous logins) for anonymous logins?

### ISSUE THREAD

**Issue by code-reflex** [conversejs/converse.js#1946]
Hi. I went through the options & couldnt figure out how to achieve the below scenario & hence asking this question here:

Assume we have a MUC with logged-in Users (consider as teachers) & anonymous users (students) in a chat room.

I want to prevent anonymous users(students) from chatting with each other i.e., they should not see any message other than those from the logged-in user  (teacher).   Anonymous-users (students) will post their queries on chat & the logged-in user can answer back & the response from logged-in user can be seen by all (its ok for everyone to see the messages/response from logged-in users)

Summarising:
1. Anonymous-users: should be able to post their messages in a chat room, should not be able to see any messages from other anonymous-users. Should be able to see messages from logged-in users. (basically restrict/filter messages).
2. Logged-in-users; should be able to post messages to everyone in the chatroom. should be able to view all the messages in the chat room (default functionality of a chatroom anyways)

How to achieve the above? What conversejs setting should be used to block anonymous-users from seeing other's messages? (I am even OK if we are going to block all messages i.e., even from logged-in users)

**Comment by jcbrand** [comment]
This is not something that can be done by just modifying Converse.js. You'll need to modify your XMPP server to route `groupchat` messages based on who the author is.
