### ISSUE TITLE
User Information not displayed on master release (Vcard data may not be rendered)

### ISSUE THREAD

**Issue by rheman** [conversejs/converse.js#1960]
Hi everyone,

After enabling master version, user information is not displayed (Vcard data may not be rendered) (Full Name or Nickname, and avatar etc.).

Take a look at the next two screenshots you will see the difference between v 6.0.1 and the master.

1- Screenshots with master version enabled

![Screenshot from 2020-04-08 08-52-39](https://user-images.githubusercontent.com/4598772/78765891-227ee780-7978-11ea-90ec-8c7cd10afc94.png)

2- Screenshots with v 6.0.1 enabled

![Screenshot from 2020-04-08 08-54-15](https://user-images.githubusercontent.com/4598772/78765918-2ad72280-7978-11ea-9220-f9ba8175af33.png)

Regards,

**Comment by rheman** [comment]
Hi,

Any comment on this bug ?

Regards,

**Comment by licaon-kter** [comment]
Seeing the same, log says: `Error: No JID to get vcard for!`

**Comment by licaon-kter** [comment]
This appears fixed.
