### ISSUE TITLE
@converse/headless is missing dist directory

### ISSUE THREAD

**Issue by tonnenpinguin** [conversejs/converse.js#1961]
**Describe the bug**
The latest version of `@converse/headless` on npm does not include a dist directory, which shows up for a user as `Module not found: Error: Can't resolve '@converse/headless' in [...]` error.

**To Reproduce**
1. Add `@converse/headless` as npm dependency
2. Add `import '@converse/headless';` to your code

**Expected behavior**
For converse headless to be imported successfully

**Environment**
 - Desktop
 - Chrome
 - Converse.js version `6.0.1`

**Additional context**
Looking through past versions it seems like the dist directory used to be there until `4.2.0` and disappeared in `5.0.1`.

For testing purposes I built the module myself from this repo by running `make src/headless/dist/converse-headless.min.js` (btw. the command differs from the one mentioned in `src/headless/README.md`!) and copied the resulting `dist` directory into my projects `node_modules/@converse/headless/` directory. This fixed the issue for me and converse is now running in the background as expected.

**Comment by jcbrand** [comment]
Thanks for the bug report, should be fixed with the next release.
