### ISSUE TITLE
Highlighting of mentions is off (when emoji's are used perhaps)?

### ISSUE THREAD

**Issue by guusdk** [conversejs/converse.js#1990]
I'm assuming that there was an attempt to mention my nickname ("Guus") in the image below. The Converse hilighting seems off by a few characters.

![image](https://user-images.githubusercontent.com/4253898/79843764-fa04dd80-83ba-11ea-9bfc-399cbec26eaa.png)

**Comment by jcbrand** [comment]
I believe this has been fixed already.
