### ISSUE TITLE
React Native typeError: Undefined is not an object

### ISSUE THREAD

**Issue by ekam123** [conversejs/converse.js#2025]
**Describe the bug**
Version 6.0.1 leads to 'typeError: Undefined is not an object (evaluating window.Event.prototype) when trying to import '@converse/headless'.

**To Reproduce**
1. Init new React native project (https://reactnative.dev/docs/environment-setup) using React-Native Cli quickstart instructions
2. install converse headless - npm i @converse/headless
3. Download master branch and build dist directory as mentioned in issue #1961 and drag directory to node_modules/@converse/headless/
4. add import '@converse/headless' to App.js and run project 'npx react-native run-ios'
5. Also tried running with adding additional line const converse = require("@converse/headless") globally in App.js and got same result

**Expected behavior**
Successful import of converse

**Screenshot**
<img width="358" alt="Screen Shot 2020-05-12 at 1 21 48 PM" src="https://user-images.githubusercontent.com/19808642/81743356-586f2a00-9456-11ea-92d7-617d6f47a644.png">

**Environment (please complete the following information):**
 - Mac running app on ios simulator (iphone 11 -13.3)?
 - react native version: 0.62.2
 - Converse.js version: 6.0.1

**Comment by ciaoamigoschat** [comment]
news?

**Comment by jcbrand** [comment]
> 'typeError: Undefined is not an object (evaluating window.Event.prototype)

I think this was because of the `converse-loaded` event that was being triggered. This code is now no longer in @converse/headless, so I believe this bug is now fixed.
