### ISSUE TITLE
Traceback when clicking on contact with non-latin1 chars.

### ISSUE THREAD

**Issue by Ppjet6** [conversejs/converse.js#2026]
**Describe the bug**

Traceback when clicking on roster entry not in latin1.

**To Reproduce**
1. Login
2. Click on contact in roster with fancy characters (I have あいうえお@foo.bar here)

**Expected behavior**
Chat opens with contact.

**Logs**

Chromium:
```
converse-chat.js:335 Uncaught (in promise) DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
```
Firefox:
```
(converse-chat.js:14) InvalidCharacterError: String contains an invalid character
```

**Environment (please complete the following information):**
- Desktop
- Chromium: Version 81.0.4044.138
- Firefox nightly: 77.0a1 (2020-05-04)
- Converse.js: efb486511

Feel free to poke me if you want a test account to add as contact.

**Comment by jcbrand** [comment]
AFAIK this is already fixed.
