### ISSUE TITLE
Backbone conflict in Nextcloud

### ISSUE THREAD

**Issue by leoyn** [conversejs/converse.js#2027]
**Describe the bug**
When i try to initialize converse with `converse.initialize` an error in the console appears and no window is shown. There were no connections made to the websocket endpoint.

**To Reproduce**
1. Download & enable JSLoader in Nextcloud
2. Copy & Paste code:
```js
(function(){
    let head = document.getElementsByTagName('HEAD')[0];  

    let link = document.createElement('link'); 
    link.rel = 'stylesheet';
    link.type = 'text/css';
    link.href = 'https://static.domain.tld/converse/converse.min.css';  
    head.appendChild(link);

   let script = document.createElement('script'); 
   document.body.appendChild(script);
   script.onload = function() {
        // error occurs when i call initialize
        converse.initialize({
            websocket_url: 'wss://messaging.domain.tld/ws',
            view_mode: 'overlayed'
        });
    }
    script.src = 'https://static.domain.tld/converse/converse.min.js';  
})();
```

**Expected behavior**
Converse should be shown in overlay mode.

**Error Message**
```js
TypeError: setting getter-only property "Backbone"      converse-core.js:31:20
```
Code on line 31:
```js
Backbone = Backbone.noConflict();
```

*Important: Nextcloud already has Backbone integrated*
Therefore, it think I would be neat to have Backbone of `converse.js` scoped so only `converse` can use it. Unfortunately, I don't have any clue on how to do this since I am not that experienced with webpack.

**Environment:**
 - Nextcloud 18.0.4
 - Desktop (Mac OS 10.15)
 - Firefox: 76.0.1 (64 bit)

I know you are probably burdened by the sheer amount of issues, but I want to deploy your xmpp client into our schools Nextcloud and it would be really nice to have `converse` directly integrated into Nextcloud. If there nothing you can or want do I would appreciate any suggestions to help fight the issue.

**Comment by leoyn** [comment]
I found a workaround that should solve the issue. However, this is not a future proof idea.

1. Change your script url to `https://static.domain.tld/converse/converse.min.js` to `https://static.domain.tld/converse/converse.js`. (Remove .min from url)
2. Open up `converse.js` in a text editor like nano
3. Search for `backbone.js` or `// Set up Backbone appropriately for the environment.` to get to line *`19817`*.
4. Add the following code below `var root = ...` like this:
```js
var root = ...

// fixes bug temporarily in nextcloud
delete root.Backbone;
```

**Comment by jcbrand** [comment]
We've removed Backbone in the master branch and are using a fork called Skeletor now.

So once version 7 has been released this won't be an issue anymore.

**Comment by leoyn** [comment]
Oh...my bad. I will compile from `master`and will test this later when I have time.

**Comment by leoyn** [comment]
> So once version 7 has been released this won't be an issue anymore.

✅ Issue will be resolved with version 7.
