### ISSUE TITLE
Implement XEP-0333 displayed and acknowledged chat markers

### ISSUE THREAD

**Issue by deleolajide** [conversejs/converse.js#2028]
**Is your feature request related to a problem? Please describe.**
Currently, only the **received** chat marker is implemented in Converse. However, Prosody is able to handle **displayed** and **acknowledged** chat markers in order to send accurate [room activity notifications](https://xmpp.org/extensions/xep-0437.html)  back to Converse

**Describe the solution you'd like**
Converse is tracking the total unread messages and first unread message displayed in a chatbox as well as user gestures that reset the counter. When the counter gets reset, mark the last message  as **acknowledged**. All new messages should be marked as **displayed**.

**Comment by jcbrand** [comment]
@deleolajide Can this be closed now?

**Comment by deleolajide** [comment]
Yes please

**Comment by mightymop** [comment]
I got a question:
How are theese markers are displayed in the chatbox? 
I only get one green marker for message reception. Are there any addional markers if the opponent have read the message? Or is the color changing? I can see that converse sends the displaymessage, so that conversations show me the message that the converseuser have read the message, but the other way around may be buggy?

**Comment by jcbrand** [comment]
@mightymop: AFAIK Converse doesn't show anything related to these markers in the UI. It only supports these markers by notifying your chat partner that a message has been received/displayed etc.

**Comment by mightymop** [comment]
> 
> 
> @mightymop: AFAIK Converse doesn't show anything related to these markers in the UI. It only supports these markers by notifying your chat partner that a message has been received/displayed etc.

@jcbrand: thanks for your answer...

so maybe it would be a good improvement to add this to the ui? maybe simple colorize the existing check symbol to blue with css or add a second one?

**Comment by jcbrand** [comment]
@mightymop: You're welcome to create a new feature request for that.
