### ISSUE TITLE
chatbox title and buttons disappear as messages history grows

### ISSUE THREAD

**Issue by n0u4n** [conversejs/converse.js#2033]
**Describe the bug**
When open a 1:1 chatbox i can see at the top of the screen the name of the contact I'm chatting with and buttons like the "x" to close the conversation. As I send messages and messages fill the page, title and buttons scroll up and disappear. I cannot even close the conversation anymore except if I type /close. This appens in fullscreen and in overlayed as well.

**To Reproduce**
1. Go to chat 1:1
2. Send message to fill the screen with history
3. Search for button for close the conversation
4. Cannot find the button anymore

**Expected behavior**
title and buttons not scroll as history grows but remains always available on top of the screen

**Screenshots**

![Screenshot at 2020-05-16 21-04-11](https://user-images.githubusercontent.com/52280384/82128155-7dda9b80-97a8-11ea-8770-01a410df1de4.png)

as you can see I can only scroll up the messages history and cannot reach the button to close the chat.

**Environment (please complete the following information):**
 - Desktop or Mobile?
Desktop
 - Browser [e.g. Chrome, Firefox]
Firefox and chrome
 - Converse.js version [e.g. 4.2.0]
6.0.1

**Additional context**

**Comment by jcbrand** [comment]
Should be fixed by now.
