### ISSUE TITLE
Clearly mark ID values as 'not UUID'

### ISSUE THREAD

**Issue by guusdk** [conversejs/converse.js#2035]
https://github.com/conversejs/converse.js/blob/b5eea12d493d6b732d753ce0dec0965b62f40691/src/headless/utils/core.js#L556-L561

Converse generates values by adding the letters `id` in front of a UUID - which is fine. The resulting value looks like, but is no longer a valid UUID. That caused a bit of confusion on my end. Can we make the value clearly not a UUID? Adding something like `id_` or `id-xmpp_` or anything a bit more standout-ish than `id` would do the trick.

**Comment by guusdk** [comment]
Thinking about this a bit more: the XEP does specify that the values SHOULD be a UUID. By prefixing them that's no longer the case. Was the prefix added in the full realization that this would cause the resulting value no longer to be a valid UUID?

**Comment by marclaporte** [comment]
Related: https://github.com/igniterealtime/openfire-monitoring-plugin/pull/102
