### ISSUE TITLE
Every unread message is highlighted

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/converse.js#2040]
I can't bisect now but I'd guess https://github.com/conversejs/converse.js/commit/cae5e9c87506a8cabbc5ac5842f3443ffdcb7b36 is at fault

Using HEAD

![unread](https://user-images.githubusercontent.com/2282799/82819575-1e5b4a80-9e90-11ea-9f6c-d3f865dc30de.jpg)

Ping @deleolajide

**Comment by deleolajide** [comment]
Yes. I am now aware of this. It is caused by persisting the first_unread flag in messages and not resetting the value when a new unread message arrives. It should be fix by https://github.com/conversejs/converse.js/pull/2031 when it is ready
