### ISSUE TITLE
Ad-Hoc Command XEP-0050: not able to Execute same command multiple time

### ISSUE THREAD

**Issue by genofire** [conversejs/converse.js#2054]
After the first Execute, we will only recieve a `Done` in blue box on every new Execute.

**Comment by jcbrand** [comment]
Tried to replicate the issue, looking at the stanzas being sent out, it looks to me like it executes the command each time.

Please provide more info on how to replicate the issue.

**Comment by genofire** [comment]
hmm the `Done` is from a other command ... happen vary rarly

**Comment by jcbrand** [comment]
> hmm the Done is from a other command ... happen vary rarly

I don't understand this sentence.
