### ISSUE TITLE
authentication by JWT token

### ISSUE THREAD

**Issue by Krakozaber** [conversejs/converse.js#2057]
ejabberd can authorize by JWT token, but converse.js turn password by base64 :-(

https://docs.ejabberd.im/admin/configuration/authentication/#jwt-authentication

**Comment by antranigv** [comment]
Hi!

I have ejabberd running with JWT authentication working fine!

**Comment by jcbrand** [comment]
@antranigv is there any code you could share? Or perhaps a GitHub gist?
