### ISSUE TITLE
Add a separator between views

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/converse.js#2059]
...a simple vertical line or maybe a slight background tint

![noseparator](https://user-images.githubusercontent.com/2282799/83629229-3f572600-a589-11ea-865d-021a063f7c82.png)
..so it's not continuous white between roster and chat, or roster and input box.

IIRC, it used to be one.

**Comment by bernard-ng** [comment]
@licaon-kter Hi, could you tell me how I can replicate this behavior? I just built the project and I don't have the same design. 
![Screenshot from 2020-07-08 20-18-55](https://user-images.githubusercontent.com/31113941/86956016-bc615680-c158-11ea-82b7-ef7c4ee1e2f6.png)

**Comment by licaon-kter** [comment]
You build from git HEAD?

**Comment by bernard-ng** [comment]
yes

**Comment by licaon-kter** [comment]
You are not building from Converse HEAD, look at the icons...

**Comment by bernard-ng** [comment]
All right, how can I build from HEAD and reproduce this bug? I'm trying to fix it.

**Comment by licaon-kter** [comment]
Yes...be my guest...

**Comment by guusdk** [comment]
This is how I build from head:

- `git pull upstream master` (to pull in the latest code)
- `make clean`
- `make watch`

Then, I open the file `fullscreen.html` (that is in the root of the source tree) in a browser.

Like @bernard-ng I'm having trouble reproducing this issue. Using the current head (commit bb9ee4caab3272dc530bd1b6b3bd89cbf881df72), I _do_ get a spacer (the vertical bar that I highlighted in the screenshot below). I can resize the window at will, which adapts the layout - but the spacer stays. I'm using Google Chrome 83.0.4103.97 

![image](https://user-images.githubusercontent.com/4253898/87025759-186cbf00-c1db-11ea-95a4-f4f5ebef84f9.png)

@licaon-kter can you please explain how you reproduce this issue?

**Comment by guusdk** [comment]
Sigh. That fullscreen.html is pulling converse in from a CDN :'( It's not using the version that was build locally.

**Comment by licaon-kter** [comment]
Gotcha!!!!1111

**Comment by guusdk** [comment]
With some help from @jcbrand I've found that doing `make dev` generates a distribution that can be used with the `dev.html` file that is in the root source (note that `make dist` generates minified files, that are not used by `dev.html`.

`dev.html` uses the 'concord' theme, which uses a different background for both views. That kind of makes the problem disappear.

![image](https://user-images.githubusercontent.com/4253898/87028569-1573cd80-c1df-11ea-87a4-7c6fd8f82829.png)

When I use the default theme (just remove the 'theme' reference in the initialization of converse in `dev.html`) then I do reproduce the isssue:

![image](https://user-images.githubusercontent.com/4253898/87028371-d5ace600-c1de-11ea-9276-8a91b9bc3f9b.png)

I'm thinking that the new layout is a design choice by @jcbrand? Maybe we should play a little with the default background colors in the default, just like in the concord theme?

**Comment by licaon-kter** [comment]
> Maybe we should play a little with the default background colors in the default, just like in the concord theme?

Yes, not much just a bit darker I'd guess, but then again I'm no UX person

@Nyco ? :)

**Comment by jcbrand** [comment]
> I'm thinking that the new layout is a design choice by @jcbrand?

The lack of separator? That wasn't intentional IIRC.

> Maybe we should play a little with the default background colors in the default, just like in the concord theme?

For the default theme, we could make the controlbox background dark blue (like the highlight color). I'm not sure how much work that would be.

**Comment by guusdk** [comment]
> For the default theme, we could make the controlbox background dark blue (like the highlight color). I'm not sure how much work that would be.

@bernard-ng want to give that a try?

**Comment by bernard-ng** [comment]
oh yeah 😁

**Comment by guusdk** [comment]
as a side-note: we discussed a lot of this (plus ways to improve the project to make it more accessible to newcomers) in the chatroom. Your input there would be valuable!

**Comment by bernard-ng** [comment]
what do you think about this? 
will change the default theme cause changes to the other themes?

![Screenshot from 2020-07-10 13-39-08](https://user-images.githubusercontent.com/31113941/87150705-ddd65580-c2b2-11ea-9d13-6328c0e5539b.png)

**Comment by jcbrand** [comment]
Hi @bernard-ng,  looks good :+1: 

>   will change the default theme cause changes to the other themes?

That depends on the changes that you made. If you make a PR I can give better feedback.

**Comment by guusdk** [comment]
I have zero weight in any discussion related to design, but I like it.

I do not know if other themes are affected, but I guess you can try a couple, and find out? Should be a matter of changing / adding one line in the configuration object that initializes converse.js.

**Comment by jcbrand** [comment]
There are only two themes in the repo currently, the default one and `concord`

**Comment by bernard-ng** [comment]
here is my pull request #2135

**Comment by licaon-kter** [comment]
Thanks @bernard-ng
