### ISSUE TITLE
OMEMO: Trusted device does not work

### ISSUE THREAD

**Issue by genofire** [conversejs/converse.js#2060]
- on try view the own profile `e.view.other_devices is undefined` appears in log
- on try to view others profile ` e.view.devicelist is undefined` appears in log

**Comment by jcbrand** [comment]
This should now be fixed after the work done in these commits:
https://github.com/conversejs/converse.js/commit/bad2577e5e7fae453ab4a87609736fa1cd19eb3d
https://github.com/conversejs/converse.js/commit/284eccf0472331950ccb2933856830bd1f1b8c2d
