### ISSUE TITLE
Save and use as a single HTML file

### ISSUE THREAD

**Issue by snshn** [conversejs/converse.js#2062]
With help of [Monolith](https://github.com/Y2Z/monolith) it's possible to save and use Converse.js as a single HTML file.

Here's how: `monolith https://conversejs.org/fullscreen.html -o conversejs.html`.

Please feel free to include this information somewhere in your documentation, as it may be useful for certain use cases. Tnks.

**Comment by jcbrand** [comment]
Thanks for the info, looks like an interesting project.
