### ISSUE TITLE
Checkmarks in consecutive messages are not aligned

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/converse.js#2064]
HEAD, Firefox 77 or Vivaldi Snapshot
![cmark](https://user-images.githubusercontent.com/2282799/83772406-dd72eb00-a672-11ea-93c0-062d60483b9c.png)

**Comment by jcbrand** [comment]
Yes, this is because of the action icons (edit, retract etc.).

I'm working on putting those in a dropdown, which should fix this.

**Comment by jcbrand** [comment]
False alarm, but working on a fix.

**Comment by licaon-kter** [comment]
Ok,look better

Any chance to fix https://github.com/conversejs/converse.js/issues/1346 while you're at it?
