### ISSUE TITLE
Keep chatboxes collapsed through page loads.

### ISSUE THREAD

**Issue by alexandre-boily** [conversejs/converse.js#2084]
**Is your feature request related to a problem? Please describe.**
Chatboxes reappear through page loads or reloads when they've been previously collapsed.

**Describe the solution you'd like**
Keep the chatboxes hidden or visible through page loads. If impossible, have an option to have them visible or hidden by default.

**Describe alternatives you've considered**
I tried changing it myself but it's hard to find them with JQuery as they have no identifier. If someone knows how to do it let me know, I'm kinda new to this.

**Comment by jcbrand** [comment]
This has been a feature of Converse since about 2014 and it seems to be working still for me (i.e. I can't reproduce a situation where they don't stay collapsed).

Please recreate a bug report (with the necessary information as asked for in the bug report template) to help with debugging this.
