### ISSUE TITLE
Chatboxes should stay collapsed through page loads, but they don't. 

### ISSUE THREAD

**Issue by alexandre-boily** [conversejs/converse.js#2087]
**Describe the bug**
Chatboxes should stay collapsed through page loads, but they don't. I start multiple user conversations, minimise them and then click the "x reduced" tab to remove them from view, but they don't stay collapsed through page loads.

**To Reproduce**
1. Start a conversation with someone.
2. Minimize the conversation by clicking the "-" in the top right corner of the conversation.
3. Hide all conversations from view by clicking the "1 reduced" tab.
4. Reload.

**Expected behavior**
They should stay hidden by then but they reappear everytime.

**Screenshots**
![reload](https://user-images.githubusercontent.com/47259616/84522109-0bc07e00-aca4-11ea-8c6f-53100218c735.gif)

**Environment (please complete the following information):**
 - Desktop
 - Tested on Chrome and Firefox
 - Converse.js version 6.0.1

**Additional context**
I tried changing the CSS via JQuery but I can't find the appropriate element.

**Comment by jcbrand** [comment]
Thanks for including the screenshot, it's clearer now what the bug is,
