### ISSUE TITLE
Open chatbox

### ISSUE THREAD

**Issue by enukepro** [conversejs/converse.js#209]
Hello,

I have my custom friend list html. I don't want to use contact list of toolbox provide by converse.js. So i need to open chatbox by custom function or link. so could you please guide me for this.

Thanks
Hari

**Comment by iqra-ansari** [comment]
hi....
I want to use the chat open API to report data between the client and the server, but it's not working correctly. Please help me with this.
let me know....
require(["converse"], function (converse) {
con=converse;
    converse.initialize({
        bosh_service_url: 'https://ravi.store:5443/bosh',
        auto_login: true,
        loglevel: 'debug',
        authentication: 'login',
        jid: 'four@ravi.store',
        password: '123456',
        keepalive: true,
        //message_carbons: true,
        play_sounds: true,
        roster_groups: true,
        show_controlbox_by_default: true,
        allow_non_roster_messaging: true,
        // allow_muc: false,
        xhr_user_search: false,
        allow_logout: false,
        whitelisted_plugins: ['startChat', 'myplugin'],
     });
});

getobj:function()
{
return s;
}
off: function (e, t) {
s.off(e, t)
}
con.getobj().chatboxesview.showChatBox({id:'one@ravi.store'})

**Comment by iqra-ansari** [comment]
hi....
I want to use the chat open API to report data between the client and the server, but it's not working correctly. Please help me with this.
let me know....
require(["converse"], function (converse) {
con=converse;
converse.initialize({
bosh_service_url: 'https://example:5244/bosh',
auto_login: true,
loglevel: 'debug',
show_controlbox_by_default: true,
allow_non_roster_messaging: true,
xhr_user_search: false,
allow_logout: false,
whitelisted_plugins: ['startChat', 'myplugin'],
});
});

getobj:function()
{
return s;
}
off: function (e, t) {
s.off(e, t)
}
con.getobj().chatboxesview.showChatBox({id:'[one@ravi.store](mailto:one@ravi.store)'})

**Comment by iqra-ansari** [comment]
hi....
I want to use the chat open API to report data between the client and the server, but it's not working correctly. Please help me with this.
let me know....
require(["converse"], function (converse) {
con=converse;
converse.initialize({
...........................
whitelisted_plugins: ['startChat', 'myplugin'],
});
});

getobj:function()
{
return s;
}
off: function (e, t) {
s.off(e, t)
}
con.getobj().chatboxesview.showChatBox({id:'[one@ravi.store](mailto:exm@example)'})

**Comment by iqra-ansari** [comment]
hi....
I want to use the chat open API to report data between the client and the server, but it's not working correctly. Please help me with this.
let me know....
require(["converse"], function (converse) {
con=converse;
converse.initialize({
...........................
whitelisted_plugins: ['startChat', 'myplugin'],
});
});

getobj:function()
{
return s;
}
off: function (e, t) {
s.off(e, t)
}
con.getobj().chatboxesview.showChatBox({id:'[one@ravi.store](mailto:exm@example)'})

**Comment by iqra-ansari** [comment]
hi....
I want to use the chat open API to report data between the client and the server, but it's not working correctly. Please help me with this.
let me know....
require(["converse"], function (converse) {
con=converse;
converse.initialize({
...........................
whitelisted_plugins: ['startChat', 'myplugin'],
});
});

getobj:function()
{
return s;
}
off: function (e, t) {
s.off(e, t)
}
con.getobj().chatboxesview.showChatBox({id:'one@example'})
