### ISSUE TITLE
Non-minified files in dist/ are not built

### ISSUE THREAD

**Issue by Zash** [conversejs/converse.js#2090]
**Describe the bug**

The non-minified files in `dist/`, like `dist/converse.js` are not built.

**To Reproduce**
1. `make dist/converse.js`
2. `ls dist/converse.js`

**Expected behavior**
`dist/converse.js` exists.

**Environment:**
 - node:lts-buster docker image

**Additional context**

`git bisect` blames 65246d0041e2bffd1ed52bce1f681db5e0bcb752

I used `git bisect run` with the following script:

```sh
#!/bin/sh

docker run -it --rm --network host -v $PWD:/app -w /app -u 1000:1000  node:lts-buster \
make dist/converse.js
RESULT=1
if [ -e dist/converse.js ]; then
	RESULT=0
fi

git checkout -- .
git clean -fdx

exit $RESULT
```

**Comment by Zash** [comment]
`make dist` only produces the minified files, while `make dev dist/converse.js` does build it.

**Comment by jcbrand** [comment]
Looks like this is fixed.
