### ISSUE TITLE
Does not scroll to bottom after sending a message

### ISSUE THREAD

**Issue by Zash** [conversejs/converse.js#2091]
**Describe the bug**
After sending a message, the view is not scrolled all the way down, so the newly sent message may not be completely visible.

**To Reproduce**
1. Open a normal 1-1 chat
2. Send some messages back and forth to fill up the view so scrollbar shows up
3. Send a message
4. Observe scroll position

![image](https://user-images.githubusercontent.com/197474/85224963-137fd100-b3ce-11ea-82e7-fb5e8492b5e2.png)

**Expected behavior**

![image](https://user-images.githubusercontent.com/197474/85224977-2d211880-b3ce-11ea-809e-0dc761c341fe.png)

**Environment:**
 - Debian Desktop
 - Firefox 77.0.1 (flatpak)
 - Firefox 68.9.0esr (Debian 10 version)
 - Converse.js version 7c29ae4a8ae69e1c7ff60b0bf15dcb29fa686ead

**Additional**

Seems to only happen in 1-to-1 chats.

A chat state from the chat partner seems to induce a proper scroll down, which may explain the random component mentioned in #2075.

**Comment by licaon-kter** [comment]
Here's a thought, if I scrolled up to read some backlog, quoted some text... scrolling me down would be a nuisance... I'll have to scroll back again and continue to read/quote.

There was a request here that made sense to me, and this is implemented by Conversations (along with a toggle to control this behavior): https://github.com/conversejs/converse.js/issues/1118#issuecomment-590239117

**Comment by jcbrand** [comment]
@licaon-kter The best default, when sending a message, is to have the chat scroll down.
