### ISSUE TITLE
Concord theme contrast issues

### ISSUE THREAD

**Issue by Zash** [conversejs/converse.js#2101]
**Describe the bug**
The concord theme has more contrast issues.

**Screenshots**

Most text on the login screen except links and buttons:

![Login screen](https://user-images.githubusercontent.com/197474/85774736-6aafd980-b71f-11ea-9064-46aff65bd14e.png)

Name in the profile corner:

![Profile](https://user-images.githubusercontent.com/197474/85775732-591b0180-b720-11ea-8140-adc62f245597.png)

**Environment (please complete the following information):**
 - Desktop with i3 / XFCE4 hybrid
 - Firefox 77.0.1 Flatpak
 - Converse.js version 33a2a368d

**Comment by licaon-kter** [comment]
You have the nick there? That's fixed?

**Comment by Zash** [comment]
> You have the nick there? 

Sorry, full name.

**Comment by Zash** [comment]
Hm, `--text-color`) which is what these all use is the same as what's used for nicknames in the chat log, which is on a light background instead of the dark here, so fixing this seems more involved than just fiddling with  `--text-color`.

**Comment by jcbrand** [comment]
Yeah, we'll need something like `--controlbox-text-color`
