### ISSUE TITLE
Auto-joined rooms hidden

### ISSUE THREAD

**Issue by Zash** [conversejs/converse.js#2114]
**Describe the bug**

**To Reproduce**
1. Configure `view_mode = "fullscreen"`
1. Set some room in `auto_join_rooms[]`
2. Launch Converse.js
3. Note that room is not shown
4. Inspect DOM, find room `<div>` having the `hidden` class.

**Expected behavior**
Room should be shown (probably asking for a nickname).

**Screenshots**

![image](https://user-images.githubusercontent.com/197474/86385045-ec5bb600-bc8f-11ea-8df7-ba47b8a38fb8.png)

**Environment (please complete the following information):**
 - Desktop Debian 10
 - Firefox 78.0 (flatpak)
 - Converse.js version eafa1573e

**Additional context**

Potentially a duplicate of #2029

Seems to work with the `overlayed` mode.

**Comment by jcbrand** [comment]
Looks like this is fixed.
