### ISSUE TITLE
TypeError: converse_core_converse.connection is undefined

### ISSUE THREAD

**Issue by Zash** [conversejs/converse.js#2127]
**Describe the bug**
A `TypeError` is thrown on page load or reload. Does not appear to affect anything from what I can tell.

**To Reproduce**
1. Some configuration with `auto_login` enabled.
2. **???**
3. Open Converse.js (observing error logs or debugger).

**Traceback**

- TypeError: converse_core_converse.connection is undefined
- https://github.com/conversejs/converse.js/blob/b0cb4897691a06c86e471e2e76b72266311cb5fd/src/headless/converse-core.js#L409-L411
- https://github.com/conversejs/converse.js/blob/22b2875b526fcb71797cc5a91e5ebc6c8bf43ee4/src/headless/converse-muc.js#L2725

**Expected behavior**
No error.

**Environment (please complete the following information):**
 - Desktop, Debian 10
 - Firefox 68.10.0 ESR
 - Converse.js version 6.0.1 and some recent `HEAD`.

**Additional context**

Observed often while investigating other issues, so I haven't investigated that much or determined what configuration (if any) is relevant.

**Comment by jcbrand** [comment]
Closing, since this is for Converse 6.
