### ISSUE TITLE
Further archives are not fetched after join

### ISSUE THREAD

**Issue by Zash** [conversejs/converse.js#2130]
**To Reproduce**
1. Connect, login etc
2. Join a MUC known to have larger archives than what is fetched on join.
3. Scroll up

**Expected behavior**
More history is fetched

**Environment (please complete the following information):**
 - Debian 10 with i3
 - Firefox 78.0.1 flatpak
 - Converse.js version 78925b011de1f2c36d16cbe61a6c72f754d9d14d

**Comment by Zash** [comment]
`git bisect` says (assuming I bisected correctly):
> b5d57f0ef80eb6287f0bb72db80e2448c4c89ea8 is the first bad commit

**Comment by licaon-kter** [comment]
Yes, https://github.com/conversejs/converse.js/issues/1637 

Thanks for bisecting

**Comment by Zash** [comment]
Ah, I searched for "mam" and "archives", so I did not see that issue. Feel free to close / merge as a duplicate.
