### ISSUE TITLE
Make onboarding easier by providing more/better documentation for new devs.

### ISSUE THREAD

**Issue by guusdk** [conversejs/converse.js#2132]
It is quite hard for new developers to get involved with this project. To make things easier, documentation could be improved to explain to new developers exactly how to get started.

**Comment by guusdk** [comment]
@bernard-ng As you are one of the newest people, I would like you to tell us what information you were missing when you just got started.

**Comment by psyduck1203** [comment]
Hey can i work on this issue ?

**Comment by guusdk** [comment]
Absolutely. All help is welcome.

**Comment by jcbrand** [comment]
No progress was made here. I don't see the need for a dedicated ticket for this. Converse has fairly extensive documentation. It can definitely be improved, but the existence of this ticket doesn't seem to help much.
