### ISSUE TITLE
'undefined' in participant title text

### ISSUE THREAD

**Issue by Zash** [conversejs/converse.js#2133]
**Describe the bug**
The title text (aka mouse over text) starts with "undefined", e.g. "undefined This user can send messages in this groupchat". I think it's supposed to be the JID, but that's unavailable in semi-anonymous groupchats.

**To Reproduce**
1. Join a semi-anonymous room as a non-moderator
2. Point at someone in the participant list
3. Wait for title text popup.

**Expected behavior**
I guess the text should start with "This user ...", which is what it does in 6.0.1.

**Screenshots**
![image](https://user-images.githubusercontent.com/197474/87108576-ec951c00-c262-11ea-970e-11033468a4f9.png)

**Environment:**
 - Desktop, Debian 10, i3
 - Firefox versions: 68.10.0 ESR, 78.0.1 (flatpak)

**Additional context**

```js
	converse.initialize({
		"authentication" : "anonymous",

		"auto_join_rooms" : [
			"room@conference.example.com",
		],
		"auto_login" : true,
		"bosh_service_url" : "/bosh",
		"jid" : "anon.example.com",
	});
```

**Comment by bernard-ng** [comment]
@jcbrand how is this *participant title generated*  ?  I want to fix this

**Comment by jcbrand** [comment]
@bernard-ng: Looks like `undefined` gets added here: https://github.com/conversejs/converse.js/blob/4534a343d6da2251d5fd6295d3da89ea378ffa01/src/templates/occupant.js#L16

You might have to do some further debugging to see and understand why the JID is undefined.

**Comment by jcbrand** [comment]
@dkbearsong: After the version 7 release, we'll change the file structure to better group files that belong to a particular plugin together. Hopefully this will make it easier to grok for newer users.

In a semi-anonymous room where there is no JID available, it should fall back to the user's nickname.
