### ISSUE TITLE
MUC - mobile browsers - no way to go back to roster

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/converse.js#2137]
HEAD (https://github.com/conversejs/converse.js/commit/6a6d0806793d4e4bbfde26ae9ca4f6167b823b26), Firefox Fennec 68, Firefox Klar 8.4.0

**Comment by poVoq** [comment]
Happens also in embedded Chromium (qtwebengine).

**Comment by poVoq** [comment]
Can confirm this is fixed now in the latest master. Thanks!
