### ISSUE TITLE
XEP-0319: Last User Interaction in Presence

### ISSUE THREAD

**Issue by msounthar** [conversejs/converse.js#2143]
**Is your feature request related to a problem? Please describe.**
Converse updates the user presence to away based on user's idle time out, is it also possible to display the exact time the user went to idle and offline? Ejabberd has the module mod_last() for tracking users last activity on the server side, was this integrated with converse? I guess we need server support for this feature.

**Describe the solution you'd like**
Users can see how long their contacts are away or offline, based on their last activity.

**Describe alternatives you've considered**
xep-0012 and xep-0319 seem to be related to this feature.

**Comment by jcbrand** [comment]
Looks like XEP-0319 provides what you want.

**Comment by aprilsacil** [comment]
It can also be: XEP-0012: Last Activity

**Comment by Echolon** [comment]
I will close this in favor of https://github.com/conversejs/converse.js/issues/1315
