### ISSUE TITLE
Why is the git workflow breaking?

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/converse.js#2146]
Every time the deps are modified  I get:
```
error: Your local changes to the following files would be overwritten by merge:
        package-lock.json
Please commit your changes or stash them before you merge.
Aborting
```
I did not modify this, is the build process doing it?

I need to `git reset --hard; git pull` to get it to update.

**Comment by jcbrand** [comment]
Yes, the build process is updating that file.

It can happen sometimes, for example if newer packages are available than are pinned in the package-lock.json (it then gets updated).

If you see that error, just run `git stash` before `git pull`.
