### ISSUE TITLE
network and ui issues when running 6.0.1 dev locally

### ISSUE THREAD

**Issue by bessiejiang** [conversejs/converse.js#2154]
Hey guys, I pulled the latest code on master branch and generated the two files `converse.min.css` and `converse.min.js` using `npm run build` locally, I tried to run it, but the UI seems strange(e.g., losing emoji, tool options) and it is stuck when I want to send messages(e.g. when I want to send a message, I click on `return`, nothing happens).

Any suggestions?

![image](https://user-images.githubusercontent.com/51675457/88244270-2ba27480-cc48-11ea-899f-747ce3a2d514.png)
![image](https://user-images.githubusercontent.com/51675457/88244300-41b03500-cc48-11ea-985a-686dacf77a9a.png)
![image](https://user-images.githubusercontent.com/51675457/88244323-57255f00-cc48-11ea-80e5-f7b0858cbdc6.png)
![image](https://user-images.githubusercontent.com/51675457/88244349-686e6b80-cc48-11ea-9322-e21dbf01a206.png)

**Comment by licaon-kter** [comment]
The errors are pretty verbose, you need other js files too.

Try to `make dist` and use the _whole dist folder_.

**Comment by jcbrand** [comment]
The main error appears to be `GET file:///dist/emojis.js`.

Looks like you're trying to load Converse via `file:///`. That won't work, you need a web server.

You can run `make serve` and then go to `https://localhost:8000/dev.html`. You'll want to update the file `dev.html` to add your own configuration settings.

**Comment by bessiejiang** [comment]
> The main error appears to be `GET file:///dist/emojis.js net::ERR_FILE_NOT_FOUND`.
> 
> Looks like you're trying to load Converse via `file:///`. That won't work, you need a web server.
> 
> You can run `make serve` and then go to `https://localhost:8000/dev.html`. You'll want to update the file `dev.html` to add your own configuration settings.

Thank you, just got it up.
