### ISSUE TITLE
FIle upload images show up twice

### ISSUE THREAD

**Issue by codecleric** [conversejs/converse.js#2168]
**Describe the bug**
When uploading and image using the toolbar paper-clip icon, the image shows up in the chat twice. 
The first one is a <converse-chat-message-body> tag, and the second is <div class="chat-msg__media">, both container img tags pointing to the newly uploaded image.

**To Reproduce**
1. Go to a private chat or group chat
2. Click on the toolbar paper-clip icon and select an image file.
3. Select 'open' on file selection dialog.
4. See image show up twice.

**Expected behavior**
I expect only one image to show up in the chat.

**Screenshots**
![converse_file-upload-error](https://user-images.githubusercontent.com/14131975/88898566-24f89c00-d20a-11ea-9fe6-10ff86790c5e.png)

**Environment (please complete the following information):**
 - Prosody 0.11.4
 - Firefox 78.0.2 (64-bit)
 - Converse.js version 6.0.1dev

**Additional context**
This is version of converse.js that I build and loaded the assets into the docker container.

**Comment by jcbrand** [comment]
Fixed in #2254
