### ISSUE TITLE
Error while sending message

### ISSUE THREAD

**Issue by muradgaribzada** [conversejs/converse.js#2174]
Hi, i am using converse-6.0.1  + openfire as xmpp server. I've two problems: 
1.  When i am adding contact the opposite not sees friend request
2.  I've enabled auto_subscribe and allow_non_roster_messaging. But when i want to send message to pending contact below error happens: 
` Sorry, an error occurred: <remote-server-not-found xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/>`

Initialization code: 
  ```
converse.initialize({
			auto_list_rooms: false,
			bosh_service_url: webConfig.configs.boshServiceUrl,  
			hide_muc_server: false, 
			prebind: false,
			show_controlbox_by_default: true,
			roster_groups: true,
			debug: true,
			errorAlerts: true,
			warningAlerts: true,
			auto_subscribe:true,
			allow_registration: false,
			allow_non_roster_messaging:true
		});  
```

**Comment by licaon-kter** [comment]
But you can send with another client and you didn't made a typo?

**Comment by muradgaribzada** [comment]
> But you can send with another client and you didn't made a typo?

No, i was unpossible

**Comment by licaon-kter** [comment]
Ok...so close this?

**Comment by muradgaribzada** [comment]
> Ok...so close this?

And, what is the solution to problem?

**Comment by licaon-kter** [comment]
The server  is not accesible...dunno..check your firewall...check your s2s....contact that server admin via email, etcp

**Comment by muradgaribzada** [comment]
> The server is not accesible...dunno..check your firewall...check your s2s....contact that server admin via email, etc

I've opened all required ports in openfire server but the problem remains, also it started to throw error after login:

 ERROR: Error stanza received while trying to fetch archived messages 
  ERROR: <iq xmlns="jabber:client" type="error" id="701905b0-5b25-44ad-8aae-a23193d6bf57:sendIQ" to="ceyhun@openfire-test/converse.js-119091412"><error code="501" type="cancel"><feature-not-implemented xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></iq>

**Comment by licaon-kter** [comment]
@Guus ?
