### ISSUE TITLE
Is there any way to add contact list by default for an anonymous User

### ISSUE THREAD

**Issue by sahaliatarek** [conversejs/converse.js#2189]
**Hello**
I am using converseJs 6, and I am wondering is there is any way to add programmatically the list of contacts by default; I know I can use _converse.api.contacts.add('buddy@site.com'); However, this does not work for anonymous users.

any clue ??

**Comment by jcbrand** [comment]
> However, this does not work for anonymous users.

What happens when you try it for anonymous users?
