### ISSUE TITLE
uploadFile() method throws exception

### ISSUE THREAD

**Issue by muradgaribzada** [conversejs/converse.js#2200]
Hi, i'm using converse.js-6.0.1 + openfire. Hi, I’ve installed HTTP File Upload plugin on the Openfire server. But file transfer not works in converse.js. 
After uploading the file I’m getting **PUT http://new2.ccms.gov.az:7443/httpfileupload/e5699182-c503-40d5-b6f7-c40cc9687a03/config.properties net::ERR_NAME_NOT_RESOLVED** error in the browser console and file lost from chat. Please help me to solve the problem

**Comment by jcbrand** [comment]
ERR_NAME_NOT_RESOLVED means that the domain name cannot be resolved. This doesn't look to be related to Converse.

This issue tracker is used for bug reports and feature requests, not for general support in setting up Converse.
