### ISSUE TITLE
Unread message indicator in browser tab

### ISSUE THREAD

**Issue by zuglufttier** [conversejs/converse.js#2216]
Currently you have no information whether there are unread messages in converse.js unless you really open the tab in the browser.

I, and some of my friends, would be very happy if there was just a small indicator like a '*' in the browser tab so that you know that there are unread messages.

**Comment by licaon-kter** [comment]
Install https://github.com/conversejs/community-plugins/tree/master/packages/browsertab ?

**Comment by zuglufttier** [comment]
Oh... Where exactly do I have to put the plugins. @licaon-kter ?

**Comment by licaon-kter** [comment]
Read: https://github.com/conversejs/community-plugins

**Comment by zuglufttier** [comment]
I certainly did! I didn't see that the structure is already shown in the github repo and the packages folder is the one I need.

Thank you, problem solved!
