### ISSUE TITLE
Group chat scroll up event not trigger  

### ISSUE THREAD

**Issue by PrakashPaul** [conversejs/converse.js#2227]
1. Group chat having 100 offline messages.
2. page size is 50
3. it is loading last 50 messages.
4. scroll bar is there but scroll up event not working hence archived messages (unread) not fetched.

NOTE: scrollbar is present for both one-on-one chat and group chat, though for one-on-one chat scroll event triggering and calling onScroll () method. but scroll event not triggering for group chat. is there any suggestion for setting or code?

**Comment by PrakashPaul** [comment]
> /close as duplicate #2134 ?

not the same, it is not fetching or triggering the scroll event at all

**Comment by licaon-kter** [comment]
Are you running HEAD? 

If you scroll down a bit then back up it doesn't get them?

**Comment by jcbrand** [comment]
Why do people insist on not using the bug report template when reporting bugs?

Do they somehow not see it? Or do they just unthinkingly remove all pre-existing text in a bug report?

The bug report template includes relevant questions, such as which version of Converse you're using. Without that, your issue is largely a waste of time.

**Comment by PrakashPaul** [comment]
> Are you running HEAD?
> 
> If you scroll down a bit then back up it doesn't get them?
> 
> Scroll by scroll bar or mouse wheel?

using scroll bar, no effect scroll up/down multiple times

**Comment by PrakashPaul** [comment]
> Why do people insist on not using the bug report template when reporting bugs?
> 
> Do they somehow not see it? Or do they just unthinkingly remove all pre-existing text in a bug report?
> 
> The bug report template includes relevant questions, such as which version of Converse you're using. Without that, your issue is largely a waste of time.

Sorry for not following the format
just modified the details 

**Describe the bug**
Group chat (MUC) scroll up event not trigger

**To Reproduce**
Steps to reproduce the behavior:
1. Group chat having 100 offline messages.
2. page size is 50
3. it is loading last 50 messages.
4. scroll bar is there but scroll up event not working hence archived messages (unread) not fetched.

**Expected behavior**
Scroll up event should load 50 or available previous messages. 

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Environment (please complete the following information):**
 - Desktop
 - Chrome
 - version v6.0.1dev

**Additional context**
scrollbar is present for both one-on-one chat and group chat, though for one-on-one chat scroll event triggering and calling onScroll () method. but scroll event not triggering for group chat. 

for converse-mam-views I can see we are binding event 
if (!this.disable_mam) {
                    this.content.addEventListener('scroll', debounce(this.onScroll.bind(this), 100));
                }
				
but not same not visible to me for MUC.
is there any suggestion for setting or code?

**Comment by licaon-kter** [comment]
Try with HEAD...

**Comment by PrakashPaul** [comment]
> Try with HEAD.
Please share more details or link or documents how I can try with HEAD.
Appreciate your help..

**Comment by licaon-kter** [comment]
Read the README and documentation on how to build I guess.

**Comment by PrakashPaul** [comment]
in converse-mam-views.js there is a method name 
renderChatArea () looks like not called any were and it's looks to me the issue. group chat scroll event is not working...
Can someone please suggest if finding is correct? and right place to call the renderChatArea ()?

**Comment by jcbrand** [comment]
This bug report for is for an old unsupported version of Converse.

Closing.
