### ISSUE TITLE
Frequent disconnect for some Virtual desktop infrastructure (VDI) users.

### ISSUE THREAD

**Issue by PrakashPaul** [conversejs/converse.js#2230]
**Describe the bug**
Frequent disconnect for some Virtual desktop infrastructure (VDI) users.
not for every user, approx 5% 
 
**To Reproduce**
1. Login into application.
2. After some time minimize the browser.
3. after 5 -10 mins it is noticed user encountered multiple disconnect and reconnect.
4. Due to this sometimes some messages get missing for users.

**Expected behavior**
Should not disconnect very frequently. 

**Environment (please complete the following information):**
 - Virtual desktop infrastructure (VDI)
 - Chrome Version 72.0.3626.121
 - Version v6.0.0

**Additional context**
Logs showing different origin for different user 
Ex 1:  
Source : i18n.js:11
Error: chat.***.com/:1 Failed to load resource: the server responded with a status of 404 (Invalid SID value.)
logs
2log.js:66  2020-09-03T12:01:36.565Z WARNING: Message Archive Management (XEP-0313) not supported by this server 
log @ i18n.js:11
log.js:66  2020-09-03T12:01:36.933Z WARNING: Message Archive Management (XEP-0313) not supported by this server 
log @ i18n.js:11
log.js:66  2020-09-03T12:01:37.179Z WARNING: Message Archive Management (XEP-0313) not supported by this server 
log @ i18n.js:11
log.js:66  2020-09-03T12:01:37.436Z WARNING: Error: not allowed to fetch member list for MUC clt_agents@conference.chat.***.com 
log @ i18n.js:11
log.js:66  2020-09-03T12:01:37.436Z WARNING: <iq xmlns="jabber:client" type="error" id="697eaf74-f0c5-41f5-80f1-28f189cea53b:sendIQ" from="clt_agents@conference.chat.***.com" to="patricia.baldwin@chat.***.com/qonnect.js-60836381"><query xmlns="http://jabber.org/protocol/muc#admin"><item affiliation="member"/></query><error code="403" type="auth"><forbidden xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></iq> 
log @ i18n.js:11
log.js:64  ERROR: request id 26.1 error 0 happened
log @ i18n.js:11
log.js:66  2020-09-03T12:01:53.016Z WARNING: request errored, status: 0, number of errors: 1 
log @ i18n.js:11
chat.***.com/:1 Failed to load resource: the server responded with a status of 404 (Invalid SID value.)
log.js:64  ERROR: request id 34.1 error 404 happened
log @ i18n.js:11
log.js:66  2020-09-03T12:05:44.463Z WARNING: request errored, status: 404, number of errors: 1 
log @ i18n.js:11
log.js:72  2020-09-03T12:05:44.465Z INFO: Status changed to: DISCONNECTING  

Ex 2:  
Error: 7443/http-bind/:1 Failed to load resource: the server responded with a status of 404 (Invalid SID value.)

logs
log.js:66  2020-09-10T13:52:53.154Z WARNING: Message Archive Management (XEP-0313) not supported by this server 
log @ log.js:66
warn @ log.js:89
e.onMAMError @ converse-mam.js:134
log.js:66  2020-09-10T13:52:53.882Z WARNING: Message Archive Management (XEP-0313) not supported by this server 
log @ log.js:66
warn @ log.js:89
e.onMAMError @ converse-mam.js:134
log.js:66  2020-09-10T13:52:53.884Z WARNING: Message Archive Management (XEP-0313) not supported by this server 
log @ log.js:66
warn @ log.js:89
e.onMAMError @ converse-mam.js:134
:7443/http-bind/:1 Failed to load resource: the server responded with a status of 404 (Invalid SID value.)
log.js:64  ERROR: request id 190.1 error 404 happened
log @ log.js:64
error @ log.js:81
$t.error @ converse-core.js:1272
_onRequestStateChange @ bosh.js:665
log.js:66  2020-09-10T13:52:57.602Z WARNING: request errored, status: 404, number of errors: 1 
log @ log.js:66
$t.log @ converse-core.js:1271
warn @ core.js:848
_hitError @ bosh.js:461
_onRequestStateChange @ bosh.js:666
log.js:72  2020-09-10T13:52:57.605Z INFO: Status changed to: DISCONNECTING

**Comment by licaon-kter** [comment]
You do have MAM? The lack of it vould explain missing messages.

What server? What connection (bosh? websocket?)? Stream management is enabled?

**Comment by jcbrand** [comment]
The problem appears to be this: `the server responded with a status of 404 (Invalid SID value.)`

It seems that your BOSH session ID (SID) expires server-side, and when Converse tries to use it again, the server rejects it.
I dont' think there's anything we can do about that in Converse.

When something like that happens, Converse should try to reconnect, based on your comment that appears to be the case.
If you experience missing messages, then *that* is a bug and something we can try to fix, but I don't see anything else to do here.

BTW, if you're using BOSH, then you shouldn't enable stream management as well. Turn that off, otherwise that might also cause weird problems, including missing messages.
