### ISSUE TITLE
One-on-one ofline user missing messages.

### ISSUE THREAD

**Issue by PrakashPaul** [conversejs/converse.js#2247]
Describe the bug
while testing noticed for One-on-One chat. when user1 is offline and User2 push messages more than the page size to User1, say page size is 50, User 2 messaged 60 messages to user 1. 
When user1 login user 1 will get 50 messages, first message and last 49 messages, rest all messages 2 to 11 are missing and scroll up event also not able to fetch missing messages, due to first message.

To Reproduce
1. We need 2 users.
2. User 1 not login.
3. User 2 login.
4. Sent 60 messages to user 1 (more than page size)
5. User 1 login.
6. Will get 50 messages, msg 1 and last 49 msgs

Environment (please complete the following information):
LAPTOP(window 10)
Chrome Version 72.0.3626.121
Converse Version v6.0.0

Additional context
While debug noticed... 
When User 1 login. Anyhow system requested server 60 times for archive messages (which is equivalent to offline message count)
sample: 
core.js:2152 <iq type="set" xmlns="jabber:client" id="b9473bdf-143f-4fa4-ac2b-2d3d33fbdf57:sendIQ"><query xmlns="urn:xmpp:mam:2" queryid="id5d273a44-57cb-418e-9f7c-2c5bf8e6cb40"><x xmlns="jabber:x:data" type="submit"><field var="FORM_TYPE" type="hidden"><value>urn:xmpp:mam:2</value></field><field var="with"><value>TestUser2@XXXXXXX.XX.qor.com</value></field></x><set xmlns="http://jabber.org/protocol/rsm"><max>50</max><before></before></set></query></iq>

NOTE: if logs needed I can share

**Comment by PrakashPaul** [comment]
core.js:2152 <iq type="set" xmlns="jabber:client" id="b9473bdf-143f-4fa4-ac2b-2d3d33fbdf57:sendIQ"><query xmlns="urn:xmpp:mam:2" queryid="id5d273a44-57cb-418e-9f7c-2c5bf8e6cb40"><x xmlns="jabber:x:data" type="submit"><field var="FORM_TYPE" type="hidden"><value>urn:xmpp:mam:2</value></field><field var="with"><value>TestUser2@XXXXXXX.XX.qor.com</value></field></x><set xmlns="http://jabber.org/protocol/rsm"><max>50</max><before></before></set></query></iq>

**Comment by licaon-kter** [comment]
Can you test with HEAD?

**Comment by PrakashPaul** [comment]
issue is reproducable when  trusted: false.

**Comment by PrakashPaul** [comment]
when I added XMLdebugger, noticed. too many message request for same fromJId to ToJid, and numbers are more or less then ofline messages...
