### ISSUE TITLE
The WebSocket connection could not be established or was disconnected.

### ISSUE THREAD

**Issue by motapod** [conversejs/converse.js#2249]
Hi, im triying to connect with a ejabberd server, ejabberd accept the connect in registration form (converse dont return me nothing), i already have an acount in the server but when i put example 'myuser@serverdomainip:port' throw me 'Connection failure

The WebSocket connection could not be established or was disconnected.
converse.js'

anyone know how to solve this? i'm trying with ports: 5222, 5280, 5223, 5443

**Comment by licaon-kter** [comment]
You don't put a port anywhere.

Is this your server that you setup?

How do you try to connect? Where is Converse hosted?

**Comment by motapod** [comment]
i put the port in 'myuser@serverdomainip:PORT' in the xmpp adress in the website. (also i don t change any of the source code of the git)
the server is ejabberd we used the default instalation for this
i m trying to connect in the localhost of my computer to a server in a vm hosted by aws.

**Comment by jcbrand** [comment]
The port should be part of the [websocket_url](https://conversejs.org/docs/html/configuration.html#websocket-url) setting, not your JID.
