### ISSUE TITLE
Images are shown twice in chat.

### ISSUE THREAD

**Issue by ChaosKid42** [conversejs/converse.js#2252]
Sent and received images are shown twice in chat:

**To Reproduce**
1. Send image using attach button
2. Image is shown twice in chatbox

**Expected behavior**
Only show image once.

**Screenshots**
![img_twice](https://user-images.githubusercontent.com/15179432/94466129-3b4ab600-01c1-11eb-8518-15f465dfdfcd.png)

**Environment (please complete the following information):**
 - Desktop
 - Browser Chrome
 - Converse.js latest head

**Comment by ChaosKid42** [comment]
Probably a duplicate of #2168.

**Comment by licaon-kter** [comment]
Doesn't look fixed.... it this intended to show image AND link?



![image](https://user-images.githubusercontent.com/2282799/95352324-a8410880-08b1-11eb-926c-789f0a83dfac.png)

**Comment by ChaosKid42** [comment]
That was at least my intention. Background: The clients I know (converse.js, Conversations) send the Image URL as plaintext and as OOB-data. Usually, they should point at the same destination. But they may not. Therefore the plaintext is rendered as an image and OOB-data is rendered as a link. btw: for other media (audio, video) that's the same, i.e. they are also rendered as media and link.

**Comment by licaon-kter** [comment]
Why not deduplicate it then?
