### ISSUE TITLE
Add custom toolbar buttons

### ISSUE THREAD

**Issue by VirginieGarcin** [conversejs/converse.js#2263]
Currently, we can customize visible_toolbar_buttons just by setting true or false on the preset buttons:

```
{
    call: false,
    spoiler: false,
    emoji: true,
    toggle_occupants: true
}
```
It would be nice to have custom buttons, to allow to trigger custom actions.

Maybe setting them this way: 
```
{
    call: false,
    spoiler: false,
    emoji: true,
    toggle_occupants: true,
    others: [ myCustomButton: { class: "myCustomClass", callback: myCallbackFunction } ]
}

```

**Comment by jcbrand** [comment]
There is a way to add custom toolbar buttons.

It's not as easy as what you're proposing, but it is more powerful.

The way you do it, is to write a plugin that listens to the `getToolbarButtons` event, and which then adds your own button to the list that's provided to the event handler.

For an example, see how the `converse-omemo` plugin adds its own button to the toolbar: 
https://github.com/conversejs/converse.js/blob/30d550596bb39245add6d98a9d4cc2409d52d8fe/src/converse-omemo.js#L485

**Comment by VirginieGarcin** [comment]
Awesome ! Will try that. Thank you !
