### ISSUE TITLE
Allow to mark up messages in for example Markdown or LaTeX

### ISSUE THREAD

**Issue by paulmenzel** [conversejs/converse.js#2265]
**Is your feature request related to a problem? Please describe.**
Instant messages have become more than short messages, but are now used for longer texts too. That requires some formatting features. Colleagues, especially mathematicians, using *Zulip* like [the possibility to use Markdown to format text and even add blocks of LaTeX code, which is then displayed](https://zulipchat.com/help/format-your-message-using-markdown).

**Describe the solution you'd like**
I’d be great if converse.js would support marking up text too.

**Describe alternatives you've considered**
For a non-centralized environment like XMPP without only one client, it’s hard to find a standard, so another solution would be to do it on the server somehow. For example, there is an outdated(?) Prosody module [mod_latex](https://modules.prosody.im/mod_latex.html).

**Additional context**
Zulip says for LaTeX they are using [KaTeX](https://katex.org/).

**Comment by jcbrand** [comment]
For markdown-like support, we have XEP-0393 and an associated ticket: https://github.com/conversejs/converse.js/issues/1083

@XaviFP is working on that currently, so we'll likely have support in the near term.

LaTex support is something which I think can be done as a [community-plugin](https://github.com/conversejs/community-plugins). I don't see a place for it in the core repo, since it adds a new dependency that most users don't need.

**Comment by paulmenzel** [comment]
> For markdown-like support, we have XEP-0393 and an associated ticket: #1083
> 
> @XaviFP is working on that currently, so we'll likely have support in the near term.

Nice. Thank you for the pointer. Quickly skimming XEP-0393, it is missing some formatting options like lists. Sorry, I am new to XMPP, but should a new XEP be proposed then for the extension?

> LaTex support is something which I think can be done as a [community-plugin](https://github.com/conversejs/community-plugins). I don't see a place for it in the core repo, since it adds a new dependency that most users don't need.

Sounds good. Should this ticket be dedicated to that task then?

**Comment by jcbrand** [comment]
>  should a new XEP be proposed then for the extension?

That XEP is still in `Proposed` state, so you could instead propose to add the feature to that XEP.

If you're interested in doing this, write to the XSF standards mailing list (standards@xmpp.org) to gather feedback. The author of the XEP will likely respond.

> Should this ticket be dedicated to that task then?

This issue tracker is for the core app and not the community plugins. Can you please make a similar ticket there? Then I'll close this one.

https://github.com/conversejs/community-plugins

**Comment by ecxod** [comment]
> For markdown-like support, we have XEP-0393 and an associated ticket: #1083
> 
> @XaviFP is working on that currently, so we'll likely have support in the near term.
> 
> LaTex support is something which I think can be done as a [community-plugin](https://github.com/conversejs/community-plugins). I don't see a place for it in the core repo, since it adds a new dependency that most users don't need.

It is true that 99% of the population does not use algebra, yet we need algebra. But there is https://latex.js.org/ so we will not give up hope.
