### ISSUE TITLE
Mobile: Controlbox bleeds though

### ISSUE THREAD

**Issue by poVoq** [conversejs/converse.js#2273]
**Describe the bug**
The new master seems to fail loading message history on 1:1 chats, that are working fine with the last release 6.0.1.
Also when failing to load the history the controlbox bleeds though on the mobile view mode (see screenshot).

**Screenshots**
![bc949b78_screenshot20201006_184325421](https://user-images.githubusercontent.com/940360/95246973-c7ce2780-0804-11eb-8320-4c478bb8fdf5.png)

**Environment (please complete the following information):**
 - Desktop or Mobile? mobile
 - Browser [e.g. Chrome, Firefox] embedded chromium
 - Converse.js version [e.g. 4.2.0] 6.0.1dev / 7.0 (compiled from source 20201006)

**Comment by jcbrand** [comment]
@poVoq: Can you check wether this commit fixes the message history issue?
https://github.com/conversejs/converse.js/commit/f68eb65cd79b4bd5edd67d0d87c5f01e22f653df

**Comment by poVoq** [comment]
Hmm, I recompiled from the current master and first it appeared to still happen, it the problem is somewhat different now.

First I get the above screen for a few seconds, but then it seems to load the history, however the 1:1 chats become totally unusable as the touch scrolling stops working and in some of the 1:1 chats not even the message text input is shown. Super odd error and I already completely reset all the browser storage and everything.

**Comment by poVoq** [comment]
On latest master (compiled 2020-10-31) this is somewhat fixed as MAM messages are loaded fine.
However before loading the history is complete, the background control-box still bleeds though for a short time.

**Comment by poVoq** [comment]
As fullscreen mode works and looks the same as mobile as of 7.0.6. and it does not happen there at least (did not reconfirm in mobile viee mode), I guess this can be closed.
