### ISSUE TITLE
Chatbox day indicator not correctly formatted, according to the i18n configuration

### ISSUE THREAD

**Issue by abevieiramota** [conversejs/converse.js#2290]
**Describe the bug**
The date that is shown at the top of a chat box is not being correctly formatted according to the i18n configuration. Using `i18n = 'pt-BR'` I expected the date to be formatted in brazilian portuguese language, but it's being formatted in english.

**To Reproduce**
1. Open conversejs with `i18n: 'pt_BR'` configuration
2. Open a chatbox that has a message and look at the day indicator

**Expected behavior**
I expected the day indicator to be localized with the locale configured with `i18n`.

**Screenshots**
![image](https://user-images.githubusercontent.com/3942896/96021028-42aaca00-0e25-11eb-8ed7-1ed98851af6e.png)

**Environment (please complete the following information):**
 - Desktop or Mobile? = Desktop
 - Browser [e.g. Chrome, Firefox] = Chrome Version 86.0.4240.75
 - Converse.js version = 6.0.1

**Comment by jcbrand** [comment]
Looks like DayJS doesn't get initialized with the right locale, or perhaps initialized too late.

Here's where it gets initialized: https://github.com/conversejs/converse.js/blob/e49f97472a797c9722e5b51f65c159dc6ca1bb14/src/i18n/index.js#L81

@guusdk: Maybe this is something that @bernard-ng could take a look at?

**Comment by bernard-ng** [comment]
okay

**Comment by bernard-ng** [comment]
@abevieiramota I've just tried to reproduce the bug with another locale, with the "fr" for example, it works without problem.

while checking the [list of locales available](https://github.com/iamkun/dayjs/tree/dev/src/locale) in dayjs, I see that "pt_BR" is not there, a solution would be to use either "pt" or "br" as locale instead of "pt_BR"

**Comment by jcbrand** [comment]
There is [pt-br](https://github.com/iamkun/dayjs/blob/dev/src/locale/pt-br.js), so maybe it's just a matter of having a `-` instead of `_` and making it all lowercase?

**Comment by bernard-ng** [comment]
> There is [pt-br](https://github.com/iamkun/dayjs/blob/dev/src/locale/pt-br.js), so maybe it's just a matter of having a `-` instead of `_` and making it all lowercase?
 
Oh my bad, let me try it
