### ISSUE TITLE
Incomplete pt_BR translation

### ISSUE THREAD

**Issue by abevieiramota** [conversejs/converse.js#2291]
**Describe the bug**
A few strings aren't translated to portuguese, even though they are translated in the locale file.

**To Reproduce**
1. For example, the string `"%1$s is now a member of this groupchat"` is translated in https://github.com/conversejs/converse.js/blob/master/src/i18n/pt_BR/LC_MESSAGES/converse.po#L389 but not in the dist locale file (pt_BR-LC_MESSAGES-converse-po.js).

**Expected behavior**
All the translated strings in the `locale/pt_BR/LC_MESSAGES/converse.po` to be present in the build.

**Screenshots**
![image](https://user-images.githubusercontent.com/3942896/96025635-c667b500-0e2b-11eb-84e6-79f55a0b79a5.png)

The red box contains an untranslated string. The green box contains a correctly translated string.

**Environment (please complete the following information):**
 - Desktop or Mobile? - Desktopn
 - Browser [e.g. Chrome, Firefox] - Chrome Version 86.0.4240.75
 - Converse.js version [e.g. 4.2.0] - 6.0.1

**Comment by jcbrand** [comment]
Looks like DayJS doesn't get initialized with the right locale, or perhaps initialized too late.

Here's where it gets initialized: https://github.com/conversejs/converse.js/blob/e49f97472a797c9722e5b51f65c159dc6ca1bb14/src/i18n/index.js#L81

@guusdk: Maybe this is something that @bernard-ng could take a look at?

**Comment by jcbrand** [comment]
If you have a checkout of the repo, you can run `make clean && make dist` to regenerate all dist files.

Looks to me like all the translations are there.
