### ISSUE TITLE
One-on-one ofline user missing messages when "Show notifications" allow or block popup.

### ISSUE THREAD

**Issue by PrakashPaul** [conversejs/converse.js#2292]
**Describe the bug**
while testing noticed for One-on-One chat. when user1 is offline and User2 push messages more than the page size to User1, say page size is 50, User2 messaged 60 messages to user1.
When user1 login first time (browser don't have notification setting) user1 will get 50 messages, first message and last 49 messages, rest all messages 2 to 11 are missing and scroll up event also not able to fetch missing messages, due to first message.

To Reproduce

We need 2 users.
User1 not login for chat app.
User1 deleted all browser history.
User 2 login for chat app.
Sent 60 messages to user1 (more than the page size)
User 1 login for chat app.
user will get "Show notifications" allow or block popup. ones it is allowed
user1 Will only get 50 messages, msg 1 and last 49 msgs
also the messages counter showing wrong info.

Environment (please complete the following information):
LAPTOP(window 10)
Chrome Version 72.0.3626.121
Converse Version v6.0.0

![notificationError](https://user-images.githubusercontent.com/4025676/96025581-505f5000-0e23-11eb-947f-7c84c4cb0ac1.png)

**Comment by jcbrand** [comment]
>  user1 will get 50 messages, first message and last 49 messages, rest all messages 2 to 11 are missing and scroll up event also not able to fetch missing messages, due to first message.

I believe this issue was fixed recently in this commit:
https://github.com/conversejs/converse.js/commit/48f119b673cb3258ab93f20630aadeccba2007b5
