### ISSUE TITLE
Error while connecting to XMPP server

### ISSUE THREAD

**Issue by yeshaParmar** [conversejs/converse.js#2301]
I want to connect to the XMPP server through converse js. Please find the code snippet I use for conver.intialise() method:

```
function InitialiseConverse() {
    converse.initialize({
        authentication: 'login',
        auto_login: true,
        bosh_service_url: 'http://xmpp.abc.eng.xyz.local:5443/bosh', 
        jid: '857b3f0a-a777-11e5-bf7f-feff819cdc9f.flow.prefix' + '@xmpp.abc.eng.xyz.local',
        password: '52a3245bb075d926ab10fdeee4b00d5ae4ee7bc78dbb4dac4bdb867034e13190',
        // auto_join_rooms: [
        //     'anonymous@conference.nomnom.im',
        // ],
        // notify_all_room_messages: [
        //     'anonymous@conference.nomnom.im',
        // ],
        singleton: true,
        muc_nickname_from_jid: true,
        visible_toolbar_buttons: {
            toggle_occupants: false,
        },
        // locales_url: '../locale/{{{locale}}}/LC_MESSAGES/converse.json',
        // auto_register_muc_nickname: true,
        // show_client_info: false,
        // show_controlbox_by_default: false,
 });
}
```
I am getting this error in the console when this method is called. 
![error while connecting to XMPP server](https://user-images.githubusercontent.com/28630848/96412448-ce4a9f00-1207-11eb-8c72-5748875a5a8a.png)

What is the exact meaning of this error? as I am not able to debug the XMPP server code and logs, all I have is the client-side converse js code. Please suggest options to debug the issue. Thanks in advance.

**Comment by jcbrand** [comment]
Looks like Converse made a [XEP-0030 Service Discovery] query against one of the entities advertised by your XMPP server, but that entity doesn't support service discovery queries.
