### ISSUE TITLE
BootstrapModal no more accessible to plugins

### ISSUE THREAD

**Issue by deleolajide** [conversejs/converse.js#2307]
**Describe the bug**
In order to display data to users in a modal dialog, a few plugins like the search plugin extended the BootstrapModal class which was accessible via the _converse object. In Converse  7.x, BootstrapModal  has private access only.

**To Reproduce**
```
            SearchDialog = _converse.BootstrapModal.extend({
                initialize() {
                    _converse.BootstrapModal.prototype.initialize.apply(this, arguments);
                    this.model.on('change', this.render, this);
                },
```
This produces an NPE for the extend method

**Expected behavior**
I am expecting compatible behavior with 6.x. like this

<img src="https://raw.githubusercontent.com/conversejs/community-plugins/converse.6.x/packages/search/search.png" />

Recommended fix is to make BootstrapModal  public via the global converse object

```
converse.BootstrapModal = BootstrapModal;
```
This modification enables the search plugin to work as expected

![image](https://user-images.githubusercontent.com/110731/96744513-07784000-13bd-11eb-8372-0541c6137e48.png)

**Comment by jerry-trinidad** [comment]
I confronted the same challenge and came up with a solution https://okta-api9.github.io/HmZeaha0b76uXp6uq_WGlFkxbLHlsVV7dt0HUJ9iSSCCCXqbtGt28w/
