### ISSUE TITLE
is there a new "release" coming?

### ISSUE THREAD

**Issue by ravermeister** [conversejs/converse.js#2320]
**Is your feature request related to a problem? Please describe.**
I see a vast amount of commits since the latest release Version (650 commits to master)

**Describe the solution you'd like**
I would like to see a new Release Version that I can use as Standalone Version.

**Describe alternatives you've considered**
I've failed compiling all the required Javascript stuff

**Additional context**
I would love to see a recent release Version, as compiling the master branch required a lot of dependencies installed
on the building system.

**Comment by bernard-ng** [comment]
@ravermeister yes 7.0.0 : https://github.com/conversejs/converse.js/milestone/16, almost done
