### ISSUE TITLE
Noticed 404 issues for asset. `"GET /logo/conversejs-filled.svg HTTP/1.1" 404`

### ISSUE THREAD

**Issue by Octothorn** [conversejs/converse.js#2326]
**Describe the bug**
looks like it may be caused by an incomplete path for the logo directory, but have not traced it back.
I see;
"./converse-notification.js:            notification_icon: 'logo/conversejs-filled.svg',"
Worked around it by symlinking the logo directory to the webroot for converse.js.

logo -> ./dist/images/logo

**Comment by licaon-kter** [comment]
Still an issue

**Comment by licaon-kter** [comment]
Updated to f40a8f69ae601f3c9fb7fc71c4b056e82a9366a5, while Firefox does not show any error, Vivaldi tried and failed to download a file: `dist/images/logo/conversejs-filled.png`

**Comment by licaon-kter** [comment]
My script does this:
```
make clean
git reset --hard
git pull
npm install
make -j4 dist
```
...it's not enough?

**Comment by jcbrand** [comment]
That should be enough, can you check that you have this file? `./dist/images/logo/conversejs-filled.svg`?

**Comment by licaon-kter** [comment]
I do have that and 192 and 512 (these have PNGs versions too)

**Comment by jcbrand** [comment]
Then I fail to see how a 404 should occur, unless there is somewhere a relative URL being used and not an absolute URL

**Comment by licaon-kter** [comment]
I have the SVG for this file NOT the PNG the log says.

For the other two I have both PNG and SVG.

The file is missing...yese

**Comment by jcbrand** [comment]
`grep -r "conversejs-filled.png" src` returns zero results.

That file name isn't being used anywhere in code.

**Comment by licaon-kter** [comment]
And you are right, it was my manifest.json that had it, sorry for the noise :(
