### ISSUE TITLE
Print clear text desktop notifications for incoming OMEMO messages

### ISSUE THREAD

**Issue by rma-x** [conversejs/converse.js#2343]
Currently when an OMEMO message comes in, the desktop notification only says that an encrypted message has arrived, but there is no way to get the decrypted message text in the notification. It would be nice to have the clear text message in the notification instead, or have a config setting to select between the two variants.

**Comment by Edu93Jer** [comment]
Hi, @rma-x  I am a newbie to this project and would like to contribute it; do you think you can put me in the right direction, please, so I can start helping you guys?

**Comment by jcbrand** [comment]
Fixed in latest master branch.
