### ISSUE TITLE
XEP-0333: Show markers on the UI

### ISSUE THREAD

**Issue by mightymop** [conversejs/converse.js#2347]
**Is your feature request related to a problem? Please describe.**
As asked in https://github.com/conversejs/converse.js/issues/2028#issuecomment-733576531 it would be nice to have
chatmarkers displayed on converse too.

**Describe the solution you'd like**
The 1st checkmark for sending to server (server received msg) - green
The  2nd one, if the receiver (client) got the message - green
Colorize both to blue if the opponent reads / displayed the message (like Whatsapp) 

**Describe alternatives you've considered**
The already existing green checkmark could be colorized to blue or another color as an alternative.

**Additional context**
Maybe it would be nice to arrange the marks on the right?

**Comment by Echolon** [comment]
Is this a duplicate of https://github.com/conversejs/converse.js/issues/324 ?

**Comment by jcbrand** [comment]
Yeah I think so.
