### ISSUE TITLE
Change usage of FontAwesome 

### ISSUE THREAD

**Issue by TheTiGuR** [conversejs/converse.js#2349]
In a webpack project that also uses FontAwesome (e.g. an Angular based project), the font files generate warnings because of name collisions. This may or may not be an actual problem, but in the interest of avoiding warnings it would be good to see this not happening. 
```
WARNING in Conflict: Multiple assets emit different content to the same filename fa-brands-400.eot
WARNING in Conflict: Multiple assets emit different content to the same filename fa-regular-400.eot
WARNING in Conflict: Multiple assets emit different content to the same filename fa-solid-900.eot
WARNING in Conflict: Multiple assets emit different content to the same filename fa-brands-400.woff2
...
```

Two options I see here would be be:
1. Rename the font files (based on FA version?)
    Includes updating the css files accordingly
2. Change to a dependency on the Font Awesome package and have references come from there. 

An alternative I see is updating the css manually on my end, which is fine in and of itself, but makes upgrading harder in the future.

**Comment by jcbrand** [comment]
We're in the process of using SVG for all icons and not fonts. There are only a few more icons using fonts left.
