### ISSUE TITLE
Custom server for register

### ISSUE THREAD

**Issue by LibreHacker** [conversejs/converse.js#2358]
We making page with recommend XMPP for messaging and having custom server for register.
For example using: blabber.im
Need feature alike, people click for (a href) link and having autofill server for register:
https://conversejs.org/fullscreen.html#converse/register#blabber.im

**Comment by jcbrand** [comment]
Have you seen this?

https://conversejs.org/docs/html/configuration.html#registration-domain

**Comment by Echolon** [comment]
@LibreHacker do you have further feedback?

**Comment by Echolon** [comment]
@jcbrand I will close this until a response comes up.

@LibreHacker please comeback anytime with more information.
