### ISSUE TITLE
Roster / Contact List is empty and 1:1 chats don't work

### ISSUE THREAD

**Issue by silberzwiebel** [conversejs/converse.js#2360]
**Describe the bug**
I can't see my contact list nor write 1-to-1 chats.

**To Reproduce**
1. Go to conversejs.org/fullscreen.html
2. Click on login
3. Scroll down to contact list
4. click on a contact
5. no chat window appears
6. logout and back in again
7. contact list is empty

**Expected behavior**
Being able to do 1-to-1 chats.

**Environment (please complete the following information):**
 - Desktop, Windows 10
 - Firefox 78.5.0esr
 - Converse.js version 7.0.3 (the one that runs on conversejs.org)

**Additional context**
Self-hosted prosody server. I cleared `localStorage` with ``localStorage.clear()` to prevent interference, still the same error.

Errors in the console:

```
Uncaught (in promise) TypeError: e is undefined
    comparator converse-roster.js:865
    sort collection.js:477
    sortAndPositionAllItems overview.js:175
    ji events.js:280
    Ei events.js:264
    e events.js:50
    trigger events.js:254
    trigger converse-core.js:443
    populateRoster converse-roster.js:109
````

````
Uncaught (in promise) TypeError: e is undefined
    comparator converse-roster.js:865
    sort collection.js:477
    set collection.js:208
    add collection.js:99
    create collection.js:518
    getGroup converse-rosterview.js:876
    addContactToGroup converse-rosterview.js:880
    addExistingContact converse-rosterview.js:895
    addExistingContact converse-rosterview.js:895
    addRosterContact converse-rosterview.js:905
    initialize converse-rosterview.js:741
    forEach collection.js:344
    each collection.js:340
    initialize converse-rosterview.js:741
    ji events.js:280
    Ei events.js:264
    e events.js:50
    trigger events.js:254
    trigger converse-core.js:443
    populateRoster converse-roster.js:111
converse-roster.js:865:20
````

**Comment by jcbrand** [comment]
@silberzwiebel: I'm unable to reproduce the issue and tracebacks from minified files are often not very helpful.

Can you please try again on https://conversejs.org/debug.html and then give me the traceback from that?

**Comment by silberzwiebel** [comment]
Right now it works just fine with the debug version. I'll use this in the next days/weeks and report back, if it is broken again.

**Comment by Echolon** [comment]
@silberzwiebel have you been able to reproduce? Otherwise I would close the issue

**Comment by silberzwiebel** [comment]
No, I couldn't reproduce. Thanks for asking, though!
