### ISSUE TITLE
Could not restore session for jid: xxxxx@domain/converse.js-77429227 Error message: _restore: no restoreable session. 

### ISSUE THREAD

**Issue by nandinibhaduri** [conversejs/converse.js#2370]
I am using the 7.0.4 version of converse.js and ejabberd as the xmpp server.

I am using the following configuration:

```
converse.initialize({
  bosh_service_url: '../xmpp/http-bind',
  view_mode: 'fullscreen',
  authentication: 'prebind',
  allow_logout: false,
  auto_login: true,
  jid: 'xxxx@domain',
  prebind_url: '../xmpp/prebind.jsp',
  keepalive: true
  });
```

But this doesn't work. I am getting the following error continuously in the console:
Could not restore session for jid: xxxxx@domain/converse.js-77429227 Error message: _restore: no restoreable session.

**Comment by jcbrand** [comment]
Can you please use an unminified bundle and then paste the full error traceback here?
