### ISSUE TITLE
Inverse throwing error for a large roster

### ISSUE THREAD

**Issue by nandinibhaduri** [conversejs/converse.js#2372]
I am using inverse 3.2.1 with ejabberd 20 as my xmpp server. It was working perfectly fine till my client decided to have a shared roster with all users in it. Now with 2000+ users in the roster the chat client doesn't work at all. I have checked that with 10 users, it works with shared rosters too.

The roster comes up but constantly disconnects and even if it doesn't it is completely impossible to send message or get in a chat room with any of the users.

Here is my configuration

converse.initialize({
    bosh_service_url: '../nc4chat/xmpp/http-bind',
    keepalive: true,
    authentication: 'prebind',
    allow_logout: false,
    jid: '<%=xmpp.getJid()%>',
    prebind_url: '../nc4chat/prebind.jsp',
    blacklisted_plugins: ['converse-minimize', 'converse-dragresize'],
    whitelisted_plugins: ['converse-inverse', 'converse-singleton','removewhitespacefromroomnameplugin','closewhendisconnectedplugin'],
    allow_otr: false,
    roster_groups: false,
    hide_muc_server : true,
    muc_domain : 'conference.<%=xmpp.getDomain()%>',
    locked_domain : '<%=xmpp.getDomain()%>',
    allow_bookmarks: false,
    allow_registration: false,
    auto_reconnect: true,
    allow_contact_requests: false,
    allow_contact_removal: false
});

**Comment by licaon-kter** [comment]
3.2.1 is really old, right?

No chance to update to 7.0.x?

**Comment by nandinibhaduri** [comment]
Did give it a try but ran into issues. Created #2370

**Comment by jcbrand** [comment]
Sorry, we're not doing any more work on such an old version.
