### ISSUE TITLE
How to send files or image in conversejs web panel ?

### ISSUE THREAD

**Issue by Omid-Mohajerani** [conversejs/converse.js#2375]
Hi,

I'm not sure if I'm asking in the correct forum as it's not a feature request and It seems it's already implemented in conversejs. I want to upload a file or image but I can't find any button in the web panel to be able to upload it. 

Im using the conversejs.org full screen and conenct to my prosody xmpp server. I appriciate your help. thanks
<img width="1201" alt="Screenshot 2020-12-26 at 3 27 36 PM" src="https://user-images.githubusercontent.com/5101364/103147283-ee11bc80-478e-11eb-80bf-b54d80de1b6f.png">

**Comment by licaon-kter** [comment]
Enable http_upload (xep-0363) support in your server config and restart it.

**Comment by Omid-Mohajerani** [comment]
> Enable http_upload (xep-0363) support in your server config and restart it.

Hi, Thanks for your help. I enabled http_upload and I can see it is enabled and have access. But how should I upload from converseJS panel ? I cant see any upload button or send image? 

<img width="559" alt="Screenshot 2020-12-26 at 9 27 57 PM" src="https://user-images.githubusercontent.com/5101364/103152253-42359480-47c1-11eb-977d-30d85dda9d65.png">

**Comment by licaon-kter** [comment]
Did you reconnect?  Above the input box near the lock or emoji button?

**Comment by Omid-Mohajerani** [comment]
do you mean logout and login again? Yes. even I created a new use . there is no button to send images or fies . 

im using the full screen live demo from convrsejs at https://conversejs.org/fullscreen.html

I have one question ? If my server for any issue in file upload the panel wont load button for sending image ? 


<img width="258" alt="Screenshot 2020-12-26 at 11 59 17 PM" src="https://user-images.githubusercontent.com/5101364/103154968-8717f600-47d6-11eb-9226-821afa6d01f9.png">

**Comment by jcbrand** [comment]
If your XMPP server doesn't support HTTP file upload, you won't see the icon in your chat toolbar.

**Comment by Echolon** [comment]
@Omid-Mohajerani have your question been answered?
