### ISSUE TITLE
The official npm package @converse/headless is missing the dist directory, causing import errors

### ISSUE THREAD

**Issue by vincentrolfs** [conversejs/converse.js#2377]
**Describe the bug**
The official npm package `@converse/headless` does not contain a `dist` folder, but it specifies `dist/converse-headless.min.js` as the entrypoint script (the `main` key in `package.json`).

The inclusion of the `dist` folder is described as a bugfix in [this github issue](https://github.com/conversejs/converse.js/issues/1352). But it seems that the folder now went missing again, and I believe the import errors I am facing are due to this.

**To Reproduce**
```
$ mkdir test && cd test
$ npm i @converse/headless
$ ls node_modules/@converse/headless
```

**Expected behavior**
The file `dist/converse-headless.min.js` is part of the official package.

**Environment (please complete the following information):**
 - Ubuntu 18.04
 - `@converse/headless@7.0.4`

**Comment by tiaod** [comment]
Same error on Windows.

**Comment by jcbrand** [comment]
Thanks, should be fixed in the next release.
