### ISSUE TITLE
browser versión 7.0.4 does NOT load browser default language

### ISSUE THREAD

**Issue by xmgz** [conversejs/converse.js#2381]
**Describe the bug**
UI does not follow browser language preferences

**To Reproduce**
- Browser (firefox & chromium) language set to galician (gl)
- conversejs 7.0.4
- interface in english
- conversejs [100% translated to galician](https://hosted.weblate.org/projects/conversejs/translations/gl/)
- previous versions were displayed using galician without issues

**Expected behavior**
I expected conversejs' UI in galician (gl, gl_ES)

**Environment (please complete the following information):**
 - archlinux with...
 - latest firefox and chromium from official sources
 - Converse.js version [7.0.4]

**Additional context**
I'm galician translator since long time ago

**Comment by suchatorg** [comment]
Same problem with Spanish es
