### ISSUE TITLE
README.md : screenshot links are broken

### ISSUE THREAD

**Issue by anubister** [conversejs/converse.js#2385]
Hi, the 3 links toward screenshots seem broken in the README.md file : 
https://camo.githubusercontent.com/17eaef5bde9136cccc9052bebf4c63f72e93fd02dadf277c05558e0e781308f4/68747470733a2f2f6f706b6f64652e636f6d2f696d672f436f6e76657273652d656d6265646465642e706e67 ==> Not found
There are helpful to spread the project.

**Comment by anubister** [comment]
Waiting for official pictures, i suggest some : 
* **overlayed** mode: 
![grafik](https://user-images.githubusercontent.com/6146191/109427156-55e3be00-79f1-11eb-878f-0e6a28b6b98d.png)

* **fullscreen** mode : 
![grafik](https://user-images.githubusercontent.com/6146191/109426784-a8bc7600-79ef-11eb-9e8f-118f08c41980.png)
* **embedded** mode : 
![grafik](https://user-images.githubusercontent.com/6146191/109427129-32b90e80-79f1-11eb-9df1-04827ff72cdd.png)

**Comment by jcbrand** [comment]
Sorry for taking so long to fix this.
