### ISSUE TITLE
using customElements.define instead of api.elements.define makes it impossible to override toolbar.js

### ISSUE THREAD

**Issue by gmournos** [conversejs/converse.js#2389]
**Describe the bug**
Most of the ui components under src/components use api.elements.define to register themselves.
However, toolbar.js, icons.js, fontawesome.js use directly window.customElements.define directly, making it impossible to override them e.g. inside a plugin, without changing the source code.

**Comment by jcbrand** [comment]
@gmournos: You're welcome to make a pull request which fixes the issue.

**Comment by gmournos** [comment]
Just returned from holiday. I was about to do a pull request but I see it is already fixed in master.  Closing issue.
