### ISSUE TITLE
ConverseJS hosted on https://conversejs.org fails to load in Microsoft Edge

### ISSUE THREAD

**Issue by JustAnotherContributor** [conversejs/converse.js#2390]
**Describe the bug**
The ConverseJS code hosted on https://conversejs.org fails to load when accessed using the Microsoft Edge web browser and has done for several months

**To Reproduce**
1. Go to 'https://conversejs.org' using Microsoft Edge and notice that the “Toggle Chat” hover in the bottom right hand corner does not appear
2. Press “F12” to display the Developer Tools
3. See error

**Expected behavior**
Upon loading “https://conversejs.org” within Microsoft Edge, the “Toggle Chat” hover should appear in the bottom right hand corner and it should be possible to log in to a chat session.

**Screenshots**
![conversejs org Javascript error](https://user-images.githubusercontent.com/77906952/105619604-6334e800-5e48-11eb-9938-eaef9c314be9.png)

**Environment (please complete the following information):**
 - Desktop
 - Browser: Microsoft Edge
 - Converse.js version: latest, presumably 7.0.4

**Comment by jcbrand** [comment]
Which version of Microsoft Edge does this happen in?

**Comment by JustAnotherContributor** [comment]
It was on a version of Edge that predates Microsoft incorporating the Chromium engine in to Edge. I have since used ConverseJS in a version of Edge that uses the Chromium engine and it worked.
