### ISSUE TITLE
Docs: example for config connection_options does not work

### ISSUE THREAD

**Issue by aw32** [conversejs/converse.js#2392]
This configuration example for the option `connection_options` does not work since `converse.env.Strophe` is not accessible before the call to `converse.initialize`.
In my case I needed this option and worked around the problem by doing the setting inside a plugin.
Version 7.0.4
https://github.com/conversejs/converse.js/blob/c0249b9c285d3a9c4be8b895c9dfcb875d3a1511/docs/source/configuration.rst#L641-L650

**Comment by jcbrand** [comment]
> since converse.env.Strophe is not accessible before the call to converse.initialize

This is not the case on the master branch. Closing.
