### ISSUE TITLE
auto_join_rooms: chatbox does not open automatically

### ISSUE THREAD

**Issue by aw32** [conversejs/converse.js#2393]
Before (Version 6.0.1) when using `auto_join_rooms` the chatbox would automatically open up:
```
auto_join_rooms: [
    'room@example.org',
],
```
Now (Version 7.0.4) an entry is added to the room list, but the chatbox does not open. A workaround is to set the `hidden` attribute to `false`:
```
auto_join_rooms: [
    {'jid': 'room@example.org', 'hidden': false }
],
```
I'm not sure if this is intended behavior.

**Comment by jcbrand** [comment]
No, this is a bug and duplicate of #2348

**Comment by aw32** [comment]
Ok, thanks!
