### ISSUE TITLE
headless require ../components/element 

### ISSUE THREAD

**Issue by pslxx** [conversejs/converse.js#2396]
**Describe the bug**

**To Reproduce**
 npm install @converse/headless and import @converse/headless/headless
**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/8417207/106796144-f4505e00-6695-11eb-83fd-0742307615c5.png)

**Environment (please complete the following information):**
7.0.4

**Additional context**

I want to build a IM Client with headless and vue.js

 so i use npm install @converse/headless and import @converse/headless/headless

but webpack throw a error

**Comment by jcbrand** [comment]
Thanks for the bug report
