### ISSUE TITLE
emoji.js uses absolute path

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/converse.js#2406]
HEAD, Firefox stable

Moved Converse from domain/ to domain/chat

Console says: 
```
GET https://mydomain.tld/dist/emojis.js
Loading failed for the <script> with source “https://mydomain.tld/dist/emojis.js”.
```

**Comment by jcbrand** [comment]
You can use the `assets_path` configuration setting to set a different path:

https://conversejs.org/7.0.4/docs/html/configuration.html#assets-path

**Comment by licaon-kter** [comment]
Ok, that fixes emojis.js and sounds/

Thanks

**Comment by juancar0505** [comment]
@licaon-kter i have the same problem with emojis, can u answer me how u check this. 

![image](https://user-images.githubusercontent.com/70941752/109787262-56a56b80-7c0e-11eb-92f0-011b66d93f3f.png)

![image](https://user-images.githubusercontent.com/70941752/109787371-72107680-7c0e-11eb-9ede-513d917cc552.png)

**Comment by licaon-kter** [comment]
See the link above, in index.html set assets-path
