### ISSUE TITLE
Using subfolder - can only send messages

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/converse.js#2407]
HEAD, Firefox stable

Moved Converse from domain/ to domain/chat

I can write encrypted or not, and messages get delivered.

I can't receive anything (eg. In Conversations I don't get the delivered checkmark)

No errors in logs.

Am I missing any extra config?

**Comment by jcbrand** [comment]
Check in the network tab whether all your resources are loaded properly, for example emojis.json.

Probably what's happening is that some paths are now broken due to the new location.

**Comment by licaon-kter** [comment]
I already opened this issue: https://github.com/conversejs/converse.js/issues/2406

**Comment by jcbrand** [comment]
Ok, then I'm closing this.

**Comment by licaon-kter** [comment]
Broken path for emoji is the reason, added an `alias` in webserver to point to the real path and now it works.

**Comment by juancar0505** [comment]
@licaon-kter Hello i have the same problem. Can u explain me how to correct this. Thanks

**Comment by jcbrand** [comment]
@juancar0505: https://github.com/conversejs/converse.js/issues/2406#issuecomment-784894691

**Comment by licaon-kter** [comment]
Can you reopen this?

The OP was a mix of issues, I fixed the folder thing.

But I still can't receive messages
```
DEBUG: <message xmlns="jabber:client" xml:lang="en" to="converseuser@mydomain.tld" from="mobile@mydomain.tld/Conversations.-9JP" type="chat" id="40e90f05-28d7-4349-b504-21c833a76692"><archived by="converseuser@mydomain.tld" id="1615900277205286" xmlns="urn:xmpp:mam:tmp"/><stanza-id by="converseuser@mydomain.tld" id="1615900277205286" xmlns="urn:xmpp:sid:0"/><request xmlns="urn:xmpp:receipts"/><markable xmlns="urn:xmpp:chat-markers:0"/><origin-id xmlns="urn:xmpp:sid:0" id="40e90f05-28d7-4349-b504-21c833a76692"/><active xmlns="http://jabber.org/protocol/chatstates"/><body>TEXTTHATDOESNOTSHOWONSCREEN</body></message>
```
