### ISSUE TITLE
Integrate App Badging API for unread messages

### ISSUE THREAD

**Issue by PacifistRiot** [conversejs/converse.js#2409]
If would be nice to have integrated support for the App Badging API so when converse is installed as a PWA a badge can be shown to show the number of unread messages.

More info: https://web.dev/badging-api/

**Comment by deleolajide** [comment]
That is a really good feature. It works very well on a Windows desktop

**Comment by deleolajide** [comment]
Same it does not work with Converse in Chrome Extensions, but does work quite nicely in a PWA

![image](https://user-images.githubusercontent.com/110731/108203440-6c993380-711a-11eb-8bb9-f0318f432fd7.png)
