### ISSUE TITLE
Installing version 7.0.4, configuring converse.js converse.initialize error

### ISSUE THREAD

**Issue by danjde** [conversejs/converse.js#2411]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Editing converse.js
2. Adding converse.initialize parameters for authentication by login
3. Reloaded page is colour indigo and no login access
4. From Firefox console error: 

```
Uncaught SyntaxError: missing : after property id
converse.js:59443:10
asm.js type error: Disabled by debugger libsignal-protocol.js
pre-main prep time: 4 ms libsignal-protocol.js:136:15
Uncaught ReferenceError: converse is not defined
<anonymous> https://converse.3x1t.org/fullscreen.html:51
```

Here the code added:

```
  converse.initialize({
  auto_list_rooms: false,
  auto_subscribe: false,
  bosh_service_url: 'https://3x1t.org:5281/http-bind',
  hide_muc_server: false,
  i18n: 'it',
  play_sounds: true,
  show_controlbox_by_default: true,
  debug: false,
  roster_groups: true
  });
```
Here the page: 
https://converse.3x1t.org

**Environment:**
 - Browser [Chrome and Firefox]
 - Converse.js version [7.0.4]

**Additional context**
[Here](https://server.3x1t.org/cloud/index.php/s/8iXRxF9JiiY4Lzf) converse.js and fullscreen.html

**Comment by jcbrand** [comment]
> Uncaught ReferenceError: converse is not defined

Looks like you might be calling `converse` before the script has finished loading.

You can listen for the `converse-loaded` event and only then call `converse.initialize` (which by then is guaranteed to be defined).

https://conversejs.org/docs/html/api/module-converse-core.html#~event:converse-loaded

**Comment by danjde** [comment]
Perfect, solved!


Thanks!
