### ISSUE TITLE
How to install without NPM and shell access?

### ISSUE THREAD

**Issue by omexlu** [conversejs/converse.js#2426]
Hello,

How can I install converse if I do not have NPM and shell access and generate all the necessary files?

Thanks in advance.

**Comment by licaon-kter** [comment]
Read the docs, either use the CDN or copy those files locally.

/close as not an issue

**Comment by omexlu** [comment]
CDN is not enough for me, I need all files.

Where can I find the section to create this local?

**Comment by licaon-kter** [comment]
See the documentation, you'll need a Debian VM and some deps.

**Comment by jcbrand** [comment]
You can download all the files on the release page: https://github.com/conversejs/converse.js/releases/tag/v7.0.4

**Comment by omexlu** [comment]
Thank you, is it possible to run conversejs behind a cloudflare proxy without trouble?

**Comment by jcbrand** [comment]
AFAIK yes.
