### ISSUE TITLE
ConverseJs chat has disconnected and returned to the login page

### ISSUE THREAD

**Issue by juanjosegarciaripoll** [conversejs/converse.js#2427]
**Describe the bug**
Quite often, ConverseJs disconnects from the server. I have not found a way to debug it, because it seems to happen "when I am not looking". Any help would be appreciated.

**To Reproduce**
1. Connect to a bosh server
2. Work as usual
3. Switch to other screens or desktop
4. The tab with the ConverseJs chat has disconnected and returned to the login page

**Expected behavior**
Once logged in, the application should remain logged and show the conversations, as well as notifications.

**Environment (please complete the following information):**
 - Desktop
 - Windows with Edge or Chrome browsers
 - Converse.js version 7.0.4

**Comment by licaon-kter** [comment]
Logs?

**Comment by juanjosegarciaripoll** [comment]
How can I extract them? I do not see that the javascript code produces any logs.

**Comment by licaon-kter** [comment]
Browser console logs, enable debug first in Converse .html

**Comment by jcbrand** [comment]
> Browser console logs, enable debug first in Converse .html

And make sure that verbose logging is enabled in the browser console.

**Comment by juanjosegarciaripoll** [comment]
Apologies: my computer has Spanish language and Edge has decided to show Console errors in Spanish. I hope it is still easy to understand.
````
log.js:66  2021-03-08T14:15:18.734Z WARNING: Could not restore session for jid: jjgarciaripoll@***.***.es/converse.js-84284961 Error message: _restore: no restoreable session. 
log @ log.js:66
warn @ log.js:89
qc.restoreBOSHSession @ converse-bosh.js:93
async function (asincrónico)
qc.restoreBOSHSession @ converse-bosh.js:87
login @ converse-core.js:528
async function (asincrónico)
login @ converse-core.js:522
reconnect @ connection.js:124
async function (asincrónico)
reconnect @ connection.js:123
reconnect @ converse-core.js:402
onDisconnected @ connection.js:235
onConnectStatusChanged @ connection.js:280
_changeConnectStatus @ core.js:2387
_doDisconnect @ core.js:2428
_dataRecv @ core.js:2503
_onRequestStateChange @ bosh.js:645
XMLHttpRequest.send (asincrónico)
(anónimo) @ VM69:1
e @ bosh.js:738
_processRequest @ bosh.js:753
_throttledRequestHandler @ bosh.js:892
_onIdle @ bosh.js:542
_onIdle @ core.js:3164
(anónimo) @ core.js:3168
setTimeout (asincrónico)
_onIdle @ core.js:3168
(anónimo) @ core.js:3168
setTimeout (asincrónico)
_onIdle @ core.js:3168
(anónimo) @ bosh.js:859
setTimeout (asincrónico)
_send @ bosh.js:859
send @ core.js:1981
send @ converse-core.js:892
send @ converse-status.js:257
async function (asincrónico)
send @ converse-status.js:256
qc.onEverySecond @ converse-status.js:148
setInterval (asincrónico)
qc.registerIntervalHandler @ converse-status.js:186
(anónimo) @ converse-status.js:192
ji @ events.js:281
Ei @ events.js:264
e @ events.js:50
mi.trigger @ events.js:254
trigger @ converse-core.js:443
(anónimo) @ converse-roster.js:981
ji @ events.js:281
Ei @ events.js:264
e @ events.js:50
mi.trigger @ events.js:254
trigger @ converse-core.js:443
e @ converse-status.js:204
success @ converse-status.js:219
e.success @ model.js:289
n @ storage.js:127
async function (asincrónico)
n @ storage.js:72
sync @ model.js:91
fetch @ model.js:293
t @ converse-status.js:218
(anónimo) @ converse-status.js:236
ji @ events.js:280
Ei @ events.js:264
e @ events.js:50
mi.trigger @ events.js:254
trigger @ converse-core.js:443
onConnected @ connection.js:160
async function (asincrónico)
onConnected @ connection.js:136
onConnectStatusChanged @ connection.js:276
_changeConnectStatus @ core.js:2387
_attach @ bosh.js:278
_restore @ bosh.js:316
restore @ core.js:1841
qc.restoreBOSHSession @ converse-bosh.js:90
async function (asincrónico)
qc.restoreBOSHSession @ converse-bosh.js:87
login @ converse-core.js:528
async function (asincrónico)
login @ converse-core.js:516
initialize @ converse-core.js:1569
async function (asincrónico)
initialize @ converse-core.js:1526
tl.initialize @ converse.js:86
initialize @ entry.js:31
(anónimo) @ converse.html:8
log.js:72  2021-03-08T14:15:18.735Z INFO: Disconnect was called 
log.js:66  2021-03-08T14:15:18.735Z WARNING: Disconnect was called before Strophe connected to the server 
log @ log.js:66
kc.e.log @ converse-core.js:1312
warn @ core.js:795
disconnect @ core.js:2354
disconnect @ converse-core.js:347
Qc @ converse-core.js:1150
t.jid @ converse-core.js:1120
async function (asincrónico)
t.jid @ converse-core.js:1120
login @ converse-core.js:536
async function (asincrónico)
login @ converse-core.js:522
reconnect @ connection.js:124
async function (asincrónico)
reconnect @ connection.js:123
reconnect @ converse-core.js:402
onDisconnected @ connection.js:235
onConnectStatusChanged @ connection.js:280
_changeConnectStatus @ core.js:2387
_doDisconnect @ core.js:2428
_dataRecv @ core.js:2503
_onRequestStateChange @ bosh.js:645
XMLHttpRequest.send (asincrónico)
(anónimo) @ VM69:1
e @ bosh.js:738
_processRequest @ bosh.js:753
_throttledRequestHandler @ bosh.js:892
_onIdle @ bosh.js:542
_onIdle @ core.js:3164
(anónimo) @ core.js:3168
setTimeout (asincrónico)
_onIdle @ core.js:3168
(anónimo) @ core.js:3168
setTimeout (asincrónico)
_onIdle @ core.js:3168
(anónimo) @ bosh.js:859
setTimeout (asincrónico)
_send @ bosh.js:859
send @ core.js:1981
send @ converse-core.js:892
send @ converse-status.js:257
async function (asincrónico)
send @ converse-status.js:256
qc.onEverySecond @ converse-status.js:148
setInterval (asincrónico)
qc.registerIntervalHandler @ converse-status.js:186
(anónimo) @ converse-status.js:192
ji @ events.js:281
Ei @ events.js:264
e @ events.js:50
mi.trigger @ events.js:254
trigger @ converse-core.js:443
(anónimo) @ converse-roster.js:981
ji @ events.js:281
Ei @ events.js:264
e @ events.js:50
mi.trigger @ events.js:254
trigger @ converse-core.js:443
e @ converse-status.js:204
success @ converse-status.js:219
e.success @ model.js:289
n @ storage.js:127
async function (asincrónico)
n @ storage.js:72
sync @ model.js:91
fetch @ model.js:293
t @ converse-status.js:218
(anónimo) @ converse-status.js:236
ji @ events.js:280
Ei @ events.js:264
e @ events.js:50
mi.trigger @ events.js:254
trigger @ converse-core.js:443
onConnected @ connection.js:160
async function (asincrónico)
onConnected @ connection.js:136
onConnectStatusChanged @ connection.js:276
_changeConnectStatus @ core.js:2387
_attach @ bosh.js:278
_restore @ bosh.js:316
restore @ core.js:1841
qc.restoreBOSHSession @ converse-bosh.js:90
async function (asincrónico)
qc.restoreBOSHSession @ converse-bosh.js:87
login @ converse-core.js:528
async function (asincrónico)
login @ converse-core.js:516
initialize @ converse-core.js:1569
async function (asincrónico)
initialize @ converse-core.js:1526
tl.initialize @ converse.js:86
initialize @ entry.js:31
(anónimo) @ converse.html:8
````

**Comment by jcbrand** [comment]
@juanjosegarciaripoll: Are you logging in manually?

If the connection drops, Converse will try to reconnect with your username and password stored in RAM, but if you ever reload the page, the username and password are gone and Converse won't be able to reconnect you.

**Comment by licaon-kter** [comment]
I never saw a reconnect. Eg. See my websocket issue, it breaks...never auto anything, I refresh and login manually.

**Comment by juanjosegarciaripoll** [comment]
I also have to login manually. I increased the Bosh timeout in Prosody, but it does not seem to help. I wonder whether it has to do with some browser-related policy, that makes the script sleep when not in foreground. We use ConverseJs in our research group and only some of us seem to be affected by the disconnect issue. In my case it typically happens when I am not looking at the particular tab, either because it is not the foreground one or because I am on another desktop.

**Comment by jcbrand** [comment]
Is there a particular reason why you're using BOSH and not websocket?

Also, do you see anything in Prosody's logs that might help?

**Comment by juanjosegarciaripoll** [comment]
I use BOSH because there instructions on how to set up an nginx proxy to isolate the prosody instance from direct connections. Maybe it is not ideal; if there are good alternatives, please let me know. I want something secure that is easy to maintain.

As for Prosody, I see some suspicious lines on the logs, probably related to the disconnects
````
Mar 07 03:12:22 mod_bosh        info    New BOSH session, assigned it sid 'c1070ea8-130b-43d2-8be2-915170b1365b'
Mar 07 03:12:23 boshc1070ea8-130b-43d2-8be2-915170b1365b        info    Authenticated as  ****@****.es
Mar 07 03:14:29 mod_bosh        info    Client tried to use sid 'c1070ea8-130b-43d2-8be2-915170b1365b' which we don't know about
Mar 07 03:14:30 mod_bosh        info    New BOSH session, assigned it sid '68ed7ae0-b5f4-4463-84ad-c416d0f34960'
Mar 07 03:14:31 bosh68ed7ae0-b5f4-4463-84ad-c416d0f34960        info    Authenticated as ****@****.es
````
The time separation corresponds to the 120s timeout that I set up in BOSH

**Comment by jcbrand** [comment]
I'd encourage you to use websocket instead of BOSH.

Websocket is quicker and simpler and since I'm using it 100% of the time, I'm more more likely to identify and fix bugs than with BOSH.

Looking at the logs, it looks like the BOSH connection expires after 120s and then Converse tries to reconnect with the session token `sid` which is expired.

What should then normally happen is that Converse should recognize that reconnection failed and then retry logging in with the username/password in memory (if you didn't reload the page), but perhaps this is no longer working properly due to a bug, I'm not sure.

**Comment by juanjosegarciaripoll** [comment]
I have tried setting up websockets, but conversejs is not working well (Conversation does). Presently, I have set up an https server at port 443, with two proxies, one for BOSH (for some users with the old configuration) and one for Websocket
````
    # BOSH
    location = /http-bind {
        proxy_pass http://127.0.0.1:5280/http-bind;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $http_host;
    }

    # xmpp websockets
    location = /xmpp-websocket {
	   proxy_pass http://127.0.0.1:5280/xmpp-websocket;
	   proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 86400;
        tcp_nodelay on;
    }
````
I have created a separate converse-websocket.html file, with only one changed line
````
          websocket_url: 'wss://***.***.es/xmpp-websocket'
````
but ConverseJS is not capable of connecting
````
WebSocket connection to 'wss://xmpp.hbar.es/xmpp-websocket' failed: 
_connect @ websocket.js:156
connect @ core.js:1772
connect @ connection.js:104
````
The BOSH sessions still work, though. Also, `curl https://***.***.es/xmpp-websocket` seems to work and returns the right message, and if I use https://***.***.es/xmpp-websocket instead of wss: I seem to get something, although a lot of timeouts in most stanzas.

**Comment by licaon-kter** [comment]
Conversations does not use websockets.

**Comment by juanjosegarciaripoll** [comment]
Ok, it definitely showed a Conversation push request in the access log. Maybe it was a residual from an open BOSH connection...

**Comment by juanjosegarciaripoll** [comment]
Ok, just for the record, I had to add two fields to my prosody configuration
````
     conside_websocket_secure = true
     cross_domain_websocket = { "https://***.***.es" }
````
Now Websockets works. I will monitor whether I experience the same timeouts and disconnects.

**Comment by jcbrand** [comment]
@juanjosegarciaripoll: I've just released Converse 7.0.5 which includes fix in Strophe related to reconnections (specifically when using SCRAM-SHA1).

This might be relevant to you as well (and might be the reason why Converse didn't reconnect after the BOSH session timed out).

**Comment by Echolon** [comment]
@juanjosegarciaripoll have your issue been solved?

**Comment by juanjosegarciaripoll** [comment]
I have managed to solve the issue by moving to Websockets. However, after some work in parallel with BOSH and Websockets, I still find out that BOSH times out, even with the latest release.

**Comment by jcbrand** [comment]
It's normal for BOSH to time out. As long as Converse reconnects it's not an issue.
