### ISSUE TITLE
Automatically list all avaiable groups

### ISSUE THREAD

**Issue by WiniciusNvoip** [conversejs/converse.js#2429]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would like it would list all the groups that I am a participant of automatically when logging in, without having to favorite the group or to click on the modal. I have already tried auto_join_room but it didn't work in my case.

**Describe alternatives you've considered**
It may be listed like contacts in the side bar.

**Additional context**
Automatically list groups when loggin and see something like this.

![listgroups](https://user-images.githubusercontent.com/59610359/110853578-8bf72c80-8292-11eb-9eba-9ebe0a44b702.png)

**Comment by licaon-kter** [comment]
Which version? Bookmarks with autojoin should work fine.

**Comment by WiniciusNvoip** [comment]
We already used auto_join with bookmarks, but in our case it do not aplly very well. We were think about some solution that lists goups the same way the contacts are listed when we log in tha apllication.

**Comment by WiniciusNvoip** [comment]
We already used auto_join with bookmarks, but in our case it do not aplly very well. We were thinking about some solution that lists goups the same way the contacts are listed when we log in tha apllication.

**Comment by jcbrand** [comment]
There isn't enough information here to know what you really want. Converse already shows all bookmarked groupchats and all groupchats that are joined via auto_join_rooms.

**Comment by WiniciusNvoip** [comment]
Is there a way for my groups to list here without the need for favorites?

![print2](https://user-images.githubusercontent.com/59610359/111382146-5cc32f80-8685-11eb-8b0a-da82af3cd9e3.png)

Instead of listing here:

![print1](https://user-images.githubusercontent.com/59610359/111382346-a27ff800-8685-11eb-8422-14de4b67ebdd.png)

**Comment by jcbrand** [comment]
This can't be done by configuration alone, but you can definitely do it by creating a plugin that overrides the `converse-rooms-list` component which is what renders the list of rooms in the controlbox sidebar.

The existing component is here: https://github.com/conversejs/converse.js/blob/bb317d1abbfbf38ed02b93fceb31d097aa8a9c55/src/plugins/roomslist/view.js

You can create a new component and call `api.elements.defined('converse-rooms-list', MyRoomsListComponent)`.
As long as your call to `api.elements.define` is called after the one in `src/plugins/roomslist/views.js` your component will be the one that's used.
