### ISSUE TITLE
Intermittent Error When visible_toolbar_buttons.emoji = false

### ISSUE THREAD

**Issue by mjvotaw** [conversejs/converse.js#2435]
**Describe the bug**
If I have visible_tooblar_buttons.emoji set to false, I occasionally encounter an error that prevents my messages from being sent. It seems to be somewhat intermittent, but I'm not 100% sure why.

The error in question:
```
Uncaught (in promise) Error: getShortnameReferences called before emojis are initialized. To avoid this problem, first await the converse.emojis.initilaized_promise.
    getShortnameReferences http://localhost:3690/dist/converse.js:68390
    addEmojisMarkup http://localhost:3690/dist/converse.js:68433
    shortnamesToEmojis http://localhost:3690/dist/converse.js:68537
    shortnamesToUnicode http://localhost:3690/dist/converse.js:68548
    getOutgoingMessageAttributes http://localhost:3690/dist/converse.js:70124
    sendMessage http://localhost:3690/dist/converse.js:66708
    sendMessage http://localhost:3690/dist/converse.js:94613
    wrappedOverride http://localhost:3690/dist/converse.js:51605
    apply http://localhost:3690/dist/converse.js:29503
    wrapper http://localhost:3690/dist/converse.js:41356
    onFormSubmitted http://localhost:3690/dist/converse.js:85156
    onEnterPressed http://localhost:3690/dist/converse.js:85313
    onKeyDown http://localhost:3690/dist/converse.js:85283
    onKeyDown http://localhost:3690/dist/converse.js:90608
    handler http://localhost:3690/dist/converse.js:77612
```

**To Reproduce**
1. Clear your cookies, local storage, session storage, etc
2. Set visible_toolbar_buttons.emoji = false in your initialization options
3. Once logged into a room, try to send a message

**Environment (please complete the following information):**
 - Desktop: macOS 11.1
 - Browser: Firefox 87.0b9
 - Converse.js version: 7.0.5

**Additional context**
As I said, I'm not 100% sure how to recreate the issue. If I set the option to true, everything of course works fine. And as long as I don't clear any of my local caches, I can set the option to false again, and I can still send messages.

It seems that the emoji plugin is being relied on to provide some core functionality, namely the shortnamesToUnicode() function. If I blacklist the emoji plugin, for instance, I receive the following error:
```
Uncaught (in promise) TypeError: utils_form.shortnamesToUnicode is not a function
    getOutgoingMessageAttributes http://localhost:3690/dist/converse.js:70125
```

**Comment by jcbrand** [comment]
Thanks for the bug report.

Looks to me like this bug is already fixed in the `master` branch and only exists in the 7.x.x branch.

As a workaround, you can hide the emoji button via CSS instead of via the configuration setting or you can try to call `_converse.api.emojis.initialize()` somewhere in the code early on.

You can also try out the code in the master branch, it's quite stable.

**Comment by mjvotaw** [comment]
I built the master branch and gave it a try, but it doesn't seem to be a drop-in replacement for the 7.x.x branch build. So I'm  just going to hide the button via css for now. 

Thanks for the suggestions.
