### ISSUE TITLE
Build fails with error about `dist/website.css`

### ISSUE THREAD

**Issue by Zash** [conversejs/converse.js#2446]
**Describe the bug**
Build fails with error about `dist/website.css`. Incomplete fix for #2443 ?

**To Reproduce**
1. `docker run -i --rm -v $PWD:/home/node/${PWD##*/} -w /home/node/${PWD##*/} -u node:node --network host node:14 make`

**Error**
```
./node_modules/.bin/node-sass --source-map true --include-path ./node_modules/ sass/website.scss dist/website.css
An output directory must be specified when compiling a directory
Makefile:147: recipe for target 'dist/website.css' failed
make: *** [dist/website.css] Error 1
```

**Environment (please complete the following information):**
 - Docker `node:14` image
 - Converse.js 724a6855eddc2accf96c1ea47c39141c5d2e74c8

**Comment by Zash** [comment]
Why's `website.css` needed for `make dist` anyway?

**Comment by licaon-kter** [comment]
Is the fix proposed in the other issue better?

**Comment by Zash** [comment]
What other issue? #2443 ? Wasn't that merged?

**Comment by licaon-kter** [comment]
That one worked for me, yes.

But the in tree changes looked different (to my eyes on a first look, didn't get a chance to make yet)

**Comment by licaon-kter** [comment]
Confirmed locally that the #2443 proposed fix is better, `make dist` produced minified files, current HEAD still does not.
