### ISSUE TITLE
ConverseJS OTR Issue

### ISSUE THREAD

**Issue by member7me** [conversejs/converse.js#2449]
Hi. 
ConverseJS last one - 7.0.5
Ejabberd - 21.01
There is OTR related issue. If user1 from desktop client is initiatization OTR session, user2 is ConverseJS see just error
`?OTR?v2? **** has requested an Off-the-Record private conversation.  However, you do not have a plugin to support that. See http://otr.cypherpunks.ca/ for more information. `
And nothing else.
User2 (ConverseJS) don't have OTR initiatization at all.
Do, OTR session doesn't opening. But should be https://opkode.com/blog/converse.js-otr-support/
OMEMO is working good.
I have tried different configs edits, like
`allow_otr: true,`
`omemo_default: true`
and so on
Where is mistake? And how to fix it?

**Comment by licaon-kter** [comment]
Is OTR a feature of Converse 7? I didn't know... I don't think there's support...

**Comment by jcbrand** [comment]
OTR isn't supported since many years already.

**Comment by member7me** [comment]
That's it! I found info in blog, thought it is.
Will Converse support OTR or PGP in future? Omemo - is good, but not enough nowadays.

**Comment by licaon-kter** [comment]
@member7me OTR4 is enough? What's the usecase?

**Comment by jcbrand** [comment]
I'm personally not going to work on OTR, but if someone is willing to work on it they can make a plugin in the community-plugins repo (and if it's high quality we could even merge it into the main project).

https://github.com/conversejs/community-plugins

**Comment by member7me** [comment]
Thanks. My knowledge in not enough for plugins development, hope someone will release OTR support in format of plugin `community-plugins`.
licaon-kter, not everyone has Omemo support and knows about it. OTR is oldschool, trusted and well known.
