### ISSUE TITLE
Captcha reloading

### ISSUE THREAD

**Issue by member7me** [conversejs/converse.js#2452]
Hi! Version 7.0.5. Found small bug. On page `#converse/register` If server supports captcha, it's not reloading.
What do I mean. Registering => page `#converse/register` , enter invalid login or weak password, system alert about this. After this, captcha is already invalid and new isn't re loading. I should reload whole page #converse/register

**Comment by jcbrand** [comment]
Hi @member7me, can you please check whether this is still an issue with release 10.1.2?

Thanks
