### ISSUE TITLE
Mozilla FF 87 bug

### ISSUE THREAD

**Issue by member7me** [conversejs/converse.js#2454]
Hello.
I have found Mozilla FF 87 & Tor browser 10.0.15 (based on Mozilla Firefox 78.9.0esr) bug.
When 1st time registering into account, left colum and Omemo generation fields freezes.
Screenshot
![1](https://user-images.githubusercontent.com/66087479/114247919-01900e80-999f-11eb-9b52-a6c03e0e7feb.png)

Any xmpp server.
Confirmed on https://inverse.chat

Second login - everything is okay in left column, but OMEMO fingerprint field isn't working.
In debug there are no errors.
In Chrome everything is okay.

**Comment by jcbrand** [comment]
Is this still an issue @member7me ?
