### ISSUE TITLE
Url history state changes in overlayed view mode

### ISSUE THREAD

**Issue by Alexbay218** [conversejs/converse.js#2457]
**Describe the bug**
When using converse.js in overlayed view mode, the url history is still changed. This causes unintended behavior with applications that use the url history or value for routing.

**To Reproduce**
1. Go to any muc with mam enabled while in overlayed view mode
2. Scroll up to trigger mam query
3. Note the address bar changes with appended `#${oldest_message.get('msgid')}`

**Expected behavior**
When converse.js is used in overlayed mode, it's expected that its used as part of the web application. Web applications using the url for routing information (for example, I'm using react-router's `HashRouter`) can be negatively effected by url history state change.

**Environment (please complete the following information):**
 - Desktop
 - Chrome
 - Converse.js 7.0.5

The exact line causing this is https://github.com/conversejs/converse.js/blob/master/src/plugins/mam-views/utils.js#L18

Best solution might be to add a settings option to manually disable all url history interactions.

**Comment by jcbrand** [comment]
> Best solution might be to add a settings option to manually disable all url history interactions.

Agreed. Are you willing to make a pull request with such a change?

**Comment by Alexbay218** [comment]
I'm not too familiar with the architecture, but I could take a stab at it.

**Comment by Alexbay218** [comment]
I've added the changes, but I couldn't get it to compile and test it on windows. https://github.com/Alexbay218/converse.js has the changes with documentation.

Here are the errors I'm getting on windows trying to do a `npm install`
![image](https://user-images.githubusercontent.com/9091117/115128399-92707680-9fab-11eb-9c21-1bbbd5740cdc.png)

**Comment by jcbrand** [comment]
Thanks, please make an MR with what you have and I'll take a look.

**Comment by jcbrand** [comment]
I think the errors you're getting is because `@converse/headless` is a lerna package, so you need to run lerna first.

Try:

```
npm install lerna
npm run lerna
npm rebuild node-sass
npm run dev
```

**Comment by Alexbay218** [comment]
Here is the draft PR, I still could not install learna on my laptop for some reason.
![image](https://user-images.githubusercontent.com/9091117/115975465-f0183c00-a532-11eb-8354-fa894d92e0aa.png)

**Comment by jcbrand** [comment]
Thanks, I've updated and merged your branch.

**Comment by jcbrand** [comment]
No fixed date yet. Probably somewhere in late May or June.
