### ISSUE TITLE
Conversejs don't working with big rosters (local DoS)

### ISSUE THREAD

**Issue by member7me** [conversejs/converse.js#2465]
Conversejs isn't working with big rosters. If roster more than ~70-100 xmpp's, Conversejs freezes browser. 
I have tried to login into XMPP with ~1000 rosters, It fully hangs my browser and leaks memory (local DoS). I should kill process throght process manager.

Conversejs v7.0.5
Browsers:
Chrome 90.0.4430.85
Mozilla FF - 88.
login as `This is a trusted device` - `yes` / `no` - it doesn't affect 

Console full of such errors:
![1](https://user-images.githubusercontent.com/66087479/115962990-7e39f580-a526-11eb-847b-c30edff75bc8.png)

**Comment by vampiebar** [comment]
I am doing the same test ( by chance ) with 1660 people in chat

it just blocks browser 5-6 seconds. But this is an also issue I think
https://github.com/conversejs/converse.js/issues/2466

**Comment by jcbrand** [comment]
See my comment here: https://github.com/conversejs/converse.js/issues/2466#issuecomment-829058488

**Comment by Echolon** [comment]
Guys, you were quicker, but I will close this in favor of #2466 as there is a bit more information. Please comment there.

Anyway, thanks for reporting!
