### ISSUE TITLE
Error: Cannot find module 'converse.js' or its corresponding type declarations 

### ISSUE THREAD

**Issue by raphael10-collab** [conversejs/converse.js#2468]
I installed `converse.js` via  `yarn` in my Electron-React-Typescript-Webpack app.

Importing it in a react page:

    import * as converse from 'converse.js';

gives this error:  `Cannot find module 'converse.js' or its corresponding type declarations`

OS: Ubuntu 18.04.4 Desktop
node: v14.5.0

How to solve the problem?

**Comment by bartenra** [comment]
Converse.js does not have Typescript bindings.

**Comment by jcbrand** [comment]
Try  `import converse from 'converse.js/src/converse.js';`
