### ISSUE TITLE
Create plugin converse.js

### ISSUE THREAD

**Issue by juancar0505** [conversejs/converse.js#2479]
Good morning, i'm using version 3.3.4 of converse (the last that support Explorer). I'm trying to create a plugin that modifies the message when it sent to the receiver. Thats is, i m going to write a link in the chat and when i send ir, the receiver will see, for example, the word photo, and can open the link from it.
What are the methods and considerations that i have to use of converse for this ? 
Thanks for the help

**Comment by jcbrand** [comment]
You can read the plugin development guide from version 3.3.4:

https://github.com/conversejs/converse.js/blob/v3.3.4/docs/source/plugin_development.rst

If you run into a specific problem I might be able to help, but I'm not going to do the work for you to figure out what you need to do.
