### ISSUE TITLE
Display refresh (every minute) always jumping to the end of the conversation

### ISSUE THREAD

**Issue by cedricmarie** [conversejs/converse.js#2493]
**Describe the bug**
When reading a conversation with relatively long history, the display refreshes every minute and brings back to the bottom of the conversation, which is quite irritating, because we just have the time to scroll up and find where we had stopped reading in the conversation, and then again it bumps to the end.

**To Reproduce**
1. Read a long conversation (several screens)
2. Scroll up
3. Wait for 1 minute (at max)
4. See that we bump to the bottom

**Expected behavior**
Whatever needs to be refreshed, I would expect the current position in the conversation to be preserved.

**Environment (please complete the following information):**
 - Desktop version
 - Firefox browser
 - Converse.js version 7.0.4

**Comment by licaon-kter** [comment]
Can you test with current HEAD?

**Comment by jcbrand** [comment]
The latest code is here: https://conversejs.org/trunk/fullscreen.html

You can check whether it happens there as well.

**Comment by cedricmarie** [comment]
It seems to be fixed on this trunk version. In fact, there seems to be no refresh (i.e. brief blank screen with spinner) at all, even when we're at the end of the conversation. But that's surely normal behaviour.
OK, so I'll just wait for the service provider to upgrade the version (Hope it's already in 7.0.5).
Thank you.

**Comment by jcbrand** [comment]
Thanks for checking. 

I think this issue is solved in 7.0.5 as well.

**Comment by cedricmarie** [comment]
Hi, sorry for commenting this issue again, but in the meantime my XMPP service provider kindly upgraded the version, first with 7.0.5, and later with 7.0.6.
With both versions, the problem was reproduced. Do you have any idea of anything else besides the source code itself - maybe a config file - that could explain the difference of behaviour?
I've just tried connecting with both this instance, and your trunk instance. And I clearly have the issue only in my 7.0.6 instance. And I had already checked that the trunk version did not have the problem, before 7.0.6 was released (comments above).

**Comment by jcbrand** [comment]
In the current master branch we no longer manually scroll down but use `flex-direction: reverse` which is finally supported by Firefox. I suspect that also fixes this issue.

**Comment by cedricmarie** [comment]
OK, so you're suggesting we should try again with the next release?
Yet the strange thing is that it was apparently fixed with the trunk before 7.0.6...

**Comment by jcbrand** [comment]
Yes, I believe it's fixed in master and so the fix will be included in the upcoming 8.0.0 release.

**Comment by cedricmarie** [comment]
The issue has been fixed - with version 7.0.6 - by changing the connection method from Websockets to BOSH. The admin from my XMPP service provider needs to investigate a little bit more, to clearly understand what caused the issue with Websockets, but he decided to test BOSH after having seen that your trunk instance was using it, and that the websocket connection was closed automatically after about one minute (which resulted in page reloading).

He's still not sure whether the problem is due to the particular setting of its installation, or a bug that anyone should have if using websockets...

**Comment by jcbrand** [comment]
Are you using Openfire?

I remember @guusdk also having an issue with the websocket connection dropping every 60 seconds.

This was the issue that caused it: https://github.com/strophe/strophejs/issues/374

**Comment by pitchum** [comment]
We are using ejabberd and the problem was actually caused by a misconfiguration on our side.
We had 2 nginx (don't ask me why) reverse proxies in front of ejabberd's websocket listener, and I guess one of those nginx was shutting connections after 60 seconds of inactivity. I'm not entirely sure of that because I couldn't find any meaningfull message in nginx's error log.

Problem solved after moving one the 2 nginx out of the equation and setting `websocket_ping_interval: 55` in *ejabberd.yml*.
It ensures that ejabberd sends a keepalive ping every 55 seconds, just before nginx consider the connection unused (nginx's default [proxy_read_timeout](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_read_timeout) is 60 secs).

Our ConverseJS now works fine with websockets :)
