### ISSUE TITLE
Syntax error with IE11 browser

### ISSUE THREAD

**Issue by SilverYoCha** [conversejs/converse.js#2498]
**Describe the bug**
I get a syntax error with IE11:
```
SCRIPT1002: Syntax error
converse.min.63snapshot.js (1,10429)
```
It refers to the line 20 of sasl.js source: `export default class SASLMechanism`.

**To Reproduce**
Just initialize a converse.js instance which is working on other common browsers.

**Environment:**
 - Desktop
 - Browser IE11
 - Converse.js version 7.0.5 (from tar.gz)

**Additional context**
As the error concerns syntax that is not supported by IE11, I tried from GitHub repository sources to set different kinds of config about `"@babel/preset-env"` from `webpack.common.js` file. But I got no success even if it was not the same error.
I'm surely lacking experience with webpack, and if anyone could help me out, I would be very grateful.

**Comment by jcbrand** [comment]
IE11 isn't supported.
