### ISSUE TITLE
No image preview for OMEMO encrypted files

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/converse.js#2554]
Using HEAD (01efb02f9e55aaaf1d27a3b77a8bc7f96e1cde88)

Neither sent, nor received are shown when using [`show_images_inline`](https://conversejs.org/docs/html/configuration.html?highlight=show_images_inline#show-images-inline)

**Comment by jcbrand** [comment]
Works fine for me locally, please provide more detail (that's what the issue template is for).

**Comment by licaon-kter** [comment]
It's an encrypted file, of course that the URL doesn't end with an extension.

So you know what the fix is, right? :)

**Comment by jcbrand** [comment]
> It's an encrypted file, of course that the URL doesn't end with an extension.

No, this is not "of course". The encrypted files are still uploaded with the filename and extension of the original file that the user shared.

Converse doesn't show images inline for URLs that don't end in image file extensions.

**Comment by licaon-kter** [comment]
Are we lost in translation here? The URL ends up with the decryption key, right? Not with extension, right? The full URL I mean.

**Comment by jcbrand** [comment]
`filename.ext` contains the extension, so the url path ends with the extension.

**Comment by licaon-kter** [comment]
Yes, it contains it, no preview.
Setting as: `show_images_inline:['upload.mydomain.tld']`

![conversenopreviewomemo](https://user-images.githubusercontent.com/2282799/124567305-67235800-de33-11eb-98fb-ce8a3f02ea72.jpg)

**Comment by licaon-kter** [comment]
Oh okay, think I got it

Log says
>  Content Security Policy: Page settings blocked resource loading of blob: https://mydomain.tld/5624cefe-5798-4b01-9171-69b6b860217f („style-src”).

Since OMEMO images are these... blobs.

**Comment by licaon-kter** [comment]
Nope, that doesn't fix it :(

**Comment by jcbrand** [comment]
@licaon-kter Please check whether the latest commit fixes this issue. Thanks.

**Comment by licaon-kter** [comment]
@jcbrand Thanks
