### ISSUE TITLE
Sending a ping IQ stanza before the stream is set up?

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/converse.js#2562]
ejabberd warnings in logs with HEAD ( https://github.com/conversejs/converse.js/commit/fe3650d7668d9be20041f78cdc0dfd4c731a1fd2 )

```
[info] <0.10993.0>@ejabberd_c2s:process_auth_result:268 (websocket|<0.10992.0>) Accepted c2s SCRAM-SHA-1 authentication for converseruser@mydomain.tld by sql backend from hidden_by_ejabberd
[warning] <0.10993.0> unexpected event from XML driver: {xmlstreamelement,{xmlel,<<"iq">>,[{<<"xmlns">>,<<"jabber:client">>},{<<"id">>,<<"some-uuid:ping">>},{<<"to">>,<<"mydomain.tld">>},{<<"type">>,<<"get">>}],[{xmlel,<<"ping">>,[{<<"xmlns">>,<<"urn:xmpp:ping">>}],[]}]}}; xmlstreamstart was expected
```

**Comment by licaon-kter** [comment]
Still an issue

Log of that ws exchange:

![conversespam1](https://user-images.githubusercontent.com/2282799/188131275-9a2b1123-3bec-4918-9ec9-672fae274f4e.png)

Holger of ejabberd said:
> Converse.js sends that `ping` out of nowhere, i.e. before the auth negotiation dance is done.
> ​​Maybe some separate "thread" for pinging or something.

**Comment by jcbrand** [comment]
@licaon-kter: Is the ping to your server or to a MUC?


I checked the code, and I see checks whether the server is connected before sending a ping, so I'm not sure where/how this is happening.

**Comment by licaon-kter** [comment]
@jcbrand Where can I see that? Why isn't that in the server log above or console log picture?

**Comment by jcbrand** [comment]
You whited out the `to-="xxx"` field of the `iq` stanza :smile: 

I don't know where you got those logs.

Having looked at the code, my suspicion is that it's a MUC being pinged.

**Comment by jcbrand** [comment]
This part of the first logs makes it look like it was your bare JID:

`{<<"to">>,<<"mydomain.tld">>}`

Did you manually change it to `mydomain.tld`?

**Comment by licaon-kter** [comment]
> You whited out the to="xxx" field of the iq stanza smile

Oops, yes that's `mydomain.tld`

> I don't know where you got those logs.

Firefox - Dev console - Network - websockets requests

> Did you manually change it to mydomain.tld?

Yes


Afaik you still have auth creds to my server, you could check directly :)

**Comment by jcbrand** [comment]
Thanks, this should now be fixed.

**Comment by licaon-kter** [comment]
Yay, no more spam, thankc
