### ISSUE TITLE
Not receiving messages on the UI

### ISSUE THREAD

**Issue by vvavepacket** [conversejs/converse.js#2597]
So Im using ejabbered (as my XMPP server) and I was able to make my conversejs work and connect to it via Websocket.

I created an account on my other PC and use Gajim (another XMPP client). Now I'm doing testing between converse and my gajim client. When sending a message from Converse to Gajim, I'm able to receive on Gajim. But when i try to reply back, the messages are not showing on Converse.

I turned debug and I'm able to see incoming messages on console like below:

` 2021-08-12T21:20:35.264Z DEBUG: <message xmlns="jabber:client" xml:lang="en" to="4a575057-ffe2-485c-b5db-1bdf0397643f@test.xxx.com" from="fa9a3044-196a-4629-a110-2342c48936f5@test.xxx.com/gajim.MTGF9JN6" type="chat" id="2f2a767d-eb78-438e-b236-91c834ef8972"><archived by="4a575057-ffe2-485c-b5db-1bdf0397643f@test.xxx.com" id="1628803235223203" xmlns="urn:xmpp:mam:tmp"/><stanza-id by="4a575057-ffe2-485c-b5db-1bdf0397643f@test.xxx.com" id="1628803235223203" xmlns="urn:xmpp:sid:0"/><origin-id xmlns="urn:xmpp:sid:0" id="2f2a767d-eb78-438e-b236-91c834ef8972"/><request xmlns="urn:xmpp:receipts"/><active xmlns="http://jabber.org/protocol/chatstates"/><markable xmlns="urn:xmpp:chat-markers:0"/><body>this is my reply</body></message>
`

But why is that Converse is not showing them up on the UI?

What are the possible issues that prevents it from showing in the UI?

**Comment by licaon-kter** [comment]
Which Converse version? Other clients work fine both ways (eg. Conversations or Dino)? Server score on https://compliance.conversations.im ?

**Comment by vvavepacket** [comment]
Im using the latest converse js version

**Comment by licaon-kter** [comment]
@vvavepacket latest from HEAD git compiled? Latest Release?

**Comment by vvavepacket** [comment]
Sorry I mean latest release.

With respect to xmpp compatibility checker.. i tested with two seperate
XMPP clients on different computers and they were able to communicate
properly. I can send on both machines and see the reply on one another.


What bothers me is the messages im sending towards conversejs is showing up
in debug logs in firefox.. so conversejs is receiving it properly, but is
there any filter on when it decides it should show up on the front-end?

**Comment by vvavepacket** [comment]
@licaon-kter 
I run compliance test and I'm 85%

I think I have the minimum requirements to receive messages right?

![image](https://user-images.githubusercontent.com/8295642/129460228-a3de6194-24dd-4092-80d1-eba2e6858f71.png)

**Comment by vvavepacket** [comment]
# There is an issue with 7.0.6 (latest release)

# If I use 7.0.5 it works as expected.


7.0.6 is broken in terms of receiving messages. @licaon-kter  can you confrm if using 7.0.6 on your end causes messages to be not received?

**Comment by vvavepacket** [comment]
Bug open [here](https://github.com/conversejs/converse.js/issues/2599)
