### ISSUE TITLE
Doesnt receive messages on UI in 7.0.6

### ISSUE THREAD

**Issue by vvavepacket** [conversejs/converse.js#2599]
**Describe the bug**
When using release 7.0.6, receiving messages doesnt work. 7.0.5 works as expected

**To Reproduce**
1. Open two pages
2. Login on different accounts
3. Message other person
4. The other person will not receive the messages in the UI (even though console debug logs appears)

**Expected behavior**
Receiving end should show the new message on front-end

**Environment (please complete the following information):**
 - Desktop or Mobile? Both
 - Browser [e.g. Chrome, Firefox] Chrome and Firefox
 - Converse.js version [e.g. 4.2.0] 7.0.6

**Additional context**
The release link in [CDN](https://cdn.conversejs.org/7.0.6/dist/converse.min.js) appears to be broken as well. Not sure if 7.0.6 is buggy enough. Are there any unit tests for this?

**Comment by licaon-kter** [comment]
Can you build HEAD from git to confirm?

**Comment by jcbrand** [comment]
Sorry, I'm no longer supporting version 7.
