### ISSUE TITLE
Question: Persistent websocket connection upon page reload

### ISSUE THREAD

**Issue by vvavepacket** [conversejs/converse.js#2600]
So I am able to use auto login feature which is via providing `credentials_url`. That means on every reload, or whenever I go to a new page on my website, I can see the chat loading up, and I'm seeing a millisecond where its attempting to login to XMPP (seeing the circling/loading icon) and it connects successfully.

That is the expected behavior right? But I was spoiled with FB's way of chatting on web since every page reload, seems the chat always load immediately with no logging in.

The user experience we have with Facebook is quite different. Whenever we visit a new page, which is a page reload, the chat appears to load instantly (no showing of logging in...)

Is that more of a UX trick? I've read previous tickets here that mentioned websockets simply dies and reconnects again on page reload. Can someone explain this further?

**Comment by jcbrand** [comment]
Make sure that you have [XEP-0198 Stream Resumption](https://xmpp.org/extensions/xep-0198.html) enabled on your server.

The websocket connection will still be torn down between page reloads, but the reconnection will be much quicker because the existing XMPP session will be re-used.
