### ISSUE TITLE
Anonymous SASL authentication fails (`Invalid token`)

### ISSUE THREAD

**Issue by tacerus** [conversejs/converse.js#2605]
**Describe the bug**
Upon attempting to authenticate to an ejabberd server anonymously, the authentication fails with an `Invalid token` error.  A wrong-looking `X-OAUTH2` log entry is generated.

**To Reproduce**
1. Clone master
2. `make dist`
3. Initialize an instance:
```
        <script>
                    converse.initialize({
                    bosh_service_url: 'https://xmpp.liberta.casa/bosh/',
                    view_mode: 'fullscreen',
                    authentication: 'anonymous',
                    auto_login: false,
                    allow_logout: false,
                    allow_message_corrections: 'last',
                    allow_registration: false,
                    auto_list_rooms: true,
                    auto_away: 1800,
                    auto_xa: 43200,
                    auto_join_on_invite: true,
                    auto_join_rooms: ['libcasa@muc.liberta.casa', 'libcasa.info@muc.liberta.casa'],
                    loglevel: 'debug',
                    default_domain: 'liberta.casa',
                    discover_connection_methods: true,
                    enable_muc_push: true,
                    jid: 'liberta.casa',
                    locked_domain: 'liberta.casa',
                    message_archiving: 'never',
                    muc_disable_slash_commands: ['mute', 'voice', 'kick', 'ban'],
                    muc_domain: 'muc.liberta.casa',
                    auto_reconnect: false
                                });
        </script>
```
4. See error in the browser console:
```
2021-08-23T18:44:03.500Z WARNING: Could not restore session for jid: liberta.casa Error message: _restore: no restoreable session. <empty string> log.js:66:19
2021-08-23T18:44:06.300Z WARNING: Could not restore session for jid: liberta.casa Error message: _restore: no restoreable session. <empty string> log.js:66:19
2021-08-23T18:44:06.400Z DEBUG: Status changed to: CONNECTING log.js:70:19
2021-08-23T18:44:06.700Z DEBUG: Websocket open log.js:70:19
2021-08-23T18:44:06.700Z DEBUG: <open to="liberta.casa" version="1.0"/> log.js:70:19
2021-08-23T18:44:06.700Z DEBUG: <open xmlns="urn:ietf:params:xml:ns:xmpp-framing" id="609608898781306914" version="1.0" xml:lang="en" from="liberta.casa"/> log.js:70:19
2021-08-23T18:44:06.700Z DEBUG: _connect_cb was called log.js:70:19
2021-08-23T18:44:06.700Z DEBUG: <stream:features xmlns:stream="http://etherx.jabber.org/streams"><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>ANONYMOUS</mechanism><mechanism>PLAIN</mechanism><mechanism>X-OAUTH2</mechanism></mechanisms><register xmlns="http://jabber.org/features/iq-register"/></stream:features> log.js:70:19
2021-08-23T18:44:06.700Z DEBUG: <auth mechanism="X-OAUTH2">AAB1bmRlZmluZWQ=</auth> log.js:70:19
2021-08-23T18:44:06.800Z DEBUG: <failure xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><not-authorized/><text xml:lang="en">Invalid token</text></failure> log.js:70:19
2021-08-23T18:44:06.800Z DEBUG: Status changed to: AUTHFAIL log.js:70:19
2021-08-23T18:44:06.800Z DEBUG: DISCONNECTED log.js:70:19
```

**Expected behavior**
The authentication should succeed using anonymous SASL (XEP-0175). I think the `X-OAUTH2` attempt should not be there.

**Environment (please complete the following information):**
 - Desktop
 - Firefox, Opera
 - Converse.js master branch (8eac03104)

**Additional context**
ejabberd configuration:
```
auth_method:
  - anonymous
  - ldap
anonymous_protocol: sasl_anon
```

The instance in question is hosted on https://xmpp.liberta.casa.

Connecting and authenticating using `login` works.

**Comment by jcbrand** [comment]
Your server advertises support for X-OAUTH2 which is given a higher priority than ANONYMOUS by Strophe.js, so Converse will try to connect via X-OAUTH2 instead of ANONYMOUS.

See here: https://github.com/strophe/strophejs/blob/2acbf6cc4f53b4a38ca758c39e67f4fcb451bb46/src/core.js#L1415

You need to either turn off support server-side support (i.e. advertisement) for X-OAUTH2 or configure Converse.js to only attempt to use supported SASL mechanisms.

You can do this with the [connection_options](https://conversejs.org/docs/html/configuration.html#connection-options) setting.

**Comment by licaon-kter** [comment]
@tacerus Did you read https://github.com/processone/ejabberd/issues/3209 yet?

**Comment by tacerus** [comment]
Hi, thanks for the input!

I didn't realize it was ejabberd advertising it.

@licaon-kter 
I am running ejabberd 21.07, which is the latest stable from what I can tell.
Setting `disable_sasl_mechanisms: ["X-OAUTH2"]` helped a bit - I would have never thought of that, as it is not included in the documented SASL mechanisms one can disable https://docs.ejabberd.im/admin/configuration/toplevel/.

Upon setting it, the page now loads, and gets to the box allowing the user to enter their nickname. On the first attempt, it would then not go further, but upon trying again to copy the error, it worked, only that it quits after 1-2 minutes with ` ERROR: Websocket closed unexpectedly`. I think that's more of a proxy or ejabberd issue though - so thanks a lot for the tip!

@jcbrand 
I then tried to also set the suggested Converse.js setting, which, if I read the Strophe documentation correctly, should be 
```
                    connection_options: {
                        'mechanisms': [
                            converse.env.Strophe.SASLAnonymous,
                        ]
                    },
```
however the browser will complain with a _TypeError: converse.env is not defined_ and refuse to load the script. Copying the MD5 example from the Converse.js documentation yields the same result. Has that possibly changed?` Either way thank you as well! I think the XMPP server side setting should have achieved the same result.

**Comment by jcbrand** [comment]
@tacerus: You're probably getting the `converse.env is not defined` error because by the time that code executes, converse.js hasn't been fully loaded and executed by the browser yet.

Converse has the `converse-loaded` event which is fired on the `window` to help you to know when the `converse` global is available.

So you can do:

```javascript
window.addEventListener('converse-loaded', () => {
    
    // now converse and converse.env should be available.
    converse.initialize({ ... });
});
```

**Comment by tacerus** [comment]
Ah - Thank you! That seems to work too now,
