### ISSUE TITLE
MUC sometimes fails to display its center pane

### ISSUE THREAD

**Issue by linkmauve** [conversejs/converse.js#2624]
**Describe the bug**
The center pane of a MUC view can be completely white, with errors spawned in the console.

**To Reproduce**
1. Go to https://inverse.chat
2. Connect to an account with existing autojoin bookmarks
3. See the participants list, but the rest is empty and there are errors in the console.

**Expected behavior**
The MUC view should display as normal

**Screenshots**
![wayland-screenshot](https://user-images.githubusercontent.com/7755816/132090023-69c4afcb-b3eb-41ae-b127-a44429f68f32.png)

**Environment (please complete the following information):**
 - Desktop
 - Firefox (Nightly from the 2021-09-04)
 - Converse.js version 8.0

**Additional context**
```js
Uncaught (in promise) TypeError: can't access property "model", t.querySelector(...) is null
Uncaught (in promise) TypeError: can't access property "toJSON", this.model.vcard is undefined
Uncaught (in promise) TypeError: can't access property "getUnopenedBookmarks", pa.bookmarks is undefined
Uncaught (in promise) Error: A "url" property or function must be specified
Uncaught (in promise) <iq id="6d41fbc2-0ce3-4d15-b87c-515bbd63fe41:sendIQ" xmlns="jabber:client" to="<my-jid>@jabber.fr/converse.js-58829258" type="error">
```
Please ask me about additional things you may need to debug this issue.

**Comment by jcbrand** [comment]
Closing this, since I haven't seen it happen in a long time.
