### ISSUE TITLE
OPTIONS is done before each BOSH request

### ISSUE THREAD

**Issue by linkmauve** [conversejs/converse.js#2625]
**Describe the bug**
Converse sends an OPTIONS request before every single POST request.

**To Reproduce**
1. Go to https://inverse.chat
2. Login (using a jabber.fr JID, not sure if relevant)
3. Observe the network console

**Expected behavior**
Only a single OPTIONS request should be emitted, before the first BOSH request in order to receive the CORS headers.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Desktop
 - Firefox (Nightly from the 2021-09-04)
 - Converse.js version 8.0

**Additional context**
N/A

**Comment by jcbrand** [comment]
OPTION requests are sent automatically by the browser and not Converse itself.

It makes sense to me that it would send the request every single time, since the HTTP server's settings might change between requests.

I don't think there's anything for us to do here.
