### ISSUE TITLE
Spoiler toggles only after switching to another tab and back

### ISSUE THREAD

**Issue by linkmauve** [conversejs/converse.js#2627]
**Describe the bug**
Clicking on the spoiler button doesn’t emit any error, but it only takes (visual?) effect after switching to another discussion and back.

**To Reproduce**
1. Go to https://inverse.chat
2. Click on the spoiler button

**Expected behavior**
This action should instantly change the input to include the spoiler input.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Desktop
 - Firefox (Nightly from the 2021-09-04)
 - Converse.js version 8.0

**Additional context**
N/A

**Comment by JohnXLivingston** [comment]
I have the same bug (ConverseJS 9.0 on my setup, and on https://conversejs.org/fullscreen.html).
In a MUC, a click on the «toggle_occupants» button also make it work.
