### ISSUE TITLE
Open groupchats toggle emits an error

### ISSUE THREAD

**Issue by linkmauve** [conversejs/converse.js#2628]
**Describe the bug**
The toggle label “open bookmarks” emits `Uncaught TypeError: can't access property "querySelector", this.el is undefined` and then doesn’t do anything else.

**To Reproduce**
1. Go to https://inverse.chat
2. Click on “open bookmarks” in the left pane.

**Expected behavior**
All open rooms would be hidden, the triangle would change direction, and no traceback would be displayed. Then when clicking it again, it would go back as it was originally.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Desktop
 - Firefox (Nightly from the 2021-09-04)
 - Converse.js version 8.0

**Additional context**
N/A

**Comment by jcbrand** [comment]
I see this with the 'Open groupchats' list, not the bookmarks.
