### ISSUE TITLE
WARNING: Received a MEP message for a non-existent room

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/converse.js#2633]
HEAD (9b4ce0011e7f59664edf2d08d91f8156d191b1d9) on Firefox Stable

Since https://github.com/conversejs/converse.js/commit/90ea092e4de092f988f884a34e955582bc5dbe05 I see this logged in console (not debug mode) on each stream reconnect: 
`WARNING: Received a MEP message for a non-existent room: account@domain.tld <empty string>` twice

and once for `contact@domain.tld`

`<empty string>` is literal, I didn't cut anything

/LE: Looks like Vivaldi Snapshot console has some info
```
WARNING: Received a MEP message for a non-existent room: account@domain.tld 
log @ log.js:66
warn @ log.js:89
(anonymous) @ utils.js:193
async function (async)
(anonymous) @ utils.js:191
Zu @ utils.js:210
run @ core.js:1264
(anonymous) @ core.js:2526
forEachChild @ core.js:316
_dataRecv @ core.js:2515
_onMessage @ websocket.js:506
socket.onmessage @ websocket.js:277
```

**Comment by jcbrand** [comment]
Can you please turn on debug logging and then send me the stanza traffic that happens just before that warning?

I'd like to see what the stanza looks like that triggers this, then I can think of a fix. Thanks.

**Comment by licaon-kter** [comment]
Updated to f40a8f69ae601f3c9fb7fc71c4b056e82a9366a5 so the messages for account@ have gone, but I still have them for contact@

Just before the warning I see this:
```
DEBUG: <message xmlns="jabber:client" to="account@domain.tld/converse.js-132945634" from="contact@domain.tld" type="headline"><event xmlns="http://jabber.org/protocol/pubsub#event"><items node="eu.siacs.conversations.axolotl.devicelist"><item id="current"><list xmlns="eu.siacs.conversations.axolotl"><device id="XXXXXXXX"/></list></item></items></event><addresses xmlns="http://jabber.org/protocol/address"><address jid="contact@domain.tld/Conversations.k1bh" type="replyto"/></addresses></message> log.js:70:19
```

**Comment by licaon-kter** [comment]
Updated to 8aa16ea0be0de752336619a80158ce95b1391b07 and it's gone now, thanks
