### ISSUE TITLE
No preview for unencrypted images

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/converse.js#2634]
HEAD (9b4ce0011e7f59664edf2d08d91f8156d191b1d9) on Firefox Stable or Vivaldi Snapshot

Wanted to see if https://github.com/conversejs/converse.js/commit/5095027a0b8808a580f78fcfe255f995af99d91f fixed https://github.com/conversejs/converse.js/issues/2281 so I uploaded 2 images, one with OMEMO and one without, from Conversations

![noomemonopreview](https://user-images.githubusercontent.com/2282799/132182198-f280b257-df51-4c30-8ae3-cf960d49ee13.jpg)

Set up as `show_images_inline:['upload.domain.tld']`

**Comment by licaon-kter** [comment]
Actually that's my servers http_upload path, not sure what locally means here :))

**Comment by jcbrand** [comment]
It means you're not using Converse served from localhost.

**Comment by licaon-kter** [comment]
But I am, you have credentials iirc.

**Comment by licaon-kter** [comment]
Anyway, it's fixed in HEAD.
