### ISSUE TITLE
I can’t log in when everything is right

### ISSUE THREAD

**Issue by Wuuko** [conversejs/converse.js#2646]
fedora 34
gnome
HP HP Pavilion Gaming Laptop 15-ec0xxx
AMD® Ryzen 7 3750h with radeon vega mobile gfx × 8 
64-bit

**Comment by licaon-kter** [comment]
Which site? Which browser? Errors in browser console?

**Comment by Wuuko** [comment]
> Which site? Which browser? Errors in browser console?

conversejs.org. tor browser. ıdk

**Comment by Wuuko** [comment]
but sometimes

**Comment by jcbrand** [comment]
Please use the bug report template and provide the asked-for information. There isn't enough information in this issue.

**Comment by Wuuko** [comment]
HOW?

**Comment by jcbrand** [comment]
<img width="1292" alt="Screenshot 2021-09-15 at 11 56 23" src="https://user-images.githubusercontent.com/683911/133412865-4a6a30ec-1984-4833-8608-6782de912b60.png">
