### ISSUE TITLE
Nothing happens when you click add account

### ISSUE THREAD

**Issue by lennylen** [conversejs/converse.js#2651]
**Describe the bug**
When I enter in the BOSH address, username@xmpp.domain.com and password, nothing happens when i click add account. All the fields reset. If i restart the app it just shows a blank display.

**To Reproduce**
1. Enter details on first launch
2. Nothing happens, so restart the app
3. App is now restarted and shows blank screen
4. If i go to debug mode I see one error in error console:

`index.html:1 Uncaught (in promise) Error: The name org.freedesktop.secrets was not provided by any .service files`

**Expected behavior**
To login and chat.

**Screenshots**
![Screenshot_20210914_230118](https://user-images.githubusercontent.com/15621636/133363398-eee61d18-ca35-4d6f-88d0-b3bec4e6d792.png)

**Environment (please complete the following information):**
Desktop App. Debian 10 Stable 

**Additional context**
none

**Comment by licaon-kter** [comment]
Report this in the proper place: https://github.com/conversejs/converse-desktop

**Comment by lennylen** [comment]
My apologies
