### ISSUE TITLE
Missing file upload button

### ISSUE THREAD

**Issue by mishadaut** [conversejs/converse.js#2668]
**Describe the bug**
If I close a chat browser tab( auto_login:true and view_mode: 'fullscreen') without logout and reopen it in the new tab, file upload button is missing.

**To Reproduce**
1. Open new chat window(auto_login:true and view_mode: 'fullscreen')
2. Open same chat window in separate browser tab without log out previous tab.
4. See error - upload button is missing

**Environment :**
  - Desktop
 - Chrome, Safari
 - Converse.js 8.0.1

**Additional context**
I did a dirty fix for it:
``//const http_upload_promise = api.disco.supports(toolbar_Strophe.NS.HTTPUPLOAD, shared_converse.domain);``

``//buttons.push(T`${until_o(http_upload_promise.then(is_supported => this.getHTTPUploadButton(is_supported)), '')}`);``
``buttons.push(this.getHTTPUploadButton(true));``

**Comment by PawBud** [comment]
I can confirm this as well, will try to fix this now.

**Comment by jcbrand** [comment]
I think the issue is that disco entities are stored in sessionStorage. When the (last) tab is closed, sessionStorage is cleared.

When a new tab is opened, I think for some reason the disco entities are not fetched again from the server, and so the upload button isn't shown because Converse thinks that the disco entity representing the user's server doesn't support file uploads.

**Comment by jcbrand** [comment]
I'm not able to reproduce this issue. I wonder if the issue might not be a timeout for the IQ request to fetch the disco features.

I'm not sure what else could be the problem. The usage of sessionStorage doesn't seem to be an issue.

**Comment by PawBud** [comment]
Browser: `Safari`

Version: `Version 15.3 (17612.4.9.1.8)`

https://drive.google.com/file/d/18L7He4GrC0ILFSnfNe0zlhH2mEq9mNUJ/view?usp=sharing

This issue does not persist in safari I believe, when I run it through localhost.

**Comment by jcbrand** [comment]
I believe this was fixed as part of #2925
