### ISSUE TITLE
Question about fetchArchivedMessages (migration from 7.0.5 to 8.0.1)

### ISSUE THREAD

**Issue by SilverYoCha** [conversejs/converse.js#2677]
About a project I work for, a plugin has been written in order to clear messages of a chat (MUC or private) when a threshold is reached (version 7.0.5).

When message clearing is done on the the chat opening, method fetchArchivedMessages on the model of the chat was then called in order to fetch last messages from XMPP server.

Today, I try to update the version of ConverseJS with the last 8.0.1 version. But the plugin does not work anymore because the used fetchArchivedMessages method is nomore available on the chat model instance.

My question is the following: is there any other way to perform the treatment done by the used method from an external Javascript plugin (converse.plugins.add used with Javascript Vanilla)? 

Thank you by advance for your help.

**Comment by jcbrand** [comment]
Check the new [prune_messages_above](https://conversejs.org/docs/html/configuration.html#prune-messages-above) configuration settings. Sounds like it does what you want.

**Comment by SilverYoCha** [comment]
Yes indeed!
I just tried this new option which exactly fulfills the need.
Thank you :-)
