### ISSUE TITLE
error stanzas not handled

### ISSUE THREAD

**Issue by phryk** [conversejs/converse.js#2683]
**Describe the bug**
Error stanzas (i.e. what prosody's `error_reply` sends) are not handled at all.

**To Reproduce**
Do anything that triggers an error stanza in a chat.

You can use my extended [mod_e2e_policy](https://rnd.phryk.net/phryk-evil-mad-sciences-llc/mod_e2e_policy) with `e2e_policy_warn_mechanism = "error"` and send a non-OMEMOed message to trigger an `error_reply` from Prosody.

**Expected behavior**
Show the error message (styled as an error) in the "window" of the chat that triggered it.

**Screenshots**
Not applicable, since nothing is visible.

**Environment (please complete the following information):**
 - Desktop, FreeBSD
 - Firefox, but likely any
 - version loaded from CDN today, so I assume 8.0.1

**Additional context**
Error stanzas are the best mechanism to communicate failures/warnings pertaining to a specific chat in the right context.

**Comment by jcbrand** [comment]
I've added a fix for this in a branch which I'll merge soon.

Looks like your error message's `id` attribute isn't set to the `id` of the sent message that triggered it. This is why the error message didn't appear in Converse and TBH I think that needs to be fixed on your end as well (assuming you wrote the module that sends this error message).
