### ISSUE TITLE
Icons don't display correctly

### ISSUE THREAD

**Issue by zouglou** [conversejs/converse.js#2702]
**Describe the bug**
I get icons to be displayed like "ï€" instead of nice graphics. This is not related #2639 where the problem is about font loading, I don't have any 404 (nor requests to any webfont (I guess those are supposed to be in webpacks? I'm quite not familiar with webpack)).

**To Reproduce**
1. Follow instructions from Quickstart guide, option 2 :
2. Download and extract converse.js-8.0.1.tgz from releases page
3. Create a minimal html file with local package/dist/converse.min.{js,css} files included, and initialize with JS sample given (using conversejs.org BOSH or my own)
4. ..or have a look here, and watch icons do their weird stuff : [noizette.net/xmpp/converse/index.html](https://noizette.net/xmpp/converse/index.html)

**Expected behavior**
I expect icons to show properly :(

**Screenshots**
![Capture d’écran de 2021-10-27 16-33-20](https://user-images.githubusercontent.com/10769882/139088240-d3a2a635-e26a-4625-a394-ca7434215bb7.png)

**Environment (please complete the following information):**
 - Desktop
 - Firefox, Chromium
 - Converse.js version 8.0.1

Also, converse.min.js delivered in the release tar is a bit different from the one served by conversejs CDN for the same version. The one I got in the release seemed buggy, and was making Converse not to receive messages (but send them correctly). Should I create an issue for that too?

**Comment by hessamhoseinkhani** [comment]
I have the same exact problem after building converse. any updates?

**Comment by hessamhoseinkhani** [comment]
I solved it, in my case i was missing <meta charset="utf-8"/> in my index.html file.

**Comment by zouglou** [comment]
What was missing?

**Comment by hessamhoseinkhani** [comment]
<meta charset="utf-8"/>

**Comment by zouglou** [comment]
Nice, it was as simpled as that! Thanks you

**Comment by zouglou** [comment]
Well, I closed the issue because it was solved for me. But maybe I should let it open until it's solved in doc/code?

**Comment by jcbrand** [comment]
I don't think there's anything to fix in the code, so this ticket can stay closed.
