### ISSUE TITLE
Send button doesn't work in a multi-user chat

### ISSUE THREAD

**Issue by johnspurlock** [conversejs/converse.js#2704]
**Describe the bug**
Send button doesn't work in a multi-user chat

**To Reproduce**
1. Open a multi-user groupchat
2. Compose a message
3. Hit the send button (send-button with paper plane icon)
4. Nothing happens

**Expected behavior**
The message should be submitted, the same way it does when "return" is pressed

**Environment (please complete the following information):**
 - Desktop
 - Chrome: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36`
 - https://cdn.conversejs.org/8.0.1/dist/converse.min.js

**Additional context**
Just did a code search for send-button, maybe the multi user form is different when submitting?
https://github.com/conversejs/converse.js/blob/fb6bafdf6c28326b19530ac5fd2b3c376cae7220/src/plugins/muc-views/bottom-panel.js#L42

**Comment by johnspurlock** [comment]
This appears to fix the issue for me locally, hopefully this can be included in a future release asap.

https://github.com/conversejs/converse.js/pull/2707

**Comment by jcbrand** [comment]
Merged thanks.
