### ISSUE TITLE
Cannot login - GET host-meta blocked by Content Security Policy

### ISSUE THREAD

**Issue by jeroenhabets** [conversejs/converse.js#2708]
I host my XMPP on xmpp.habets.dev and use https://habets.dev/.well-known/host-meta to support '@habets.dev' usernames. It seems Converse CSP blocks that host-meta from loading.

**To Reproduce**
1. In Firefox or Chrome go to https://conversejs.org/fullscreen.html
2. Open Web Developers Tool - Network
3. Fill in 'conversejsbug@habets.dev' as username and dummy password
4. Click 'Log In'
5. In red the following error is displayed 
'Connection failure.
Sorry, we could not connect to the XMPP host with domain: "habets.dev"'

In Web Dev Tools Network Errors it shows:
'Content Security Policy: The page’s settings blocked the loading of a resource at https://habets.dev/.well-known/host-meta (“connect-src”).'

**Expected behavior**
https://habets.dev/.well-known/host-meta loaded and used, followed by a login error (due to unknown username)

**Environment:**
 - Desktop (MacOS Monterey 12.0.1)
 - Browser Chrome 95.0.4638.54 (Official Build) (x86_64), Firefox 93.0 (64-bit)
 - Converse.js version v8.0.1dev

- My XMPP Server is running ejabberd 21.07 and passes all compliance tests.

**Comment by licaon-kter** [comment]
Your server hosts and serves that host-meta file, fix your CORS.

**Comment by jeroenhabets** [comment]
But I had a CORS header and now added a few more:
```
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range' always;
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range' always;
```

But I am no CORS expert... It is not your Content-Security-Policy connect-src 'self' from the error I saw or other CSP part that is preventing the load?

`Content-Security-Policy | default-src 'self' https://inverse.chat https://opkode.com https://conversejs.org https://www.youtube-nocookie.com; connect-src 'self' https://conversejs.org  wss://conversejs.org; img-src * 'self' data:; style-src 'self'  'unsafe-inline' cdn.conversejs.org fonts.googleapis.com; script-src  'self' 'unsafe-inline' stats.opkode.com cdn.conversejs.org; font-src  'self' fonts.gstatic.com fonts.googleapis.com cdn.conversejs.org data:`

**Comment by jeroenhabets** [comment]
<img width="885" alt="image" src="https://user-images.githubusercontent.com/1929535/139601242-5c305aa2-9b1b-4166-92be-4fe8274a7bbc.png">

**Comment by jcbrand** [comment]
```
'Content Security Policy: The page’s settings blocked the loading of a resource at https://habets.dev/.well-known/host-meta (“connect-src”).'
```

This is a CSP error, which is not CORS. 

Looks to me like you're expecting the file at https://habets.dev/.well-known/host-meta to be loaded by Converse as hosted o https://conversejs.org but the CSP settings for that domain don't allow files to be loaded from JavaScript for other domains besides `conversejs.org`.

So this is a CSP restriction from https://conversejs.org.

I'm not sure what should be done about this from our side. I'm a bit reluctant to completely open up `connect-src` so that any resources can be fetched via scripts, but looks like that's what would need to be done to let people use XEP-0156 on conversejs.org.

**Comment by jcbrand** [comment]
@jeroenhabets I've now updated the CSP policy to set `connect-src` to `*`.

Please check and let me know whether it now works for you.

**Comment by jeroenhabets** [comment]
Hi @jcbrand,
Yes! I can confirm now it works again for me :).
Thanks!, Jeroen
