### ISSUE TITLE
Error when building with docker 

### ISSUE THREAD

**Issue by rain-1** [conversejs/converse.js#2713]
**Describe the bug**
I got this error when building with docker https://github.com/conversejs/converse.js-docker 

```
E: Unable to correct problems, you have held broken packages.
ERROR: Service 'conversejs' failed to build: The command '/bin/sh -c sudo apt-get install -y npm' returned a non-zero code: 100
```

**To Reproduce**
1. `git clone https://github.com/conversejs/converse.js-docker.git`
2. `cd converse.js-docker`
3. `docker-compose up -d`

**Expected behavior**
A successful build

**Environment (please complete the following information):**
 - linux, raspberry pi

**Additional context**

I also noticed this, but this may be a separate issue

```
                              DEPRECATION WARNING                            

  Node.js 10.x is no longer actively supported!

  You will not receive security or critical stability updates for this version.

```

**Comment by jcbrand** [comment]
That docker config is very old (3 years old) and it looks like the Node version is too old for current Converse.

We're looking for a maintainer for that repo, or at least someone who would be willing to update it so that it works with the latest version of Converse.

**Comment by rain-1** [comment]
https://github.com/conversejs/converse.js-docker/pull/1

**Comment by rain-1** [comment]
much easier to just run these commands

```
git checkout v8.0.1
docker run -v $PWD:/tmp -w /tmp node:14.17.0 make dist
docker run -v $PWD:/tmp -w /tmp -p 8000:8000 node:14.17.0 make serve
```

maybe just delete the docker repo.
