### ISSUE TITLE
Singleton + fullscreen mode styling issue

### ISSUE THREAD

**Issue by JohnXLivingston** [conversejs/converse.js#2715]
**Describe the bug**

With the current version of the repository, singleton mode is working with the fullscreen mode (it wasn't working in ConverseJS v8, see https://github.com/conversejs/converse.js/issues/2647 )

But there is a styling problem:
![image](https://user-images.githubusercontent.com/38844060/140728844-6dea7e0d-dd9b-409a-bb15-f3260df0667c.png)

The window is shifted to the right (border on the left, and cut on the right).

**To Reproduce**

Here are the parameters given to the initialize function:

```javascript
{
allow_adhoc_commands: false
allow_contact_requests: false
allow_logout: false
allow_message_corrections: "all"
allow_message_retraction: "all"
assets_path: "/plugins/livechat/4.0.2/static/conversejs/" // Note: this is the path to the default ConverseJS assets on my setup
authentication: "login"
auto_focus: true
auto_join_rooms: ['xxxxxxx']
auto_login: true
bosh_service_url: "/plugins/livechat/4.0.2/router/webchat/http-bind"
discover_connection_methods: false
hide_muc_participants: false
jid: "root@localhost"
keepalive: false
muc_instant_rooms: true
muc_mention_autocomplete_filter: "contains"
muc_mention_autocomplete_min_chars: 3
nickname: "root"
notify_all_room_messages: ["xxxxx"]
password: "xxxxx"
persistent_store: "sessionStorage"
play_sounds: false
show_client_info: false
show_controlbox_by_default: false
show_retraction_warning: false
singleton: true
view_mode: "fullscreen"
visible_toolbar_buttons: {…}
websocket_url: undefined
}
```

And here is my html (copied from the fullscreen.html in this repo):

```HTML
<!DOCTYPE html>
<html class="no-js">
<head>
    <title>Converse</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="description" content="Converse XMPP/Jabber Chat"/>
    <link type="text/css" rel="stylesheet" media="screen" href="/plugins/livechat/4.0.2/static/conversejs/converse.min.css" />
    <script type="text/javaScript" src="/plugins/livechat/4.0.2/static/conversejs/converse.min.js"></script>
    <script type="text/javascript" src="/plugins/livechat/4.0.2/static/static/builtin.js"></script>
</head>
<body class="converse-fullscreen">
<noscript>You need to enable JavaScript to run the Converse.js chat app.</noscript>
<div id="conversejs-bg"></div>
<script type="text/javascript">
  // Here i'm calling a function that will call the initialize method
</script>
</body>
</html>

```

**Expected behavior**

ConverseJS should use all the space, and not exceed the right side of the screen.

**Screenshots**

![image](https://user-images.githubusercontent.com/38844060/140728844-6dea7e0d-dd9b-409a-bb15-f3260df0667c.png)

**Environment (please complete the following information):**
 - Desktop or Mobile? desktop
 - Browser [e.g. Chrome, Firefox] Firefox (dev edition)
 - Converse.js version [e.g. 4.2.0] v9 as on the master branch on 2021-11-08 (commit https://github.com/conversejs/converse.js/commit/ecfc3e9fcf5b1aa0b0a9fd917148475c95735f52 )

**Comment by rscmbbng** [comment]
Can confirm! You can see it live here: https://lumbung.lurk.org/

**Comment by JohnXLivingston** [comment]
> Can confirm! You can see it live here: https://lumbung.lurk.org/

Thanks!
