### ISSUE TITLE
Chat via URL does not display when you have one already open

### ISSUE THREAD

**Issue by polianomartini** [conversejs/converse.js#2716]
**Describe the bug**
It is not displaying a chat room started via URL when you already have a room open.

**To Reproduce**

1. Initialize Converse with `view_mode: 'fullscreen'`;
2. Open a new chat via URL `#converse/room?jid=room@domain` with an already open chat;
3. The chat is displayed in the list of conversations but it does not load automatically, the previous one is displayed.

**Expected behavior**
That open chat via URL overlaps the current conversation.

**Screenshots**
No open chat
![Screenshot_4](https://user-images.githubusercontent.com/13044849/141010811-90fbc39b-136d-4ba7-8ee9-c23271ebed79.png)

Opening the first chat via URL
![Screenshot_5](https://user-images.githubusercontent.com/13044849/141010962-af4da73b-b129-4933-9558-10efb9573b53.png)

Opening the second chat via URL with a chat already open
![Screenshot_6](https://user-images.githubusercontent.com/13044849/141010992-2298fe58-8374-42f2-8e74-99b84a66532c.png)

**Environment (please complete the following information):**
 - Desktop
 - Edge 94.0.992.50 / Chrome 95.0.4638.54
 - Converse.js version 8.0.1

**Comment by Trevy05** [comment]
is this still open? I would like to try.

**Comment by jcbrand** [comment]
Hi @Trevy05 

That would be great, thanks.

I think you can look at the `routeToRoom` function in utils.js

https://github.com/conversejs/converse.js/blob/605c02901aa424b79cbce79d0fda498d47c7f0bf/src/headless/plugins/muc/utils.js#L59

It gets called when the URL changes:

https://github.com/conversejs/converse.js/blob/605c02901aa424b79cbce79d0fda498d47c7f0bf/src/headless/plugins/muc/index.js#L245

I think to fix this issue you might just have to update the call `api.rooms.open` to pass a third `force` parameter to force it to open.

https://github.com/conversejs/converse.js/blob/605c02901aa424b79cbce79d0fda498d47c7f0bf/src/headless/plugins/muc/api.js#L64

**Comment by iota-008** [comment]
Is this still open?
