### ISSUE TITLE
Message is not displayed if it contains a certain string

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/converse.js#2718]
...but it is received, decrypted, sent and shown in notification. Just not displayed in the chat.

The string is: `https://ltt.rs/fdroid/repo/Ltt.rs-%v-fdroid-release.apk`

Firefox Stable (Desktop and Android)
Converse HEAD (https://github.com/conversejs/converse.js/commit/ecfc3e9fcf5b1aa0b0a9fd917148475c95735f52)   

Will get a log asap

**Comment by jcbrand** [comment]
Thanks, if I have to guess, it's the `%v` in the message that might be causing the issue.
