### ISSUE TITLE
Is it possible to reload an open room?

### ISSUE THREAD

**Issue by polianomartini** [conversejs/converse.js#2724]
I have an open room and I changed the naturalName via Openfire's REST API.

How can I force to "reload" room?

**Comment by jcbrand** [comment]
I don't know what the `naturalName` is, sounds like an Openfire specific thing.

You can try calling `refreshDiscoInfo()` on the room model.

**Comment by polianomartini** [comment]
> You can try calling `refreshDiscoInfo()` on the room model.

That's right! Thanks!
