### ISSUE TITLE
XEP-0363: Not sending headers with upload request

### ISSUE THREAD

**Issue by mwild1** [conversejs/converse.js#2728]
**Describe the bug**
Converse.js does not set the headers provided by the server with the upload. See ['Requesting a Slot'](https://xmpp.org/extensions/xep-0363.html#request) and example 6 to see what that looks like.

> The `<put>` element MAY also contain a number of `<header>` elements which correspond to HTTP header fields. Each `<header>` element MUST have a name-attribute and a content with the value of the header. Only the following header names are allowed: `Authorization`, `Cookie`, `Expires`. Other header names MUST be ignored by the requesting entity and MUST NOT be included in the HTTP request. The requesting entity MUST strip any newline characters from the header name and value before performing the HTTP request.

**To Reproduce**
You can use [mod_http_file_share](https://prosody.im/doc/modules/mod_http_file_share) in Prosody trunk, which now requires an Authorization header on uploads.

Currently Converse.js will receive a HTTP 401 status code when attempting the upload.

**Additional context**
I'm happy to provide test accounts on a server requiring upload headers if needed.

**Comment by jcbrand** [comment]
Thanks. It's not possible to set the `Cookie` header in JavaScript, instead it needs to be set via `document.cookie`.

I've decided to leave that out for now.

**Comment by nikita-cerejo** [comment]
I am getting **403** status code and prosody logs say that `Missing or malformed Authorization header`.

**To Reproduce**
You can use mod_http_file_share in Prosody trunk.
And I am using Converse.js v8.0.1 and I am running it locally on Desktop.

Please can you help out with this issue? Also find the below error message on console. 

![image](https://user-images.githubusercontent.com/90706172/143395772-8075f503-682e-4d25-b969-6fe33e8f2e7e.png)

**Comment by jcbrand** [comment]
This fix isn't in Converse 8.0.1.

It will only be part of the next release, version 9.

**Comment by nikita-cerejo** [comment]
Thanks @jcbrand. Is there any specific brand on which this has been fixed? Like the master branch or any other which I can use temporarily?

**Comment by jcbrand** [comment]
Yes, it's been fixed on the master branch.

You can try out the latest code here: https://conversejs.org/trunk/fullscreen.html (notice the `trunk` in the URL).

>  Please can you tell approximate time for version 9 release?

Soon™

**Comment by nikita-cerejo** [comment]
Thanks for the help. I'll try it out.
