### ISSUE TITLE
Send button is not sending the message

### ISSUE THREAD

**Issue by polianomartini** [conversejs/converse.js#2731]
**Describe the bug**
It is not sending the message when clicked on the send button.

**To Reproduce**
1. Initialize Converse with `view_mode: 'fullscreen'`;
2. Type any message in the textarea element;
3. Click the send button.

**Expected behavior**
Send the message when you click the send button.

**Environment (please complete the following information):**
- Desktop
- Edge 94.0.992.50 / Chrome 95.0.4638.54
- Converse.js version 8.0.1

**Comment by afriedmanGlacier** [comment]
I think this has been fixed in https://github.com/conversejs/converse.js/commit/1c6ada4af81969ad0bfc8c84a62f3686666ecc45 and will be out with the next release

**Comment by polianomartini** [comment]
Thanks @afriedmanGlacier !
