### ISSUE TITLE
How to change language in development mode

### ISSUE THREAD

**Issue by hessamhoseinkhani** [conversejs/converse.js#2744]
At first I wanted to now how I can change the applications language in development mode.
I would be more happier If It could be possible to change applications language in runtime If this so please tell me how I can do that.

I'm using converejs 8.0.1 right now.
Thanks.

**Comment by jcbrand** [comment]
You can use the i18n configuration setting.

See https://conversejs.org/docs/html/configuration.html#i18n

**Comment by hessamhoseinkhani** [comment]
> You can use the i18n configuration setting.
> 
> See https://conversejs.org/docs/html/configuration.html#i18n
> 
> You can change it at runtime via `api.settings.set('i18n', 'de')`, but that's not going to magically rerender all the strings in the new language.

So If It's not rerendering strings to a new language what's its runtime usage?

**Comment by jcbrand** [comment]
The API let's you set settings at runtime which is useful in some cases.

**Comment by hessamhoseinkhani** [comment]
@jcbrand as I mentioned setting i18n in api is not causing ui to change reactively.
