### ISSUE TITLE
Linkify the various links in MUC details

### ISSUE THREAD

**Issue by linkmauve** [conversejs/converse.js#2745]
**Is your feature request related to a problem? Please describe.**
When I view the details of a room, the description and topic fields might contain links, and it’s painful to have to select them and copy/paste them in a different tab. The Groupchat XMPP Address field is also not very easily usable.

**Describe the solution you'd like**
Linkify all of the http:, https: and xmpp: links (and perhaps also mailto: and magnet:, but less important) present, and make the Groupchat XMPP Address a link to xmpp:“the address”?join.

**Describe alternatives you've considered**
Living with the pain of copy/pasting. I’d rather not.

**Additional context**
![wayland-screenshot-2021-12-05_21-23-57](https://user-images.githubusercontent.com/7755816/144762679-ff8c9f66-3d17-4ff2-be84-ae8c04aeb74a.png)

**Comment by Echolon** [comment]
@jcbrand is that difficult or a possible low-hanging fruit?

**Comment by jcbrand** [comment]
Hi @Echolon, for future reference, something like this isn't very difficult, it usually means just wrapping the text in a `converse-rich-text` component.
