### ISSUE TITLE
Media not rendered when Converse runs in a browser extension

### ISSUE THREAD

**Issue by deleolajide** [conversejs/converse.js#2751]
**Describe the bug**
When Converse is run inside a Chrome or Edge extension, **window.location.protocol** return "chrome-extension:". This causes the checkFileTypes  method to return false.
See https://github.com/conversejs/converse.js/blob/6cff47c6d8ff028c31b650f6c8dbf1ef85a1f194/src/headless/utils/url.js#L24

**To Reproduce**
1. Run ConverseJs in a Chrome extension and upload an image.
2. Image is not rendered. Instead the image URL is turned into a clickable URL

**Expected behavior**
Image to be rendered

**Screenshots**

![image](https://user-images.githubusercontent.com/110731/145440277-c0ce439f-9c4d-49e3-b407-0fdf2b6a5227.png)

**Environment (please complete the following information):**
 - Desktop 
 - Browser Chrome and Edge browser extensions
 - Converse.js version 9.0.0

**Additional context**
The screen shot was produced after hacking checkFileTypes and adding a test for 'chrome-extension:'
```
function checkFileTypes (types, url) {
    const uri = getURI(url);
    if (!window.location.protocol === 'chrome-extension:' && (uri === null || !checkTLS(uri))) {
        return false;
    }
    const filename = uri.filename().toLowerCase();
    return !!types.filter(ext => filename.endsWith(ext)).length;
}
```

**Comment by jcbrand** [comment]
`!window.location.protocol === 'chrome-extension:'` looks wrong :)

Should be `window.location.protocol !== 'chrome-extension:'` right?

Please make a PR with the fix.

**Comment by deleolajide** [comment]
> Should be `window.location.protocol !== 'chrome-extension:'` right?

Yes, both expressions achieve the same result I guess even though everyone expects *a != b* and not *!(a = b)*. 
No worries, I will raise a PR with the expected expression 👍

**Comment by jcbrand** [comment]
`!a === b` is not the same as `!(a === b)` because the not operator `!` has higher precedence than equality `===`.

So you were in effect checking `(!window.location.protocol) === 'chrome-extension:'`

**Comment by deleolajide** [comment]
> So you were in effect checking `(!window.location.protocol) === 'chrome-extension:'` which will always be false.

![image](https://user-images.githubusercontent.com/110731/145677595-86ffd341-d2ef-4e05-955c-ec6237da74cf.png)

QED 👍
