### ISSUE TITLE
Navigation keys doesn't work anymore into chat input message

### ISSUE THREAD

**Issue by SilverYoCha** [conversejs/converse.js#2754]
**Describe the bug**
Sometimes, but often after trying to edit a previous message, navigation keys into input message do not work anymore.
It is no more possible to use left key, for example, to position the cursor one letter before.

**To Reproduce**
It is been a while that I try to identify a reproductible case, but without success.
Has anyone ever got this behavior?

**Expected behavior**
Navigation keys always usable.

**Environment (please complete the following information):**
 - Desktop
 - Browser all common WEB browsers
 - Since Converse.js v7 (I don't know for previous versions)

**Additional context**
ConverseJS is used in overlayed mode.
<details>
  <summary>Initialization options</summary>

```
 converse.initialize({
          'view_mode' : 'overlayed',
          'i18n' : 'a language',
          'assets_path' : '/myserver/chat/converse/',
          'sounds_path' : '/myserver/chat/converse/',
          'play_sounds' : false,
          'bosh_service_url' : 'bosh url',
          'allow_logout' : false,
          'auto_login' : true,
          'auto_reconnect' : true,
          'jid' : 'a jid',
          'default_domain' : 'a domain',
          'domain_placeholder' : 'a domain',
          'password' : 'a password',
          'autocomplete_add_contact' : false,
          'notification_icon' : 'aLogo.png',
          'muc_domain' : 'conference.a.domain',
          'locked_muc_domain' : 'hidden',
          'muc_disable_slash_commands' : true,
          'locked_muc_nickname' : true,
          'nickname' : 'a nickname',
          'auto_register_muc_nickname' : true,
          'notify_all_room_messages' : true,
          'auto_join_on_invite' : false,
          'roster_groups' : false,
          'allow_adhoc_commands' : false,
          'allow_contact_removal' : false,
          'allow_contact_requests' : false,
          'allow_registration' : false,
          'show_controlbox_by_default' : false,
          'discover_connection_methods' : false
        });
```

</details>

**Comment by deleolajide** [comment]
>Has anyone ever got this behavior?

I can confirm it. It is difficult to reproduce, but I get a fairly consistent hit after using an emoji. I am yet to confirm if it happens when no external plugins are activated.

**Comment by SilverYoCha** [comment]
I finally found a reproductible case.
* write and send a message (it is just at least to have one)
* open emojis drop down
* select one by using navigation keys
* close emojis drop down by using escape key
* try to modify previous message by using navigational keys
