### ISSUE TITLE
Do not put random translation strings into new strings

### ISSUE THREAD

**Issue by wrooot** [conversejs/converse.js#2756]
This is a general request. As i am doing translation for Converse from time to time i often see random translated string assigned to new strings that were added to GUI. In most cases they don't make sense at all. I assume this is some automatic script trying to pick best matching existing translation? And i think wouldn't it be better to leave new strings empty? Will it use English string then? It will be less confusing probably to the users.

Like, i would prefer to see "Hide commands" in English than "Hide users" in my language on the button somewhere.

**Comment by wrooot** [comment]
Oh, and that would make translating easier, when you just parse for empty strings.

**Comment by licaon-kter** [comment]
So on the Weblate translation portal you have these issues?

**Comment by wrooot** [comment]
I don't use Weblate

**Comment by licaon-kter** [comment]
Well, you should as **that's** the official way to translate this.

/close as invalid

**Comment by licaon-kter** [comment]
Do track down what's going on, maybe it's an issue with sync to weblate or smth. What's the state there? Afaik, it should not insert random strings...but...software can be broken. :)
