### ISSUE TITLE
Documentation problem for embedded mode

### ISSUE THREAD

**Issue by kicken** [conversejs/converse.js#2763]
The documentation for view_mode = embedded needs updating.  The documentation currently says:

 >  embedded is used to embed a single chat into a DOM element in the page. The DOM element must have the id #conversejs.

While trying to upgrade an existing app using this mode, I was getting a very broken full-screen like UI instead.   A minimal test page was also broken.  Checking the demo page source code here it appears that one now needs a <converse-root> element not an element with an id="conversejs"

**Comment by jcbrand** [comment]
Fixed here: ca9e13a047948670bb5a5b925b072325d554d605
