### ISSUE TITLE
Unable to receive messages

### ISSUE THREAD

**Issue by jjschwarz** [conversejs/converse.js#2766]
I have converse running on jabber.insect.com just fine with the following initialize:

        websocker_url: 'wss://jabber.insect.com:5443/ws',
        view_mode: 'fullscreen',
        allow_adhoc_commands: false,
        allow_non_roster_messaging: true,
        allow_registration: false

The users are able to do everything except receiving a message.  I can add groups, send messages, etc just fine.  Any thoughts on where to start debugging?

**Comment by jjschwarz** [comment]
Forgot to mention I also tried bosh with the same result.  The server is ejabberd 21.12.34

**Comment by jjschwarz** [comment]
Testing on conversejs.org on the full screen version works...so it is something about my install.

**Comment by licaon-kter** [comment]
Converse 9, yes?

**Comment by jjschwarz** [comment]
Yes

**Comment by licaon-kter** [comment]
Set loglevel to debug, then open the browser console, see what happens when you send a messages.

**Comment by jjschwarz** [comment]
The log from Chrome is a bit messy...but I never see anything when I send a message, and the other user does get my message.  Here is the entire log from login until they replied.
[](url
[jabber.insect.com-1641487090718.log](https://github.com/conversejs/converse.js/files/7823412/jabber.insect.com-1641487090718.log)
)

**Comment by jjschwarz** [comment]
Cleaner view from the screen shot
<img width="547" alt="Screen Shot 2022-01-06 at 11 40 37 AM" src="https://user-images.githubusercontent.com/5250033/148417995-d678e35c-593e-4b62-a43e-1dffe1467e10.png">

**Comment by jjschwarz** [comment]
OK, I found the issue...it was a broken link to dist in the folder...not sure how it worked at all honestly.
