### ISSUE TITLE
Http-bind runs every second

### ISSUE THREAD

**Issue by ikucera** [conversejs/converse.js#277]
Hi,

I am using Converse as a client for our web app and it works quite good (I can log in, send messages, etc.), but it is calling http-bind every second. The setup is as follows:
- Backend
  - Apache (with ProxyPass configured)
  - PHP
  - Openfire 3.9.3
  - XMPPHP for prebinding
- Frontend
  - AngularJS

The log looks like this:
**POST http://ourhost.com/http-bind/    200 OK  1,01s**                         _strophe.js (line 4435)_
`<body rid="3009" xmlns="http://jabber.org/protocol/httpbind" sid="92b115b5">` _converse.js (line 664)_
0 request id 3.1 state changed to 2                                             _converse.js (line 665)_
0 request id 3.1 state changed to 3                                             _converse.js (line 665)_
0 request id 3.1 state changed to 4                                             _converse.js (line 665)_
0 removing request                                                              _converse.js (line 665)_
0 _throttledRequestHandler called with 0 requests                               _converse.js (line 665)_
0 request id 3 should now be removed                                           _converse.js (line 665)_
0 request id 3.1 got 200                                                        _converse.js (line 665)_
1 _dataRecv called                                                              _converse.js (line 665)_
<body xmlns="http://jabber.org/protocol/httpbind">                             _converse.js (line 663)_
1 no requests during idle cycle, sending blank request                         _converse.js (line 665)_
0 request id 4.0 posting                                                        _converse.js (line 665)_
0 request id 4.0 state changed to 1                                             _converse.js (line 665)_

**POST http://ourhost.com/http-bind/ 200 OK 1,01s**                             _strophe.js (line 4435)_
`<body rid="3010" xmlns="http://jabber.org/protocol/httpbind" sid="92b115b5">` _converse.js (line 664)_
0 request id 4.1 state changed to 2                                            _converse.js (line 665)_
0 request id 4.1 state changed to 3                                            _converse.js (line 665)_
0 request id 4.1 state changed to 4                                             converse.js (line 665)
0 removing request                                                              _converse.js (line 665)_
0 _throttledRequestHandler called with 0 requests                               _converse.js (line 665)_
0 request id 4 should now be removed                                            _converse.js (line 665)_
0 request id 4.1 got 200                                                       _converse.js (line 665)_
1 _dataRecv called                                                             _converse.js (line 665)_
<body xmlns="http://jabber.org/protocol/httpbind">                              _converse.js (line 663)_
1 no requests during idle cycle, sending blank request                         _converse.js (line 665)_
0 request id 5.0 posting                                                        _converse.js (line 665)_
0 request id 5.0 state changed to 1                                             _converse.js (line 665)_

**POST http://ourhost.com/http-bind/ 200 OK 1,01s**                             _strophe.js (line 4435)_
`<body rid="3011" xmlns="http://jabber.org/protocol/httpbind" sid="92b115b5">`    _converse.js (line 664)_
0 request id 5.1 state changed to 2                                             _converse.js (line 665)_
0 request id 5.1 state changed to 3                                             _converse.js (line 665)_
0 request id 5.1 state changed to 4                                             _converse.js (line 665)_
0 removing request                                                              _converse.js (line 665)_
0 _throttledRequestHandler called with 0 requests                               _converse.js (line 665)_
0 request id 5 should now be removed                                           _converse.js (line 665)_
0 request id 5.1 got 200                                                       _converse.js (line 665)_
1 _dataRecv called                                                              _converse.js (line 665)_
`<body xmlns="http://jabber.org/protocol/httpbind">`                             _converse.js (line 663)_
1 no requests during idle cycle, sending blank request                          _converse.js (line 665)_
0 request id 6.0 posting                                                        _converse.js (line 665)_
0 request id 6.0 state changed to 1

And it goes on and on...

Thank you in advance.

**Comment by yasaswyaluri** [comment]
i have downloaded converse js and i able to connect but i would like change some of the things everything is in Jquery is there opensource which are coded in Angular JS

**Comment by yasaswyaluri** [comment]
I need one more suggestion . sending and receiving messages is happening properly but i am unable to register but when we add the domain name it is working perfectly but when i registering it is unable to register at all .
