### ISSUE TITLE
Storage issue

### ISSUE THREAD

**Issue by Paupolo** [conversejs/converse.js#2774]
I log in to my account but I can't press anything. There is no option.

**Comment by licaon-kter** [comment]
You login where? The Converse instance is hosted where? Your account is on the same server? Which browser?

**Comment by Paupolo** [comment]
Tor Browser, same server, conversejs.org

**Comment by Paupolo** [comment]
there is only my nick@server, "group chats", "contacts".

**Comment by licaon-kter** [comment]
Tor Browser is bocking any scripts via uBlock or Noscript?

**Comment by Paupolo** [comment]
No,%100 no. Jcbrand know this issue

**Comment by licaon-kter** [comment]
Can un uncheck "trusted device" ? Tor Browser is always in "private mode" and IndexDB storage is not available.
