### ISSUE TITLE
For windows, build converse.js fail

### ISSUE THREAD

**Issue by chenmj201601** [conversejs/converse.js#2786]
**Describe the bug**
For windows, I want to build converse.js, but it's failed!

My environments:

Windows:11 home basic
NodeJS:16.13.2
NPM:8.1.2

Clone the repository and go to converse.js directory. Then run

`npm install`

Then I got some error.
![image](https://user-images.githubusercontent.com/19809251/150636589-a7aa48fc-28aa-4485-aa46-2e67bbf52f1b.png)

Thanks!

**Comment by kicken** [comment]
Give this branch a test and see if it works for you:  https://github.com/kicken/converse.js/tree/webpack-windows-fix

**Comment by chenmj201601** [comment]
> ``



> Give this branch a test and see if it works for you: https://github.com/kicken/converse.js/tree/webpack-windows-fix

thanks! I have resolved it!

**Comment by chenmj201601** [comment]
resolved!

**Comment by jcbrand** [comment]
@kicken: Will you make a pull request with your fix please?
