### ISSUE TITLE
An attempt to use headless build of converse

### ISSUE THREAD

**Issue by roro-lv** [conversejs/converse.js#2788]
**Describe the bug**

I am very interested in using the 'headless' version of converse. However, I have the impression that it may not work without a bit of tinkering (https://github.com/conversejs/converse.js/issues/1994) and so I have tried using `@converse/headless` npm package, following [the headless example](https://github.com/conversejs/headless-example). Unfortunately it does not work and I have the feeling that is because the `converse` object is not injected in the object `window`. To counter this I added the file [entry.js ](https://github.com/conversejs/converse.js/blob/master/src/entry.js) to my project, which takes care of this role (it requires `@converse/headless` l60, instead of `./converse.js`).
So I managed to get the `@converse/headless `version 8.0.1 working. 
**However I get the following error when I use version 9.0.0:** 

![image](https://user-images.githubusercontent.com/83247226/151041686-465f387b-bef5-43dc-8be9-2d3ea8d541ad.png)

**To Reproduce**
1. add `@converse/headless` v9.0.0 to the project
2. add `https://github.com/conversejs/converse.js/blob/master/src/entry.js` to your project and make it require `@converse/headless` instead of `./converse.js`, line 60)
3. import `entry.js` where you want to use converse
4. initialize converse as you will normally do when you want to use it

**Expected behavior**
I'm expecting `@converse/headless` npm package to work properly

**Environment (please complete the following information):**
 - @converse/headless v9.0.0

**Comment by jcbrand** [comment]
Hi, please use `converse-headless.js` (not the minified file) to get a better error traceback with usable line numbers and then past that here.

**Comment by roro-lv** [comment]
> Hi, please use `converse-headless.js` (not the minified file) to get a better error traceback with usable line numbers and then past that here.

I don't see any `converse-headless.js` file neither on this repo nor in `@converse/headless` package. Maybe are you suggesting to change wepack configuration to generate myself a `converse-headless.js` file ?

**Comment by jcbrand** [comment]
Oh, I see the unminified file isn't included in the `dist` directory. That's unfortunate.

There is however a `.map` file, maybe that can help. In your screenshot of the error, there is a triangle icon on the left side. You can click that to open up the error and get more info. Please do that and show the results here. That might be enough to figure out what's going on.

**Comment by roro-lv** [comment]
And this is what I have when using the non-minified file (i just noticed you specially added a commit, ty)
![image](https://user-images.githubusercontent.com/83247226/152215567-28950074-083a-44b1-8974-aa7c8e8e8538.png)

**Comment by roro-lv** [comment]
Hello again, 
I have made some researches, and it happens that this error is due to this statement  : 
`api.elements.register();` in `src/headless/core.js`

It was added in commit [84c6a0039](https://github.com/conversejs/converse.js/commit/84c6a0039c78b6e1f1e6054ec9ee42586c45f600#diff-a3f31229725baf4cbd2ab23be014f043270bd36ccfc7175a197a2cc81287e6f0R832-R833)

This statement raises an error when converse-headless is used alone, because it calls register() method on undefined api.elements. Indeed, view plugins (muc-views, chatview, headlines-views, etc..) create and fill api.elements. But these plugins are not used in converse-headless, and the ones which are registred aren't using api.elements, which cause this error.
It don't really know how you can fix this, but I guess maybe a simple if(api.elements){api.elements.register()} could be enought ?

**Comment by jcbrand** [comment]
Hi @roro-lv, looks like you found the issue.

Thanks for the explanation. I've pushed a fix for this. If you run into other issues, please let me know via a new bug report.

**Comment by roro-lv** [comment]
Ok, thanks you !
