### ISSUE TITLE
Some display problems with mobile view mode

### ISSUE THREAD

**Issue by SilverYoCha** [conversejs/converse.js#2794]
### Chat with few or no message is not displayed on entire page

**Describe the bug**
A chat with few or no message is not displayed entirely over the screen:
![image](https://user-images.githubusercontent.com/1503467/151404311-788659da-0894-4e11-bd6c-8e4ca6593a33.png)

**To Reproduce**
1. Go to homepage
2. Aim a contact with few or no message and open the chat

**Expected behavior**
The chat should be displayed over the entire screen like it is the case about the group chat (cf. screenshot of common information).

### Can't write message with a chat having lot of message

**Describe the bug**
A chat with lot of message is displayed entirely over the screen, but there is no possibility to write a message.
![image](https://user-images.githubusercontent.com/1503467/151406086-e4a9e31d-2d1e-4616-97e4-f3924ddb1b2a.png)

If editing a previous message, then message edition bloc is displayed, but the chat header disapear and it is no more possible to close the chat.

**To Reproduce**
1. Go to homepage
2. Aim a contact with lot of message and open the chat
3. Try to send a new message

**Expected behavior**
Message edit bloc should be displayed when the chat is displayed over the entire screen like it is the case about the group chat (cf. screenshot of common information).

### Common information

**Screenshots**
Homepage after successful login
![image](https://user-images.githubusercontent.com/1503467/151399276-151b775b-17ea-4b6a-9438-b837188a2d95.png)

Display of a group chat (which is displayed over the entire page)
![image](https://user-images.githubusercontent.com/1503467/151402874-e9b1bdd5-3686-42b8-a218-60a26f9866f9.png)

**Environment**
 - Mobile
 - Browser Chrome
 - Converse.js 9.0.0

**Additional context**
Inspired from `mobile.html` page:
```
  <meta charset="utf-8">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
```

Mobile CSS is applied:
![image](https://user-images.githubusercontent.com/1503467/151407064-b1254c77-9e3b-4dd2-917b-c86561200ea1.png)

<details>
  <summary>Initialization options</summary>

```
 converse.initialize({
          'view_mode' : 'mobile',
          'i18n' : 'a language',
          'assets_path' : '/myserver/chat/converse/',
          'sounds_path' : '/myserver/chat/converse/',
          'play_sounds' : false,
          'bosh_service_url' : 'bosh url',
          'allow_logout' : false,
          'auto_login' : true,
          'auto_reconnect' : true,
          'jid' : 'a jid',
          'default_domain' : 'a domain',
          'domain_placeholder' : 'a domain',
          'password' : 'a password',
          'autocomplete_add_contact' : false,
          'notification_icon' : 'aLogo.png',
          'muc_domain' : 'conference.a.domain',
          'locked_muc_domain' : 'hidden',
          'muc_disable_slash_commands' : true,
          'locked_muc_nickname' : true,
          'nickname' : 'a nickname',
          'auto_register_muc_nickname' : true,
          'notify_all_room_messages' : true,
          'auto_join_on_invite' : false,
          'roster_groups' : false,
          'allow_adhoc_commands' : false,
          'allow_contact_removal' : false,
          'allow_contact_requests' : false,
          'allow_registration' : false,
          'show_controlbox_by_default' : false,
          'discover_connection_methods' : false
        });
```

</details>

**Comment by robjloranger** [comment]
I have been able to reproduce in multiple browsers, both mobile and desktop (with mobile sized view port).

Still digging into the cause.

**Comment by jcbrand** [comment]
@SilverYoCha Can this ticket be closed?

**Comment by SilverYoCha** [comment]
Yes @jcbrand, it can be closed :-)
