### ISSUE TITLE
Weird unicode characters rendering outside of line-height

### ISSUE THREAD

**Issue by yandrey** [conversejs/converse.js#2797]
because of the font chosen, it is quite easy to mess up a chat in Converse using symbols like (at least on quite some OS and browsers):
```
yyyyyyyyyy
yyyyyyyyy
 
sdfsdfdsfsdfsdf
 
sdfsdfdsfsdfsdf
```

e.g.Android, Chrome (Samsung, latest firmware update):
![image](https://user-images.githubusercontent.com/76512/151590015-40887d0c-87af-4d9a-b3cf-6909a8da32b6.png)

**Comment by robjloranger** [comment]
I feel like this font will mess up any web based application.

Which font is this?

**Comment by yandrey** [comment]
the Converse  `font-family` is `Helvetica, Arial, sans-serif` for message content. This is the screenshot of the browser console:

![image](https://user-images.githubusercontent.com/76512/153281058-23248efc-c99a-42b0-9834-769dc138e156.png)

Here in GitHub page, the above letters looks quite OK, and the `font-family: ui-monospace,SFMono-Regular,SF Mono,Menlo,Consolas,Liberation Mono,monospace;` is used

**Comment by jcbrand** [comment]
y̰̰̰̰̰̰̰̰̰̰̰̰̰̰̰̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆y̰̰̰̰̰̰̰̰̰̰̰̰̰̰̰̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆y̰̰̰̰̰̰̰̰̰̰̰̰̰̰̰̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆y̰̰̰̰̰̰̰̰̰̰̰̰̰̰̰̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆y̰̰̰̰̰̰̰̰̰̰̰̰̰̰̰̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆y̰̰̰̰̰̰̰̰̰̰̰̰̰̰̰̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆y̰̰̰̰̰̰̰̰̰̰̰̰̰̰̰̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆y̰̰̰̰̰̰̰̰̰̰̰̰̰̰̰̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆y̰̰̰̰̰̰̰̰̰̰̰̰̰̰̰̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆y̰̰̰̰̰̰̰̰̰̰̰̰̰̰̰̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆
y̰̰̰̰̰̰̰̰̰̰̰̰̰̰̰̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆y̰̰̰̰̰̰̰̰̰̰̰̰̰̰̰̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆y̰̰̰̰̰̰̰̰̰̰̰̰̰̰̰̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆y̰̰̰̰̰̰̰̰̰̰̰̰̰̰̰̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆y̰̰̰̰̰̰̰̰̰̰̰̰̰̰̰̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆y̰̰̰̰̰̰̰̰̰̰̰̰̰̰̰̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆y̰̰̰̰̰̰̰̰̰̰̰̰̰̰̰̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆y̰̰̰̰̰̰̰̰̰̰̰̰̰̰̰̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆y̰̰̰̰̰̰̰̰̰̰̰̰̰̰̰̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆̆
 
s̷̛͕̗̙͕̎̓͑̂͗̾̾͠ḍ̸̿̍̉͌ͅf̷̨̤͇͉̥̝̭͍͓̺͕̰͉̊͐̆̆s̷͕̯̤̼̭̪͇̎̆̿̔̉͂̓͒̇͗̃̕͠͠͠ḑ̸̡̛͇̣̖̮̯͈̺̩̣͇̩̋̃͐̂̏͋́̒f̴̰̺̿͑ḏ̴̹̯͙͚͈̜̻̌̊̿̈́̽̉̽̉̈͐͐͛͑̚s̵̰̝̼̳͊̔͒͆͑̔͐͌̿͋͛̒̽̔f̴̡̪͙̦̰̰̙̹̭̗̗͑͝ś̷͓̘͇͍̄̈́̎d̶̨̢͖̩͖̯̳͉͚̗̲̘͚̒̏̅̔́̈́̈́̀͌͑̈́̿̇͝͠f̴̨̡̥̻̺̙͐͂͆͘ͅs̶͍̙̎͋́̈́̋͝d̴̨̨͓̫̼̱̪̻́f̴̨̡̛̠͇̹̼̫̻͖̞̘̖̲̻͐͊͛͌͑̃̃̇͆̉͌̕͘͜͝
 
ș̷̢̧̛̛̛̛͖̩̤̮̙̖͓͕̝̤̙̲̫͚͉̞͈̠͈̙͇͈̲͈̥͔̯̠̘̯͚͖̭̲̦̳̓́̈̓̈̍̊̆̊̅͊̔̏̆̄̈̎̓̆̈́̽͑̀̓̂̋̽̔̒̓̓̓̿͆̀̀̿͗̈́̌̉͌̒͌́͑̉͛͑̿̈̄͌̔̍̋̐͊̈̀̀͛͌͐̀͗͑̾͌̒͒͒͛́̊̋͑̈̀̆̋̂͐̀͊̽̌͑́̈́́̾̕͘͘̚̕̚̚͠͝͝͝ͅͅḑ̵̢̢̡̡̢̧̨̧̢̧̡̨̨̨̧̧̧̢̨̡̨̨̨̢̨̨̨̛̛̛̛͎̬̟̝̮̜͖̲̲͎̟̙͓̣͖͙͇̲̲͉̦̺̥̼͖͖̼̣̯̯͈̹̪͚͔̝̗̳̰̮͚͖̳̫̤̹̤̼͉̺̳̪̦͈̺̳̖̹͚̖͚̻̰̱͙̤̤̲̤̬̳̗̖͍̹͉̼̳͇͖̫͚̳̳̩̤̙̟̜̞̖̹̬̲̫̙̜͎̥̬̮͕̠͇͍̗̺̻͉̱̲͕̯̖̺͇̜̥̹̬̤̪̫̠͙͓̱͍̼͍͚͈̮̠̭̤͍̤̘̝̖̬͇̮̦̪̩̯̣̤̭̭̘̳͎͈̱̣̱̟͍͈͍̥̲̪̤̦̠̼̼͍̪͕̣̩͉͎̻͚͖͕̦̯̞͉̺̳̪̪̮̻̟͍̦͓̘̦̼̯̫͍̗̳̤͙̣͎͓͕̠̳̦̘̣͓̥̩͍̬̝͚̮͖̩̝̤͈̰̫̝͈̼͍͎̩̹͔̠̪̥͎̭̞͖̦͓͚̟͓̰̼̱͔̆̿̅̌̇̊͒͛̾̋́̐͌̽͊̄́́̑̀͐̎́̿̇͐̈́̎̅́͆̀̒́̒̍͒͗̔̆͌̊̈̌̔͐͋̓̆̋͂̾͐͆͌̊̍͂̆̿̆̏̽̇̎̐̀̀̄̾͌̽̈̎̄̎̓̀̒͗͆̋̚͘͘͜͜͝͠͝͝͝͝͝͠͝ͅͅͅͅͅͅͅf̴̨̨̛̛̭̲͔̹̞̬̮̠̺̟̤̫̜̘͎̥̹̳͉̫͒̎̊͗̈́̓̇̓̂̀̋̽̉́̾̆̎̔̇̀̈́̾͆͒̔͂̒̏̽͂̓̈̓̌́̊͌̔̈̓̕̕̚̕̚͜͝͠͝͝s̴̡̢̢̡̡̨̨̨̨̡̨̡̨̡̨̨̧̛̛̛̛̛̛̛̛̤̗̱̠̪̗̭͓̗̤̗̭̳̘̣͓̙͙̬̦̬̬̳̲͓̬͚̗̲̣͍̯̱̻͕̱̘̻̘͖̗̱̥̱̰̺͚̞͍͈̩͕̻̼̺̖̱̪͕̻̟̳̣͉̖͙͕̖̪̲̱̮̺͉̼͍̮̞̳̼̺̲̩̩̠̲̻̲̼̜̲̩̦͇͍̼̹͙̼̝͓̜̹͉͇̞̩͎̞̖̯̹̯̲̙̗̯͚̭̟͈͉̣̳̣̹̝̣̬̳̗̭̰̺̯̙̞̱̜̲̮̰̭͈̘̬̰̼̣̞͓͔̣̤̲͈̙̍̌̑͒̎̇͐̇͋̌̔͗͒̏͗̃̃̆̄̍̀̆̽̔̑́̽̌͋̃̂͗̑̅̓̈͑͛̌̋̄̽͗̅̊́̑̈́́̀̂̈́̄̋̐̊̽̽̂̌̄́̓́̐͑̄̒̾̿͂̈́́̇̐̄̊̐̉̄̃̍̿̊̉̃̈́̀̈́͑̈́̾̈̎̍̽̿̂̄͛̈́̍͋́̔͆̏̀̑̾̒̈̽̍̈͌͌̅̅͌̃͂͐̀̎̈́̇̆͗̒̉̊͂̍̀̒͌̈̈́̂̉̔̓͗̅̐͋̓̈́̇̃̍͊̽̓̅̀̑͆͛̍͑́̐̆̃̍͂͆̀̎͂͛̔́̎͑̅̑̂̈́̃͒́̚̕̕̕̚͘͘̚͘̚͘̚̚̚̕̕̚̚͜͜͜͜͜͜͝͝͠͝͝͠͝͝͠͝͝͝͝͠͝ͅͅͅd̸̨̢̨̡̢̡̢̢̡̢̧̧̢̢̨̠͙̦̖̹̗̜̟̭̫̻̮̰̟͇̞̟͇̭͈̠̖̱̗̟̦̯̯͖̼̖̦̖̯̥͖͎̫͖̩͕͈̭̥̰͚̞͎͇͇̻͕͎̼̹̥̻̫̺̱̞͖̲̤̠͈̰̼̥͍̗̲̬͍̪͈̠͔̲̫̝̫̱̭̠̥͚͓͖̖̜͓͉͇̻͎̺͖̩̺̭̺͚̫͎̲͉̫̼̹̪̜̦͓̻̥̺̳͎͇̣̦͓̘̯̳͓̞͓̹͎̦̘̻͈̭̳̻̗͚̗͉̦̻̖̳̝̥͉̹̗̹̯͈̟̫͖̊̂́̔̅̇̈́̅́͒̈́̈́̐̅̂͂͌͐̎̋͑̉͒̋̆̿̅͆̏͐̈͛̏̎̕̚͘̚͘͘͜͜͝͝ͅͅͅͅͅͅͅf̶̛̛̛̛̛̛̛̗̱̒́̈̀̄̀̇̎̈́͆͊̒̈́̽̓̊͛̌̂̈́̀̎̈́̃̑̑̔́̈́̓̄́̽̈͂̈̾̂͌͋̄̉͋͛̎͂̄͋͒̽̽̃͑̍͑͂̌̌̔͑͑̄͆̍͌̅͛͐̀̌͑̒̑̇̈́̈́́̔̾͑͂͛͐͐̓̾̊̎͌̐̿͛̓͛̾̑͗̏̐̌̏̔̓̄̀̓̍̾͆̈́̔͑͐̓̏̀̈́̄̾̒̉̉̆̈̏́̈͗̍͂̔̎̽̍͑̄͐͘̕̚̕̕̕̕͠͝͝͝͠͝͠͝͠͝d̵̡̢̧̛̛̛̩͙͙̬̰̦̦̔́̊̑́̊̆͑̋̍̅̾͂̓̃̈́̎͂͆̈́̅̅͐̾͛̉̈́̈̍̍̓̔̈́̌͌̀̐̿̍̇̈́͑̌̓̒̉̏́̏̂̓̽̾͐́͐̀́̆̿̔̑̾́̄͛̓̄͒͗̆̔̈́͌́̓͂͌̓̂͌̓̈̃̈́̂̒̂͒͑̋̂̒͂̽͆̍̉̇̿̑̒͊͊̂̇̉̉̌͊́̈́̃̋̄͗͗̄̐̌̀͗̏͌̆͊̽͐̓̔̐̔͌̏͐̈́̄̿̂͛̍̿̈́̒͂̈́̎͗̑͛̔̌͘͘͘͘̚̚̚̚̕̕̕͠͠͠͝͠͝͝͝͠͝͝͝s̴̢̢̡̨̧̨̡̢̢̢̧̢̡̛̛̛̛̛̛͚̟̰̣̪̙̪̥̹̣̯̗͚̰͚̜̲͖̞̯̖̘͉̩͖̻̤͇̟̗̞̘͓͓͇̘͇̗̻̹̰̘͙̱͓͕͕͕̹̥̟͍͚̻̜̬̟̝̲͙̦̜̮̬̞̠̦̫͚̟͕̟͓̦̟̩̳̲͚̤̗̬̯̫̣̳̯͍͙͇̗̤͖̖̦͓̹̮̥̙̭̙̭͕̳̹͙̫͉̦͖͍̺̤̱͈͍̳͇̗̈́̀̆͑̿̒̀͑̊̽͋͐̿̔̓̀̈́̃̈́͌̃͌͐͋̌̂͌͆̀̐͐͋̈̊̍̇̎̆͒̆͒͑̋̌̈́̿͂̏̊̈̾̍́̍̌̐͆͗̅͌̈́̏͆́̓̔̿̈̅̀͋̐͗̆̈́͛́̂̌͗͋͒̍̒̋͐̎̿̎͐́̑̾̒͒͌͆̾̈́́̂͋̑̋͊̆̋̈́̔̒̂͂̃̅̽͐͋̈́̒͋̉̄͋̔̃̅̿̑̓͂̽́͗̾̍͛́̅̎̇̀͌̐͋̀̾͒̑̓̅͆̅́́̃͒̽͐̔͂͊̇̍̈́̈̉̓̇̋̎͑̓͋̀͐͋̉̓̈́̎͒̀͆̀̄̿̐̔͐̊͆̿̿̉̑̂̅̀̅͌̄̿̽̋͘̚̕̚̚̚͘͘̚̕̚͜͜͜͜͠͠͠͝͠͠͝͠͝ͅͅͅf̴̡̢̧̡̡̡̡̡̡̢̨̢̧̢̧̧̨̢̢̡̢̧̧̡̡̛̮̲̹̝̳̜̜̬̪͉̩͖͎̹̰̜̣̪̻̭̼̠̖͕̗͇̲͖͇̥̻̩̮͙̗̤̮̦̪̩͓͙̹̻͖̙̥͎̖͍̤͉̘̫͚̦̜͈̞̹̹̙̟̮̰̤̜̠̫͎̮͔̳͓͖͓͈̼̥̬̻̮̟̮̦̙͚̹͉͍̻͍̼̪̯̦͇̥̥̹̹̞̗̜̦̞͓̥̝͇̠̤̰̣̩̰̫̥͍̣̻̙̜̬͔͓̟̙͚̰͓̣̪͓̘̮̠̼̞͙̞̪͖͖̳̣̯̤͍̱͇̫̺͙̭̞̝͔̙͔͕̩̖̗̟̗͈̟̳̖̱̮̭̗̦̮̰̟̤̥̙̘̓̈́́́̈́̈́͆̒͐̈̌͗̎̐̎̄̽̐̒̿͒͂͌́̂̏͐̎͗̓̆̊̑̈̉̋̇͌̎́͑͆̓̓̿̏́͌̍̇́͑̃̾̍͌͊͋̀͂̒̔̅̆̅̈̍̀͛̀͋̊̐̍̆̓̀̄́̇̇̃̏͂̈́̅͋͋̓̀̍̂͋̍̓̍̓̉͂͑̂͂̍̒̎͊͆͂̌͘̚̕̚͘̕̚͜͜͜͜͜͜͝͠͝͝͝͠͠͝͠ͅͅͅͅͅͅͅs̴̡̢̧̨̢̨̢̢̨̢̡̡̡̡̧̢̡̢̢̢̡̛̛̘̜̞͉͍̘̺͖̫̗̟͈̗̻̖̮͙̬͈͙͎̘͕͎̺̩̠̗̤̮̜̘̜̥̣̜̜͇̬͓̼͚̟̥̞͖̗̝͕̲̯̦̗̝͈̣̻͕̼͎͎̮̥̝̲̹̪̦̰͎̟͉̦͖̥͉̫̦̻̱̙̱̙̱͖̫̟̙̻̰̗̠͕̩͙͎͕̙͈̳̳̝̗̭͙̫͖̱̱̦̠̘̦͓̼̪̜̠̰͙̖̮̤̺͇̜̺̠͍͚͈̼͎̘̗̮̼͙͉̦̟͕̰̻̣̬̤͎͖̱͇͙͈̺͉͖̠̱̹̱͓̭̣̦͇̼̟̼̳̹̠̠͈̱̭̜̺̼̠͍̐͌͋̅͆̎͂̽̀̃̄̓̔͗̎̎͗͆̉͛͗̈̌̉́̐̀̂́̏̔͒́͌̂͊͂͑̋̐͊̾̏̋̍̾̽̌̅͂͌̀̌́̒͑͌̑́̍̌̓̑͆̐̇̓̿̓̔̒͊͛̃̐͐̀͋̇̒̀́̀̀́̅̈̈́̏́͛̆͐̐̇̀̊̈́̅͊́͐̇͒̃̽̚̚͘̚̕̚̕̚̕̕̕̕͘̚͝͠͠͠͝͝ͅͅͅͅͅd̶̢̢̧̧̢̡̢̨̢̨̨̢̧̧̢̛̛̛̛̛̛̛̛͈̘̼̖̜̺͇̠̱͍̠͉͇͉̲̥͍͖̼̥̗̪̪̬̺̙̘̩̙̼̞͈̱̠̘̤̱͉̠̙͔̣͓̗̣̹͙̖̙̹̺̖̭̘̝͎̲̰͇͚͓͕͔͙͕͇̳͓̳͙͓̜̭̘̠̼̟̹̬̪͓͖̲̱̼̰̭̮̳̪̹̟͕̖̻̫̙̥̻̫̜͖̼̦̩͔̮̜͙̰͔̮̹̻̞̦̞̻̳͓̳̪̩̱̦̰̘̬̩̮̗̪̪̥̭̖̺̣͉̜̮̳̜̫̦͎̝̺͚̂̌̓͛̄̌̒͑̈́͑̽̉̽͛͒͗̐͑̿́̈̎͆͌͑̑͛̀̌͊͐̐̂̉̾̑̃͒͂̿̉̋̏́̾̀̒̅́̂̇̅͌́̒͌͑͂̄̂́̓̎̿̓̿̅͌͋͗̄̉̓̈̄̌̉͌͐̅̏̎̒̔̎̓̃͆̑̈́͐̈́̏̌̒̄͊͐̓̌̿̆͆̊̽́͂͌̂͊́͆͒̾͂͑̀̏̾̂̄̓̎͋͆̓̈́̈́́̃̏̋̔̓̓͌̎̍̓͌͗̈́̓̽̍̌͂̑̐̄̌̒̈́̌͑͒̓̿̐̅́́̈̀͊̅͊̽̿̈̃̔̑̊̉̑͊͐̇̈́̉͋͊͐̇̃͂͊̔̈́̏͋̈́͆͒͒́̓̓̎͐̒̎̃̇̄͒̽̉͆̓̿̔̅͂̽̈́̽̏̓̄̃͋̆̓̈́̈́̽̾͌̀̉̂̿̏̕͘̚͘̕͘͘̕͘̚͘̚͘͘̚̕͘̚̕͘̚̚̕̕͘̚͘̕͜͜͜͜͜͝͝͝͠͠͠͝͝͠͠͠͝͝͝͝͠͝͝͠͝͝͝͝ͅḟ̷̧̨̢̨̡̢̨̧̧̨̡̧̧̢̛̛̛͖̘̟̙̯̝̻̪̲̜̳̫͉̦̖̱͈̗̥͙͚̫̱͖̣͇͎̩͕͖̤̙̖͕̟͇͖̬͔̻͎̪͔̳͈͙̠͖͉͇͍̗͉̰̯̘̹̟̟̹̝̼̞̹͉̤̟̼̟̬̩̝̱̘̟͍͇̞͉̝̠̰̟̰͙͔̑̀̋͊̈́͑͋̐͑̉̈́̓͐̉̑̆͌̋͆͐͋̅̅́̌̽̂́̀͛́̿̊̍̅̀̍͒̌͋̋̆̔͒̀̂̅̿̽̋͑͆̿̅̉̈́̈̓̓̄̃̅͗̃̊̈̈́̓̉͂̐̆̄̏̏̓̈́̽̈͗̐̒͆̂̇͛͐̽͑͂͊́̄͊̊̈̀͒̔̅̈́̿͂̌̏̒̆̀̐͛͌̊͊̈́̊̃̈́̓̋̄́̅́̀̇͌͂͆̓́̈́̽̂̈́̔̓̄̎̀̑̅̊̑̑̅̊͒̒̂̈́̂̃̈̚̕͘̚̕̕͘͘̚̕̚̚͜͜͜͠͝͝͝͝͝͝͝͝͠͝͝͝͝ͅş̴̨̢̡̡̨̡̧̡̧̡̡̧̡̢̨̢̡̧̨̧̧̛̛̛̛̛̛̛̛̛̛̛̛̲̹̱̲̣̞͖̮͖̲̪̦̖̫̻̬̫͍̹͉̯̝͉̯̼̼̯̺̭͎̲̲̹͕̠̙̩̞͎͈̮͔̦͚̩̥̗̠̱͕̮̫͉͉̳͖͎͎͉̠͈̩͍̦̤̮̯͍̞̤̻͓͎̠̠̮̣̭̬͉̺̫͍̫̫̩̫̝̞̤̝̪̖̰̺͈͈̙̲̬̮̻̹̰̮̭͉͖̪͔̻̖̳͔͙̫͙̼̱͉̤̗̝̬̳̦̪̻͈̥̞̬͉͕͖̯̥̠̹͇̺̠͉̭͇͔͖̭̟̠̻͈̺͇̻̬̦̖͍̲͙̦̝͓̦̟͍̭͍̯̼̬͇̙̞̠̘̤͓͉̝̹̻̥͈̤̥̰͎͚̝̘̳̘͈̘̜̘̫̺̰̤̰̮̦̬̻̥̱̱̦̥͔̤̪̗̭͈̰̰̙̠̼̤̣̗͖̫̳̬̩̪̝̻̱̳̤͎͕̩̲̲̭̟͖̰̳̄͂͐̎̈́̉͌̀̋̏̀̃̔͌̈́̽̃͆̃̋̍́͂̋͌̒͛̇̎̽̍̂̏͛̓͒̿̈̃̍̊̿͑̋̄͂͂̆͋̇͒͋́͛̾͛̒͂̈͌̀͒̇̆͋̍͒̿͂͒͆̈̄́̉́̐̈͂͐̅̍͗̐̃̔́̊̾̉͒̌̓̈́͑̋̎́̀̊͒͒̀̍̃̾̂͆̔͊͗͂̔̽͗̀͋̍̀̑͊̀̀̈́̔̊̊̅̈́̀̒̄̓̅͂̇̎̌̇̈́̍̋̒͆͌̊́̉̂̃̉͆̐̃̀̂̔̏̆̓́̂̑͑̾͊͒͑̀̀̐̐̀͑̐͊̏̅̋̇̄̌̓̒͛́̽̔́͋̈́̈́̕͘̕̚͘̕̚̕͘̕̚̚͘͜͜͜͜͜͝͠͝͝͝͝͠͝͠͝͝͠͝͝͝͠͝͝͠͝͝ͅͅͅͅͅͅͅͅd̸̨̧̢̢̨̡̡̡̢̡̲̳̞̼̮͙̙̼̟͚̜̗͎̘͙̟̱̘̲̖͖̻͕̻̯̬̗̘̪͉̘̫͉̠̗̘̙̗̭̣͔̞̹̤̠̞̥̳̘͉̰̦͇̪͙̗͓̲̫̮͙̬͓͓͇̱̟̝̯̳̩̟͔̩͙̖͍͗̉́̏̑̆͜͜͝ͅf̷̧̡̢̡̨̨̧̛̛̛̛̪̘̲̥̲̪̬͖̲̟̼͖͕͎̺̣̞̣̲͍͇̦̗̣̮͍̮̻̗̻̟̹̮̞̞̟̺̝͉̣̞̬̜͍̭͖̮̤̟͑͌͂̇̔̋́͊̊̊̊̂̈́̓̓̐̽͑̋̌͐̈́̅̌̽͆͐̊́́͒̀̾͐̋͐́̃̍͒͐̀́͐̇̍̀̈́̆̌̽̈́͂́͊͋̀̔͗̏̇̈́̑̀̾̉̌̎̂͆͊́̑̐̄͌̾̌̾̀̽̒̅̌͒́͗̍̑̋̍̅͛̋̅̊̀̚͘̚͘͜͜͝͝͠͠

**Comment by jcbrand** [comment]
I don't think this is a font issue. Someone pasted weird Unicode chars in the chat which they know often don't render properly.

Look above, they don't even render properly in Github (they go over the bounds of the issue comment).

**Comment by jcbrand** [comment]
I'm not saying there isn't a solution for this (although I don't know what that might be), but I don't think changing the font is the solution.

**Comment by jcbrand** [comment]
<img width="990" alt="Screenshot 2022-02-10 at 10 02 19" src="https://user-images.githubusercontent.com/683911/153373339-800fb3d2-800d-4534-a2d4-139cf2086c63.png">

**Comment by yandrey** [comment]
Helvetica - again :slightly_smiling_face:

**Comment by yandrey** [comment]
see the difference for your insert here:
![image](https://user-images.githubusercontent.com/76512/153377554-b37d8401-6630-432c-95df-4cdaacc0d339.png)

**Comment by jcbrand** [comment]
If using monospace font is the solution, then why doesn't the entire web use monospace?

**Comment by yandrey** [comment]
i guess when developers/authors write themselves its ok, but in multiuser-chats with vandals :face_with_spiral_eyes:

**Comment by yandrey** [comment]
seems not all monospace work. the same mess for several i tried from here https://www.w3.org/Style/Examples/007/fonts.en.html

**Comment by jcbrand** [comment]
Those characters don't serve any real purpose in any case except to cause grief, so one solution here is to just ban/kick the person from the chat and to delete the message.

**Comment by yandrey** [comment]
in most xmpp servers without DIY modules, moderators can't delete garbage messages.

**Comment by yandrey** [comment]
conversejs in particular is not telegram, moderation is a real pain

**Comment by yandrey** [comment]
in principle can be solved using custom css theme. anyway, no dark theme

**Comment by jcbrand** [comment]
Kicking/banning users from chats is part of XEP-0045 and all servers support that. What's not supported by all is deletion of messages by moderators. Seems like a reason to choose a server that does support it.

**Comment by yandrey** [comment]
kicking does nothing (just to re-enter), only ban. there is no possibility to remove other guy message in Converse even if server support this. only possible to retract own message. retract must be shown for moderators on every message

**Comment by jcbrand** [comment]
> there is no possibility to remove other guy's message in Converse

This is not true, Converse supports XEP-0425 which lets MUC moderators remove messages.

**Comment by yandrey** [comment]
ahh, indeed.

**Comment by kicken** [comment]
As seen in the original comment code block, Github prevents the the text from making too much of a mess via the overflow css property.  That could be a possible solution to prevent such a message from messing up the chat too much.

**Comment by yandrey** [comment]
not sure if i put in proper location :slightly_smiling_face: , but looks good:
![image](https://user-images.githubusercontent.com/76512/153450736-6467145e-dea1-4305-9edb-458e702f2de3.png)
