### ISSUE TITLE
Links are mangled on open/copy

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/converse.js#2814]
HEAD (0fb4dcac9693f6ce883daef8bfca23db94aba173) self build, Firefox Stable, Vivaldi Snapshot

**To Reproduce**
Share to a Converse user a link: `https://mov.im/?node/pubsub.movim.eu/Dino/urn-uuid-979bd24f-0bf3-5099-9fa7-510b9ce9a884`

**Expected behavior**
Opening/Copying the link works fine

**Actual result**
Link is mangled to: `https://mov.im/?node%2Fpubsub.movim.eu%2FDino%2Furn-uuid-979bd24f-0bf3-5099-9fa7-510b9ce9a884` by replacing some `/` with `%2F`

**Comment by robjloranger** [comment]
Might be related to #2765

**Comment by jcbrand** [comment]
Why is there a `?` before `node`? That seems to be causing the issue.

Converse uses URI.js to normalized URLs and because there is a `?` before `node`, it interprets the part after the `?` as the query string of the URL and therefore escapes the forward slashes since they're reserved and not allowed in a query string.

CC @edhelas

**Comment by jcbrand** [comment]
Ok, but then it needs to be escaped by the time it's arrives in Converse, it's not up to Converse to escape it since a `?` has a special meaning in a URL.

**Comment by licaon-kter** [comment]
I just pasted a link In Conversations chatting to the Converse user. Hope it's not expected that I escape it by hand :)

**Comment by jcbrand** [comment]
I'm not sure where the issue is, but it might be that Movim is not properly escaping that character. I don't see anything for Converse to do here.

**Comment by jcbrand** [comment]
I've removed the normalization on Converse's side. Looks like it's not strictly necessary.

**Comment by licaon-kter** [comment]
Thanks
