### ISSUE TITLE
Singleton doesn't work in overlayed view_mode

### ISSUE THREAD

**Issue by karolyi** [conversejs/converse.js#2822]
**Describe the bug**
Hey, I'm trying to embed this chat into my website with overlayed mode and singleton: true. It seems that two setting doesn't like each other and I get a Javascript error: `Uncaught (in promise) TypeError: wa.ControlBoxView is undefined`

**To Reproduce**
```html
<script type="text/javascript">
const isChatInitialized = true;
converse.initialize({
    "assets_path": "https://xmpp.example.com/conversejs/dist/",
    "bosh_service_url": "https://xmpp.example.com/http-bind",
    "jid": "xmpp-anon.example.com",
    "muc_domain": "xmpp-anon.example.com",
    "singleton": true,
    "view_mode": "overlayed",
    "websocket_url": "wss://xmpp.example.com/xmpp-websocket",
});
</script>
```

**Expected behavior**
I shouldn't get that JS error.

**Screenshots**
![image](https://user-images.githubusercontent.com/987055/154848180-c3a3a7f8-20d4-42d7-8faa-5d40e6f7fb87.png)

**Environment (please complete the following information):**
 - Desktop
 - LibreWolf (Firefox 97.0), but it seems to be broken on Chrome too.
 - Converse.js version 9.0 (downloaded from github release)

**Comment by jcbrand** [comment]
Looks like the bug is in the `dragresize` plugin. As a workaround for now, you can disable that plugin (but you then won't be able to resize chats with the mouse).

When calling `converse.initialize`, add `'converse-dragresize'` to the `blacklisted_plugins` array.

**Comment by karolyi** [comment]
thanks!
