### ISSUE TITLE
the room is locked issue in MUC 

### ISSUE THREAD

**Issue by Banu1412** [conversejs/converse.js#2856]
**Describe the bug**
chatroom is created using this  
```
_converse.api.rooms.create('room@conference.example.org',{'nick':'hello group'});
```
The room is created. but cant able send message or do anything.
it throws the error that  the room is locked.

**To Reproduce**
can you tell me how to solve this issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/100141120/158985000-b595eb77-327c-4ebe-8492-77535df730c3.png)

**Comment by jcbrand** [comment]
Newly created rooms are locked until they have been configured.
https://xmpp.org/extensions/xep-0045.html#enter-locked

To create an automatically configured room, which is not locked, you can pass `'auto_configure': true` when you call `api.rooms.create`.

```
api.rooms.create('room@conference.example.org', {'nick': 'nicky', 'auto_configure': true});
```
