### ISSUE TITLE
Quotes, only the first line URL is linkified

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/converse.js#2870]
4d4e0ffc8d5e7de299c490cec77b503467dd5e32, Firefox Stable
![quotedlinks](https://user-images.githubusercontent.com/2282799/162137738-13beb4a7-b703-4d9e-9894-7b5a7475870e.jpg)

**Comment by debanjana-a11y** [comment]
Hello, I was trying to reproduce this issue in Firefox with a development setup but I cant find "Quote line" feature, can you guide me how to quote lines to reproduce it ?

**Comment by licaon-kter** [comment]
Paste this:
```
> https://nohello.net
> https://xmpp.work
```

**Comment by debanjana-a11y** [comment]
Thanks for the reply.
I tried and links are working alright at my end. Sharing screenshot here, am I using same version of Firefox as yours ?
![post](https://user-images.githubusercontent.com/89571066/177362393-72e37b17-d73e-4b3b-bbf7-5f2bd2a017dd.png)

**Comment by debanjana-a11y** [comment]
Found it on both Firefox and Google Chrome. Can anyone assign it to me, I might try to fix this.

![post](https://user-images.githubusercontent.com/89571066/177363113-d476da0e-2689-404b-a0a3-2d831300d343.png)

**Comment by debanjana-a11y** [comment]
Any suggestion on how to start adding test case for this ? I could test the fix only from browser.

**Comment by jcbrand** [comment]
Hi @debanjana-a11y, is your work in a branch somewhere where I can take a look?

The styling tests are here: https://github.com/conversejs/converse.js/blob/3ca478da32941af534207230e36df3bda01cbea3/src/plugins/chatview/tests/styling.js#L235

**Comment by debanjana-a11y** [comment]
```Hi @debanjana-a11y, is your work in a branch somewhere where I can take a look?```
Hi, It is here
https://github.com/conversejs/converse.js/commit/be6bef85d5d2d0d84be1223ca1f5a3fc62c130c4

**Comment by debanjana-a11y** [comment]
> 
@jcbrand how to test this individual test cases ? If I write a test case how I'm going to test it ? Like I said above `make check` causes many test failure in my setup (screenshot above)
 
Thanks in advance

**Comment by debanjana-a11y** [comment]
I have checked with my testcase only with other tests commented and it is working 
![post](https://user-images.githubusercontent.com/89571066/182038199-226a6067-9b8b-49b2-b7fb-f381f8c507da.png)

**Comment by jcbrand** [comment]
I've merged @debanjana-a11y's fix. Thanks!
