### ISSUE TITLE
In bosh mode, after the connection is abnormal, the loop is reconnected

### ISSUE THREAD

**Issue by shijiumei** [conversejs/converse.js#2911]
**Describe the bug**
`<body xmlns='http://jabber.org/protocol/httpbind' type='terminate' condition='item-not-found'/>`

2022-05-09T05:28:25.114Z WARNING: Could not restore session for jid: test@xxx/conversejs_20220509045247_8534 Error message: _restore: no restoreable session.

**Environment (please complete the following information):**
 - Desktop 
 - Browser : Chrome
 - Converse.js version : 9.1.1

**Additional context**
server ejabbered

**Comment by shijiumei** [comment]
![image](https://user-images.githubusercontent.com/99791885/167347034-e1eb539f-e890-465a-8144-e8ddc87ce07c.png)

**Comment by shijiumei** [comment]
{
    "bosh_service_url": "https://xxx/bosh",
    "authentication": "prebind",
    "prebind_url": "/wp-json/conversejs/v1/prebind?client=conversejs_20220509052736_5075",
    "prebind": true,
    "auto_login": true,
    "auto_reconnect": true,
    "show_controlbox_by_default": true,
    "auto_subscribe": false,
    "i18n": "zh",
    "locales_url": "https://xxx/wp-content/plugins/conversejs/core/locale/{{{locale}}}/LC_MESSAGES/converse.json",
    "allow_logout": false,
    "xhr_user_search": false,
    "message_carbons": true,
    "play_sounds": false,
    "sounds_path": "./sounds/",
    "roster_groups": false,
    "keepalive": true,
    "auto_away": 0,
    "auto_xa": 0,
    "default_domain": "xxxx",
    "message_archiving": "always",
    "csi_waiting_time": 5,
    "hide_offline_users": false,
    "whitelisted_plugins": [
        "chatme-logout",
        "converse-bookmark-views",
        "converse-chatboxviews",
        "converse-chatview",
        "converse-controlbox",
        "converse-dragresize",
        "converse-fullscreen",
        "converse-headlines-view",
        "converse-mam-views",
        "converse-minimize",
        "converse-modal",
        "converse-muc-views",
        "converse-notification",
        "converse-omemo",
        "converse-profile",
        "converse-push",
        "converse-register",
        "converse-roomslist",
        "converse-rootview",
        "converse-rosterview",
        "converse-singleton"
    ],
    "priority": 10,
    "show_send_button": true,
    "registration_domain": "xxx",
    "allow_registration": false,
    "theme": "default",
    "visible_toolbar_buttons": {
        "call": false,
        "spoiler": false,
        "emoji": true,
        "toggle_occupants": true
    },
    "allow_chat_pending_contacts": true,
    "allow_non_roster_messaging": true,
    "allow_message_corrections": "last",
    "clear_cache_on_logout": true,
    "allow_muc": false,
    "allow_muc_invitations": false,
    "auto_register_muc_nickname": false,
    "blacklisted_plugins": [
        "converse-profile",
        "converse-register",
        "converse-spoilers"
    ],
    "jid": "test@xxx/conversejs_20220509052736_5075"
}

**Comment by shijiumei** [comment]
Configuration.jid only supports barejid

**Comment by shijiumei** [comment]
function saveJIDtoSession (_converse, jid) {
    console.log('zzh [jid] saveJIDtoSession jid:' + jid);
    jid = _converse.session.get('jid') || jid;
    console.log('zzh [jid] saveJIDtoSession jid2:' + jid);
    if (_converse.api.settings.get("authentication") !== _converse.ANONYMOUS && !Strophe.getResourceFromJid(jid)) {
        jid = jid.toLowerCase() + Connection.generateResource();
    }
    console.log('zzh [jid] ### _converse.jid = ' + jid);
    _converse.jid = jid;

**Comment by shijiumei** [comment]
Hope to support fulljid

**Comment by udanieli** [comment]
I don't know if I have the same issue but I get the same error and an infinite loop of reconnection at very high speed (4-5 requests/second)

```
log.js:66  2022-06-06T06:19:10.344Z WARNING: Could not restore session for jid: xxxx@rxxxxx.it/972655467562938831120226 Error message: _restore: no restoreable session. 
log @ converse.min.js:2
warn @ converse.min.js:2
ul.restoreBOSHSession @ converse.min.js:2
await in ul.restoreBOSHSession (async)
login @ converse.min.js:2
reconnect @ converse.min.js:2
await in reconnect (async)
reconnect @ converse.min.js:2
onDisconnected @ converse.min.js:2
onConnectStatusChanged @ converse.min.js:2
_changeConnectStatus @ converse.min.js:2
_doDisconnect @ converse.min.js:2
_dataRecv @ converse.min.js:2
_onRequestStateChange @ converse.min.js:2
XMLHttpRequest.send (async)
e @ converse.min.js:2
(anonymous) @ converse.min.js:2
setTimeout (async)
_processRequest @ converse.min.js:2
_throttledRequestHandler @ converse.min.js:2
_onRequestStateChange @ converse.min.js:2
XMLHttpRequest.send (async)
e @ converse.min.js:2
_processRequest @ converse.min.js:2
_throttledRequestHandler @ converse.min.js:2
_onRequestStateChange @ converse.min.js:2
XMLHttpRequest.send (async)
e @ converse.min.js:2
_processRequest @ converse.min.js:2
_throttledRequestHandler @ converse.min.js:2
_onIdle @ converse.min.js:2
_onIdle @ converse.min.js:2
(anonymous) @ converse.min.js:2
setTimeout (async)
_send @ converse.min.js:2
send @ converse.min.js:2
sendIQ @ converse.min.js:2
(anonymous) @ converse.min.js:2
sendIQ @ converse.min.js:2
ping @ converse.min.js:2
wg @ converse.min.js:2
setInterval (async)
initialize @ converse.min.js:2
initializePlugin @ converse.min.js:2
(anonymous) @ converse.min.js:2
initializePlugins @ converse.min.js:2
(anonymous) @ converse.min.js:2
initialize @ converse.min.js:2
await in initialize (async)
Su.initialize @ converse.min.js:2336
initialize @ converse.min.js:2336
(anonymous) @ (index):512
load (async)
(anonymous) @ (index):492
controlbox.js:10 connection_status
controlbox.js:11 13
controlbox.js:10 connection_status
controlbox.js:11 8
controlbox.js:10 connection_status
controlbox.js:11 13
```

This is my configuration:

```
converse.initialize({
     "bosh_service_url":"https://chat.mydomain.it:5443/bosh",
     "authentication":"prebind",
     "auto_login": true,
     "auto_reconnect": true,
     "prebind_url": "/chat/prebind",
     "discover_connection_methods":false,
     "default_domain":"chat.mydomain.it",
     "domain_placeholder":"chat.mydomain.it",
     "registration_domain":"chat.mydomain.it",
     "assets_path":"/static/conversejs/",
     "allow_non_roster_messaging": true,
     "i18n":"en",
     "allow_registration": false,
     "persistent_store": "localStorage",
   });

```

In ejabberd logs I see the same error:

`2022-06-06 06:44:08.771326+00:00 [info] <0.9308.2>@ejabberd_c2s:process_terminated/2:291 (http_bind|<0.9307.2>) Closing c2s session for xxxx@xxxxx.it/1485710009400655089523650: Stream closed by local host: Improper 'from' attribute (invalid-from)
`

How did you resolve this issue?

**Comment by jcbrand** [comment]
> Stream closed by local host: Improper 'from' attribute (invalid-from)

This seems to imply that the JID that you're using to connect is not valid.

**Comment by shijiumei** [comment]
![image](https://user-images.githubusercontent.com/99791885/173521208-cd0d1f45-6b99-42d6-a19b-c792923caf07.png)

maybe

**Comment by shijiumei** [comment]
> I don't know if I have the same issue but I get the same error and an infinite loop of reconnection at very high speed (4-5 requests/second)
> 
> ```
> log.js:66  2022-06-06T06:19:10.344Z WARNING: Could not restore session for jid: xxxx@rxxxxx.it/972655467562938831120226 Error message: _restore: no restoreable session. 
> log @ converse.min.js:2
> warn @ converse.min.js:2
> ul.restoreBOSHSession @ converse.min.js:2
> await in ul.restoreBOSHSession (async)
> login @ converse.min.js:2
> reconnect @ converse.min.js:2
> await in reconnect (async)
> reconnect @ converse.min.js:2
> onDisconnected @ converse.min.js:2
> onConnectStatusChanged @ converse.min.js:2
> _changeConnectStatus @ converse.min.js:2
> _doDisconnect @ converse.min.js:2
> _dataRecv @ converse.min.js:2
> _onRequestStateChange @ converse.min.js:2
> XMLHttpRequest.send (async)
> e @ converse.min.js:2
> (anonymous) @ converse.min.js:2
> setTimeout (async)
> _processRequest @ converse.min.js:2
> _throttledRequestHandler @ converse.min.js:2
> _onRequestStateChange @ converse.min.js:2
> XMLHttpRequest.send (async)
> e @ converse.min.js:2
> _processRequest @ converse.min.js:2
> _throttledRequestHandler @ converse.min.js:2
> _onRequestStateChange @ converse.min.js:2
> XMLHttpRequest.send (async)
> e @ converse.min.js:2
> _processRequest @ converse.min.js:2
> _throttledRequestHandler @ converse.min.js:2
> _onIdle @ converse.min.js:2
> _onIdle @ converse.min.js:2
> (anonymous) @ converse.min.js:2
> setTimeout (async)
> _send @ converse.min.js:2
> send @ converse.min.js:2
> sendIQ @ converse.min.js:2
> (anonymous) @ converse.min.js:2
> sendIQ @ converse.min.js:2
> ping @ converse.min.js:2
> wg @ converse.min.js:2
> setInterval (async)
> initialize @ converse.min.js:2
> initializePlugin @ converse.min.js:2
> (anonymous) @ converse.min.js:2
> initializePlugins @ converse.min.js:2
> (anonymous) @ converse.min.js:2
> initialize @ converse.min.js:2
> await in initialize (async)
> Su.initialize @ converse.min.js:2336
> initialize @ converse.min.js:2336
> (anonymous) @ (index):512
> load (async)
> (anonymous) @ (index):492
> controlbox.js:10 connection_status
> controlbox.js:11 13
> controlbox.js:10 connection_status
> controlbox.js:11 8
> controlbox.js:10 connection_status
> controlbox.js:11 13
> ```
> 
> This is my configuration:
> 
> ```
> converse.initialize({
>      "bosh_service_url":"https://chat.mydomain.it:5443/bosh",
>      "authentication":"prebind",
>      "auto_login": true,
>      "auto_reconnect": true,
>      "prebind_url": "/chat/prebind",
>      "discover_connection_methods":false,
>      "default_domain":"chat.mydomain.it",
>      "domain_placeholder":"chat.mydomain.it",
>      "registration_domain":"chat.mydomain.it",
>      "assets_path":"/static/conversejs/",
>      "allow_non_roster_messaging": true,
>      "i18n":"en",
>      "allow_registration": false,
>      "persistent_store": "localStorage",
>    });
> ```
> 
> In ejabberd logs I see the same error:
> 
> `2022-06-06 06:44:08.771326+00:00 [info] <0.9308.2>@ejabberd_c2s:process_terminated/2:291 (http_bind|<0.9307.2>) Closing c2s session for xxxx@xxxxx.it/1485710009400655089523650: Stream closed by local host: Improper 'from' attribute (invalid-from) `
> 
> How did you resolve this issue?

**Comment by shijiumei** [comment]
@udanieli
