### ISSUE TITLE
Multiplexed web socket integration

### ISSUE THREAD

**Issue by PhotonicDev** [conversejs/converse.js#2950]
**Is your feature request related to a problem? Please describe.**
Current converse.js as I understand requires a web socket URL to be provided to be able to connect, in my project I have a multiplexed web socket and therefore would like a hook or some method to relay communications to converse.js client from xmpp server which is behind behind our main server. We don't want to have a direct connection to the xmpp server since we use multiplex web socket and due to security reasons less entry points is better. And we also want to authenticate on the server, meaning the server already knows everything it needs to know regarding the authorization.

**Describe the solution you'd like**
A method or a hook for a plugin that we can relay the the bidirectional messages over web socket without providing web socket URL

**Describe alternatives you've considered**
There's not really much in alternatives, either I could build plugin for this to overwrite the way messages are being patched

**Additional context**
Any resources or anything I've missed on the docs looking to integrate this is greatly appreciated

**Comment by licaon-kter** [comment]
How do you multiplex? Eg. SSLH and nginx are used around the XMPP ecosystem. Say for a domain (ALPN/SNI) or port or etc.

**Comment by PhotonicDev** [comment]
We're using the ALPN since we already had a problem with the web socket limit before

**Comment by jcbrand** [comment]
@PhotonicDev: If I understand you correctly, you already have a websocket connection that you want to re-use, and you therefore just want to provide that connection to Converse, instead of giving it a websocket URL with which it creates its own connection. Is that correct?

**Comment by PhotonicDev** [comment]
@jcbrand kind of yeah, we already have the web socket connection that can send all the messages and ideally we should be able to just plug the messages into the library via listeners and methods. We don't really want to authenticate as well since both client and server already knows the user that is connected via web socket and can do the xmpp authentication. Is that possible in some way or do we have to have a connection for Converse? 
I mean if the web socket connection would be exposed I could also just do a some sort of a fake web socket that just relays the data from our multiplexed one.

**Comment by deleolajide** [comment]
You could use the connection_options

```
connection_options: { 'worker': getSetting("useWebworker", false) ? "./pade-connection-worker.js" : undefined },
```

And write your connection worker to integrate into your web socket multiplexor like this

https://github.com/igniterealtime/pade/blob/4d58b9e3974a4285c072458a97b6899247fe9f40/docs/pade-connection-worker.js#L26

Mine is not doing much at the moment, but the plan is to make jitsi-meet and converse share the same xmpp connection.

**Comment by PhotonicDev** [comment]
@deleolajide this actually looks like it could work, awesome idea! Any other suggestions are greatly welcome and I will close the issue in a couple of days if nothing else comes up!

**Comment by deleolajide** [comment]
The other approach as you have already suggested is to use an alternative WebSocket class  like this

https://github.com/conversejs/community-plugins/blob/master/packages/galene/galene-socket.js

I used this in the galene plugin for converse to multiplex galene json and converse xmpp on same websocket connection.

**Comment by PhotonicDev** [comment]
@deleolajide That does look like the ideal solution! Thank you for your help!
