### ISSUE TITLE
How to install a plugin

### ISSUE THREAD

**Issue by rheman** [conversejs/converse.js#2964]
Hi everyone,

May be the answer of my question is simple. But do no know how to install a new plugin.

I used to compile the convers.js (make dist) form source code. So How can I add some community-plugins in the source before compilation. I such a way that after compile (make dist) I will be able to whitelist of blacklist extra plugins based on my needs.

Regards,

**Comment by jcbrand** [comment]
You can include them in your DOM via the `script` tag or bundle them together with something like Rollup or Webpack.
