### ISSUE TITLE
Add an event for nickname changes (in a MUC chatroom)

### ISSUE THREAD

**Issue by joudinet** [conversejs/converse.js#2970]
**Is your feature request related to a problem? Please describe.**
To follow the ePrivacy Directive, I have to ask user consent before saving information such as a nickname in a browser storage. I do that in a form before starting converse but if the user consents to save its nickname in a cookie, I like to save it whenever it changes. So, I'd like to detect nickname changes in converse.

**Describe the solution you'd like**
```
api.listen.on('setNickname', function(nickname) {
  // Do whatever you want with the new nickname.
});
```
**Describe alternatives you've considered**
I intercept the `enteredNewRoom` event and get the nickname from `model.attributes.nick`. It works until the user changes its nickname after having entered a room. I see no event to detect such changes.

**Comment by jcbrand** [comment]
You can try something like this:

```

**Comment by joudinet** [comment]
Thanks @jcbrand 
Your solution works.
