### ISSUE TITLE
Add options to the settings menu to allow user to customize certain options

### ISSUE THREAD

**Issue by luigi311** [conversejs/converse.js#2977]
**Is your feature request related to a problem? Please describe.**
In the settings window can we add an options tab to allow the user to customize certain options such as inline media for those that are on a metered connection

**Describe the solution you'd like**
Options tab in the settings window

**Describe alternatives you've considered**

**Additional context**

**Comment by jcbrand** [comment]
I think this is a duplicate of #1981

**Comment by luigi311** [comment]
You are correct looks like that is the same thing marking this as closed
