### ISSUE TITLE
MUC Icon support

### ISSUE THREAD

**Issue by bqv** [conversejs/converse.js#2980]
**Is your feature request related to a problem? Please describe.**
As discussed on xmpp, the ability to show and set MUC icons would be desired

**Describe the solution you'd like**
The ability as described above - functionality to set icons when >admin privileges present, and displaying MUC icons when available

**Describe alternatives you've considered**
N/a

**Additional context**
N/a

**Comment by based-a-tron** [comment]
The MUC icons actually display for me in firefox, but not in brave. Not sure what's going on there and I haven't spent enough time on it to debug it.
