### ISSUE TITLE
Fullscreen and embedded lack encryption button.

### ISSUE THREAD

**Issue by onefang** [conversejs/converse.js#2987]
**Describe the bug**
The fullscreen and embedded views don't have the encryption button in the IM tab.

I keep stumbling across little differences between the various views that probably shouldn't be different.  I know they where originally different code bases, are they not yet fully merged?

**Environment (please complete the following information):**
 - Desktop browser Firefox-ESR
 - Converse.js version v9.1.1

**Comment by jcbrand** [comment]
The fullscreen version does have a button to encrypt, I use it every day.

If you don't have it, you likely don't have libsignal loaded.
https://github.com/conversejs/converse.js/blob/master/docs/source/dependencies.rst#libsignal
