### ISSUE TITLE
Can't send offlines when encryption is turned on.

### ISSUE THREAD

**Issue by onefang** [conversejs/converse.js#2988]
**Describe the bug**
One of my users was complaining that offline messages are not working.  After lots of testing I figured out that the overlay view defaults to encrypted, and can't send offlines unless you turn off encryption.

Though maybe they just need to have exchanged keys already, but it should at least tell you why it couldn't send the message.

**Environment (please complete the following information):**
 - Desktop browser Firefox-ESR
 - Converse.js version v9.1.1

**Comment by jcbrand** [comment]
>  the overlay view defaults to encrypted
This is not true, unless you configured it as such.

> can't send offlines unless you turn off encryption
What is an "offline"? You mean you can't send an encrypted message to someone who's offline?
