### ISSUE TITLE
User Registration Problems

### ISSUE THREAD

**Issue by benni1516** [conversejs/converse.js#2990]
Hello, I'm having problems with user registration.

When I'm trying to register duplicate users, I don't get the User already exists mesage.
I do get it in the answer for this post request:
`<body rid="294745395" sid="92bdad75b57e4da8961fa46321bcf597eeeaca38" xmlns="http://jabber.org/protocol/httpbind"><iq id="9398e362-89f5-4b8a-9a73-e46afa9c955e" type="set" xmlns="jabber:client"><query xmlns="jabber:iq:register"><username>testuser</username><password>thisisnotmypassword</password></query></iq></body>`

I get this back:
`<body xmlns='http://jabber.org/protocol/httpbind'><iq xml:lang='en' from='ejabberd.teamserver.at' type='error' id='9398e362-89f5-4b8a-9a73-e46afa9c955e' xmlns='jabber:client'><query xmlns='jabber:iq:register'><username>testuser</username><password>thisisnotmypassword</password></query><error code='409'><resource-constraint xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/><text xml:lang='en' xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>User already exists</text></error></iq></body>`

But the Error message doesn't appear because right after that there are other requests:

`<body content="text/xml; charset=utf-8" hold="1" rid="196239515" to="ejabberd.teamserver.at" ver="1.6" wait="59" xml:lang="en" xmlns="http://jabber.org/protocol/httpbind" xmlns:xmpp="urn:xmpp:xbosh" xmpp:version="1.0"/>`

With this answer:

`<body xmpp:version='1.0' authid='9601417560245952892' xmlns='http://jabber.org/protocol/httpbind' sid='62795c6a8992cd049354d5b8059d1ecdfa5da451' wait='59' ver='1.11' polling='2' inactivity='30' hold='1' xmpp:restartlogic='true' requests='2' secure='true' maxpause='120' xmlns:xmpp='urn:xmpp:xbosh' xmlns:stream='http://etherx.jabber.org/streams' from='ejabberd.teamserver.at'><stream:features><mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'><mechanism>PLAIN</mechanism><mechanism>SCRAM-SHA-1</mechanism></mechanisms><register xmlns='http://jabber.org/features/iq-register'/></stream:features></body>`

Then this:

`<body rid="196239516" sid="62795c6a8992cd049354d5b8059d1ecdfa5da451" xmlns="http://jabber.org/protocol/httpbind"><iq id="9f7d5555-a92d-4a8a-8cca-1b8d89392357:sendIQ" type="get" xmlns="jabber:client"><query xmlns="jabber:iq:register"/></iq></body>`

With this answer:

`<body xmlns='http://jabber.org/protocol/httpbind'><iq xml:lang='en' from='ejabberd.teamserver.at' type='result' id='9f7d5555-a92d-4a8a-8cca-1b8d89392357:sendIQ' xmlns='jabber:client'><query xmlns='jabber:iq:register'><username/><password/><instructions>Choose a username and password to register with this server</instructions></query></iq></body>`

Now I am back to the normal register page.

When I try to do that again then a massive loop with thousands of requests to the server occurs.
Also When I register a valid user, then a massive loop with thousands of request to the server accours and the UI is glitched.

Now:
Why does this happen?
Why is http://jabber.org in the request when I am on https://ejabberd.teamserver.at
What should I do?

Your help would be much appreciated. Thanks to anyone who tries to help.

Benni :)

**Comment by jcbrand** [comment]
I don't have time to look into this, but looks like it might be related to this:

https://github.com/conversejs/converse.js/issues/1490

**Comment by benni1516** [comment]
thank you, i deleted the line registration_domain now it works,
now when i try to register a user that already exists it says "user already exists"
if i then try to register an available username it doesn't change the status it will again say "user already exists" after reloading i can register normally again

**Comment by jcbrand** [comment]
Closing as a duplicate.
