### ISSUE TITLE
messages containing "message replies" XEP-0461 do not show up in converse.js

### ISSUE THREAD

**Issue by code17568** [conversejs/converse.js#3005]
**Describe the bug**
When a reply message is sent that is supposed to conform to XEP-0461 "Message Replies", in this case produced by Movim, this message does not show up in converse.js. The message is silently ignored.

**To Reproduce**
1. from the movim client, join a chat
2. join the same chat with converse.js
3. in movim, click the reply button on any message from another user
4. type message and hit enter to post
5. notice that the posted reply message does not show up in the converse.js client

**Expected behavior**
In clients that do not support XEP-0461, they should display the fallback text if it is provided by the sending client, which is optional to send. Movim sends fallback text, so it is expected that converse.js would show this. 

**Additional context**
https://xmpp.org/extensions/xep-0461.html

**Comment by jcbrand** [comment]
Closed via #3004
