### ISSUE TITLE
Links in message lose their properties on message edits

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/converse.js#3007]
97be0bd8acee5bcdba32cbea08d74698a915f3de Firefox Stable

Repro:
* write a message
![step1](https://user-images.githubusercontent.com/2282799/185110792-a4be9a61-a570-493b-9870-b5553d54e72e.jpg)
 * edit it
![step2](https://user-images.githubusercontent.com/2282799/185110845-1bfc66d7-7456-4d09-9b6c-4c21e98e6cc8.jpg)
 * edit it again
![step3](https://user-images.githubusercontent.com/2282799/185110874-a7747862-fa27-4338-af67-fe038dd59d0e.jpg)

**Comment by jcbrand** [comment]
I just tried to reproduce and couldn't... can you post the exact text of each message please?

**Comment by licaon-kter** [comment]
The text is in the pictures, yes outgoing :)
