### ISSUE TITLE
how can i add reply message in conversejs

### ISSUE THREAD

**Issue by buithevuong** [conversejs/converse.js#3024]
According to @vahid 's instructions how to do this step , i can't find where to add : "first in convers.js/src/plugins/chatview/view.js add this before onMessageEditButtonClicked". Looking forward to your help, I'm using version 9.1.1
https://stackoverflow.com/questions/65956139/how-can-i-add-reply-message-in-conversejs

**Comment by jcbrand** [comment]
This issue tracker is for reporting bugs and feature requests. You're question is too vague and requires too much work from me. Sorry.
