### ISSUE TITLE
 From a custom plugin with headless (without ui) the new messages appear as readed when entering

### ISSUE THREAD

**Issue by SMG-elgonzalez** [conversejs/converse.js#3025]
**Describe the bug**
From a custom plugin with headless (without ui) new messages appear as read when entering. Also if converse-headless is already initialized, new messages remain as if they had been readed.

**To Reproduce**
1. I generate a new build from headless with the following code:
import converse from '@converse/headless';

```
converse.plugins.add('myplugin', {

    initialize: function () {
        const _converse = this._converse;
        window._converse = _converse;
        _converse.api.rooms.get(
            '2075244@conference.srv-php'
        ).then(r=>{
            console.log(r.attributes);
        });
    }

});

converse.initialize({
    auto_away: 300,
    show_client_info: false,
    bosh_service_url: 'http://srv-php/bosh/',
    allow_contact_requests: false,
    authentication: 'login',
    auto_login: true,
    jid: 'elg@srv-php',
    password: 'password12',
    debug: false,
    whitelisted_plugins: ['myplugin'],
    auto_join_rooms : ['2075244@conference.srv-php'],
    visible_toolbar_buttons:
        {
            call: false,
            spoiler: true,
            emoji: true,
            toggle_occupants: false
        },
    send_chat_state_notifications: false
});
```

2. I create the chat room and subscribe to the user "elg" and user "test".
3. I send two messages from the user "test" to the room "2075244@conference.srv-php".
4. I enter the compiled client, and when I enter it appears that the "num_unread" and "num_unread_general" attribute of that room is 0.
5. Then I send one more message having the client raised without UI and I execute from the console:
```
_converse.api.rooms.get(
                '207524481@conference.srv-php02'
            ).then(r=>{
                console.log(r.attributes);
            });
```
and the attributes of "num_unread" and "num_unread_general" continue to appear as 0.

**Expected behavior**
I expect that having two unread messages from user "elg" in that chat room tells me there are two when converse.js without UI is fully loaded.
And if I were to see new messages with the client without UI, it also appears that I have an unread message if I want to check that room from the browser console.

**Screenshots**
It does not apply because there is no UI

**Environment (please complete the following information):**
 - Desktop
 - Chrome 105
 - Converse.js 9.1.1

**Additional context**

**Comment by jcbrand** [comment]
The `num_unread` counter only gets incremented when the chat is hidden. Probably what's happening in your case is that `this.isHidden()` returns false.
