### ISSUE TITLE
conversejs does not process the thread, but receives and saves it for the user to customize, right?

### ISSUE THREAD

**Issue by buithevuong** [conversejs/converse.js#3027]
conversejs does not process the thread, but receives and saves it for the user to customize, right? I don't see any difference in the interface when attaching the thread

**Comment by jcbrand** [comment]
I don't understand your question @buithevuong 

Also, the issue tracker is not the appropriate place to ask questions, it's for bug reports and feature requests, and I expect people to use one of the two issue templates when creating a new issue.

![Screenshot from 2022-09-19 10-17-55](https://user-images.githubusercontent.com/683911/190976806-52ae1349-2aa5-445f-8591-ae408c78820d.png)

You can ask questions in our XMPP chatroom: xmpp:discuss@conference.conversejs.org?join

Here's a link for joining with your browser: https://inverse.chat/#converse/room?jid=discuss@conference.conversejs.org
