### ISSUE TITLE
File transfer broken on Android (Brave, Firefox) browsers

### ISSUE THREAD

**Issue by DanielKonopka** [conversejs/converse.js#3028]
Trying to send a 45kB png file to XMPP client (Conversations) shows "Uploading file: ..." message with the progress bar. It then fills up until 100%, then whole message disappears, no file is sent, not even message notification is seen, nothing.

Trying to send a file from XMPP client (Conversations) to converse.js - just a aesgcm:// URL appears, no possibility to view/download.

Same behavior whether OMEMO is off or on.
Text messaging works fine.

Instances tried:

- https://conversejs.org (9.1.1)
- https://conversejs.org/fullscreen.html (9.1.1)
- https://conversejs.hot-chilli.im/index-ws.html (9.1.1) (WebSockets version)
- https://conversejs.hot-chilli.im (9.1.1) (BOSH)
- https://inverse.chat (9.1.1)

Browsers tried:

- Brave Beta 1.44.68
- Firefox Beta 95.0.0-beta.1

**Comment by licaon-kter** [comment]
Can you try with a different user server that's not hot-chilli? 

Latest Firefox is 104, try to update that too.

**Comment by DanielKonopka** [comment]
I will try it soon. Could you please test this on your side as well?

**Comment by licaon-kter** [comment]
Using it on my own server, hosted by me, works fine.

**Comment by DanielKonopka** [comment]
Used a test account (both sides are on e2e.ee).

- I can send files **from** Converse to Conversations, works fine here.

- I still can't view/download files sent **from** Conversations to Converse, only plain aesgcm:// URL appears as message, no media is shown, even if I choose "Show media" from message's hamburger menu.

**Comment by jcbrand** [comment]
@DanielKonopka: Please set `loglevel` to `debug` and then open your browser's developer console and set logging to verbose.

Then send an encrypted file to Converse.

Check if you see any errors logged in the console.

**Comment by jcbrand** [comment]
I see now you're only using hosted versions of Converse, so you can't set the `loglevel`, but still, any logged errors will be visible in the browser's developer console. Please check if you see any there.
