### ISSUE TITLE
To add Hovering effect in the Navbar Buttons

### ISSUE THREAD

**Issue by Vanshika7902** [conversejs/converse.js#3040]
**Describe the bug**
I want to add Hovering effect in the Navbar Buttons .

**To Reproduce**
I will add Hovering effect in the Navbar Buttons .

**Screenshots**

![Screenshot (109)](https://user-images.githubusercontent.com/92636041/193746081-658fc031-dd8a-4646-9d73-b4b80d02fa71.png)

**Comment by jcbrand** [comment]
The website CSS is here: https://github.com/conversejs/converse.js/blob/master/src/shared/styles/website.scss
