### ISSUE TITLE
KaiOS Port

### ISSUE THREAD

**Issue by sjehuda** [conversejs/converse.js#3086]
Port Converse.js to GerdaOS/KaiOS (FirefoxOS).

There's no Jabber app currently.
https://store.bananahackers.net/
https://www.kaiostech.com/store/

**Comment by jcbrand** [comment]
Out of scope for this project, but there  is another project that uses `@converse/headless` with a different UI to build a chat app for KaiOS:

https://git.disroot.org/badrihippo/convo

**Comment by sjehuda** [comment]
Thank you for the link, JC!
