### ISSUE TITLE
Specifying a fixed width to .box-flyout breaks responsive design in embedded, mobile viewport mode

### ISSUE THREAD

**Issue by karolyi** [conversejs/converse.js#3100]
Hey,

I'm using the latest conversejs on my website and it seems that when using in embedded mode and mobile view, the design breaks as there is a specified width one can't override since it's marked with `!important`.

Investigating the issue, the culprit is [this line.](https://github.com/conversejs/converse.js/blob/e63ba2075f565a952b3ae5eebcd21beda4fad836/src/plugins/controlbox/styles/_controlbox.scss#L603)

If you comment that line out, the chat box will stay within its boundaries.

I can prepare a quick PR for this if you like.

**Comment by jcbrand** [comment]
That line is only active on small viewports and is there to make the chat full width when the browser is resized to be small.
I'm not convinced that it needs to be changed.

Closing this ticket due to inactivity.

**Comment by jcbrand** [comment]
I've updated the relevant CSS so that it's not enabled for embedded.
