### ISSUE TITLE
Offline messages to a chatbox that do not exist were not successfully saved to messages in the chatbox model

### ISSUE THREAD

**Issue by buithevuong** [conversejs/converse.js#3105]
I have a problem with _converse.ChatBox#createMessage function, when I receive many offline messages to a chat that doesn't exist yet, even though the createMessage function returns the message to create but in chatbox.messages there is no message (many messages are generated but only one is saved to chatbox.messages and displayed), please help
Conversejs version 9.1.1

**Comment by jcbrand** [comment]
This issue tracker is for bug reports and feature requests.

If you believe you've found a bug, please use the `Bug report` issue template and provide all relevant data.
