### ISSUE TITLE
Error in locale setting with i18n to 'ug'

### ISSUE THREAD

**Issue by Keram-Yasin** [conversejs/converse.js#3118]
I downloaded the latest version of converse.js, then I have built the converse.js files according to the steps in option 3 in this link: https://conversejs.org/docs/html/quickstart.html
Then i had the JavaScript and CSS files in Dist directory. I saved the dist directory in my webpage root directory.
Then i added the JavaScript and CSS filed to the head section of the index page. I also initialized the converse.js in the bottom section of the index page. Everything worked perfect with this integration.

I also changed the locale to different languages which can be found in '/dist/locale' directory. I am able to change the 
locale to all the 39 languages except one: 'ug'. My converse.js initialization code is shown below:
```
  <script>
    converse.initialize({
        bosh_service_url: 'https://conversejs.org/http-bind/', // Please use this connection manager only for testing purposes
        show_controlbox_by_default: true,
		i18n:'ug',
    });
  </script>
```

When i set i18n to 'ug', the converse.js is in English which is failure in the setting. Then i looked at 
the browser console to see if there is any errors. I found the following errors for the issue:

```
 FATAL: Cannot find module './ug.js' log.js:68:19
    log log.js:68
    fatal log.js:93
    initialize index.js:121
    initialize core.js:574
    initialize converse.js:53
    initialize entry.js:31
    <anonymous> index.html:57
```
can anybody verify if this is a bug?

**Comment by licaon-kter** [comment]
@Keram-Yasin did you update to https://github.com/conversejs/converse.js/commit/451ed18261b7149ffbd98e8007a3c3405ce94477 and tested?

**Comment by Keram-Yasin** [comment]
@licaon-kter i haven't know about that issue before. let me try with that commit.

**Comment by Keram-Yasin** [comment]
@licaon-kter now it works. thank you very much!
