### ISSUE TITLE
Contacts do not show up online until chat is opened with them.

### ISSUE THREAD

**Issue by ganderatc** [conversejs/converse.js#3123]
**Describe the bug**
Since upgrading from Converse 10.0.0 to 10.1.0, every contact in my contact list shows as offline (gray dot and the tooltip says "offline") until I click their name to open the chat with them. Javascript console shows no errors with either version.

Curiously, the contact list does still sort online contacts above offline contacts.

**Screenshots**

**Environment (please complete the following information):**
 - Desktop environment, Windows 10
 - Chrome 108.0.5359.125
 - Converse.js version 10.1.0
 - The server is running nginx on Debian and the client is connecting to a local server via websocket. None of that's changed.

Also verified on my iPhone 11 in Safari.

**Comment by jcbrand** [comment]
Does the problem go away when you log out and log in again?

You can also try clicking the refresh button (the two arrows pointing at one another) to refetch the roster.

![Screenshot from 2023-01-16 10-17-14](https://user-images.githubusercontent.com/683911/212641782-b03bd55a-017b-42c2-a8f6-10baab8447b2.png)

**Comment by samjunction** [comment]
> Does the problem go away when you log out and log in again?
> 
> You can also try clicking the refresh button (the two arrows pointing at one another) to refetch the roster.
> 
> ![Screenshot from 2023-01-16 10-17-14](https://user-images.githubusercontent.com/683911/212641782-b03bd55a-017b-42c2-a8f6-10baab8447b2.png)

When i was connecting via BOSH, it was happening frequently but after switching to websocket it is much better but issue does happening randomly and clicking on Refresh button does not refetch or update the roster.

**Comment by jcbrand** [comment]
So, all contacts are shown as offline and then wen you click on a contact to start chatting with them they become green (assuming they're online at that time)?

Works fine on my end, I haven't seen this behavior recently.

Have you tried on a different browser? Perhaps related to something cached in that specific browser.

**Comment by SilverYoCha** [comment]
Hello, I also have this behaviour.
I noticed that the presence statuses of the contacts in a MUC room are correct. So a contact can be shown as online in a MUC room while it is shown as offline in the control box contacts.
(In my environment, it was already the case with previous versions)

**Comment by jcbrand** [comment]
@SilverYoCha Are you using BOSH or websocket?

**Comment by SilverYoCha** [comment]
I am using websocket @jcbrand.

**Comment by samjunction** [comment]
> Hello, I also have this behaviour. I noticed that the presence statuses of the contacts in a MUC room are correct. So a contact can be shown as online in a MUC room while it is shown as offline in the control box contacts. (In my environment, it was already the case with previous versions)

I am also having exactly same issue. I am using websocket.

**Comment by licaon-kter** [comment]
I'm running ejabberd HEAD, websockets, but not seeing this issue.

Can you also state complete server info?

**Comment by samjunction** [comment]
> I'm running ejabberd HEAD, websockets, but not seeing this issue.
> 
> Can you also state complete server info?
Using openfire 

![serverinformation](https://user-images.githubusercontent.com/49243203/212892336-457db9f7-d4c1-461a-9ae1-711032cee122.png)

**Comment by ganderatc** [comment]
> @SilverYoCha Are you using BOSH or websocket?

I have tried it both ways, with the same behavior. Normally run WebSocket.

> So, all contacts are shown as offline and then wen you click on a contact to start chatting with them they become green (assuming they're online at that time)?

I have tried with Chrome on Windows, Chrome on Mac, Safari on iOS, and Safari on Mac. Retried using private browsing mode on all. Same behavior everywhere. Doesn't seem to be a caching problem.

Running ejabberd 21.01 (Debian Bullseye).

**Comment by licaon-kter** [comment]
Ok, oddly enough now I'm seeing it too :( and worse, it does not appear online even if I write messages between the accounts.

**Comment by drlight17** [comment]
I confirm this behaviour. I tested it on the CDN versions 6.0.1, 7.0.5, 8.0.1, 9.1.1 and 10.x.x. BOSH and websocket. With websocket it can be fixed on click at refresh button, but not with BOSH.
At 5.0.5 CDN version statuses work correctly in my cases.

**Comment by p42ity** [comment]
I can confirm this behaviour, too.

**Comment by samjunction** [comment]
Doing below change in function presenceHandler(presence) in converse.js  should fix the issue :
Change:
var status_message = presence.querySelector('status')?.textContent;    
To:
var status_message = presence.querySelector('status')?.textContent;    
if (status_message === undefined) {
    status_message = presence.querySelector('show')?.textContent;
}

**Comment by drlight17** [comment]
> Doing below change in function presenceHandler(presence) in converse.js should fix the issue : Change: var status_message = presence.querySelector('status')?.textContent; To: var status_message = presence.querySelector('status')?.textContent; if (status_message === undefined) { status_message = presence.querySelector('show')?.textContent; }

I will check this, thank you.

**Comment by brneor** [comment]
> Doing below change in function presenceHandler(presence) in converse.js should fix the issue : Change: var status_message = presence.querySelector('status')?.textContent; To: var status_message = presence.querySelector('status')?.textContent; if (status_message === undefined) { status_message = presence.querySelector('show')?.textContent; }

Tried to build it myself with your fix but still didn't work... Am I missing something?

**Comment by samjunction** [comment]
> > Doing below change in function presenceHandler(presence) in converse.js should fix the issue : Change: var status_message = presence.querySelector('status')?.textContent; To: var status_message = presence.querySelector('status')?.textContent; if (status_message === undefined) { status_message = presence.querySelector('show')?.textContent; }
> 
> Tried to build it myself with your fix but still didn't work... Am I missing something?

I did changes in released version. 

![conversejs-dist](https://github.com/conversejs/converse.js/assets/49243203/5cc6c8e3-af85-4adc-b38a-6f58980b23f1)

**Comment by licaon-kter** [comment]
@samjunction fyi 7-zip is open source and better than proprietary stuff ffs

**Comment by brneor** [comment]
Found out that I was not setting `assets_path` which messed things up. Your fix almost worked 100% for me, now if I reload the page logged as _User A_ I only see the status of _User B_ if they change it, otherwise I see it as offline.

**Comment by jcbrand** [comment]
Should be fixed now.

Please let me know if the problem persists somehow.

**Comment by brneor** [comment]
That's great! 

@jcbrand how can I test it?
