### ISSUE TITLE
Register bug (version 10.1.0)

### ISSUE THREAD

**Issue by member7me** [conversejs/converse.js#3131]
Hello.

**To Reproduce**
After upgrading to version version 10.1.0 noticed bug. Page isn't loading and redirected correctly after user's register. Just hanging. User register and page isn't redirected.

**Screenshots**
![1](https://user-images.githubusercontent.com/66087479/216433873-fd1b5953-a20a-4bdd-af40-c309ddb18291.png)

**Console:**
![2](https://user-images.githubusercontent.com/66087479/216433893-46449e9a-684f-422d-91fc-592a7f9f7589.png)

Chrome, Firefox
Converse.js v10.1.0 

**Config:**

>         authentication: 'login',
>         auto_reconnect: true,
>         allow_chat_pending_contacts: true,
>         allow_non_roster_messaging: true,
>         allow_user_trust_override: false,
>         ping_interval: 30,
>         default_domain: 'urlsite.com',
>         registration_domain: 'urlsite.com',
>         show_client_info: false,
>         domain_placeholder: 'urlsite.com',
>         bosh_service_url: 'https://urlsite.com:5443/bosh',
>         clear_cache_on_logout: 'true',
>         view_mode: 'fullscreen'

**Comment by member7me** [comment]
With such config everything works good
>     converse.initialize({
>         // Please use this connection manager only for testing purposes
>         bosh_service_url: 'https://urlsite.com:5443/bosh',
> 	reuse_scram_keys: true,
>     });

**Comment by jcbrand** [comment]
@member7me: Can you please check whether this is still an issue with the latest release (10.1.2)? Thanks!

**Comment by member7me** [comment]
> @member7me: Can you please check whether this is still an issue with the latest release (10.1.2)? Thanks!
Hello. Seems to work.
