### ISSUE TITLE
Uncaught Error: WebCrypto not found

### ISSUE THREAD

**Issue by johnstrong1** [conversejs/converse.js#3136]
iI followed the instructions exactly, but I keep getting this error on browser's console
i have simple html page and downloaded  these files from converse.js site:

    <link type="text/css" rel="stylesheet" media="screen" href="/static/cjs/dist/converse.min.css" />
    <script src="/static/cjs/libsignal-protocol.js"></script>
    <script src="/static/cjs/dist/converse.min.js"></script>

**Screenshots**
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/12671628/218192910-c37fb23f-c2cc-4131-8114-7fa32002bba5.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/12671628/218193037-c19c48ae-dd2a-4dd2-bd7c-eaf9eee20c5f.png">

 - Desktop
 - Browser [Firefox]

**Comment by licaon-kter** [comment]
And the signal .js file?

**Comment by licaon-kter** [comment]
Everything is in https://conversejs.org/docs/html

**Comment by member7me** [comment]
> libsignal-protocol.js

As I understand, here it was:
/static/cjs/libsignal-protocol.js

Just renamed.

**Comment by jcbrand** [comment]
@johnstrong1  `crypto.subtle` is a built-in library but it's only available via https or on localhost. 

You're most likely using a non-local domain via HTTP (no SSL/TLS), which is why `window.crypto.subtle` is not available.
The solution is to use HTTPS.

**Comment by guusdk** [comment]
@jcbrand I've burned myself (in a development context) twice now, at this very issue. Is there any way where this (missing crypto) can either be worked around (depend on some kind of alternative library), gracefully ignored, or made completely impossible (eg: do not allow logins at all)? Clients now suffer from weird issues when opened on a non-secure web endpoint, which leads to wild goose chases and annoyance.

**Comment by jcbrand** [comment]
@guusdk It's possible to tell the browser (at least Chrome) to treat an origin as secure:
https://stackoverflow.com/a/78581469/587370

We can perhaps add a warning modal that informs the user when they're using an insecure context and that Converse won't work properly.
