### ISSUE TITLE
Registration failed.

### ISSUE THREAD

**Issue by mkassir95** [conversejs/converse.js#3151]
ERROR: Registration failed.

1.create a free xmpp account at converse.org
![image](https://user-images.githubusercontent.com/72728047/220965955-1f9b82e9-fc96-4edb-aec7-3869f145f130.png)
2. Click on 'fetch registration form'
3. Continue registration
![image](https://user-images.githubusercontent.com/72728047/220966390-08af5df3-5dad-40f6-b3b4-d585f4d540cc.png)
5. See error
![image](https://user-images.githubusercontent.com/72728047/220966676-1716a56c-91ac-48f1-bb4b-93dae21c96de.png)

**Comment by mkassir95** [comment]
This is my code 

> <!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
        integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

        <link rel="stylesheet" type="text/css" media="screen" href="https://cdn.conversejs.org/10.1.2/dist/converse.min.css">
        <script src="https://cdn.conversejs.org/10.1.2/dist/converse.min.js" charset="utf-8"></script>

    <style>
        body {
            background-color: #F5F5DC;
            margin-top: 0px;
            margin-left: 0px;
        }

        .headerTitle {
            font-size: 30px;
        }


        .chat-icon {
            color: green;
            position: fixed;
            bottom: 100px;
            right: 30px;
            z-index: 99;
            font-size: 80px;
        }
    </style>
</head>

<body>
    <p class="headerTitle" style="text-align: center">Apliman Chatting Server Web Demo</p>
    <i class="fas fa-comment chat-icon" id="chat-icon"></i>
    <div id="conversejs"></div>
</body>

<script>
    document.getElementById("chat-icon").onclick = function(){
        alert ("This is a warning message!");
    
        converse.initialize({
        bosh_service_url: 'https://conversejs.org/http-bind/', // Please use this connection manager only for testing purposes
        show_controlbox_by_default: true
    });
};
</script>




</html>

>

**Comment by visionm45** [comment]
I cannot register with conversejs.org either... it seems there may be an ip allowlist that you must be on to create an account because I got the message in the client that 

Your IP address is not allowlisted. 

if this is the case then this is not an issue with the client, just that conversejs.org is not allowing registration at this time.

**Comment by jcbrand** [comment]
Yes, registrations are closed for conversejs.org.

**Comment by mkassir95** [comment]
I used my own ejabberd server. Thank you all
