### ISSUE TITLE
conversejs v10.1.2 Initialization settings i18n: 'zh_ CN 'error

### ISSUE THREAD

**Issue by wensongyu** [conversejs/converse.js#3152]
**Describe the bug**
Vue2.6.14 Integrated conversejs v10.1.2 Initialization settings i18n: 'zh_ CN 'error

**To Reproduce**
1. Vue2.6.14 Integrated conversejs v10.1.2
2. Configure i18n: 'zh_ CN'

**Screenshots**
![image](https://user-images.githubusercontent.com/77663927/221117319-ef8a576e-8bde-4976-846a-83f4c0c84b6b.png)

**Comment by jcbrand** [comment]
I think you are missing `po-loader` in your configuration.

https://github.com/conversejs/converse.js/blob/3530ccc35de9965ac8ba4a6c0c1e510fb5564728/webpack/webpack.common.js#L40
