### ISSUE TITLE
chat ui refreshes every minute

### ISSUE THREAD

**Issue by mkassir95** [conversejs/converse.js#3153]
chat ui refreshes every minute

**To Reproduce**
1. open the chat ui form
2. The form refreshes every minute

**Comment by mkassir95** [comment]
This is my code 

> <!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
        integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" media="screen"
        href="https://cdn.conversejs.org/10.1.2/dist/converse.min.css">
    <script src="https://cdn.conversejs.org/10.1.2/dist/converse.min.js" charset="utf-8"></script>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <style>
        body {
            background-color: #F5F5DC;
            margin-top: 0px;
            margin-left: 0px;
        }

        .headerTitle {
            font-size: 30px;
        }


        .chat-icon {
            color: green;
            position: fixed;
            bottom: 100px;
            right: 30px;
            z-index: 99;
            font-size: 80px;
        }

        .center {
            display: block;
            margin-left: auto;
            margin-right: auto
        }
    </style>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <script type="text/javascript">
        function codeAddress() {
            converse.initialize({
                bosh_service_url: 'http://localhost:5281/bosh', // Please use this connection manager only for testing purposes
                keepalive: true,
                message_carbons: true,
                play_sounds: true,
                roster_groups: true,
                show_controlbox_by_default: true,
                xhr_user_search: false
            });
        }

    </script>
</head>

<body onload="codeAddress();">
    <p class="headerTitle" style="text-align: center">Apliman Chatting Server Web Demo</p>
    
    <img src="https://icons.iconarchive.com/icons/hopstarter/soft-scraps/256/User-Chat-icon.png" class="center">
    </body>

     




</html>

**Comment by jcbrand** [comment]
Please provide clear instructions how to reproduce the issue with a non-modified version of Converse. 
`open the chat ui form` is not useful or actionable information.

My guess is that the issue is in your own code. Perhaps you're calling `converse.initialize` multiple times?

In future, please use the `Bug Report` template  when creating bug reports .

![Screenshot from 2023-02-24 14-34-31](https://user-images.githubusercontent.com/683911/221194557-a7516afa-a061-41d8-a288-c87d2aeb3934.png)
