### ISSUE TITLE
conversejs v10.1.2 demo Unable to log in in Chinese

### ISSUE THREAD

**Issue by wensongyu** [conversejs/converse.js#3158]
**Describe the bug**
conversejs v9.1.1 demo Can log in in Chinese ， Chinese login does not work with conversejs v10.1.2 demo

**To Reproduce**
Configure i18n: 'zh_ CN 'is enough

![image](https://user-images.githubusercontent.com/77663927/222032103-1c60d69e-a0cd-4f72-8c4d-97dc12a8d3b0.png)

**Openfire server log**
`
2023.03.01 10:44:06 TRACE [Jetty-QTP-BOSH-24438]: org.jivesoftware.openfire.http.HttpBindServlet - Data is available to be read from [172.25.78.44]
2023.03.01 10:44:06 TRACE [Jetty-QTP-BOSH-24438]: org.jivesoftware.openfire.http.HttpBindServlet - All data has been read from [172.25.78.44]
2023.03.01 10:44:06 DEBUG [Jetty-QTP-BOSH-24438]: org.jivesoftware.openfire.http.HttpSession - Session 1wj410v8or being opened with initial connection org.jivesoftware.openfire.http.HttpSession$HttpVirtualConnection@50ec4d77
2023.03.01 10:44:06 TRACE [Jetty-QTP-BOSH-24438]: org.jivesoftware.openfire.net.SASLAuthentication - Cannot support 'ANONYMOUS' as it has been disabled by configuration.
2023.03.01 10:44:06 TRACE [Jetty-QTP-BOSH-24438]: org.jivesoftware.openfire.net.SASLAuthentication - Cannot support 'GSSAPI' as the 'sasl.gssapi.config' property has not been defined.
2023.03.01 10:44:06 TRACE [Jetty-QTP-BOSH-24438]: org.jivesoftware.openfire.net.SASLAuthentication - Cannot support 'JIVE-SHAREDSECRET' as it has been disabled by configuration.
2023.03.01 10:44:06 TRACE [Jetty-QTP-BOSH-24438]: org.jivesoftware.openfire.http.HttpBindServlet - Data can be written to [172.25.78.44]
2023.03.01 10:44:06 TRACE [Jetty-QTP-BOSH-28198]: org.jivesoftware.openfire.http.HttpBindServlet - Data is available to be read from [172.25.78.44]
2023.03.01 10:44:06 TRACE [Jetty-QTP-BOSH-28198]: org.jivesoftware.openfire.http.HttpBindServlet - All data has been read from [172.25.78.44]
2023.03.01 10:44:06 DEBUG [Jetty-QTP-BOSH-28198]: org.jivesoftware.openfire.http.HttpSession - Creating connection for rid: 2236914142 in session 1wj410v8or
2023.03.01 10:44:06 DEBUG [Jetty-QTP-BOSH-28198]: org.jivesoftware.openfire.http.HttpSession - Adding connection to stream 1wj410v8or with rid 2236914142
2023.03.01 10:44:06 DEBUG [Jetty-QTP-BOSH-28198]: org.jivesoftware.openfire.http.HttpSession - Detected a queued connection (for session 1wj410v8or) with request ID (2236914142) that is exactly one higher than the last sequential request ID (2236914141). This inbound data on this connection will now be processed, after which the connection can be used to send outbound data back to the client.
2023.03.01 10:44:06 TRACE [Jetty-QTP-BOSH-28198]: org.jivesoftware.openfire.http.HttpSession - Immediate delivery of pending data to the client on session 1wj410v8or was requested, but no data is pending.
2023.03.01 10:44:06 DEBUG [httpbind-worker-12]: org.jivesoftware.openfire.net.SASLAuthentication - SASL negotiation failed for session: HttpSession{address=tf-20220902vmsl/1wj410v8or, streamID=1wj410v8or, status=1 (connected), isSecure=false, isDetached=false, serverName='tf-20220902vmsl', isInitialized=false, hasAuthToken=false, peer address='172.25.78.44', presence='
<presence type="unavailable"/>', hold='1', wait='PT59S', maxRequests='2', maxPause='PT5M', lastActivity='2023-03-01T02:44:06.389Z', lastAcknowledged='2236914142', inactivityTimeout='PT30S'}
javax.security.sasl.SaslException: Invalid first client message
    at org.jivesoftware.openfire.sasl.ScramSha1SaslServer.generateServerFirstMessage(ScramSha1SaslServer.java:147) ~[xmppserver-4.7.3.jar:4.7.3]
    at org.jivesoftware.openfire.sasl.ScramSha1SaslServer.evaluateResponse(ScramSha1SaslServer.java:114) ~[xmppserver-4.7.3.jar:4.7.3]
    at org.jivesoftware.openfire.net.SASLAuthentication.handle(SASLAuthentication.java:356) ~[xmppserver-4.7.3.jar:4.7.3]
    at org.jivesoftware.openfire.SessionPacketRouter.route(SessionPacketRouter.java:60) ~[xmppserver-4.7.3.jar:4.7.3]
    at org.jivesoftware.openfire.http.HttpSession.lambda$sendPendingPackets$2(HttpSession.java:564) ~[xmppserver-4.7.3.jar:4.7.3]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_342]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_342]
    at java.lang.Thread.run(Thread.java:750) [?:1.8.0_342]
2023.03.01 10:44:06 TRACE [httpbind-worker-12]: org.jivesoftware.openfire.http.HttpSession - Got a connection that is ready for outbound delivery of session 1wj410v8or. The connection's RID is 2236914142. The last sequential RID was: 2236914142
2023.03.01 10:44:06 TRACE [httpbind-worker-12]: org.jivesoftware.openfire.http.HttpSession - Delivering 1 deliverables to the client on session 1wj410v8or, using connection with RID 2236914142
2023.03.01 10:44:06 TRACE [Jetty-QTP-BOSH-28191]: org.jivesoftware.openfire.http.HttpBindServlet - Data can be written to [172.25.78.44]
2023.03.01 10:44:06 TRACE [Jetty-QTP-BOSH-28191]: org.jivesoftware.openfire.http.HttpSession - Session 1wj410v8or Request ID 2236914142, event complete: org.eclipse.jetty.server.AsyncContextEvent@169a1024
`

**Comment by licaon-kter** [comment]
Why is there a space between `zh_` and `CN`?

**Comment by wensongyu** [comment]
> Why is there a space between `zh_` and `CN`?
> 
> Did you set BOSH or Websockets?
> 
> Are those in index.html?
> 
> Why not set `host-meta` as the error log says?

`zh_` No space between and ` CN`

There is no BOSH problem with English login

This is my initialization configuration

```
converse.initialize({
            bosh_service_url: 'http://tf-20220902vmsl:7070/http-bind/', // 服务器地址
            prebind_url: 'https://tf-20220902vmsl:7070/http-prebind/',
            jid: Cookies.get('userName') +'@tf-20220902vmsl', // 账户
            password: 'admin', // 默认密码
            auto_login: false, // 不自动登录
            // assets_path: 'dist\\',
            i18n: 'zh_CN',  // 配置中文
            show_controlbox_by_default: false, // 最小化控制面板
            allow_logout: false, // 隐藏退出按钮
            allow_registration: false, // 隐藏注册按钮
            whitelisted_plugins: ['myplugin-logout'] //自定义插件加入白名单
 })

```

**Comment by jcbrand** [comment]
The error about not finding alternative connection methods is not fatal and should probably be reduced to a warning.

I tried Converse with `zh_CN` yesterday and it worked fine. I think the choice of language is irrelevant here. Did you try with a different language?

Looks to me like a simple authentication failure, in other words you provided the wrong JID or password.

**Comment by wensongyu** [comment]
> The error about not finding alternative connection methods is not fatal and should probably be reduced to a warning.
> 
> I tried Converse with `zh_CN` yesterday and it worked fine. I think the choice of language is irrelevant here. Did you try with a different language?
> 
> Looks to me like a simple authentication failure, in other words you provided the wrong JID or password.

I can guarantee that there is no problem with JID and password, because I have tried many times in v9.1.1 and v10.1.2, and reset the password in openfire to retry.
This is my test video：

https://user-images.githubusercontent.com/77663927/222114504-6226fe4e-77e5-4351-a462-bbdcb44fbcaf.mp4

**Comment by jcbrand** [comment]
So you were able to log in with the `admin` user but then afterwards not with a different user?

This makes me think that the bug is related to logging in with different accounts in one browser tab.

Have you tried logging in with the second user in a different browser or in a tab in incognito mode?

Also, please set `loglevel: 'debug'` when calling `converse.initialize`. And then turn on verbose logging in your browser developer console.

You will then see all the XML stanzas being sent and received. Check what happens in the situation where you cannot log in. Perhaps Converse is using the wrong JID (for example the previous user's JID) or something like that. You should be able to see that from the stanzas. You can also paste them here.
