### ISSUE TITLE
Missing files in package

### ISSUE THREAD

**Issue by M-Stenzel** [conversejs/converse.js#3206]
**Describe the bug**
There are missing files in the package, I was not able to find them in the source as well

**Environment (please complete the following information):**
 - Web 
 - Converse.js version 10.1.4

**Additional context**
There are several files missing, see the nginx log

2023/06/25 20:51:42 [error] 21128#21128: *7652 open() "/srv/www/converse.js/media/logos/primesound.png" failed (2: No such file or directory), client: 127.0.0.1, server: converse.xy-space.de, request: "GET /media/logos/primesound.png HTTP/2.0", host: "converse.xy-space.de", referrer: "https://converse.xy-space.de/"
2023/06/25 20:52:11 [error] 21128#21128: *7652 open() "/srv/www/converse.js/inverse-analytics.js" failed (2: No such file or directory), client: 127.0.0.1, server: converse.xy-space.de, request: "GET /inverse-analytics.js HTTP/2.0", host: "converse.xy-space.de", referrer: "https://converse.xy-space.de/fullscreen.html"
2023/06/25 21:47:44 [error] 21128#21128: *14061 open() "/srv/www/converse.js/analytics.js" failed (2: No such file or directory), client: 127.0.0.1, server: converse.xy-space.de, request: "GET /analytics.js HTTP/2.0", host: "converse.xy-space.de", referrer: "https://converse.xy-space.de/"
2023/06/25 21:47:44 [error] 21128#21128: *14061 open() "/srv/www/converse.js/media/logos/bairesdev-primary.png" failed (2: No such file or directory), client: 127.0.0.1, server: converse.xy-space.de, request: "GET /media/logos/bairesdev-primary.png HTTP/2.0", host: "converse.xy-space.de", referrer: "https://converse.xy-space.de/"
2023/06/25 21:47:44 [error] 21128#21128: *14061 open() "/srv/www/converse.js/media/logos/primesound.png" failed (2: No such file or directory), client: 127.0.0.1, server: converse.xy-space.de, request: "GET /media/logos/primesound.png HTTP/2.0", host: "converse.xy-space.de", referrer: "https://converse.xy-space.de/"
2023/06/25 21:47:44 [error] 21128#21128: *14061 open() "/srv/www/converse.js/media/logos/bairesdev-primary.png" failed (2: No such file or directory), client: 127.0.0.1, server: converse.xy-space.de, request: "GET /media/logos/bairesdev-primary.png HTTP/2.0", host: "converse.xy-space.de", referrer: "https://converse.xy-space.de/"
2023/06/25 21:47:44 [error] 21128#21128: *14061 open() "/srv/www/converse.js/media/logos/primesound.png" failed (2: No such file or directory), client: 127.0.0.1, server: converse.xy-space.de, request: "GET /media/logos/primesound.png HTTP/2.0", host: "converse.xy-space.de", referrer: "https://converse.xy-space.de/"

Any clues?

Martin.

**Comment by jcbrand** [comment]
The missing files are PNG images of sponsors. I'm purposefully excluding them from this repo to avoid unnecessary bloat.

If you really want them, you can check them out from here: https://github.com/conversejs/media
Check that repo out inside the root of your Converse repo.

The analytics.js file is also purposefully kept separate since I don't want analytics from other people's installations (privacy concerns).
