### ISSUE TITLE
Change language doesn't work

### ISSUE THREAD

**Issue by madfoss** [conversejs/converse.js#3207]
In the last 2 versions 10.1.3/10.1.4 the language cannot be changed, only the default language English is possible.
The language files under /dist/locales/ are available but without content.

- Desktop
 - Browser [e.g. Chrome, Firefox]
 - Converse.js version 10.1.3/10.1.4

Example of the complete content of de-LC_MESSAGES-converse-po.js

`"use strict";
(self["webpackChunkconverse_js"] = self["webpackChunkconverse_js"] || []).push([[2895],{

/***/ 1658:
/***/ ((module) => {

module.exports = {};

/***/ })

}]);`

**Comment by madfoss** [comment]
Works with version 10.1.5 thanks!

**Comment by madfoss** [comment]
Works with version 10.1.5 thanks!

**Comment by jcbrand** [comment]
Thanks for checking @madfoss
