### ISSUE TITLE
Chat message hide after 5sec 

### ISSUE THREAD

**Issue by iqra-ansari** [conversejs/converse.js#3225]
In this chat system when i built it i face chat message gide after 5 sec or display none, would you like to resolve it please

**Comment by iqra-ansari** [comment]
let me know how can i develope?

**Comment by jcbrand** [comment]
This issue tracker is for bug reports and feature requests. If you'd like to learn how to use and develop plugins for Converse, please read the documentation.

https://conversejs.org/docs/html/plugin_development.html
