### ISSUE TITLE
i18n value pt_BR is not being respected

### ISSUE THREAD

**Issue by brneor** [conversejs/converse.js#3233]
**Describe the bug**
In latest release, the setting `pt_BR` for `i18n` configuration has no effect apparently. 

**To Reproduce**

```html
<!DOCTYPE html>
<html lang="en">
<head>
	<link rel="stylesheet" type="text/css" media="screen" href="https://cdn.conversejs.org/10.1.5/dist/converse.min.css">
	<script src="https://cdn.conversejs.org/10.1.5/dist/converse.min.js" charset="utf-8"></script>
</head>
<body>
	<script>
		converse.initialize({
			bosh_service_url: 'https://conversejs.org/http-bind/', // Please use this connection manager only for testing purposes
			show_controlbox_by_default: true,
			i18n: 'pt_BR'
		});
	</script>
</body>
</html>
```

**Expected behavior**
UI text is in Brazilian portuguese.

**Actual behavior**
UI text is in English (not sure if defaults to english or try to use my system language)

**Environment (please complete the following information):**
 - Desktop 
 - Any browser
 - Converse.js version 10.1.5

**Additional context**
Worked just fine in version 10.1.2 and works for other values of `i18n` like `de` or `pt`.

**Comment by jcbrand** [comment]
Tested on the current master branch and works correctly.
