### ISSUE TITLE
Badge color not responsive to dark theme.

### ISSUE THREAD

**Issue by Zash** [conversejs/converse.js#3246]
The class used for [Hats](https://xmpp.org/extensions/xep-0317.html) sets text color to `white`:
https://github.com/conversejs/converse.js/blob/12a7933e390b8b9392a2837f9cc07d3fff6ffbbd/src/shared/styles/badges.scss#L34-L35

This leads to poor contrast when combined with a dark theme: 
![image](https://github.com/conversejs/converse.js/assets/197474/705c6bd6-a1b5-4d6e-996a-6b5dc56cca12)

I imagine the solution is to use a variable, but which?

**Comment by jcbrand** [comment]
Probably just `var(--background)`

**Comment by Zash** [comment]
Thanks!
