### ISSUE TITLE
XEP-0077: Ability to change XMPP account password

### ISSUE THREAD

**Issue by nodiscc** [conversejs/converse.js#326]
Hello, I'd like my users to be able to change their XMPP passwords using converse.js. Is this already implemented/possible? AFAIK it depends on [XEP-0077](http://xmpp.org/extensions/xep-0077.html#usecases-changepw) which is already (partially?) implemented for in-band registration.

Any help is welcome

**Comment by jcbrand** [comment]
In-band-registration is already supported, as you know, but not yet the resettting of passwords.

It's something I'd like to add but there's no timeline or deadline for it.

This feature will require some UI changes. We'll need to add a way to let users configure their accounts.
I'm not yet exactly sure what's the best way of exposing this option. I'm thinking of adding a "configure" icon next to the "close" icon (similar to the configure icon of chat rooms) which will render a configuration form where users can do things like change their passwords.

**Comment by nodiscc** [comment]
XEP-0077 adds 3 available actions for the user: register, change password, and [cancel account](http://xmpp.org/extensions/xep-0077.html#usecases-cancel). I don't know if you want to add account cancellation, but even then it should fit in the main view (I'd keep account management next to roster management like this:)

![converseui](https://cloud.githubusercontent.com/assets/3950390/6545522/ccc1f26a-c58b-11e4-91c8-ddce5203c29a.png)

On clicking the gear icon, unfold this:

 ![manage](https://cloud.githubusercontent.com/assets/3950390/6545523/d03e2fc6-c58b-11e4-957f-2790c09f78f6.png)

**Comment by jcbrand** [comment]
Thanks, I really like your suggestion. It's simple and logically grouped.

I think I'll go with that.

**Comment by nodiscc** [comment]
I don't use the software anymore, cleaning up my issues list

**Comment by licaon-kter** [comment]
Why close this if it's not fixed?

**Comment by PandaScience** [comment]
Would love to see this feature as well (at least pw change). Any chance this will come in the near future?
