### ISSUE TITLE
`Uncaught (in promise) TypeError: Xv.toStanza is not a function`

### ISSUE THREAD

**Issue by paulmenzel** [conversejs/converse.js#3280]
With commit https://github.com/conversejs/converse.js/commit/3f0a81973 trying to log in, I get:

```
2023-10-06T09:47:28.347Z INFO: SASL authentication succeeded. <empty string> log.js:74:19
Uncaught (in promise) TypeError: Xv.toStanza is not a function
    ly utils.js:180
    trigger events.js:31
    trigger events.js:31
    onConnected index.js:196
    onConnectStatusChanged index.js:340
    _changeConnectStatus connection.js:1133
    _onSessionResultIQ connection.js:1778
    run handler.js:122
    handlers connection.js:1263
    _dataRecv connection.js:1260
    F utils.js:473
    _dataRecv connection.js:1254
    _onMessage websocket.js:503
    onmessage websocket.js:282
    _replaceMessageHandler websocket.js:282
    _onInitialMessage websocket.js:267
    onmessage websocket.js:170
    _connect websocket.js:170
    connect connection.js:517
    connect index.js:112
    Tl init.js:448
    $l init.js:343
    login user.js:70
    connect loginform.js:92
    onLoginFormSubmitted loginform.js:57
    handleEvent lit-html.ts:2018
utils.js:180:25
```

**Comment by paulmenzel** [comment]
(Correct commit hash.)

**Comment by paulmenzel** [comment]
Sorry, looks like, the my SSL certificate expired. :/

**Comment by paulmenzel** [comment]
Hmm, the cert is valid until May 2024, so that’s not it.

**Comment by paulmenzel** [comment]
> Sorry, looks like, the my SSL certificate expired. :/

That was wrong, and ejabberd works fine:

    $ openssl s_client -connect xmpp.molgen.mpg.de:5222 </dev/null -starttls xmpp -xmpphost molgen.mpg.de
    […]
    SSL handshake has read 5911 bytes and written 603 bytes
    Verification: OK
    […]

So, I am re-opening the issue.

**Comment by paulmenzel** [comment]
I corrected the commit hash again. Commit https://github.com/conversejs/converse.js/commit/3f0a81973f6ba5f3237e28f69fa4fd1ccdccd487 (Update to latest Strophe) introduced the regression

**Comment by jcbrand** [comment]
The `toStanza` function is now in Strophe:
https://github.com/strophe/strophejs/blob/6b24a2a2121884b2d02aeb5756142f7dcaf05d9e/src/stanza.js#L10

Looks like you don't have the latest version of Strophe in your node_modules.

Try running `make clean` and then `make watch`  or `make dev` again.

**Comment by paulmenzel** [comment]
I always do `rm -rf dist/ && make dist`.

```
$ head -10 node_modules/strophe.js/src/stanza.js 
import Strophe from './core.js';

const PARSE_ERROR_NS = 'http://www.w3.org/1999/xhtml';

/**
 * @param { string } string
 * @param { boolean } [throwErrorIfInvalidNS]
 * @return { Element }
 */
export function toStanza (string, throwErrorIfInvalidNS) {
```

**Comment by paulmenzel** [comment]
With commit https://github.com/conversejs/converse.js/commit/b048daa717c35cb28a8118e4457938d02175d2e1 from current master, I have a different problem:

    Uncaught TypeError: class heritage r.default is not an object or null

**Comment by paulmenzel** [comment]
Even going back to commit https://github.com/conversejs/converse.js/commit/3f0a81973, I am unable to reproduce the `Xv.toStanza` issue. So I guess it was outdated Strophe version.
