### ISSUE TITLE
Error with suggestion-box using autocomplete_add_contact: true && xhr_user_search_url 

### ISSUE THREAD

**Issue by sergiogonzalez2** [conversejs/converse.js#3290]
ERROR with configuration autocomplete_add_contact: true && xhr_user_search_url . When I try to add a contact in my chat using the autocomplete config, suggestions that matches with the query introduced are showed, so my endpoint works (also without the autocomplete, contact matched is added, if only one matches). The problem come when I select one of the suggestions that matches in the suggestion-box, in that moment I have the next error and can´t fill the input w that value: 

Uncaught TypeError: Cannot read properties of undefined (reading 'value')
    at AutoComplete.insertValue (converse.js:51317:1)
    at AutoComplete.select (converse.js:51372:1)
    at AutoComplete.onMouseDown (converse.js:51397:1)

I think that with the last version of converse, this bug will be fixed, but can´t change mi version because of incompatibility with my Angular version. I´m now comparing converse.js file in the last version with mine, but autocomplete functions are so similar, I can´t  see where the error is. My petition is to know exactly what I must change to fix it, if it is fixed.

I attach a screenshot: 
<img width="804" alt="Captura de pantalla 2023-11-23 180013" src="https://github.com/conversejs/converse.js/assets/72086017/89bff78f-8bc9-4eed-abf4-9f4bab572823">

**Environment :**
 - Desktop 
 - Browser Chroome or Edge
 - Converse.js version 10.0.0

**Comment by sergiogonzalez2** [comment]
@jcbrand

**Comment by sergiogonzalez2** [comment]
@licaon-kter

**Comment by licaon-kter** [comment]
@sergiogonzalez2

**Comment by sergiogonzalez2** [comment]
help?

**Comment by licaon-kter** [comment]
I'm not a dev... sorry
