### ISSUE TITLE
Poezio with OMEMO breaks encryption for conversejs clients

### ISSUE THREAD

**Issue by roughnecks** [conversejs/converse.js#3291]
**Describe the bug**
When in a private MUC where OMEMO is enabled, a user running Poezio joins, all conversejs clients are unable to send encrypted messages.

**To Reproduce**
1. Join a private, members only muc with OMEMO enabled
2. Let a user running Poezio join in too
3. Enable OMEMO in Poezio
4. Try to send an encrypted message from conversejs
5. Message is held back, never sent.

**Expected behavior**
Poezio shouldn't break encryption for conversejs clients, since other clients like Gajim and Conversations still work fine.

**Environment (please complete the following information):**
 - Desktop
 - Firefox
 - Converse.js version 10.1.6
 - Poezio 0.14 Flatpack

**Comment by licaon-kter** [comment]
@roughnecks debug console output from Converse when this happens?

**Comment by roughnecks** [comment]
Hi, this is what I could gather, not sure if there is anything else, got a lot of errors in console.

https://gist.githubusercontent.com/roughnecks/2264c4b6ebf4312fdb2f30ae8c44581e/raw/37c6fe3f4e74311f7e8123eb1c286cc1183f527c/2023-12-05_10-32-28.txt

**Comment by resoli** [comment]
Same here.

**Comment by licaon-kter** [comment]
What's the corresponding poezio issue?

**Comment by licaon-kter** [comment]
@resoli same what? Same server as OP? Which server software? Same poezio version? Converse version? Poezio logs? Converse debug logs?

**Comment by resoli** [comment]
Hello @licaon-kter. Right.
Same Converse version 10.1.6, but served via apache instead of the OP who served it via prosody module.

I participated in the same muc with OMEMO enabled as the OP, same symptoms.

The Poezio client was operated by a third participant.

**Comment by resoli** [comment]
> What's the corresponding poezio issue?

May be the Poezio user would open one? Will ask him.

**Comment by resoli** [comment]
Update: we somewhat managed to make the issue disappear on an ad-hoc muc on another server. Will report here our findings ...

**Comment by resoli** [comment]
It's difficult to say what resolved. The only thing that forma dure me and the other partecipanti changed was adding `allow_non_roster_messaging: true` to configuration. I think that the OP might close the issue, if he has no other remarks to point out.
