### ISSUE TITLE
avatar image not displayed for connected user and displayed not always in front of users contacts names 

### ISSUE THREAD

**Issue by Dihcar-76** [conversejs/converse.js#3293]
**Describe the bug**
Avatar is displayed intermittently in main chat box view for connected user, and for contacts users not displayed for all users and some degradation of image from colors to black and white after a refresh in profile modal window.
When connecting with another contact user, user that hasn't got an image displayed, gots its image displayed inthe contact user list as it appears as a contact. It seems that it has the good image stored but somehow when it is the connected user, default image is displayed.

**To Reproduce**
login to chat avatar is not dot displayed in main chat box view for connected user, and for others users displayed not for all users who have an image

**Expected behavior**
image is displayed correctly for connected users and for contacts users.

here is a screenshot, as we see connected user (Rbo) doesn't have his image displayed and contact users have all an image defined but image is not displayed for all (user U_Valid doesn't have an image displayed). Also after a refresh avatar image is in black and white instead of colored image for one user (mes2) 
![image](https://github.com/conversejs/converse.js/assets/35745701/4ef2a206-3834-4e0d-ac40-c0207c07ef63)

**Environment (please complete the following information):**
 - windows 11,
 - Browser edge, firefox
 - Converse.js version 6.0.1
 -  Openfire 4.6.6,

**Additional context**
image is defined like this 

	public IVCard createVCard( User user, IVCard vCard )
				 throws Exception
	{
		if( vCard == null )
			return vCard;

		AbstractXMPPConnection connection = null;

		try
		{
			// connection = getXMPPConnection( user );

			connection = XMPPHelper.createXMPPConnection( ServerInfo.TCP_CONNECTION_TYPE, serverInfo,
																										user.getUsername() );

			if( ( connection != null ) && connection.isConnected() )
			{
				org.jivesoftware.smackx.vcardtemp.VCardManager vcardManager = null;

				org.jivesoftware.smackx.vcardtemp.packet.VCard smackVCard = new org.jivesoftware.smackx.vcardtemp.packet.VCard();

				smackVCard.setAvatar( vCard.getAvatar() );//byte[] image passed
				smackVCard.setFirstName( vCard.getFirstName() );
				smackVCard.setLastName( vCard.getLastName() );
				smackVCard.setNickName( vCard.getNickName() );
				smackVCard.setEmailWork( vCard.getEmail() );
				vcardManager = org.jivesoftware.smackx.vcardtemp.VCardManager.getInstanceFor( connection );

				org.jivesoftware.smackx.vcardtemp.packet.VCard currentsmackVCard = vcardManager.loadVCard();

				vcardManager.saveVCard( smackVCard );

				return vCard;
			}
			else
			{
				System.err.println( "User : " + user.getUsername() + " not connected !" );
				throw new ConnectionException( "User : " + user.getUsername() + " not connected !" );
			}
		}
		catch( InterruptedException ie )
		{
			ExceptionLogger.log( ie, false );
			throw new ConnectionException( ie.getMessage(), ie );
		}
		catch( NoResponseException nre )
		{
			ExceptionLogger.log( nre, false );
			throw new ConnectionException( nre.getMessage(), nre );
		}
		catch( NotConnectedException nce )
		{
			ExceptionLogger.log( nce, false );
			throw new ConnectionException( nce.getMessage(), nce );
		}
		catch( XMPPErrorException xmppee )
		{
			ExceptionLogger.log( xmppee, false );
			throw new ConnectionException( xmppee.getMessage(), xmppee );
		}
		catch( Exception e )
		{
			ExceptionLogger.log( e, false );
			throw new ConnectionException( e.getMessage(), e );
		}
		finally
		{
			if( connection != null )
			{
				connection.disconnect();
				connection = null;
			}
		}
	}

**Comment by Dihcar-76** [comment]
as you can see I display only custom nickname (see in the screenshot)

**Comment by Dihcar-76** [comment]
Issue resolved as I have used custom Jid, when i do a vcard.findWhere(jid) it is not working. Issue resolved.

**Comment by Neustradamus** [comment]
@Dihcar-76: How is for you a "custom Jid"?
