### ISSUE TITLE
The application crashes in Chromium when specifying i18n setting

### ISSUE THREAD

**Issue by aitzol76** [conversejs/converse.js#3295]
**Describe the bug**
The application crashes and doesn't load in Chromium if I specify via the `i18n` setting `eu`(basque) as locale and at the same time in the browser that language is not selected as first. In the browser's console I don't get any error message that makes me suspect it.
Here is my config:
```
converse.initialize({
  authentication: "login",
  theme: "concord",
  domain_placeholder: "user@example.org",
  view_mode: "fullscreen",
  i18n: "eu"
});
```
**To Reproduce**
1. Setup explicit locale via i18n, in my case `eu`
2. Try to open the client in Chromium
3. The page does not load correctly.

**Expected behavior**
As in other browsers, I expect the application to load correctly.

**Environment (please complete the following information):**
 - Desktop
 - Chromium Version 120.0.6099.129 (Official Build) built on Debian 12.4, running on Debian 12.4 (64-bit)
 - Converse.js v10.1.6

**Additional context**
Works fine in Firefox and also Webkit based browsers.

**Comment by jcbrand** [comment]
Tested on master, works fine.
