### ISSUE TITLE
New release build?

### ISSUE THREAD

**Issue by Neustradamus** [conversejs/converse.js#3333]
Dear ConverseJS team, @jcbrand,

It is possible to have a new build?

Several projects wait the new build to solve an important problem which has been solved into StropheJS by ejabberd team more one month ago and the StropheJS 2.0.0 has been released yesterday (2024-02-21):
- https://github.com/strophe/strophejs/releases/tag/v2.0.0
- https://github.com/strophe/strophejs/pull/698
- https://github.com/strophe/strophejs/commit/d43a619346abf40d6533302bd5aea5bc907a3dd9

For example, ejabberd needs ConverseJS update:
- https://github.com/processone/ejabberd/issues/4142

Thanks in advance.

Linked to:
- https://github.com/conversejs/roundcube-plugin/issues/23
- https://github.com/strophe/strophejs/issues/702

**Comment by Neustradamus** [comment]
ejabberd 24.02 has been released:
- https://www.process-one.net/blog/ejabberd-24-02/

It is possible to create the new ConverseJS build?

Thanks in advance.

**Comment by Neustradamus** [comment]
Dear ConverseJS team, @jcbrand,

A solution exists, it is to create a 10.1.6.1 build (= 10.1.6 + the 2.0.0 StropheJS with fix), it is the best solution to do not touch other.

All admins/users will be happy.

Thanks in advance.

**Comment by jcbrand** [comment]
Done.

**Comment by Neustradamus** [comment]
@jcbrand: Thanks a lot for 10.1.7 release build!
- https://github.com/conversejs/converse.js/releases/tag/v10.1.7
