### ISSUE TITLE
Do not create empty nick element in bookmarks

### ISSUE THREAD

**Issue by guusdk** [conversejs/converse.js#3362]
When creating a bookmark, Converse (from older versions up to and including the current latest release, v10.1.7), appears to always add a `nick` element, even when there is no nickname.

This leads to bookmarks, like these:

```xml
<storage xmlns="storage:bookmarks">
	<conference autojoin="false" jid="myRoom@conference.example.org" name="Test Room">
		<nick/>
	</conference>
</storage>
```

It appears that Converse adds an empty `nick` element for pre-existing bookmarks (possibly defined in other clients in the past), while adding/modifying antoher bookmark in the collection of bookmarks.

This arguably breaks the specifications. Other clients fail to parse these empty elements, leading to bugs. Eg: https://github.com/igniterealtime/Smack/pull/485

**Comment by jcbrand** [comment]
Thanks, should be fixed now in master.
