### ISSUE TITLE
Api call to update vcard

### ISSUE THREAD

**Issue by teseo** [conversejs/converse.js#337]
Hello,

We have a Backbone application that also runs converse.js on top of it. Both works simultaneously brilliant. 
In our application users can change their avatar as well as name and we would like to be able to change, at the same, change the vcard information in converse.js.

The information is in sessionStorage and we would not like to clear the whole converse.js entries as well as not scrapping and chasing around among the stored information.

Would it be considered as a new enhancement with this feature? maybe a new api call to retrieve again the new vcard information in db for a given jid?

Many thanks!

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/9527906-api-call-to-update-vcard?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github).

<bountysource-plugin>

**Comment by fpytloun** [comment]
I would also appreciate this! Or at least give possibility to use xhr resource for obtaining such informations similar way as xhr_user_search.

**Comment by proton5000** [comment]
hellow!
i have same problem, when i update user avatar, it not update in conversation, if only user re-login then avatar will update.
how can i update user avatar without re-login user???
help me please :'(

**Comment by proton5000** [comment]
@teseo 
Hello! Do you solved your problem??? I have same problem with card, but cannot solve.

**Comment by teseo** [comment]
@proton5000 I ended working at that project 2 years ago :(
