### ISSUE TITLE
HTTPS serve on virtual host instead of port

### ISSUE THREAD

**Issue by avidseeker** [conversejs/converse.js#3406]
Following the guide for prosody [mod_conversejs](https://modules.prosody.im/mod_conversejs.html), conversejs successfully runs on https://example.com:5281/conversejs, but there doesn't seem a way to change the port and base domain that conversejs uses. According to the documentation, conversejs uses "Prosodys internal [http server](https://prosody.im/doc/http)", and the module provides the following settings that I can't find a documentation for:

> These settings are set to the current `VirtualHost`:
* jid
* default_domain
* domain_placeholder
* registration_domain

How can I set conversejs to serve https://chat.example.com instead of https://example.com:5281/conversejs?

The closest I found was an [nginx setup here](https://m.conversejs.org/docs/html/setup.html) but what should be `root   /path/to/converse.js/;` the path to converse.js if I installed it as a prosody module?

**Comment by BetaRays** [comment]
This seems to be an issue with your Prosody configuration, not with Converse.js.
Have you tried asking https://prosody.im/discuss yet?
