### ISSUE TITLE
Converse v11: missing constants in exports (for custom plugins)

### ISSUE THREAD

**Issue by JohnXLivingston** [conversejs/converse.js#3440]
**Describe the bug**

When developping plugins, we could get some constants on `_converse`.
For example, `_converse.CHATROOMS_TYPE`.

In v11, some of the classes that were on `_converse` moved to `_converse.exports`. But i can't find constant such as `CHATROOMS_TYPE`.

How can we get such constants in v11?

**Comment by jcbrand** [comment]
Try this:

```
import { constants } from '@converse/headless';

const { CHATROOMS_TYPE } = constants;
```

**Comment by jcbrand** [comment]
I've made a commit which also puts it on `_converse.constants`

**Comment by JohnXLivingston** [comment]
All my plugins are not in the Converse bundle, so I can't use the first solution.
Thanks for the addition in `_converse.constants`!
