### ISSUE TITLE
Sending a message with an uppercase emoji code breaks the message field.

### ISSUE THREAD

**Issue by JohnXLivingston** [conversejs/converse.js#3499]
**Describe the bug**

If you try to send a message with an emoji code, but with at least one uppercase letter, it breaks the message field.
There is this error in the javascript console:

```
can't access property "cp", qg.emojis.by_sn[e[0]] is undefined
```

**To Reproduce**
1. Open a chat
2. try to send `:A:`

**Comment by JohnXLivingston** [comment]
The bug is because of this:

```javascript
converse.emojis.shortnames_regex = new RegExp(getShortNames(), 'gi');
```

The shortnames_regex is case insensitive.

It is then used to search the emoji:

```javascript
const references = [...text.matchAll(converse.emojis.shortnames_regex)].filter(ref => ref[0].length > 0);
return references.map(ref => {
        const cp = converse.emojis.by_sn[ref[0]].cp;
        return {
            cp,
            'begin': ref.index,
            'end': ref.index+ref[0].length,
            'shortname': ref[0],
            'emoji': cp ? convert(cp) : null
        }
    });
```

This is the only call of this function.

So, there are two possible fix:

* remove the `i` modifier, and make it case sensitive
* `ref[0].toLowercase()` so it remains case insensitive.

What's your preferred version @jcbrand ?


PS: There is a `getEmojisByAtrribute` function. I guess it is a typo, and it should be `getEmojisByAttribute`. There is no bug with this, as the typo is everywhere.

**Comment by jcbrand** [comment]
Thanks for the bug report.

> ref[0].toLowercase() so it remains case insensitive.

I think we should make it case insensitive.

> PS: There is a getEmojisByAtrribute function. I guess it is a typo, and it should be getEmojisByAttribute. There is no bug with this, as the typo is everywhere. (the function is added in converse.env, so i don't know if renaming it would not break some plugins)

The next release is in any case a breaking one, so I think we can just fix the typo.

**Comment by JohnXLivingston** [comment]
I will make a PR.
Just found another bug: if i write `:A:`, the message does not show the emoji bigger, as it should.
I'm looking for the bug.
