### ISSUE TITLE
Conversejs.org various issues (registration, login, settings)

### ISSUE THREAD

**Issue by HansLachman** [conversejs/converse.js#3500]
I encountered various issues when attempting to register and use an XMPP account, and documented them in a write-up of what actions I took and the results of those actions, see attached text file.  I previously posted this file in the xmpp.org GitHub project ( https://github.com/xsf/xmpp.org/issues/1419 ), and since some of the issues involve Conversejs.org, they suggested I post about it here (conversejs GitHub project), so I'm attaching the same write-up - see Chapters 2, 5, 7 for conversejs-related issues, and specifically, Suggestions 2a, 2b, 2c, 5a, 7b.  Note that 2a, 2b, 2c are registration-related issues (apparently as-yet unresolved), mentioned previously in a conversejs problem report ( https://github.com/conversejs/converse.js/issues/3466 - see items listed there as (1), (2), (3)), while 5a is a login issue (forever-spinning wheel when login hangs, perhaps not reproducible at will, as I don't know what causes a login to hang), and 7b is an issue with account settings not working (reproducible).
[xmpp-adv.txt](https://github.com/user-attachments/files/16903904/xmpp-adv.txt)

**Comment by jcbrand** [comment]
Thanks, but this is not a proper bug report. We have a bug report template that you're offered when creating a new issue, please use that.
