### ISSUE TITLE
Changelog is missing the changes in 10.1.7

### ISSUE THREAD

**Issue by joudinet** [conversejs/converse.js#3552]
**Describe the bug**
CHANGES.md that contains the Changelog does not mention the version 10.1.7, which has been release in March 15th.
The release description says: "Update to Strophe 2.0.0. Fixes login issue with newer versions of Ejabberd".
I guess these two lines should be in the ChangeLog but I don't know if there are more changes between 10.1.6 and 10.1.7.

**Comment by jcbrand** [comment]
https://github.com/conversejs/converse.js/commit/8f32df723e3aa392db02326dc6a3279c9497b6fb
