### ISSUE TITLE
Browser console contains `WARNING: No missing prekeys to generate for our own device <empty string>`

### ISSUE THREAD

**Issue by paulmenzel** [conversejs/converse.js#3554]
**Describe the bug**

Looking at the browser console, the warning below is logged:

> New remote ephemeral key
> Duplicate PreKeyMessage for session
>  2024-12-02T11:02:20.046Z WARNING: No missing prekeys to generate for our own device <empty string>

**To Reproduce**
1. Log into https://converse.molgen.mpg.de
2. Open browser console

**Expected behavior**
No error should be logged.

**Environment (please complete the following information):**
 - Browser: Firefox Nightly 135.0a1 (20241201095257)
 - Converse.js version: commit https://github.com/conversejs/converse.js/commit/8f32df723e3aa392db02326dc6a3279c9497b6fb (Fixes #3352. Add changelog for version 10.1.7)

**Comment by jcbrand** [comment]
Thanks, I've reduced the loglevel.

**Comment by paulmenzel** [comment]
Thank you.
