### ISSUE TITLE
XEP-0384: OMEMO Encryption

### ISSUE THREAD

**Issue by muzirian** [conversejs/converse.js#497]
Request for adding support for omemo encryption http://conversations.im/xeps/multi-end.html

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27208020-xep-xxxx-omemo-encryption?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github).
</bountysource-plugin>

**Comment by lovetox** [comment]
would be great getting this !

**Comment by tristan-k** [comment]
+1

**Comment by devdan** [comment]
I am very interested in this, too.

**Comment by nick4me** [comment]
I'm also very interested. That's really a great feature.

**Comment by rasos** [comment]
+1 
would fit perfectly with the Conversations Android App, which also supports omemo

**Comment by GreenLunar** [comment]
See also OMEMO.js at https://github.com/cryptocat/cryptocat/issues/178

**Comment by herbsmn** [comment]
What are the blockers you have that are preventing implimentation of OMEMO?

**Comment by jcbrand** [comment]
@herbsmn I currently don't have the time for it.

**Comment by 3615pipou** [comment]
The XEP is now release http://xmpp.org/extensions/xep-0384.html

**Comment by jcbrand** [comment]
There is a pending [GSOC Proposal](https://wiki.xmpp.org/web/Summer_of_Code_2017#OMEMO_encryption_in_Converse.js) for this feature.

**Comment by ignatdoc** [comment]
Maybe someone want to implement OMEMO support for bounty ? We can discuss )

**Comment by jcbrand** [comment]
Unfortunately converse.js didn't get any GSOC students this year.

There were three applications, but none of them made the cut. The decision was made by the XSF foundation and myself. What also played a role was that I wasn't able to find a backup mentor to help me this year.

This means that there's nobody working on OMEMO currently.

@ignatdoc Why don't you simply post a bounty on bountysource? The link is in the ticket description. The money doesn't get subtracted unless and until this ticket gets closed.

This applies to anyone else who wants to see this ticket move forward.

**Comment by plambe** [comment]
jsxc has a new OMEMO plugin: 
https://github.com/jsxc/jsxc-plugin-omemo

I hope this helps since it's written in javascript.

**Comment by Mrfuyu** [comment]
Conversations now is encrypting with OMEMO by default, what can breaks communication. Would be nice to have this now also in Converse.js !

**Comment by albjeremias** [comment]
how is the progress on this? what needs to be done? i see some commits... :)

**Comment by albjeremias** [comment]
https://github.com/conversejs/converse.js/compare/converse-omemo its this branch you have been working on?

**Comment by jcbrand** [comment]
yes

**Comment by jcbrand** [comment]
OMEMO support has been added. Tested with Conversations.

**Comment by muppeth** [comment]
how do you enable it?

**Comment by jcbrand** [comment]
> how do you enable it?

[libsignal](https://github.com/signalapp/libsignal-protocol-javascript) needs to be loaded and available. Then you will see a lock icon in the chat toolbar.

**Comment by genofire** [comment]
okay got it, just do a `wget "https://raw.githubusercontent.com/signalapp/libsignal-protocol-javascript/master/dist/libsignal-protocol.js"` and include it by adding `<script src="/static/libsignal-protocol.js"></script>
` in html file. ;)

Is there any way of qrcode to scan for Conversations and co?

**Comment by MatthiasKauer** [comment]
I wanted to try OMEMO from https://inverse.chat/ or https://conversejs.org/.
I can't find the "lock" you mention above there, however.
Looking at the page source, I find: 
`<script src="3rdparty/libsignal-protocol-javascript/dist/libsignal-protocol.js"></script>`
Unfortunately, that file gives me a 404.
Is there a problem with that link or am I just missing something?

**Comment by jcbrand** [comment]
@MatthiasKauer Should be fixed now, thanks for reporting.

**Comment by MatthiasKauer** [comment]
It's fixed as far as I can tell.
I happily used inverse.chat yesterday.

**Comment by MaggusK** [comment]
> It's fixed as far as I can tell. I happily used inverse.chat yesterday.

I'm really pleased for you. Could you please tell me how to use omemo on this sites? As you can see on the screenshot there is nothing like a lock icon :(
![screenshot-inverse chat-2018-10-23-12-02-25](https://user-images.githubusercontent.com/6929342/47353221-015f0400-d6bc-11e8-9f7c-034b9a9662e8.png)

**Comment by MaggusK** [comment]
obviously OMEMO encryption is only supported for XMPP IDs of the same server. I created a new conversejs ID and with this encryption works on conversejs.org. But also the conversejs ID does not work on inverse.chat as all my other IDs don't.
Is there anybody who can explain this?

**Comment by jcbrand** [comment]
> obviously OMEMO encryption is only supported for XMPP IDs of the same server.

No, this is not true. OMEMO encryption is client-based and largely independent of the server (as long as it is modern enough to implement PEP).

>  I created a new conversejs ID and with this encryption works on conversejs.org. But also the conversejs ID does not work on inverse.chat as all my other IDs don't.

Both users need to use an OMEMO compliant client. What did the other user use?

**Comment by MaggusK** [comment]
> Both users need to use an OMEMO compliant client. What did the other user use?
I always chat with the same other jabber.de user that is using conversations. If I log in with my new conversejs.org ID it works.
So, is there an explanation, why, if I log in with my jabber.de ID I can not send encypted messages to the same user with the same client?

**Comment by jcbrand** [comment]
@MaggusK I don't know. Maybe you have old cached JavaScript files? Clear your cache and then check again.

**Comment by MaggusK** [comment]
**@jcbrand** : I found out, there is also a jabber webchat at https://chat.jabber.de/  (using conversejs).
If I login with my jabber.de ID I can see the lock icon there, but an error occurs while sending a message: "_Sorry, could not send the message due to an error. bundle is undefined_". Unencryptet messages can be delivered. What ever this could be?! Seems there is a problem with the jabber ID.
Maybe this is also the reason, why the file adding icon isn't appearing.

**Comment by NicoHood** [comment]
But then this list ist wrong:
http://omemo.top/

**Comment by orbitz** [comment]
Is there any plan for converse.js to support group chat and OMEMO?

**Comment by Neustradamus** [comment]
@jcbrand: OMEMO works in groups if all users have OMEMO keys of all users in the group.

Can you look it?
