### ISSUE TITLE
XEP-0050: Ad-Hoc Commands

### ISSUE THREAD

**Issue by singpolyma** [conversejs/converse.js#515]
Could be very useful to provide a menu of commands on any entities that support them.  Especially the sever the user is connected to, for bits of administrivia, etc.

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/28138209-xep-0050-ad-hoc-commands?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github).

<bountysource-plugin>

**Comment by MotoGP-Fan** [comment]
Personally I would be happy about an "invite" function (Prosody's mod_invite) for the users. This would allow every user to create an invitation link to his friends without having to install e.g. Gajim.

**Comment by genofire** [comment]
It would be nice to have better Ad-Hoc Commands support, to set persistant by this irc-transport software:
- [every ad-hoc command of biboumi](https://doc.biboumi.louiz.org/user.html#ad-hoc-commands
- [for channel](https://doc.biboumi.louiz.org/user.html#on-a-channel-jid) only thi

(Dino create a setting only for irc-channel persistant option would be nice, but maybe a generic solution like in gajim should be the solution)

**Comment by genofire** [comment]
Oh sorry, found on master ... a little bit hidden.

**Comment by genofire** [comment]
@jcbrand there are some bugs:
1. it does not send/set the session id (and status)
   `<command node="global-configure" xmlns="http://jabber.org/protocol/commands" status="next" sessionid="d606c521-6598-483c-a306-d284acefdeea">`
1. it does not set the checkboxes (do not know if it is a `true` vs. `1` as char)

**Comment by jcbrand** [comment]
Please create a separate issue for that @genofire

**Comment by genofire** [comment]
okay see #2048 and #2049 - it would be nice, if you fix #2048 the sessionid first.
