### ISSUE TITLE
Feature suggestion: XMPP URI such as "xmpp:coven@chat.shakespeare.lit?join" as link

### ISSUE THREAD

**Issue by MRYingLEE** [conversejs/converse.js#537]
1. To show such a kind of URI as link,
2. To join MUC by clicking the link.

You may find the detail protocol and samples at:
http://xmpp.org/extensions/xep-0045.html#registrar-querytypes .

Thank you in advance,

Ying

---

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29486324-feature-suggestion-xmpp-uri-such-as-xmpp-coven-chat-shakespeare-lit-join-as-link?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github).
</bountysource-plugin>

**Comment by MRYingLEE** [comment]
Just for your reference, https://github.com/jappix/jappix (WEB chat) supports this feature. Maybe some logic can be borrowed.

**Comment by jacksgt** [comment]
[Web based protocol handlers](https://developer.mozilla.org/en-US/docs/Web-based_protocol_handlers) might be useful for this.
