### ISSUE TITLE
OTR Messages need to be sent to full JID

### ISSUE THREAD

**Issue by nick4me** [conversejs/converse.js#553]
I tried to open an OTR chat connection to the client "Conversations" on Android
(https://github.com/siacs/Conversations).
But on the Android app only some strange characters appeared. This problem could be reproduced every time I started OTR. Please let me know if you need some more data.
I'm also not sure if this is a bug of Conversations or of converse.js. But OTR works fine between Conversations and other XMPP clients like Jitsi or Pidgin.

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29976037-otr-messages-need-to-be-sent-to-full-jid?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github).

<bountysource-plugin>

**Comment by petmue** [comment]
https://github.com/siacs/Conversations/issues/1660

**Comment by iNPUTmice** [comment]
Works fine for me as long as the recipient is only connected with one client.
converse.js doesn't address a specific resource but sends the encrypted messages to the bare JID.

To quote from XEP-0364:
> XMPP is designed so that the client needs to know very little about where and how a message will be routed. Generally, clients are encouraged to send messages to the bare JID and allow the server to route the messages as it sees fit. However, OTR requires that messages be sent to a particular resource. Therefore clients SHOULD send OTR messages to a full JID, possibly allowing the user to determine which resource they wish to start an encrypted session with

**Comment by jcbrand** [comment]
Thanks for the info @iNPUTmice, I'll update converse.js to send OTR messages to the full JID.

**Comment by iNPUTmice** [comment]
@jcbrand awesome. Thank you. While you are at it please also set the processing hints mentioned in [Section 4.3](http://xmpp.org/extensions/xep-0364.html#sect-idp737072) of XEP-0364.

**Comment by jcbrand** [comment]
@iNPUTmice I've added the processing hints. I'm not sure how best to determine which resource to initiate OTR with. How do you do this with conversations? I'm reluctant to let the user choose the resource, since I don't think that's very user-friendly and it might confuse people.

**Comment by iNPUTmice** [comment]
@jcbrand thanks for adding the hints.

There is no *good* solution in choosing the resource. I can tell you what I do in Conversations and that is letting the user decide but default to the most recently used resource. (I display a dialog with n radio buttons labeled with the resource names and select the one I received the last message from.)

But I of course also memory the resource over the course of a session. So I'm not asking for every message. 

I mean I guess you could do some magic to guess the resource. But having the messages appear on the wrong device isn't user friendly either.

Also keep in mind that really, really novice users are probably using only one resource and then you don't have to display the dialog.

**Comment by iNPUTmice** [comment]
If you are afraid that resource names are too random you can also display the identity string from Disco instead of the resource nam

**Comment by jcbrand** [comment]
Good suggestions thanks.

**Comment by jcbrand** [comment]
OTR has been dropped in favour of OMEMO.
