### ISSUE TITLE
Improve workflow for theming

### ISSUE THREAD

**Issue by rlanvin** [conversejs/converse.js#576]
I'm trying to build a custom theme (templates+css) for Conversejs, that will use Bootstrap and Fontawesome, and even after reading the documentation for theming [here](https://conversejs.org/docs/html/theming.html) I don't really understand how I'm supposed to work, and what is the workflow for creating a new theme. Here are a couple of issues I noticed:
1. The mockups are fairly useless when modifying the templates, mainly because they are completely static. Is there a way to generate mockups files from the templates files (e.g. a script that concatenates all the files into one static html)? Or better, is there a way to make the mockups files more dynamic (e.g. make them render the javascript templates with placeholder values)?
2. There is no `make templates` in the Makefile. The only way is to `make build` which also triggers `jsmin`, which takes forever. I have found that I can run `./node_modules/.bin/grunt jst` to rebuild the `templates.js`, but this isn't documented anywhere. A `watch` task (similar to `compass watch`) to rebuild `templates.js` everytime a file is changed could be very useful here.
3. Some things are hardcoded in `converse.js` file. For example, I am trying to use a [Bootstrap nav](http://getbootstrap.com/components/#nav) for the
   controlbox tabs, but it needs a class named "active" on the `li` element, whereas Conversejs uses a class named "current" on the `a` element.
4. I am a bit concerned as to the maintenance of the theme. As the moment, the only way I can think of is to maintain my own github fork, make my own custom build, and tell Bower to install Conversejs from my fork. I will have to rebase my fork from upstream on a regular basis to stay up-to-date. I don't see how custom themes can be easily distributed with this workflow. So is this the right way? Couldn't the themes be separated from the main build (e.g. with two files: `converse.js` and `converse-theme-X.js` that contains the templates, and possibly custom js for the theme)?
5. This last point isn't strictly about theming, but I think it's related to the general workflow: it's quite difficult to remove unwanted locales, and redundant dependencies (such as `typeahead.js`, already included in my site), without modifying some core files (namely `main.js` and some others), which again makes maintenance more difficult (this is related to #82).

So what is the correct workflow for creating and maintaining a custom theme? If I'm doing something wrong, please feel free to point me to the right direction. I'm also willing to help if needed, but I'm not a JS dev so I'll need some directions.
### List of template-related things hardcoded in the JS
- [ ] Tabs (don't know yet how to fix this)
- [ ] `pure-button` in `renderConfigurationForm` and `renderRegistrationForm`. Could be replaced by a template (like the form_\* templates)
- [ ] `display:none` form the roster filter form. It would be nice to have a class instead, so I can customize the appearance (e.g. instead of hiding it completely, I would like to dim it)

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/30641123-improve-workflow-for-theming?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github).

**Comment by jcbrand** [comment]
> Is there a way to generate mockups files from the templates files (e.g. a script that concatenates all the files into one static html)?  Or better, is there a way to make the mockups files more dynamic (e.g. make them render the javascript templates with placeholder values)?

No, it's not so simple because the template files are not enough to generate the mockups. The Backbone.js views also generate DOM elements (in which the templates are usually rendered).

I think a tool for this could be created, based upon the Jasmine tests. When you run the tests in the browser, the different UI elements get rendered. A test spec could be created that renders certain UI elements. Every time you reload the page, the elements get rendered new and will incorporate any changes you made in the templates/JS/CSS (unless changes are cached).

> There is no `make templates` in the Makefile. The only way is to make build which also triggers jsmin, which takes forever. I have found that I can run ./node_modules/.bin/grunt jst to rebuild the templates.js, but this isn't documented anywhere. A watch task (similar to compass watch) to rebuild templates.js 
everytime a file is changed could be very useful here.

Agreed.

> Some things are hardcoded in converse.js file. For example, I am trying to use a Bootstrap nav for the controlbox tabs, but it needs a class named "active" on the li element, whereas Conversejs uses a class named "current" on the a element.

I guess this could be made configurable via the config options. Perhaps there's a more elegant way, (there are so many config options already) but I'm not aware of one right now.

>  I am a bit concerned as to the maintenance of the theme. As the moment, the only way I can think of is to maintain my own github fork, make my own custom build, and tell Bower to install Conversejs from my fork. I will have to rebase my fork from upstream on a regular basis to stay up-to-date. I don't see how custom themes can be easily distributed with this workflow.

So you're making an open source theme that you'd like to make broadly available?

> Couldn't the themes be separated from the main build (e.g. with two files: converse.js and converse-theme-X.js that contains the templates, and possibly custom js for the theme)?

Converse.js uses require.js to manage and load dependencies. If I were to make my own theme, I would include in the new repo only those template files which I'm overriding, and then also the custom CSS.

Then in a new main.js file I would specify the paths to those templates, so that they override the original ones. The new repo would then also have its own Makefile and build step, to create a version of converse.js that uses that particular theme.

Some knowledge of require.js and Javascript is however required.

>   This last point isn't strictly about theming, but I think it's related to the general workflow: it's quite difficult to remove unwanted locales, and redundant dependencies (such as typeahead.js, already included in my site), without modifying some core files (namely main.js and some others), which again makes maintenance more difficult (this is related to #82).

Yes, this is a known problem.

**Comment by jcbrand** [comment]
You make some good points and suggestions. I'd be keen to improve thing further, but currently all work on this have to be done in my free time, which I'd rather spend doing other stuff :)

I'm seriously considering making a proprietary, paid-for add-on for converse.js which might help me fund more development on this project.

**Comment by rlanvin** [comment]
> So you're making an open source theme that you'd like to make broadly available?

Well originally no, I was just trying to make a custom theme for myself. But then I realized, my custom theme is not so custom (it is simply a Boostrap/Fontawesome version), so I started to think "what if it can be useful to somebody else?", and then realized all the problems with distributing it that I mentioned.

> I'm seriously considering making a proprietary, paid-for add-on for converse.js which might help me fund more development on this project.

I totally understand your situation and I really appreciate all the work you put into this project. For what it's worth, I think you could start with two easy things:

- Make it a lot more obvious that your are available for freelance. At the moment it's only mentioned at the very bottom of the "Contact" section of the website (and on this ticket). It should be "in your face", like a Download page with a big *Hire me to integrate Converse.js on your website* button, and a smaller *download it from Github and do it yourself* link. :)
- Have you considered a "Donate" button (Paypal or similar)? Not everybody has a company or the resources to hire a freelancer.

Anyway, sorry this is getting a bit off-topic.

**Comment by jcbrand** [comment]
Thanks for the tips, I'll keep them in mind.

**Comment by rszabo** [comment]
"I'm seriously considering making a proprietary, paid-for add-on for converse.js which might help me fund more development on this project."

Sounds good. The project I am working on will without doubt bring you more visitors and users as we always highlight each component used in our system.

**Comment by jcbrand** [comment]
@rlanvin Where is the repo for your theme? I think a good Bootstrap theme is a good idea that other people would also use. Perhaps I can help you a bit with it.

**Comment by rlanvin** [comment]
@jcbrand it's here: https://github.com/rlanvin/converse.js/tree/bootstrap

I just started butchering everything, it's not quite usable yet :) Also, because I'm a bit lost with the workflow (as I explained above), I did a complete fork (I don't know how to use require.js to do what you suggested) and I'm testing directly on my dev website. The problem is that I don't have a static overview of all the templates (like in the mockup folder), so there are some views that I cannot test because I don't use them (e.g. login, room password, emoticons). And I'm also assuming bootstrap and fontawesome are already loaded. I'll be working on it today, so I'm open to feedback and - of course - any help!

**Comment by jcbrand** [comment]
I don't know when I'll be able to get to it, but I'll try to come up with a way for you to test changes you make to templates (by letting the mockups render the templates).

Making a complete fork is IMO fine for now and a good way to start. It can always be refactored again later to remove duplicated stuff.

**Comment by rlanvin** [comment]
@jcbrand Ok after a lot of thought I got an idea. One thing that could be useful, and maybe simpler/faster to implement (I don't know), is to reorganize slightly your repository. For example:

- `src` (the common JS files)
- `themes` (contains one folder per theme)
  - `default` (the name of the theme)
    - `css` (the css/sass files)
    - `templates` (the templates of the theme)
    - `js` (custom JS for this theme only if possible, for example the tabs)
  - `customtheme`
    - ...

Then reorganize the Makefile/Gruntfile/etc. (not sure which one does what to be honest) so that the build produces something like:

- `builds`
  - `converse.js` (the core converse file, without templates)
  - `themes`
    - `default` (the name of the theme)
       - `theme.css` (the theme css)
       - `theme.js` (templates + custom js for this theme only, if possible)
       - `converse.js` (converse bundled with this theme js and templates into one file, totally optional in my opinion)

Regarding the dependencies, I would also remove jquery, typeahead, icomoon & co from the build. I'd write on the installation instructions what third party lib needs to be loaded. As a fallback, requirejs could load them dynamically from a CDN whenever applicable. Similarly a theme built on Bootstrap & FontAwesome will just explicitly mention that Bootstrap & FontAwesome needs to be loaded, but not embed its own version of both.

What do you think?

**Comment by jcbrand** [comment]
I like it, I think it's a good suggestion.

I'm not 100% convinced on removing the dependencies, but I do see the point that they're often already included in people's projects. There already is a build that doesn't include jQuery, so that could perhaps be expanded upon.

**Comment by jcbrand** [comment]
I intend to do some work on converse.js over the weekend, and could then make such a structure.

**Comment by rlanvin** [comment]
That would be sweet! In the meantime, I pushed a semi-working version of the bootstrap/fontawesome theme (at least on my website it looks ok). I'm a bit stuck with some hardcoded classes, so I started to list them in this ticket (if the first message).

If you're curious, it looks like that:
![image](https://cloud.githubusercontent.com/assets/1701590/12919789/5f1f28ae-cf4e-11e5-9bd2-fac9207556cb.png)

**Comment by jcbrand** [comment]
@rlanvin I've pushed a commit which makes `mockup/index.html` now render based upon the templates in `src/templates`.

It should still be expanded upon and not all usecases are yet covered, but it's a start and shows that this is possible.

**Comment by rlanvin** [comment]
@jcbrand Nice, thanks! I justed tested it, and I have only one problem with it: the browser cache is too strong. It sends a `max-age` of one hour for each template file, so the browser doesn't request the file again until the hour is up. The only way I found this to be usable is to manually disable the browser cache, but then it takes 4-5 seconds to render the page... It should have a `If-modified-since` header instead of `max-age`, do you know where this is controlled?

**Comment by jcbrand** [comment]
Are you using `make serve` to serve the files? Or how are you accessing them?

**Comment by rlanvin** [comment]
I am using `make serve`, accessing them directly using `file://` protocol doesn't work.

**Comment by jcbrand** [comment]
Yeah, so I think it's [http-server](https://github.com/indexzero/http-server) which adds the `max-age` header.

I just committed a fix for that: https://github.com/jcbrand/converse.js/commit/76ed0b7b853ce8cdcf5e2abfb5e2359b6591a8d2

**Comment by marclaporte** [comment]
ConverseJS 4.x will use Bootstrap 4.x, offering multiple benefits, including easier themeing.
https://github.com/conversejs/converse.js/commits/bootstrap4

**Comment by jcbrand** [comment]
Yes, I think in light of that, this ticket can be closed.

Tabs are no longer there, the contact add form is in a modal and the `pure-button` class is no longer used.
