### ISSUE TITLE
Synchronise availability status between converse.js instances in the same browser

### ISSUE THREAD

**Issue by jcbrand** [conversejs/converse.js#599]
Related to #597 and #598 

There's now the option to disable availability synchronization, but this means that instances in the same browser won't be synchronized. We need to find a solution for that.

Here the proposed idea:

> Instances of converse.js in the same browser (in different tabs) all share the same session storage as far as I'm aware. Each instance however stores it's data under a unique key, so they don't read one another's data. In this case however, we'd like to know if another instance has changed the status. I think what could be done, would be to store the user's status in a global in sessionStorage, for example under the bare JID. Then when one instance changes it, other instances should immediately know about it, since it should change for them as well, since they share the sessionStorage. That's the theory at least.

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/30977988-synchronise-availability-status-between-converse-js-instances-in-the-same-browser?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github).

**Comment by rlanvin** [comment]
Just a question here: aren't instances of converse.js in different tabs considered as different resources? If so, why should they be treated differently regarding the availability synchronization?

**Comment by jcbrand** [comment]
If they are in different tabs but under the same domain (i.e. in the same website) then they represent for practical intents and purposes a single client, and the different resources is more an implementation detail.

If they are under different domains, then they are separate clients and in that case they aren't treated differently regarding synchronization.
