### ISSUE TITLE
implementing sound when new message arrived/send etc

### ISSUE THREAD

**Issue by rubytastic** [conversejs/converse.js#62]
Implementing sound when new message arrived/send etc
I plan to contribute to your project in short run I have development env setup and will contribute some patches.

What would be suggested format? 
Perhaps some plugin structure would be a good suggestion so you can keep core clean.

I also removed several code for my custom version ( like rooms ) since im planning on using this to implement an instant messenger feature in my social media type rails application.

**Comment by gpadbidri** [comment]
I think this code has a BUG..The code should be : 

<code>
 if ((!delayed && sender !== this.model.get('nick')) || (new RegExp("\\b"+this.model.get('nick')+"\\b")).test(body)) {
                   playNotification();
}
</code>

The last part should be an OR and not AND...This bug causes not being played on Chat Rooms in any case ! Please let me know if this one makes sense !

**Comment by jcbrand** [comment]
@gpadbidri When you are posting code, please wrap it with three backticks ``` ``` ```, so that it gets properly formatted (instead of writing ```<code> </code>```).

The original code is correct. Notifications should only be played when the user is mentioned in the message, otherwise they should not be played.
