### ISSUE TITLE
v1.0.0 Unable to make/build file on Windows

### ISSUE THREAD

**Issue by hendry91** [conversejs/converse.js#641]
Hi, 
my conversejs 1.0.0 getting error when build the file.
My step: 
1. make -f makefile.win
2. test run on visual studio, get error, but I skip it, and it run without problem.
3. make -f makefile.win build

But step 3 I get : 

```
node_modules\.bin\grunt.cmd touch:npm
Warning: Task "touch:npm" not found. Use --force to continue.
Aborted due to warnings.
```

I try to build previous version 0.10.1, no problem with that.
Can help me? how to solve it?
Thanks. 

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/34080222-v1-0-0-unable-to-make-build-file-on-windows?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github).

<bountysource-plugin>

**Comment by hendry91** [comment]
Hi, anyone can help?

**Comment by hendry91** [comment]
hi, can someone help me?

**Comment by mckaygerhard** [comment]
**use linux**, step that verify a file are not present.. due seems the makefile are incomplete, must be a task target named touch

use a real os ...

**Comment by hendry91** [comment]
Thanks @mckaygerhard , will try it later.

**Comment by hendry91** [comment]
Thanks @mckaygerhard .

**Comment by jcbrand** [comment]
@hendry91 Looks like you don't have `touch`, which is a native Linux/Unix utility. You can try to install the NPM version: `npm install touch` and see if that works for you. If it does, please let me know, and I'll update the code.

**Comment by hendry91** [comment]
@jcbrand unfortunately it getting the same error. 
I use VM ubuntu to make it ady..
Thanks.

**Comment by mckaygerhard** [comment]
again use a real os to really understang what happened

touch:npm

its a target in the makefile, and one of the errors was touch are not installed, then there's a target named npm

**Comment by jcbrand** [comment]
@mckaygerhard Telling people to use "a real os" is not helping, please stop.

**Comment by thatguyyoulove** [comment]
A workaround for this is to [install Bash on Ubuntu on Windows](https://msdn.microsoft.com/en-us/commandline/wsl/install_guide).
Via a command line, enter your new bash installation (it may ask you to make a user first, if so, do it):
`bash`
Then install the nodejs from the node PPA and ruby.
`curl -sL https://deb.nodesource.com/setup_6.x -o nodesource_setup.sh`
`sudo bash nodesource_setup.sh`
`sudo apt-get install nodejs ruby-full git`

Checkout the project and build it:
`git clone https://github.com/jcbrand/converse.js.git`
`cd converse.js`
 `npm install`
`make dist`

This particular sequence of events got the project compiling for me. Note that to get `make serve` to work, should you want to view the mockups, you will need to opt-in to the Windows Insider builds Fast Ring and run Windows Update first.
