### ISSUE TITLE
XEP-0071: XHTML-IM

### ISSUE THREAD

**Issue by sneerix** [conversejs/converse.js#667]
At the beginning. thank you for great work you are doing here.

Is it possible to make Converse.js to display multi line messages formatted way?

**Source** window looks like this (Gajim):

![source_gajim](https://cloud.githubusercontent.com/assets/3126585/16614052/6f2992bc-436f-11e6-819f-7a39212ad4dc.jpg)

**Destination** window (Converse.js):

![dest_converse](https://cloud.githubusercontent.com/assets/3126585/16614063/7fa9c0ee-436f-11e6-81fb-e5f1f0a331a4.png)

Message content (xml) (see attachment for details):

<body sid='SID' xmlns:stream='http://etherx.jabber.org/streams' xmlns='http://jabber.org/protocol/httpbind'><message type='chat' to='dest@user/converse.js-XXXXXX' from='source@user' id='XXX' xmlns='jabber:client'><body>1
2
3
4
5</body><thread>SoMeRaNdOmChArS</thread></message></body>

[message.txt](https://github.com/jcbrand/converse.js/files/349493/message.txt)

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/35787334-xep-0071-xhtml-im?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github).

<bountysource-plugin>

**Comment by jcbrand** [comment]
I think Gajim supports HTML-formatted messages. Converse.js doesn't support HTML messages (yet). I did some work on that a year or so ago, but stopped when it became clear that a lot of care would need to be taken to sanitize HTML messages to avoid security holes and XSS attacks.

**Comment by jcbrand** [comment]
XEP-0071 has been deprecated by the XSF.

I therefore don't think we'll implement this as a core plugin.
