### ISSUE TITLE
Private MUC chat

### ISSUE THREAD

**Issue by ffPjrZUGXfcxuAj** [conversejs/converse.js#698]
It's not possible to chat private with MUC occupants

**Comment by jcbrand** [comment]
No, this feature isn't implemented yet.

**Comment by aahutsal** [comment]
@jcbrand is it still actual?

**Comment by jcbrand** [comment]
@aahutsal What do you mean?

**Comment by hessamhoseinkhani** [comment]
@aahutsal @jcbrand select a user to chat with from chatrooms occupants list ...
is that right?

**Comment by aahutsal** [comment]
@jcbrand 

> @aahutsal What do you mean?

"Is this task still current/relevant?"

**Comment by jcbrand** [comment]
@aahutsal yes.
