### ISSUE TITLE
Theme construction and modification

### ISSUE THREAD

**Issue by coderhs** [conversejs/converse.js#70]
Is there any how to, or documentation, regarding theme customization for converse. I am presently trying to move the application from the right side of the webpage to the left, and make tall the chat windows open to the right of it.

**Comment by alexanderadam** [comment]
@jcbrand is the mockup available somewhere else now?

**Comment by jcbrand** [comment]
@alexanderadam:

https://conversejs.org/mockup
https://conversejs.org/mockup/chatroom.html
