### ISSUE TITLE
Contacts list organized by groups

### ISSUE THREAD

**Issue by henriquebol** [conversejs/converse.js#83]
Any idea how I could show the contacts list organized by groups?

**Comment by gpadbidri** [comment]
Hi All,

I have ConverseJS Web Client (Latest Version) setup on my site. I want a FLATTENED list of Contacts being displayed in my Contacts Panel. I want to be able to display a FLAT List of Users just like Facebook shows. How can I achieve that ? Where can I tweak the code for it ?

I want the following : 

1. Regardless of the Status (Online / Offline) I want users to be listed in alphabetical order.

2. I want users to be displayed without their Groups.. I need a flat list not UI wise, but logically I want to merge ALL Contacts across all available groups and show them to user in a flat list.

Can anyone help me on that ? Thanks !
