### ISSUE TITLE
conflicts with other js

### ISSUE THREAD

**Issue by rameshgolla** [conversejs/converse.js#86]
Hi JC , 
i am integrating converse.js into my application while integrating i am getting conflict with other js .i am getting errors like
1) Uncaught TypeError: Object [object Object] has no method 'draggable'    from scrollbar.js
2)Uncaught TypeError: Object [object Object] has no method 'prettyCheckboxes'  from prettyCheckboxes.js
please can you help to solve this .

Thanks in Advance .

**Comment by ajinkyac** [comment]
The URL above is now at:
https://conversejs.org/docs/html/troubleshooting.html

[Received from JC Brand]
