### ISSUE TITLE
OTR bug, hidden conversation

### ISSUE THREAD

**Issue by ignatdoc** [conversejs/converse.js#863]
One more problem: conversation may be started, but it will not show up a window! So you can't see messages, counters of unread and etc. This is very serious bug...

#848

**Comment by jcbrand** [comment]
Then set debug to true, look for errors and paste them here.

**Comment by ignatdoc** [comment]
You copypasting this fraze? )) I know, see closed topic 848
And this is unreal to catch. Rare bug and I see this when come to computer after night

**Comment by jcbrand** [comment]
If you know, then I shouldn't have to tell you again and again. If you can't replicate the problem or provide error messages or debug output, I can't do anything about it.

**Comment by ignatdoc** [comment]
So tried to catch error, watched logs. Scenario:
1. Someone starting OTR with you
2. Someone writes you after conversation is started

In this case there is no errors in debug log, stanzas is going as they should but message window is not visible! It is just don't open. If you open it manualy by clicking in roster - you will see all messages there - OTR service messages about session and keys and messages from contact.
So there will be no autoopened window with this contact, nor you will know about he is writing...

**Comment by ignatdoc** [comment]
Have you looked at this problem?

**Comment by jcbrand** [comment]
OTR has been removed in favour of OMEMO
