### ISSUE TITLE
conversation pane should show my own identity in pane header

### ISSUE THREAD

**Issue by RainerBielefeld** [conversejs/converse.js#956]
Over the years, I created some few identities on different XMPP servers, and most of them I still use every now and then. 
Unfortunately currently only the conversation partner is indicated in the header pane, but I can't see which of my identities I'm currently using.
For my particular needs it would be great if the login pane would show the I identity I am currently using.

**Comment by jcbrand** [comment]
I've noticed the need for this as well, and it's on the (imaginary) roadmap.

**Comment by jcbrand** [comment]
This has been implemented in the master branch already.
