### ISSUE TITLE
Broken session after pagereload using prebind

### ISSUE THREAD

**Issue by qroac** [conversejs/converse.js#98]
I am using converse.js on a webpage using prebind with a BOSH session that gets created on server side and stored in a cookie for reuse after page reload.

On first page call this works fine.
The BOSH session is created on server side and Converse gets initiated using the given boshurl, jid, sid and rid.

But after reloading the page and initiating Converse using the same boshurl, jid, sid and rid as used before the reload, the functionality is a bit ... weird
Contact and room list gets loaded but all contacts are shown as offline
Former opened chats get reopened but not refreshed with new messages and messages written by user are not sent

**Comment by Nagesh29** [comment]
I am also facing the same issue. Everything works perfect when I invoke initialize function on page load.
Connected event is fired and following functionalities works as expected
converse.contacts.get(),  converse.archive.query(options, callback, errback), message send, message on received event, etc.
I am getting connection timeout after one minute and then nothing is working.

**Comment by prajwalpoojari-TOPS** [comment]
@jcbrand 
Hi, we were facing the same issue that the chat was not working after page reload. We made a solution for this, we removed `authentication: prebind`, instead we are using `authentication: login` only. And on page unload we logout the user. So on refresh page its login again. The chat runs smoothly,

```
converse.plugins.add('myplugin', {
	initialize: function () {
	    var _converse = this._converse;
	    _converse.on('connected', function () {
	        sitechat = _converse;
	    });
	}
});

$(window).unload(function(){
    sitechat.api.user.logout();
});
```
