### ISSUE TITLE
Standardise English typography

### ISSUE THREAD

**Issue by linkmauve** [conversejs/converse.js#987]
Many strings have a wrong typography, they lack a final point for sentences, they use "" quotes instead of “”, they use ' instead of ’, they have only one space after a final point instead of two, etc.

This would also help other locales to get it right.

**Comment by jcbrand** [comment]
IMO, not all sentences in a UI should end in a point. It's not a book and sometimes it just looks better without a point.

Look at the title of this ticket, you didn't add a point. Why not? Titles generally don't get points.

Look at the text in the Github UI below "Styling with Markdown is supported" doesn't have a point either.

Concerning the quotes, I've never known or heard that "" quotes are worse than the skew ones. Same with single quotes.

**Comment by linkmauve** [comment]
The GNOME human interface guidelines list a few incorrect yet common usages of ASCII to replace proper Unicode characters here: https://developer.gnome.org/hig/stable/typography.html

I of course agree that titles shouldn’t get a point, but there are quite a few sentences in converse.js which aren’t titles, have a proper sentence structure, and yet don’t obey this general grammar rule.
