### ISSUE TITLE
Standardise vocabulary, if possible with other projects

### ISSUE THREAD

**Issue by linkmauve** [conversejs/converse.js#988]
https://wiki.xmpp.org/web/Usability/Glossary describes a few XMPP-specific terms and their recommended user-facing translation, use them or challenge them, and add the other ones!

**Comment by jcbrand** [comment]
I think this can be closed, no?

**Comment by linkmauve** [comment]
I remember seeing both “JID”/“XMPP Address” in user-facing code, also “roster” in the options, so probably not yet.
