### ISSUE TITLE
mobile and show_controlbox_by_default: false

### ISSUE THREAD

**Issue by camaran** [conversejs/converse.js#996]
in mobile versione the show_controlbox_by_default: false is ignored

**Comment by jcbrand** [comment]
Seems to work fine: https://conversejs.org/mobile.html

**Comment by camaran** [comment]
but you use converse-mobile.min.js not converse.min.js

**Comment by camaran** [comment]
i see https://m.conversejs.org/ and not work

**Comment by jcbrand** [comment]
Refs #1057
